### ISSUE TITLE
Enhancement:  Copy profile to new profile in GUI

### ISSUE THREAD

**Issue by rickhg12hs** [bcpierce00/unison#1004]
It would be convenient in the GUI if a profile could be copied to a new profile ... to make a few minor changes.

For example, a new subdirectory might be made of a remote parent directory that has many subdirectories.  If a profile exists for one of those subdirectories, a new profile would be useful for the new subdirectory ... and it shares all or virtually all parameters except the base directory.

**Comment by gdt** [comment]
I will likely move this to the speculative features wiki page after a while.    If you are going to write code for this please share your design and UI spec on unison-hackers.   It seems like a fair bit of work to avoid a "cp" invocation on the command line, and this raises the usual codebase complexity vs utility over the entire userbase concerns.  It is thus unlikely that someone will code this based on this issue.

**Comment by rickhg12hs** [comment]
understood.
