### ISSUE TITLE
Add open file option to the -ui graphic

### ISSUE THREAD

**Issue by Massimo-B** [bcpierce00/unison#1005]
Enhancement or feature request:

Please add an option to "Open" a file from the graphic ui with the default application or additionally "Open with".
This would be very useful when comparing pictures or other documents before going to apply the changes.

**Comment by gdt** [comment]
If you or anyone else would like to write the code, please post the details of the proposed behavior to the hackers list.   Otherwise, I'll move this to the not-likely-to-be-implemented features wiki page after a while.

**Comment by Massimo-B** [comment]
I'm not involved in the development, and don't know about the portability and target platforms of unison... But as for Linux, isn't this just an `xdg-open $file` ?

**Comment by gdt** [comment]
Anything we do has to work on all platforms unison runs on.  If someone wants to put the time into figuring out a broader plan and propose/discuss on -hacikers, that's fine.

**Comment by gdt** [comment]
This is similar to but not quite the same as #843.

**Comment by tleedjarv** [comment]
I could potentially help with the code, given that a specification is provided for how this should work on each platform (I guess XDG, macOS, Windows is what we need). Examples of this working cross-platform in other software could be useful.

**Comment by nekohayo** [comment]
> Examples of this working cross-platform in other software could be useful.

I haven't seen such a feature in LibreOffice, but Firefox's downloads list does have that, so I searched around a bit to try to find where/how it was implemented. I've noted my broad findings in https://github.com/bcpierce00/unison/issues/843#issuecomment-2344626957 for you. I hope that helps.

**Comment by gdt** [comment]
Merged into #843 since it's just about the same thing, or at least the hard parts are the same.   Plus, if one can open the containing folder with the file highlighted, that's most of what you want.  Thus closing as now a dup to reduce the cognitive load of open tickets, specially because this is not going to happen with a PR.
