### ISSUE TITLE
unison fails to build with ocaml 4.05.0

### ISSUE THREAD

**Issue by DamienCassou** [bcpierce00/unison#102]
I've just downloaded unison-2.48.15.tar.gz from github releases page and face the same bug as #12 with ocaml 4.05:

```session
File "/home/cassou/Downloads/unison-2.48.15/src/system.ml", line 1:
Error: The implementation /home/cassou/Downloads/unison-2.48.15/src/system.ml
       does not match the interface system.cmi:
       Values do not match:
         val symlink : ?to_dir:bool -> string -> string -> unit
       is not included in
         val symlink : string -> fspath -> unit
make[1]: *** [Makefile.OCaml:435: system.cmx] Error 2
make[1]: Leaving directory '/home/cassou/Downloads/unison-2.48.15/src'
make: *** [Makefile:11: src] Error 2
10:32:45 [:~/Downloads/unison-2.48.15] 2 $ 
> ocaml --version
The OCaml toplevel, version 4.05.0
```

**Comment by brabalan** [comment]
This has been fixed by https://github.com/bcpierce00/unison/commit/5ac68ace9b036c0ac619bde4a4c4fffa3d9f510d and there had not been a release since. I just create one, please let me know if it works for you.

**Comment by DamienCassou** [comment]
Issue #103 is currently breaking the build. If I use the workaround discussed there, the build passes. I'm closing this issue. Thanks for the fix.
