### ISSUE TITLE
Add command to change the hostname of a root, and perhaps the path

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#1023]
Unison stores hostnames/paths in archive files, and the files are hashed.   It would be great if one could
```
$ unison update-roots oldroot1 newroot1 oldroot2 newroot2
```
and have the archive/fingerprint files updated on both hosts, both in content and name.

This likely needs more thought, a prototype implementation, and experimenting with it.

**Comment by gdt** [comment]
moved to https://github.com/bcpierce00/unison/wiki/Feature-Requests

**Comment by we-taper** [comment]
Can someone point out the related code responsible for these? Such as, how is the archives files created and where the path/hostname is stored.

I'd like to work on this problem which has created problems for myself. However, I am not familiar with Ocaml and would like some brief guidance.

**Comment by gdt** [comment]
Please ask on -hackers; issues are not for help requests.

**Comment by tleedjarv** [comment]
I don't recommend this as a first issue to work on. This is going to be rather involved and I'd prefer it being considered in a more general framework for administrative commands, such as #495.
