### ISSUE TITLE
Build fails with scanf: bad input at char number 4

### ISSUE THREAD

**Issue by DamienCassou** [bcpierce00/unison#103]
1. download unison-2.48.15v2
2. untar
3. run make

```
/usr/bin/make tags
make[2]: Entering directory '/tmp/unison-2.48.15v2/src'
./mkProjectInfo > Makefile.ProjectInfo
Fatal error: exception Scanf.Scan_failure("scanf: bad input at char number 4: looking for ':', found '$'")
make[2]: *** Deleting file 'Makefile.ProjectInfo'
```

**Comment by DamienCassou** [comment]
Workaround:

Change

```ml
let revisionString = "$Rev$";;
```

in mkProjectInfo.ml to

```ml
let revisionString = "$Rev: 600$";;
```

**Comment by brabalan** [comment]
Sorry about that. @bcpierce00, what is the correct way to do a source code release? I thought just using the tarball from github was sufficient.

**Comment by bcpierce00** [comment]
Since we switched to git, the “$Rev” mechanism from SVN no longer works.  In the master branch, we handle this by just editing Makefile.ProjectInfo directly as necessary.  I guess if we re-release an older version we should do the same plus remove the line in the Makefile that does this:

    ./mkProjectInfo > Makefile.ProjectInfo

— Benjamin

**Comment by bcpierce00** [comment]
The other issue we should be careful of is that the directory you get when you do "tar xvf ..." should be unison-x.x, not src.

**Comment by brabalan** [comment]
@bcpierce00 I just tried it with the release compressed by github, and the folder you get is the release name, so it should be fine.

**Comment by bcpierce00** [comment]
Great!

**Comment by brabalan** [comment]
@DamienCassou There is a new release that should build out of the box (https://github.com/bcpierce00/unison/releases/tag/v2.48.15v3). Could you please check if it works for you?

**Comment by DamienCassou** [comment]
Everything seems fine. Thank you.
