### ISSUE TITLE
Unison keeps complaining about my archives files on ARM Mac

### ISSUE THREAD

**Issue by cleterrier** [bcpierce00/unison#1031]
Hi, long time Unison user here on Mac and Windows. I have a setup for more than 10 years now to backup and sync my work computer with my laptop. It goes like this:

- A whole "Work" folder from my desktop Mac (Intel iMac, drive is APFS SSD, MacOS 13.6.6) is synced to a folder on a 2 TB external SSD drive (formatted as APFS). It uses Unison 2.53.3 with ocaml 4.14.1
- I then sync a subset of this folder (some subfolders etc.) from the external SSD drive to my  laptop (MacBook Air M2, APFS SSD drive, MacOS 13.6.6) to keep with what I'm currently working on. It uses Unison 2.53.4 with ocaml 4.14.1.
- I go from iMac to laptop and back using the external drive, syncing on each machine to update with what I've done on the other.

No problem syncing between iMac and external drive, but when I try to sync between external drive and laptop, I often get the "No archive files were found for these roots" error. I have to delete the archives files in Library/Application Support/Unison, rescan the whole thing and then it accepts to sync the small changes. Then it works for ~24h before complaining about the missing archive files (even if I only worked on the laptop in between, meaning the external drive was synced with the laptop last, next day I sync again with the laptop, I get the error).

How can I help get this problem solved? It's hard to keep using Unison if it entails a ~1h sync and rebuilding archives every time I sync with one of my two computers

**Comment by gdt** [comment]
This seems like a support request rather than a bug request and thus more appropriate for the unison-users@ list.   If you can turn it into a bug report (with enough details to argue there is a unison bug, that would be great.  But it smells like "the mac changes the pathnames" so far.

**Comment by cleterrier** [comment]
Thanks! I had no idea there was a user list. How can I access the archives
to see if my problem was solved already?

**Comment by actualben** [comment]
<https://github.com/bcpierce00/unison/wiki/Mailing-Lists> has info on the lists but doesn't answer your specific question about how to access the archives of the unison-users list. If you're signed into google groups it may be findable?

**Comment by gdt** [comment]
Calling this a dup of #1026
