### ISSUE TITLE
wiki/Mailing Lists: add archives and information on joining Google group

### ISSUE THREAD

**Issue by mvglasow** [bcpierce00/unison#1037]
I’ve added a link to the mailing list archives (the Google one in particular is hard to find, I pulled the link from some issue which was closed without updating the wiki). Also, I’ve added information on joining the Google group.

Since Github does not support forking and issuing pull requests for wiki content, I’ve cloned the wiki into a repo of its own. You should be able to clone your own wiki locally, then add my repo as an additional remote and merge my branch, and finally push to your wiki.

Changes are at:
[mvglasow/github-wiki@mailing-list-update](https://github.com/mvglasow/unison-wiki/tree/mailing-list-update)

**Comment by gdt** [comment]
Commit  pushed to wiki, thanks.
