### ISSUE TITLE
OSX GUI doesn't compile on 10.13

### ISSUE THREAD

**Issue by bcpierce00** [bcpierce00/unison#104]
I'm experimenting with Unison on an OSX 10.13 machine.  The text interface works fine, but compiling the GUI generates a bunch of warnings and then fails like this:

2017-11-24 12:19:06.176 ibtoold[14525:63931] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error getting value for parameter key 'class' of extension 'Xcode.InterfaceBuilderKit.AppleTVIntegration.ConfigurationList' in plug-in 'com.apple.dt.IDE.IDEInterfaceBuilderAppleTVIntegration''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2ada02fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5170dc76 objc_exception_throw + 48
	2   DVTFoundation                       0x0000000102e124dd -[DVTExtensionParameter valueForKey:error:] + 0
	3   Foundation                          0x00007fff2cdeca29 -[NSArray(NSKeyValueCoding) valueForKey:] + 430
	4   Foundation                          0x00007fff2cde9300 -[NSArray(NSKeyValueCoding) valueForKeyPath:] + 436
	5   Foundation                          0x00007fff2cde90fd -[NSObject(NSKeyValueCoding) valueForKeyPath:] + 260
	6   IDEInterfaceBuilderKit              0x00000001024672f9 -[IBPlatform matchesExtension:] + 50
	7   IDEInterfaceBuilderKit              0x00000001024674af __42-[IBPlatform extensionsForExtensionPoint:]_block_invoke + 27
	8   IBFoundation                        0x0000000103453062 -[NSSet(IBSetAdditions) ib_setByFilteringUsingBlock:] + 258
	9   IDEInterfaceBuilderKit              0x0000000102467466 -[IBPlatform extensionsForExtensionPoint:] + 218
	10  IDEInterfaceBuilderKit              0x000000010246657f -[IBPlatform registerMemberConfigurationVariables] + 166
	11  IDEInterfaceBuilderKit              0x00000001025a1d29 -[IBScopedSingletonRegistry init] + 1350
	12  IDEInterfaceBuilderKit              0x00000001025a17c9 __43+[IBScopedSingletonRegistry sharedInstance]_block_invoke + 41
	13  libdispatch.dylib                   0x00007fff522c2e88 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00007fff522c2e3b dispatch_once_f + 41
	15  IDEInterfaceBuilderKit              0x00000001025a179d +[IBScopedSingletonRegistry sharedInstance] + 45
	16  IDEInterfaceBuilderKit              0x00000001023ba175 -[IBInterfaceBuilderPlugin init] + 146
	17  IDEInterfaceBuilderKit              0x00000001023ba0c9 +[IBInterfaceBuilderPlugin ide_initializeWithOptions:error:] + 34
	18  IDEFoundation                       0x000000010373ecd2 _IDEInitializeOnePlugInAndPrerequisites + 2324
	19  IDEFoundation                       0x000000010373e5d9 _IDEInitializeOnePlugInAndPrerequisites + 539
	20  IDEFoundation                       0x000000010373e5d9 _IDEInitializeOnePlugInAndPrerequisites + 539
	21  IDEFoundation                       0x000000010373ccce _IDEInitializePlugIns + 1604
	22  IDEFoundation                       0x000000010373c085 IDEInitialize + 8547
	23  ibtoold                             0x00000001020b5535 ibtoold + 70965
	24  ibtoold                             0x00000001020b46b0 ibtoold + 67248
	25  libdyld.dylib                       0x00007fff522fc145 start + 1
	26  ???                                 0x0000000000000015 0x0 + 21
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Command /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool failed with exit code 6. The tool may have crashed. Please file a bug report at http://bugreport.apple.com with the above output and attach any crash logs for ibtool, ibtoold, Xcode, and Interface Builder Cocoa Touch Tool created around the time of this failure. These logs can be found in ~/Library/Logs/DiagnosticReports or /Library/Logs/DiagnosticReports.

** BUILD FAILED **

The following build commands failed:
	CompileXIB English.lproj/MainMenu.xib
(1 failure)

**Comment by bcpierce00** [comment]
Also, src/Makefile.OCaml probably needs some tidying -- it refers to some OSX GUI options that don't actually exist!
 
Ditto the documentation -- search for uimac and bring up to date.

**Comment by alanshutko** [comment]
Which version of Xcode is this? I just tried with 10.13.2 and Xcode Version 9.1 (9B55) and a simple "make" in the root built the app just fine.

**Comment by bcpierce00** [comment]
I will try my 10.13 machine later today, but on my other machine (10.12.6, just updated to XCode 9.1) it fails in a similar way:

2017-11-28 07:19:42.342 ibtoold[3652:85889] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error getting value for parameter key 'name' of extension 'Xcode.InterfaceBuilderKit.PepperIntegration.Singletons' in plug-in 'com.apple.dt.IDE.IDEInterfaceBuilderWatchKitIntegration''

In case it's useful, here is the whole log from make in /src:

[log.txt](https://github.com/bcpierce00/unison/files/1509810/log.txt)

**Comment by brabalan** [comment]
@bcpierce00 I found many references of this problem online. What seems to have fixed it here is to open xcode and let it download the additional stuff it need.

Unfortunately I cannot do the final linking step because I get this:
```
Undefined symbols for architecture x86_64:
  "_caml_floatarray_create", referenced from:
      _camlArray__38 in unison-blob.o
  "_caml_floatarray_get", referenced from:
      _camlObj__double_field_1017 in unison-blob.o
      _camlObj__24 in unison-blob.o
  "_caml_floatarray_set", referenced from:
      _camlObj__set_double_field_1020 in unison-blob.o
      _camlObj__24 in unison-blob.o
  "_caml_sys_unsafe_getenv", referenced from:
      _camlUnix__fun_3236 in unison-blob.o
      _camlUnix__execvpe_ml_1123 in unison-blob.o
      _camlUnix__315 in unison-blob.o
  "_caml_unix_map_file", referenced from:
      _camlUnix__map_file_inner_3282 in unison-blob.o
      _camlUnix__315 in unison-blob.o
  "_unix_environment_unsafe", referenced from:
      _camlUnix__fun_3240 in unison-blob.o
      _camlUnix__315 in unison-blob.o
```

**Comment by bcpierce00** [comment]
Ah, yes, opening Xcode does seem to get it further.  Not quite to the end, though, yet.  On my 10.12 machine, I can build an executable and it appears to run fine.  But 'make install' fails.

On 10.13, on the other hand, I now get this:

/Users/bcpierce/tmp/unison/src/uimac14/MyController.m:11:10: fatal error: 
      'caml/callback.h' file not found
#include <caml/callback.h>
         ^~~~~~~~~~~~~~~~~

Here, again, is the whole log:

[make.txt](https://github.com/bcpierce00/unison/files/1511474/make.txt)

**Comment by bcpierce00** [comment]
Here is the `make install` failure on 10.12:
[make.txt](https://github.com/bcpierce00/unison/files/1511503/make.txt)

**Comment by brabalan** [comment]
I cannot help for 10.13, as I'm still on 10.12.

I'm confused regarding the `make install`. I never do that, what does it do in addition to building the binary?

**Comment by bcpierce00** [comment]
OK, after some head-scratching, I think I understand: `make install` doesn't actually work for the OSX GUI -- I guess everyone has always adopted your approach of just not using it for that!  So we seem to be OK now on 10.12.

**Comment by alanshutko** [comment]
@bcpierce00 It looks like it is not finding ocamlc in your path.

```
OSARCH = osx
/bin/sh: ocamlc: command not found
(cd uimac14; xcodebuild  OCAMLLIBDIR="" SYMROOT=build)
```

**Comment by bcpierce00** [comment]
Hmm -- not sure why, as it was finding ocaml just fine elsewhere.  But in any case it seems to work now.  :-)
