### ISSUE TITLE
Unison 2.51.2 with Ocaml 4.02.1 make error

### ISSUE THREAD

**Issue by koumak55** [bcpierce00/unison#1040]
Hi,
i need help with compilation on Ubuntu 24.04:
ocaml -version
The OCaml toplevel, version 4.02.1

sudo mkdir -p /usr/src/unison/
sudo wget https://github.com/bcpierce00/unison/archive/refs/tags/v2.51.2.tar.gz -O unison.tar.gz
sudo tar xzvf unison.tar.gz  --strip-components 1
sudo make UISTYLE=text

make -C src UISTYLE=text
make[1]: Entering directory  „/usr/src/unison/src“
UISTYLE = text
Building for Unix
NATIVE = true
THREADS = false
STATIC = false
OSTYPE =
OSARCH = Linux
ocamlopt: ubase/rx.mli ---> ubase/rx.cmi
ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -c /usr/src/unison/src/ubase/rx.mli
ocamlopt: OCaml has been configured with -force-safe-string: -unsafe-string is not available.
Usage: ocamlopt <options> <files>
Try 'ocamlopt --help' for more information.
make[1]: *** [Makefile.OCaml:413: ubase/rx.cmi] Error 2
make[1]:  Leaving directory„/usr/src/unison/src“
make: *** [Makefile:6: text] Error 2

Thx

**Comment by gdt** [comment]
Before opening an issue, did you read the following, pointed to by the wiki and README?

https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests

**Comment by gdt** [comment]
I'd still like to understand whether or not you came across the reporting bugs page.   Please follow up on the list.
