### ISSUE TITLE
Crashes randomly during sync

### ISSUE THREAD

**Issue by isumix** [bcpierce00/unison#1044]
I think it started from 2.53.4 about 4 month ago. Before that it was working flawlessly. When I hit "Go" button it could close window immediately or after a while or not at all. While doing this many times it is somehow possible to complete the sync. From console it works fine. So obviously it is the GUI version issue.

Maybe it was fixed in 2.53.5, but I have not tried it yet. I'm going to update soon and will let you know if the problem persists.

My setup:
Unison 2.53.4
OS is Manjaro KDE with Btrfs
unison.log seems to be ok

**Comment by tleedjarv** [comment]
This should be fixed in 2.53.5.
