### ISSUE TITLE
unison gui report: `bash: line1: unison: command not found`

### ISSUE THREAD

**Issue by eval-exec** [bcpierce00/unison#1048]
I installed unison on my laptop, and I launch the unison gui program, specified two directory and click Open, it show me:
![image](https://github.com/bcpierce00/unison/assets/46400566/8a5d8c8b-0121-4625-9b4a-67bbcf408617)

I guess it's related to my `NixOS` operating system.
I'm sure I have `unison` executable file on my `PATH`:
```bash
❯ which unison
/etc/profiles/per-user/exec/bin/unison
nixos-configuration on  main
❯ unison -version
unison version 2.53.5 (ocaml 5.1.1)
```
And, in `NixOS`, there is no `/bin/bash`:
```bash
❯ ls /bin/bash
"/bin/bash": No such file or directory (os error 2)
```
How to fix this?

**Comment by eval-exec** [comment]
It works after I install `unison` on my remote server.

**Comment by gdt** [comment]
@eval-exec I see you closed this, but the issues are not a help forum.  Please explain how you came to file an issue without seeing the Reporting Bugs wiki page.

**Comment by eval-exec** [comment]
> @eval-exec I see you closed this, but the issues are not a help forum. Please explain how you came to file an issue without seeing the Reporting Bugs wiki page.

I apologize for not adhering to the guidelines. I missed the Reporting Bugs wiki page, but I will make sure to review it thoroughly before submitting any future issues. Thank you for bringing this to my attention.
