### ISSUE TITLE
path = not supporting *

### ISSUE THREAD

**Issue by Massimo-B** [bcpierce00/unison#1050]
unison-2.53.5, Linux

My configuration has several `path =` lines to sync a list of directories.
I tried adding a pattern like `MC**` in order to track a list like `MC-01, MC-02, MC-03` but it doesn't work. I did not find an example if some kind of pattern is allowed in the `path =` line, is it?

PRF file:
```
root = /home/mo/0.SYNC/data
root = ssh://mo@vmsuse//mnt/cifs/data

mountpoint = work

ignore = Name {Thumbs.db}
ignore = Name {*.mkv}

path = All
path = DEV/Service
path = DEV/QPI/Interfaces/C1
path = DEV/QPI/Interfaces/H3.1
path = DEV/QPI/Interfaces/H3.2
path = Custom/05 - Custom/Medicine
path = Custom/05 - Custom/MC**
path = Custom/05 - Custom/Tools

include CO_Common
```

**Comment by gdt** [comment]
Please use the mailinglist for questions and help request.  The
tracker is only for bug reports.

See
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists
