### ISSUE TITLE
Feature Request: Auto-pruning Large Log Files

### ISSUE THREAD

**Issue by weiT1993** [bcpierce00/unison#1051]
When I keep Unison running for a long time, the log files could become multiple GBs large. Is there a feature to automatically rewrite the logs when they become too large?

**Comment by weiT1993** [comment]
Here's a workaround.

1. Create a shell script
```
#!/bin/bash

# Directory to check
DIR_TO_CHECK="/path/to/directory"
# Size limit in bytes (e.g., 10485760 bytes = 10 MB)
SIZE_LIMIT=10485760

# Infinite loop to check every 10 seconds
while true; do
    # Find and check all .log files
    find "$DIR_TO_CHECK" -type f -name '*.log' | while read -r FILE; do
        FILE_SIZE=$(stat -f%z "$FILE")
        if [ "$FILE_SIZE" -gt "$SIZE_LIMIT" ]; then
            rm "$FILE"
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Deleted $FILE (size: $FILE_SIZE bytes)" >> /path/to/watch_log_files.log
        fi
    done

    # Sleep for 10 seconds before checking again
    sleep 10
done
```

2. Give script permissions: `chmod +x /path/to/watch_log_files.sh`
3. Create a LaunchAgent plist file in `~/Library/LaunchAgents/`, for example, `com.example.watch_log_files.plist`.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.example.watch_log_files</string>
    <key>ProgramArguments</key>
    <array>
        <string>/path/to/watch_log_files.sh</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/path/to/watch_log_files.out</string>
    <key>StandardErrorPath</key>
    <string>/path/to/watch_log_files.err</string>
</dict>
</plist>
```

4. Launch it via `launchctl load ~/Library/LaunchAgents/com.example.watch_log_files.plist`

**Comment by gdt** [comment]
This is a question about what exists already.   Please ask on the mailing list as the issue tracker is for bugs and validated/well-defined feature requests.

See
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists
