### ISSUE TITLE
error prompt incorrectly suggests <spc> as a valid action (in old unison)

### ISSUE THREAD

**Issue by VA00** [bcpierce00/unison#1055]
When encountering a connection error in Unison, the prompt displays: 

`Press return to continue.[<spc>]`

Pressing space do nothing. Very annoying error message. Please remove "[<spc>]" and change error message to just "Press return to continue.".

**Comment by gdt** [comment]
Please read  https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests (which you should already have read) and adjust your bug report to provide the missing information.   In particular I can't tell if you are running the latest release or 2.48.

**Comment by VA00** [comment]
Full error message is

`Unison 2.51.5 (ocaml 4.13.1): Contacting server...
Warning: Can't connect to server xxx.xxx.xxx.xxx[xxx.xxx.xxx.xxx]:xxxx: Connection refused

Press return to continue.[<spc>] `

**Comment by gdt** [comment]
That's very out of date.   Did you see the part in the page I linked to that said bugs are not accepted against old versions?
Specifically:
```
The unison project does not provide support for old versions. As of 2023-10, only 2.53.3 and newer are considered new enough to be allowed in the issue tracker. You must upgrade both the local and the remote computer. (We realize you might not have administrative permissions on the remote, but that does not create an obligation for the unison project to spend time dealing with old versions.)
```

As always, I'm not claiming it's fixed in the most recent.  I'm saying that I choose not to pay attention to old releases.

**Comment by gdt** [comment]
feedback timeout; no reproduction with the most recent release received.   Happy to re-open with a valid recent test.

**Comment by VA00** [comment]
So this is similar message, this time with 2.53.5:

% unison DocumentsVPN -auto  
Unison 2.53.5 (ocaml 5.1.0): Contacting server...
Connected [//************** -> //dhcp**********/Documents]

Looking for changes
Warning: No archive files were found for these roots, whose canonical names are:
	/XXXXXX
	//YYYYYYY
This can happen either
because this is the first time you have synchronized these roots, 
or because you have upgraded Unison to a new version with a different
archive format.  

Update detection may take a while on this run if the replicas are 
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.


Press return to continue.[<spc>]
