### ISSUE TITLE
Tool for updating a renamed source directory, retaining cache

### ISSUE THREAD

**Issue by hirak99** [bcpierce00/unison#1056]
This is probably more like a question.

The issue is I have a large directory whose name / mount point is something I need to change frequently.

When I change it, the data remains, just the name changes. But it causes Unison to again scan everything in the directory and rebuild its cache, which is quite time consuming. Is there any way to tell Unison to move the cache from old directory name to the new one?

I am happy to tinker, so if there is a format reference and I have to manually write some code to update it, that is perfectly fine.

**Comment by hirak99** [comment]
My hope is that may be it's just a matter of renaming the `~/.unison/arHASH` and `~/.unison/fpHASH`, after computing a new HASH for the renamed directory.

**Comment by acolomb** [comment]
You can use the rootalias preference to let unison think the new path is equivalent to the old path, and the archives will get reused.  Check the manual for details.

**Comment by gdt** [comment]
Please use the mailinglist for questions and help request.  The
tracker is only for bug reports.

See
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists

Please explain how you came to create an issue without reading the
above wiki page
Or if you did, how you didn't understand that questions are not
allowed in the issue tracker.

**Comment by gdt** [comment]
If you want to work on code to improve things, the right place to discuss is unision-hackers@.

**Comment by hirak99** [comment]
Thank you. Where's unison-hackers@ at? Discord / Google Group / any other forum?

For anyone who may stumble here (as I did again), here are a few pointers that might be helpful.

I tried rootalias, it sort of worked, with some issues - it did not complain but appeared to rescan the directory. I am not sure if intended.

## How the Hash is Computed

The hash is computed in unison/ml/update.ml. Once I read through it, it is incredibly simple. Here is an equivalent Python for computing the hash.

```python
import hashlib

def show_hash(local_root: str, remote_root: str, remote_hash_file: bool=False, version: int=23):
    stored_at = remote_hash_file if remote_hash_file else local_root
    n = f"{stored_at};{local_root}, {remote_root};{version}"
    hash_object = hashlib.md5(n.encode())
    d = hash_object.hexdigest()
    print(f"Archive name is {n}; hashcode is {d}")
```

Here `local_root` and `remote_root` must be of the format: `//[HOSTNAME]/[DIRECTORY]` (note that `[DIRECTORY]` will start with a `/`, so it may look like `//host//path/to/directory`).

A way to check what is being hashed is to run with `unison ... -debug verbose` flag, and search for the hash that you see is stored in `~/.unison/ar[HASH]`.

I have not had the chance to try renaming the hash file as I suggested in the main post since rootalias worked; so I cannot confirm if it actually works. But if it does, rootalias may be removed and just the files may be renamed, which can sometimes be desirable.

## How rootalias works

It is explained well here, https://raw.githubusercontent.com/bcpierce00/unison/documentation/unison-manual.pdf

The documentation was hard to find at first, as I did not expect it to be in PDF format.

I saw the man page first, but the documentation there is partial and omits critical information—i.e. the actual format of the argument.

**Comment by gdt** [comment]
See the link I posted earlier MailingLIsts that.....   explains where the mailinglists are.
