### ISSUE TITLE
enhancement: websocket as a transport

### ISSUE THREAD

**Issue by hadmut** [bcpierce00/unison#1059]
Hi, 

I do know that you're short of people and time to work on unison, but unfortunately I don't speak OCaml to help you. 

Unison can use ssh and plain tcp (dreprecated for security reasons) as a transport, which is part of it's age and heritage. ssh requires to give clients ssh access to a server machine, which is also somewhat risky. Even if there's things like rush and ssh restrictions to limit the attacks over ssh, it still requires an open ssh port.  

Therefore, it would be useful to have websockets as a third transport. There's OCaml libraries for that, eg. https://github.com/vbmithr/ocaml-websocket

regards

**Comment by gdt** [comment]
Moved to https://github.com/bcpierce00/unison/wiki/Feature-Requests to not forget it and not have an open non-actionable issue.

If you want to discuss, please use -hackers.
