### ISSUE TITLE
GUI version with `repeat=watch` not working

### ISSUE THREAD

**Issue by mikolchon** [bcpierce00/unison#106]
I have compiled `2.48.4` for Ubuntu 14.04 as per instructions. My test profile `test.prf` contains `repeat=watch`. When I use the CLI version `unison test`, it succesfully propagates changes between roots as soon as modified, but when I use the GUI version, it does not work. Instead, I need to manually scan and push the changes. I think it might be a problem with the GUI version not working properly with the `unison-fsmonitor`?

**Comment by mikolchon** [comment]
Sorry, I now saw it is explained in the doc
> -repeat xxx        synchronize repeatedly **(text interface only)**

Are there plans to make it work also in the GUI?

**Comment by bcpierce00** [comment]
No one is working on that, as far as I know.  Should not be too hard if someone wants to take it on -- in particular, for the OSX GUI it should not require much OCaml background.

**Comment by bcpierce00** [comment]
(For Ubuntu you'd need the GTK version, which is more ocaml-intensive.)
