### ISSUE TITLE
Using Unison with multi-boot?

### ISSUE THREAD

**Issue by paul35621** [bcpierce00/unison#1061]
I'm using Unison to sync files between several computers and a Linux (Raspberry Pi) file server. One computer uses a Windows/Windows/Linux multi-boot setup. My data is on a shared NTFS partition that is synced with Unison on Linux startup.

Can I also run the Unison sync when I start one of the Windows installations, without having the data multiple times on my hard drive? Should I use the same Unison folder (.unison) for all the three installations? When I tried it, it was very slow.

**Comment by gdt** [comment]
Please use the mailinglist for questions and help request.  The
tracker is only for bug reports.

See
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists

Please explain how you came to create an issue without reading the
above wiki page
Or if you did, how you didn't understand that questions are not
allowed in the issue tracker.
