### ISSUE TITLE
macOS-related issues w/profiles, cltool

### ISSUE THREAD

**Issue by dmpop** [bcpierce00/unison#1083]
Apologies for using this space as a support forum, but I searched high and low to no avail. I'd been using Unison on Linux for ages with no issues at all. But recently I started using it on macOS, and I can't for the live of me figure out two issues.

1. In the Unison GUI app, I can create profiles, but I can neither delete nor edit them. I can't find where profiles are stored either. Admittedly, I'm not well-versed in macOS, so maybe I'm missing something obvious here.
2. Installing cltool seemingly does nothing. Or if it does, I have no idea how to call it from the command line.

Again, apologies for posting my clueless questions here, but if you could help me find the answers, I'd be happy to document them in the project's wiki.

Thank you in advance for your help!

**Comment by tleedjarv** [comment]
> In the Unison GUI app, I can create profiles, but I can neither delete nor edit them.

As I've not seen the GUI app myself, I can't say, but could this be a bug?

Overall, the issues you're facing mostly seem to be documentation issues. I don't use macOS myself so someone else has to judge the nature of these issues.

However, if you're not specifically interested in the mac-native GUI, the GTK GUI also works on macOS. You have to install GTK separately first. I don't know if any packaging repositories provide the GTK GUI but it is available as part of the CI builds. If you look at the release files on https://github.com/bcpierce00/unison/releases you'll see that there are two separate files for macOS, one with suffix `.app` and one without. The latter is the GTK GUI.

**Comment by gdt** [comment]
the right place for support is unison-users@.  Please do not abuse the issue tracker.
