### ISSUE TITLE
Where get monitoring data?

### ISSUE THREAD

**Issue by orlovds** [bcpierce00/unison#1086]
Hi.
Please tell me, is there information about the parameters of monitoring and integration with prometeus somewhere?

thank you in advance.

**Comment by avollmerhaus** [comment]
Please read https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests#understand-the-purpose-of-the-github-issue-tracker

**Comment by gdt** [comment]
Wow, you beat me to it!  My standard text:

Please use the mailinglist for questions and help request.  The
tracker is only for bug reports.

See
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists

Please explain how you came to create an issue without reading the
above wiki page
Or if you did, how you didn't understand that questions are not
allowed in the issue tracker.
