### ISSUE TITLE
Where get monitoring data?

### ISSUE THREAD

**Issue by orlovds** [bcpierce00/unison#1087]
**Is your feature request related to a problem? Please describe.**
How to get monitoring metrics?

**Describe the solution you'd like**
You need a point for getting metrics in prometeus format

**Describe alternatives you've considered**
I don't see any alternatives

**Additional context**
Metrics on connections, load, errors are needed

**Comment by avollmerhaus** [comment]
I'd point you to the same wiki articles as yesterday, but I don't think that would help in any way.  
I really don't think these issue reports will get you anywhere.  
If you really want this feature, please consider contacting the mailing list.  
But be prepared to develop and maintain this feature for yourself.  
I have a feeling nobody will develop, let alone maintain, this feature for you.  
You have to understand that Unison is maintained by volunteers in their free time.

**Comment by orlovds** [comment]
Can you at least tell me the points of getting at least some statistics on the operation of Unison? 

Then we'll do it ourselves...

**Comment by gdt** [comment]
This feels like a help request to me.   If you want to discuss what kind of monitoring might make sense, in the context of  you implementing it, or in creating a fully-baked plan that the list agrees is broadly useful to be an enhancement, please use unison-hackers.

Please use the mailinglist for questions and help request.  The
tracker is only for bug reports.

See
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists

Please explain how you came to create an issue without reading the
above wiki page
Or if you did, how you didn't understand that questions are not
allowed in the issue tracker.
