### ISSUE TITLE
Wrong message about the path of the command line tool in El Capitan

### ISSUE THREAD

**Issue by mimaoffice** [bcpierce00/unison#11]
While installing the command line tool (for Mac OS X El Capitan), you get informed that the binary will
 be installed in /usr/bin, but in fact it will be installed in /usr/local/bin

**Comment by bcpierce00** [comment]
Does the message you're referring to look like this?

The command-line tool is a small program that can be installed in a standard place on your computer (/usr/bin/unison) so Unison can easily be found. If you want to be able to synchronize files on this computer by running Unison on a remote computer, you should probably install it.

**Comment by bcpierce00** [comment]
Hopefully this is fixed now.
