### ISSUE TITLE
Unable to install: This expression has type string but an expression was expected of type

### ISSUE THREAD

**Issue by phuongnd11** [bcpierce00/unison#111]
Encountered this issue while trying to install Unison:
File "/blah/src/unicode.ml", line 25, characters 16-33:
Warning 3: deprecated: String.unsafe_set
File "/blah/src/unicode.ml", line 822, characters 20-21:
Error: This expression has type string but an expression was expected of type
         bytes
make: *** [unicode.cmx] Error 2

**Comment by brabalan** [comment]
You are probably using OCaml 4.06. You should apply this commit 51f3dc69ceaa22d3c0955b4a64384438a90782cb to disable safe strings.

@bcpierce00 Should I make a release of 2.48 with that fix?

**Comment by bcpierce00** [comment]
Sounds like a good idea in any case. But are we ready to make 2.51 the standard release?

       - Benjamin

**Comment by brabalan** [comment]
@phuongnd11 there is a new release that should work out of the box with OCaml 4.06.

@bcpierce00 Does 2.51 work with High Sierra?

**Comment by bcpierce00** [comment]
Still waiting for someone to reply to my yell for help...

       - Benjamin

**Comment by phuongnd11** [comment]
@brabalan I've applied the commit, it still failed to install:
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
make: *** [unison] Error 2
------------------------------

Also, this is how I install unison:
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/aedba6f9e8662740b5d9efa7189169cc9e5d9827/Formula/unison.rb
mkdir -p ~/.unison
Do you know how I can install the new version like this?

**Comment by bcpierce00** [comment]
Maybe easier just to build it from scratch.  If all you want is the text UI, this should be completely straightforward.  
  
    - B

**Comment by phuongnd11** [comment]
I got it installed using HomeBrew tap with the formula here:
https://github.com/Homebrew/homebrew-core/blob/8b1f3ada186da08f84c86d62b0d7ebda8f0b8883/Formula/unison.rb
Thanks.
