### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by maxisme** [bcpierce00/unison#112]
Is there anyway to run callbacks?

I run my script like this:

    /usr/local/bin/unison -auto -repeat watch "$d1" "$d2" -maxerrors 1 -fastcheck true

and this returns strings such as `failed:`, `skipped:`, `Synchronization complete` `Looking for changes` 

I would like to run a script when these things happen is that possible?

**Comment by bcpierce00** [comment]
Not supported directly, but it would be pretty trivial to insert calls to external programs into uitext.ml and recompile.
