### ISSUE TITLE
unison gives error if sshargs ProxyCommand has spaces in it

### ISSUE THREAD

**Issue by WyseNynja** [bcpierce00/unison#113]
I am trying to move all our servers behind a bastion server, but unison is fighting me.

This proxy command works with Vagrant and ssh-config:
```
$ vagrant ssh-config

Host VAGRANTNAME
  HostName ec2-XX-XX-XX-XXX.us-west-2.compute.amazonaws.com
  ...
  ProxyCommand ssh devbastion-us-west-2.dev.uberinternal.com -W %h:%p
```

But unison gives an error
```
$ unison $VAGRANTNAME.dev.uber.com -ui text -debug all -batch -fastcheck false
[startup] Preferences:
...
sshargs = -o ProxyCommand="ssh devbastion-us-west-2.dev.uberinternal.com -W %h:%p"
...
[remote] Shell connection: ssh (ssh, -l, uber, -p, 22, ec2-54-69-76-157.us-west-2.compute.amazonaws.com, -e, none, -o, ProxyCommand="ssh, devbastion-us-west-2.dev.uberinternal.com, -W, %h:%p", unison, -server)
/usr/local/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/usr/local/bin/bash: -c: line 1: syntax error: unexpected end of file
ssh_exchange_identification: Connection closed by remote host
Fatal error: Lost connection with the server
```

I believe the way unison is splitting sshargs is incorrect. I've tried a few combinations of different quotes, but none have worked.

I think we need the remote to look like this (note the lack of commas):
```
[remote] Shell connection: ssh (ssh, -l, uber, -p, 22, ec2-XX-XX-XX-XXX.us-west-2.compute.amazonaws.com, -e, none, -o, ProxyCommand="ssh devbastion-us-west-2.dev.uberinternal.com -W %h:%p", unison, -server)
```

**Comment by bcpierce00** [comment]
I’m guessing that what you’re seeing has something to do with these lines in remote.ml:

  (* Split compound arguments at space chars, to make
     create_process happy *)
  let args =
    Safelist.concat
      (Safelist.map (fun s -> Util.splitIntoWords s ' ') preargs) in

But the comment here suggests that if we just remove this code, other bad things may happen.

(My next few weeks is very busy, so I may not be able to look into this more deeply in a timely way.  But I will be connected at least intermittently and can try to help answer questions if you want to investigate further.  May require looking at what the create_process library function is doing internally — it’s probably a pretty thin layer around a posix system call...)

   - Benjamin

**Comment by tjim** [comment]
Note that as a workaround you could set up your ProxyCommand in your ~/.ssh/config file instead of your unison config.

**Comment by WyseNynja** [comment]
I think Util.splitIntoWords needs to be a little smarter. right now its splitting too much. It should just not split things that are in quotes.

~/.ssh/config does work. We actually use that right now once the instance has DNS records setup, but our unison commands was using IPs to avoid needing to wait for DNS to propagate.  We could make a tool that creates entries in ~/.ssh/config, but I don't love the idea of that. Does anyone know of any tools for managing configs programmatically?

**Comment by bcpierce00** [comment]
It should be easy to rewrite Util.splitIntoWords this way.  It's not used in any inner loops or on large strings (IIRC), so doesn't need to be especially fast.

**Comment by WyseNynja** [comment]
Awesome. I don't know ocaml though.

**Comment by g-raud** [comment]
Pull request #121 gives a solution to the problem by implementing an escaping backslash.  The proxy command used in the test can be specified as follows for example:
```
sshargs = -o ProxyCommand=ssh\ devbastion-us-west-2.dev.uberinternal.com\ -W\ %h:%p
```
