### ISSUE TITLE
Version check in remote.ml is broken for 4.02 versions

### ISSUE THREAD

**Issue by jkrinke** [bcpierce00/unison#116]
The current version check in remote.ml is the following:

```
    if    major < 4 
       || major = 4 && minor <= 2
       || major = 4 && minor = 2 && patchlevel <= 1

```
Any 4.02 version will trigger the second line of the condition and the third line is irrelevant.

If should be 

```
    if    major < 4 
       || major = 4 && minor < 2
       || major = 4 && minor = 2 && patchlevel <= 1

```
https://github.com/bcpierce00/unison/blob/23e7ea9509fa5c678db0de4cd87772ff06d83180/src/remote.ml#L923

**Comment by bcpierce00** [comment]
Oops.  
Thanks.
