### ISSUE TITLE
unison fails to build with ocaml 4.03.0

### ISSUE THREAD

**Issue by fjaell** [bcpierce00/unison#12]
make -j1 UISTYLE=text THREADS=true NATIVE=true unison unison-fsmonitor
...
ocamlopt -g -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -c /tmp/unison/src/unison-2.48.3/system.ml
File "/tmp/unison/src/unison-2.48.3/system.ml", line 1:
Error: The implementation /tmp/unison/src/unison-2.48.3/system.ml
       does not match the interface system.cmi:
       Values do not match:
         val symlink : ?to_dir:bool -> string -> string -> unit
       is not included in
         val symlink : string -> fspath -> unit
Makefile.OCaml:434: recipe for target 'system.cmx' failed
make: *** [system.cmx] Error 2

Same with unison 2.49.543. Both unison version build just fine with ocaml 4.02.x

**Comment by 0-wiz-0** [comment]
I see the same. Is there a patch available?

**Comment by jaapb** [comment]
The two attached patches solve the problem (at least, it compiles again...)
[patch1.txt](https://github.com/bcpierce00/unison/files/252406/patch1.txt)
[patch2.txt](https://github.com/bcpierce00/unison/files/252405/patch2.txt)

**Comment by bcpierce00** [comment]
Ouch.  The patched version does indeed compile under 4.03 (thanks!), but it does not compile under 4.02!  Wonder if there's any way we can have both...

**Comment by bcpierce00** [comment]
OK, I found a different way to patch it that also compiles under 4.02.  Whew.  Closing this pull request -- thanks for the help!

**Comment by brianthelion** [comment]
@bcpierce00 What was the solution for ocaml 4.02? I'm struggling here.

**Comment by bcpierce00** [comment]
Unison 2.48.4 should compile with 4.02 (and 4.03).

**Comment by bcpierce00** [comment]
(available on the Unison download page)

**Comment by brianthelion** [comment]
Thanks! But not the Github master?

**Comment by bcpierce00** [comment]
The github master also compiles under both 4.02 and 4.02, but it's now at version 2.50, so it won't interoperate with 2.48.
