### ISSUE TITLE
Lost connection with the server

### ISSUE THREAD

**Issue by felbinger** [bcpierce00/unison#122]
Hello,
I am using Unison to sync the data between my notebook, server and computer. Until yesterday my pc was working fine. Only my notebook has problems with exactly this error. I fixed it by copying the data manually and delete the unison databases. It was working but it is to much work...
I guess that this error has something to do with the filenames. I can sync one profile on the notebook, but on the computer it fails. I looked in the logfile. Searched in the issues for the error in line 57 and found issue #94 Unfortunately I don't know exactly how the problem could be solved. How can I recompile ocaml? Is this even nessesarry? See output of version below.

**Server**
OS: Debian 9.3
Unison: 2.48.3
OCaml: `The OCaml toplevel, version 4.02.3`

**Clients** (one PC and one Notebook)
OS: Linux Mint 18.2 (Ubuntu 16.04 fork)
Unison: 2.48.3
OCaml: `The OCaml toplevel, version 4.02.3`

Logfile (unison-2.48.3-gtk -debug all): [unison-all.log](https://github.com/bcpierce00/unison/files/1631799/unison-all.log)

Thanks for your help ahead

**Comment by felbinger** [comment]
Oh, by the way sometimes, the sync is successful. I have multiple Profiles - the "documents" profile showed me the error midway. Now the sync is working. It may has something to do with the files that I am trying to sync, but I'm not sure about this.
I looked for spaces in the file-/folder names but I can't find a schematics...

I hope you can help me!

**Comment by bcpierce00** [comment]
I think we've seen reports of systems where the OCaml versions on both sides look the same but on one side the Unison binary was actually compiled with a different OCaml version.  

OCaml itself should not need to be recompiled.  If all you need is a text UI, you can just grab the Unison sources and follow the simple instructions to compile (basically just "make text").
