### ISSUE TITLE
backport escaping whitespace to 2.40

### ISSUE THREAD

**Issue by WyseNynja** [bcpierce00/unison#129]
https://github.com/bcpierce00/unison/compare/2.40...WyseNynja:unison-2.40

I can't create a PR for this because you can only create PRs against branches. If you push a branch for 2.40, this compare should work.

**Comment by brabalan** [comment]
I just create a unison-2.40 branch.

**Comment by WyseNynja** [comment]
Thanks @brabalan . https://github.com/bcpierce00/unison/pull/145

**Comment by bcpierce00** [comment]
I think this is now handled.
