### ISSUE TITLE
unison 2.51.2 fails to build

### ISSUE THREAD

**Issue by david-geiger** [bcpierce00/unison#153]
Hi,

I tried to compile unison 2.51.2 on  Mageia Cauldron with ocaml 4.06.0 but it fails to build, see the attached build log:

Regards,
David
[unison_build_log.txt](https://github.com/bcpierce00/unison/files/1692618/unison_build_log.txt)

**Comment by brabalan** [comment]
The build fails because a Lablgtk function seems to be missing. Do you have Lablgtk 2.18.6 installed? (It's the one that is compatible with ocaml 4.06)

**Comment by david-geiger** [comment]
Yes we have the latest 2.18.6 release of ocaml-lablgtk, see our spec file:

http://svnweb.mageia.org/packages/cauldron/ocaml-lablgtk2/current/SPECS/ocaml-lablgtk2.spec?revision=1179355&view=markup

**Comment by brabalan** [comment]
I'm sorry, but I'm not on Linux so I cannot test it here. Does the build succeed with older versions of ocaml?

**Comment by david-geiger** [comment]
Yes it compile fine on mageia 6 with ocaml 4.02.3 and ocaml-lablgtk2-2.18.3

**Comment by david-geiger** [comment]
So what's for an ocaml 4.06.0 fix?

**Comment by bcpierce00** [comment]
I’m afraid I’m not a lablgtk expert (or user) either.  Maybe worth asking if something happened to Gpointer.region_of_string on the lablgtk mailing list?  (https://lists.forge.ocamlcore.org/cgi-bin/listinfo/lablgtk-list <https://lists.forge.ocamlcore.org/cgi-bin/listinfo/lablgtk-list>)

**Comment by david-geiger** [comment]
So after some search I found what is going wrong and this build issue come from new Lablgtk 2.18.6 and not from ocaml 4.06.0, I found a fix here:

https://bitbucket.org/camlspotter/camlimages/commits/e8ee74a584ff83b86e279cea6e59e6970a956642

This patch fixes build:

http://svnweb.mageia.org/packages/cauldron/unison/current/SOURCES/unison-2.51.2-fix-for-lablgtk-2.18.6.patch?view=markup&pathrev=1205069

**Comment by bcpierce00** [comment]
Thank you!!!

Would it be easy for you to generate a pull request?  If not, I can do it at some point...

**Comment by david-geiger** [comment]
Done!

**Comment by cyounkins** [comment]
Merged here: https://github.com/bcpierce00/unison/pull/164

I'd love have a release to include this!

**Comment by gdt** [comment]
PR has been merged, so this feels fixed.  reopen if not and explain why.
