### ISSUE TITLE
2.51.2 Fails to build on Windows

### ISSUE THREAD

**Issue by delmartechdude** [bcpierce00/unison#159]
Since there are no pre-compiled Windows binaries for 2.51.2 yet, I need to build it. I've followed the Windows build instructions for Microsoft Visual Studio exactly, and I can't get it to work. Keeps saying "no such file or directory" for some things it needs during the build. But I can easily access those files from that same terminal session with `cat`, for example. What's going on here?

Unison 2.51.2
OCaml 4.06.0
Windows 10 Pro Version 1709, build 16299.248
MS Visual Studio Community Edition 2017

output of `make UISTYLE=text`:
```
$ make UISTYLE=text
make -C src UISTYLE=text
make[1]: Entering directory '/cygdrive/c/Users/Person/Downloads/unison-2.51.2/unison-2.51.2/src'
UISTYLE = text
Building for Unix
NATIVE = true
THREADS = false
STATIC = false
OSTYPE =
OSARCH =
ocamlopt: ubase/rx.ml ---> ubase/rx.cmx
ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -c /cygdrive/c/Users/Person/Downloads/unison-2.51.2/unison-2.51.2/src/ubase/rx.ml
File "/cygdrive/c/Users/Person/Downloads/unison-2.51.2/unison-2.51.2/src/ubase/rx.ml", line 1:
Error: I/O error: /cygdrive/c/Users/Person/Downloads/unison-2.51.2/unison-2.51.2/src/ubase/rx.ml: No such file or directory
make[1]: *** [Makefile.OCaml:423: ubase/rx.cmx] Error 2
make[1]: Leaving directory '/cygdrive/c/Users/Person/Downloads/unison-2.51.2/unison-2.51.2/src'
make: *** [Makefile:6: text] Error 2
```

**Comment by delmartechdude** [comment]
Ok - realized that for some reason, OSTYPE wasn't getting set. Fixed that and got further, but still running into an error. New output:

```
$ make UISTYLE=text
make -C src UISTYLE=text
make[1]: Entering directory '/cygdrive/c/Users/Person/Downloads/unison-2.51.2/unison-2.51.2/src'
UISTYLE = text
Building for Windows
NATIVE = true
THREADS = false
STATIC = false
OSTYPE = cygwin
OSARCH = win32
ocamlopt: system/system_win_stubs.c ---> system/system_win_stubs.obj
ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/win -I lwt/win -ccopt /Fo./system/system_win_stubs.obj -c ./system/system_win_stubs.c
x86_64-w64-mingw32-gcc: error: /Fo./system/system_win_stubs.obj: No such file or directory
make[1]: *** [Makefile.OCaml:427: system/system_win_stubs.obj] Error 2
make[1]: Leaving directory '/cygdrive/c/Users/Person/Downloads/unison-2.51.2/unison-2.51.2/src'
make: *** [Makefile:6: text] Error 2
```

**Comment by delmartechdude** [comment]
Somehow we ended up getting it to build.

https://fdopen.github.io/opam-repository-mingw/installation/ - Use 32 bit graphical version (even if on 64 bit OS)

Update `src/Makefile.OCaml`
- Update 107 for win32:
```
      # Win32 system
      EXEC_EXT=.exe
      OBJ_EXT=.o
      OUTPUT_SEL=-o

      CLIBS+=-cclib "-link win32rc/unison.res.lib"
      STATICLIBS+=-cclib "-link win32rc/unison.res.lib"
```
*    Update Line 300-ish, add:

```
        ifeq ($(OSARCH),win32)
        -include fsmonitor/windows/Makefile src/fsmonitor/windows/Makefile
        endif 
```

**Comment by bcpierce00** [comment]
Are these changes needed for all modern windows builds?  I.e., should we make this a PR?

**Comment by delmartechdude** [comment]
I'm not sure. I'd have to do some testing. Not sure I'll get around to doing comprehensive OS testing, but maybe it would be good to add to a troubleshooting page of some type.

**Comment by yannickmodahgouez** [comment]
I’m looking into building for win32 too. Thanks for the details.
Would you mind sharing that binary @delmartechdude ? ;)

**Comment by delmartechdude** [comment]
@yannickmodahgouez I would be willing to consider sharing the binary, but would need approval from @bcpierce00 as well as my legal team :) Did those instructions not work for you?

**Comment by bcpierce00** [comment]
No problem from my side.

**Comment by yannickmodahgouez** [comment]
Haha thanks @delmartechdude but I really didn't want to bother you.
I'm building an cli tool that depends on unison and was looking for a 2.51/Ocaml > 4.01 Wind32 build to do a quick test on windows before getting seriously into it.
I will have to build it anyway in the future so no need to ask your legal team :)

I'm setting up my windows environment as we speak, will let you know my progress.

Btw @bcpierce00 I noticed that Jérôme Vouillon's page was slightly out-of-date.
Since my cli tool depends on unison, I will gladly share regular win32 builds if it's of any interest for you.

**Comment by delmartechdude** [comment]
Haha alright :) I agree though @yannickmodahgouez it would be great to have regular automated builds published for various platforms for every GitHub "Release"

**Comment by yannickmodahgouez** [comment]
Hi @bcpierce00 I made a PR with @delmartechdude proposed fix and uploaded the build for v2.52.1 here : https://github.com/sticksh/unison/releases/tag/v2.51.2 
I'd suggest some updates to the Windows build documentation but I didn't want to change too much things at once. Hope this helps.

**Comment by manu212** [comment]
@yannickmodahgouez could you provide this version with GTK? I looked for up to date binaries on the web but couldnt find anything :(

**Comment by franferri** [comment]
Same error in cygwin. has this fix been updated in the code?

**Comment by mintsoft** [comment]
@franferri I think it's an environmental issue. I have managed to get it to build on windows using something like : https://github.com/mintsoft/unison/blob/master/src/INSTALL.win32#L15

**Comment by rivy** [comment]
If/when PR #380 is incorporated, packaged builds should be available automatically for any release.
In the meanwhile, releases can be found on my fork ([GH:rivy/unison/releases](https://github.com/rivy/unison/releases)).
