### ISSUE TITLE
tree-view in gtk-version

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [bcpierce00/unison#16]
Some gui-version (Mac?) of unision use a tree-view to display the differences before a sync.

The gtk-version doesn't. It would be very helpfull to have tree view where we can (un)fold some parts.

**Comment by bcpierce00** [comment]
Agreed -- it would be nice to improve the GTK UI in this way.  Happy to consider a patch if someone wants to do it.

**Comment by buhtz** [comment]
I realy tried to get into the Ocaml-thing. But I wasn't successfull. I don't understand the code or even know where the ListView object is created.

**Comment by gdt** [comment]
This is the same as #272, and I find the discussion there more helpful to understand things, assuming one reads one and not the other, so I'm closing this as a dup.   Please interpret this as merging the issues.
