### ISSUE TITLE
Support Unix domain sockets for -socket option

### ISSUE THREAD

**Issue by fboundp** [bcpierce00/unison#163]
Unix domain sockets would allow safe use of the `-socket` server option in many circumstances. For example, by using `spiped` to forward encrypted network connections to Unison without making the server available to every process running on the same host.

I suggest the `-socket` interpret an argument that begins with `/` as the absolute path name of a Unix domain socket to create and listen on. Meanwhile, in the specification of a root, a URL such as `socket:///path/name` would specify the Unix domain socket to which to connect.

**Comment by bcpierce00** [comment]
This sounds reasonable.  Happy to consider a PR.

**Comment by gdt** [comment]
This would allow socket-mode testing to be safe, so it actually would help a lot.
