### ISSUE TITLE
Hover tooltips instead of permanent info bar at the bottom of the sync window

### ISSUE THREAD

**Issue by nekohayo** [bcpierce00/unison#169]
Considering that the info bar at the bottom of the main synch window contains mostly redundant information from the window's listview (such as the local file status and the path+filename), and it therefore eats valuable vertical screen space, would you consider simply putting that information into a standard tooltip widget that instantly shows up when the mouse cursor is over a particular row in the listview? You could simply show the modification times and size that way, and that would probably be enough.

**Comment by gdt** [comment]
Moved to https://github.com/bcpierce00/unison/wiki/Feature-Requests
