### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by speedpacer** [bcpierce00/unison#18]
I've installed Unison on CentOS 6.7 and on Cygwin, both using the git clone method and building from scratch but unison -version responds with 2.49.543 on CentOS and 2.40.102 on Cygwin.  

When I try to sync, I receive the error, "Fatal error: Received unexpected header from the server:
 expected "Unison 2.40\n" but received "Unison 2.49\n\000\000\000\000\017",
which differs at "Unison 2.49"."

Also, the instructions have changed slightly in Cygwin from what was in INSTALL.win32-cygwin-gnuc. Ocaml has moved from the Interpreters category into their own Ocaml category. In order to compile, I needed ocaml, ocaml-base and ocaml-compiler-libs which are located there, and also flexdll from the Devel category.

**Comment by bcpierce00** [comment]
Did you build from the same sources on both machines?  It seems like the Cygwin installation must be older.

**Comment by bcpierce00** [comment]
Did the master not compile on both machines?  That would be the simplest way.

Otherwise the build error is easy to fix — change $Rev$ to $Rev: 600$ near the bottom of mkProjectInfo.ml

    - B

**Comment by speedpacer** [comment]
My apologies, disregard... I had an old version left over in my path from when I tried installing this on Windows a while ago that I'd forgotten about.
