### ISSUE TITLE
No changes detected when following the local sync tutorial?

### ISSUE THREAD

**Issue by TomD3Wiz** [bcpierce00/unison#180]
Hi I have installed unison on Mac using brew.

I've tried just a basic local directory sync, which didn't appear to work. So I followed the unison documentation to test a local sync and again, no changes are detected.

Below is the terminal command input and outputs along with unison version information.

**OS is maOS Sierra (10.12.6)**

```
Fri Mar 16 ~ $> unison -version
unison version 2.51.2 (ocaml 4.06.1)
Fri Mar 16 ~ $> mkdir a.tmp
Fri Mar 16 ~ $> touch a.tmp/a a.tmp/b
Fri Mar 16 ~ $> mkdir a.tmp/d
Fri Mar 16 ~ $> touch a.tmp/d/f
Fri Mar 16 ~ $> cp -r a.tmp b.tmp
Fri Mar 16 ~ $> unison a.tmp b.tmp
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Warning: No archive files were found for these roots, whose canonical names are:
	/Users/Thomas/a.tmp
	/Users/Thomas/b.tmp
This can happen either
because this is the first time you have synchronized these roots, 
or because you have upgraded Unison to a new version with a different
archive format.  

Update detection may take a while on this run if the replicas are 
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted: 
http://www.cis.upenn.edu/~bcpierce/unison

Press return to continue.[<spc>]  Reconciling changes
Nothing to do: replicas have not changed since last sync.
Fri Mar 16 ~ $> rm a.tmp/a
Fri Mar 16 ~ $> echo "Hello" > a.tmp/b
Fri Mar 16 ~ $> echo "Hello" > b.tmp/b
Fri Mar 16 ~ $> date > b.tmp/c
Fri Mar 16 ~ $> echo "Hi there" > a.tmp/d/h
Fri Mar 16 ~ $> echo "Hello there" > b.tmp/d/h
Fri Mar 16 ~ $> unison a.tmp b.tmp
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Warning: No archive files were found for these roots, whose canonical names are:
	/Users/Thomas/a.tmp
	/Users/Thomas/b.tmp
This can happen either
because this is the first time you have synchronized these roots, 
or because you have upgraded Unison to a new version with a different
archive format.  

Update detection may take a while on this run if the replicas are 
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted: 
http://www.cis.upenn.edu/~bcpierce/unison

Press return to continue.[<spc>]  Reconciling changes
Nothing to do: replicas have not changed since last sync.
Fri Mar 16 ~ $>
```

**Comment by TomD3Wiz** [comment]
Solved this by adding 

```
export UNISON="$HOME\.unsion"
```

to my .bashrc file, other Mac users might need to add this to their .bash_profile depending on your console setup.

Seemed to have something to do with unison not liking the following profile directory from the initial brew install

```
Profile /Users/Thomas/Library/Application Support/Unison/profile.prf does not exist
```

**Comment by brabalan** [comment]
I'm surprised, because this is the default location for the unison directory. (I have not used the brew version, though, so it might be modified there.) When you run it without this export, does it create a profile.prf in the `~/Library/Application Support/Unison` directory? Or in the `~/.unison/` directory? Or nowhere? (If it's the latter it is a bug.)

**Comment by TomD3Wiz** [comment]
Hi Alan,

It didnt create one in either. Basically the behaviour of unison was that
it just thought every run was an initial sync.


I got the brew version working with the export, but i settled for a
reinstall with macports as it had a matching version to a windows binary i
am using on a another host.

Great piece of software by the way, worked great with the socket sync.


When i get some time ill will reproduce and update the issue. I can also do
a deeper search for any profile.prf on the fs

All the best

**Comment by brabalan** [comment]
Sorry, I was confused, I meant to search for a file with the name starting with `ar` in one of those directories. (It's not supposed to create a profile, but it's supposed to create an archive at the end of synchronization.)

Ideally you could do a clean run with debugging enabled, so we will have more information.

**Comment by TomD3Wiz** [comment]
Ah ok can do,

8pm on friday where I am so ill try get you some more info next week?

How do i enable debugging, commandline switch?

**Comment by brabalan** [comment]
No hurry, and to debug, use the option `-debug all` or `-debug verbose` (the latter is more verbose).

**Comment by gdt** [comment]
This seems like a homebrew issue.    If you can articulate a "unison silently fails when it cannot write the profile directory", with 2.51.2, please file a new bug about that.
