### ISSUE TITLE
add choice to send all files in a direction, rather than just one

### ISSUE THREAD

**Issue by tralce** [bcpierce00/unison#187]
Just hoping that in a soon release we could have a keybind for "all files x direction" when using resolve or auto mode. For example pressing ',' sends the *current* file from host2 to host1, but I'd like something along the lines of 'shift+,' or '[' or similar to send ALL conflicts from host2 to host1. 

And the question: Are the windows binaries at https://www.irif.fr/~vouillon/unison/ going to be updated?

**Comment by tleedjarv** [comment]
This has been available for some time (#151). You can first "match all" and if you then propagate to one direction, all matched files will be propagated to same direction. In addition to "match all" there are several other matching predicates.

> And the question: Are the windows binaries at https://www.irif.fr/~vouillon/unison/ going to be updated?

Working Windows binaries are now available at https://github.com/bcpierce00/unison/releases
