### ISSUE TITLE
Cannot set option value to 0 via GUI

### ISSUE THREAD

**Issue by mvglasow** [bcpierce00/unison#188]
**Steps to reproduce**

* Start the Unison GUI.
* Set up sync between to local directories.
* Add the `perms` option (or any other numeric setting of your choice)
* In the dialog box, enter 0 (which should be the suggested value).
* Select the profile.

**Behavior observed**

* Unison gives an error because of the option not having a value, and the directory cannot be synced.
* Upon examining the profile settings file manually, there is indeed a line `perms = ` (with no value instead of the expected zero value).

**Behavior expected**

* A zero value in the file, and Unison syncing the two directories.

**Additional information**

If I manually edit the profile settings file, supplying the missing zero value, and restart Unison, everything works as expected.

**System Environment**

Unison 2.48.3 on Ubuntu MATE 16.04 LTS. I have observed the same behavior in earlier Unison versions (around 2.4x) on Windows 7; did not test 2.48.3.

**Comment by fenugrec** [comment]
Still an issue as of 2.51.2
