### ISSUE TITLE
Gtk2 interface: Impossible to change integer/text values in profiles

### ISSUE THREAD

**Issue by AlexSchr** [bcpierce00/unison#19]
It is impossible to change integer or text values (e.g. for properties
perms, key) in profiles using the GUI (unison-gtk). Instead, the values
become empty if one tries to change them.
The error seems to be around line 1820 in uigtk2.ml.

**Comment by bcpierce00** [comment]
This needs to be looked at by someone familiar with the GTK2 GUI.

**Comment by fenugrec** [comment]
is Jerome @vouillon still around ? I think we need an ocaml wizard

**Comment by gdt** [comment]
Please retest with 2.51.2_rc2 or newer.

**Comment by fenugrec** [comment]
I've been trying... my distro is still on 2.51, and building from git fails with
```
Linking unison
ocamlopt -verbose -g -I  [...]
File "_none_", line 1:
Error: Files /usr/lib/ocaml/lablgtk2/lablgtk.cmxa
       and /usr/lib/ocaml/stdlib.cmxa
       make inconsistent assumptions over implementation Stdlib__nativeint
```

**Comment by gdt** [comment]
See the builds from the CI system, and note that we only support some versions of ocaml.  The one on your system may be too old.   And there is also quesition of the lablgtk version and how it a was built.  That looks like it might be lablgtk built with a different ocaml you are building unison with.

You can try binaries from https://github.com/bcpierce00/unison/releases/tag/v2.51.3 but that won't help you build.

**Comment by AlexSchr** [comment]
The issue still seems to be there.
I just tried it with v2.51.3

**Comment by gdt** [comment]
Thanks for confirming that the bug still is present in v2.51.3.   I don't think there are any commits since then that would affect this.  So I've removed the feedback label, and now we need someone to supply a detailed analysis or fix :-)

**Comment by tleedjarv** [comment]
It is my understanding that the problem is caused by edit field being destroyed before the value is read out. A PR with fix is coming soon.
