### ISSUE TITLE
Building 2.51.2 on Linux - no make target for "make configure"

### ISSUE THREAD

**Issue by toddjames** [bcpierce00/unison#192]
I downloaded the latest source release from GitHub (2.51.2), and tried `make configure` per [the build instructions](http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#build-unix), but apparently there is no `configure` target. I tried in both the root directory and the `src` directory (since the documentation didn't make it clear which directory this should be done in, though I assume src).

```
todd@leeroy:~/unison-2.51.2/src$ make configure
make: *** No rule to make target 'configure'.  Stop.
todd@leeroy:~/unison-2.51.2/src$ cd ..
todd@leeroy:~/unison-2.51.2$ make configure
make: *** No rule to make target 'configure'.  Stop.
```

**Comment by brabalan** [comment]
The part of the build instructions that mention `make configure` is for the lablgtk library. There is no configure step for unison. If you want to build a command-line version, you should do `make UISTYLE=text`, and if you want a gtk version you should do `make UISTYLE=gtk2`.
