### ISSUE TITLE
Never connects

### ISSUE THREAD

**Issue by jasonwehling** [bcpierce00/unison#193]
Running the latest Unison (2.51.2) on Mac OX 10.12.6, I get a "Connecting..." message and the spinning gear and nothing else happens when opening a profile. I've tested SSH access to the remote sync point with the configured options, and that works. I see nothing in the ~/unison.log file — nothing logs at all.

**Comment by brabalan** [comment]
There might be some information in the Console.app utility. Search for unison there.

**Comment by jasonwehling** [comment]
Here's lines from the console; looks like some exception was thrown.

<img width="939" alt="screen shot 2018-04-16 at 9 02 55 am" src="https://user-images.githubusercontent.com/22478900/38821405-44aefdde-4155-11e8-8de7-13e1ca751531.png">

**Comment by brabalan** [comment]
There is no additional detail, like the name of the exception?

**Comment by jasonwehling** [comment]
Okay, so as a hailmary, I upgraded to High Sierra (10.13.4). I still have the same exact issue, but the messages in the Console have changed a little. Still no details on the exception in the console, unfortunately. I sampled the hung process, and have attached that trace — maybe that helps? 

I watched the console, and the first two console entries (launchservice and the "AEGetDescData of non-desc type 'reco' not a good idea" entry) show up when I start Unison. The other entries show up when attempting to login to the remote desktop). 

Finally, I'm including a screen of the hung login process. 

<img width="928" alt="screen shot 2018-04-16 at 4 14 23 pm" src="https://user-images.githubusercontent.com/22478900/38839809-4766609e-4191-11e8-8185-2ab996514294.png">

<img width="939" alt="screen shot 2018-04-16 at 9 02 55 am" src="https://user-images.githubusercontent.com/22478900/38839699-cc7d66fc-4190-11e8-9b36-6272d9726830.png">
[Sample of Unison.txt](https://github.com/bcpierce00/unison/files/1917616/Sample.of.Unison.txt)

**Comment by jasonwehling** [comment]
Sorry, I attached the wrong updated screen for the Console. That's here: 

<img width="939" alt="screen shot 2018-04-16 at 4 08 58 pm" src="https://user-images.githubusercontent.com/22478900/38839839-6c1161b4-4191-11e8-80a8-670579db20e7.png">

**Comment by bcpierce00** [comment]
You may be able to find out more by starting Unison from a Terminal window, like this:

/Applications/Unison.app/Contents/MacOS/Unison -debug all

**Comment by jasonwehling** [comment]
Well this is interesting (bash: unison: command not found). Is this a problem on the remote machine perhaps? Or I guess it's unclear which bash doesn't know where unison lives. And yes, it's installed on both sides.

Vox:~ jason$ /Applications/Unison.app/Contents/MacOS/Unison -debug all
Preferences:
ui = graphic
host = 
server = false
prefsdocs = false
doc = 
version = false
silent = false
dumbtty = false
testserver = false
showprev = false
selftest = false
confirmmerge = false
retry = 0
repeat = 
contactquietly = false
key = 
label = 
expert = false
height = 15
auto = false
maxthreads = 0
maxsizethreshold = -1
prefer = 
force = 
sortnewfirst = false
sortbysize = false
keeptempfilesaftermerge = false
diff = diff -u CURRENT2 CURRENT1
copyonconflict = false
backupdir = 
maxbackups = 2
backups = false
backupsuffix = 
backupprefix = .bak.$VERSION.
backuploc = central
copymax = 1
copyquoterem = default
copythreshold = -1
copyprogrest = rsync --partial --append-verify --compress
copyprog = rsync --partial --inplace --compress
rsync = true
fastcheck = default
ignorelocks = false
dumparchives = false
showarchive = false
rootsName = 
ignorearchives = false
fastercheckUNSAFE = false
fat = false
allHostsAreRunningWindows = false
someHostIsRunningWindows = false
ignore = Path {.DS_Store}
ignore = Name {,.}*{.DS_Store}
confirmbigdel = true
batch = false
root = ssh://jason@xxx.netx/Users/jason/Working
root = /Users/jason/Working
killserver = false
halfduplex = false
stream = true
addversionno = false
servercmd = 
sshargs = 
rshargs = 
rshcmd = rsh
sshcmd = ssh
xferbycopying = true
sshversion = 
clientHostName = Vox.local
ignoreinodenumbers = false
links-aux = true
links = default
times = false
group = false
owner = false
numericids = false
dontchmod = false
perms = 1023
watch = true
rsrc-aux = false
rsrc = default
maxerrors = 1
unicodeCS = false
unicodeEnc = false
unicode = default
someHostIsInsensitive = false
ignorecase = default
timers = false
terse = false
logfile = /Users/jason/unison.log
log = true
debugtimes = false
debug = all
addprefsto = 
[remote] Shell connection: ssh (ssh, -l, jason, xxx.netx, -e, none, unison, -server)
bash: unison: command not found

**Comment by jasonwehling** [comment]
Here's a simply shell test on both desktops:

Vox:~ jason$ unison -version
unison version 2.48.15

and

Durruti:~ jason$ unison -version
unison version 2.48.15

So it _seems_ to be there. ???

**Comment by jasonwehling** [comment]
It appears to be a path issue. For example, rerunning that with the full path on the remote desktop, it doesn't fault like that:

Vox:~ jason$ ssh -l jason durruti.netx -e none "/usr/local/bin/unison -server"
Password:
Unison 2.48

However, Mac won't let me copy that bin to /bin or /usr/bin.

**Comment by jasonwehling** [comment]
I'm not sure what the "servercmd" option is? If you mean this: 

Vox:~ jason$ ssh -l jason durruti.netx -e none unison -servercmd
Password:
bash: unison: command not found

That doesn't work either.

**Comment by bcpierce00** [comment]
Have you tried looking at the documentation?  The servercmd option is explained there.

**Comment by jasonwehling** [comment]
So, what you're saying is that I could resolve this issue by using the commandline system, and not the GUI? Or can I somehow manually add a servercmd directive to a PRF file perhaps?
