### ISSUE TITLE
-times option overrides -silent, and causes strange unison output

### ISSUE THREAD

**Issue by paulchr20** [bcpierce00/unison#197]
Version 2.48.4, static link, Debian 9, running this command:

unison -repeat 10 -silent -times /root/uni-test  ssh://someserver/uni-test > unison.out 2>&1 &

The unison.out file has this in it, referencing files in uni-test directory.  More of this is appended every
10 seconds (the repeat interval):

props    <-?-> props      baseline-cluster-list  props    <-?-> props      baseline-cluster.tar  props    <-?-> props      cluster-add-cmd  props    <-?-> props      cluster-create-cmd  props    <-?-> props ...

The unison.log file has this sort of output appended every 10 seconds (the repeat interval):

Synchronization complete at 09:23:42  (0 item transferred, 17 skipped, 0 failed)
  skipped: baseline-cluster-list (contents changed on both sides)
  skipped: baseline-cluster.tar (contents changed on both sides)
  skipped: cluster-add-cmd (contents changed on both sides)
  ...

Without the -times option, everything works as expected.  The unison.out file is empty, and unison.log only has output when something changes.  BTW, the contents have not "changed on both sides"; contents of all files are sync'ed and identical.  The order of options in the command line makes no difference.

Thanks.

**Comment by gdt** [comment]
Can you retest with 2.51.2 or git master?  However, this likely remains.

**Comment by paulchr20** [comment]
Hi,

I'm no longer working on this (retired).

Thanks,
-Paul

**Comment by glondu** [comment]
Note that with the -times option, a change of last modification time is considered the same as "contents" change. So, if for example you modify the file on one side, and copy it to the other side, you would get what is described in the initial post and that would be normal.

> I'm no longer working on this (retired).

Closing, then.
