### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by adam3e8** [bcpierce00/unison#198]
I've been using Unison this way for years:
I have several PCs running windows (either Win7 or Win10).  One of these is named "desktop", and all of the others sync with this.  The desktop is running cygwin, and runs Unison within that (this unison is only ran as "unison -server" - the desktop never initiates unison itself).  All of the other clients are running native windows clients (downloaded from https://www.irif.fr/~vouillon/unison/).

I updated cygwin recently, for other program (not for Unison).  Now, my client will Seg Fault shortly after connecting with the server.  If I use unison-2.48.3 with OCaml-4.01.0, after starting Unison I get the dialog asking me to select a profile; I select one; the status message says "contacting server", I see "Connected..." in the command window, and then the status says "Looking for changes" for several seconds.  Then the window goes away, and I see "Segmentation fault" in the command window.

If I use Unison-2.48.3 with OCaml-4.02.1, I get the "Segmentation fault" immediately after I see "Connected..." in the command window.

Trying Unison binaries 2.50, I get a vesion incompatibility, as 2.50 isn't on the server (it isn't readily available through cygwin, so I would have to compile, which I've never done); 2.51 is available in cygwin, but no windows binaries.

Any suggestions?  I'm willing to try to compile something if that will help or is necessary, but I haven't done this before, so I'll have to find a good walk-through.

**Comment by adam3e8** [comment]
I have an update: I the desktop computer, I installed the 2.50 windows binary, and linked /bin/unison in cygwin to this binary.  When I ran unison 2.50 on my desktop, I got errors that "watcher" could not be installed (and it noted that watcher could be disabled).  I disabled watcher, and it now seems to work.

From my perspective, since I believe I have something working, I am okay to close the issue.  However, if there is any info you'd like from me to help with debugging, I'm willing to help.

**Comment by gdt** [comment]
Please retest with the latest release and if still a problem, reopen, describing it as "when configured this way,  and this other thing is done, unison segfaults".  With old versions and not being sure what happened, I don't see anything useful coming out of this remaininig open.
