### ISSUE TITLE
Crash during fastercheckUNSAFE

### ISSUE THREAD

**Issue by tehfink** [bcpierce00/unison#20]
Mac OS X El Capitan 10.11.5 (15F34), unison 2.48.15
2 volumes: external disk mounted via USB, with recent clone thereof mounted via SMB

In the GUI, Unison will quickly compare the two disks until crashing, with no log output.
On the command line, the following error is shown:
```
$ unison media
2016-06-08 17:41:58.725 Unison[2173:307171] Roots are not set on the command line
2016-06-08 17:41:58.737 Unison[2173:307171] Connecting to media...
about to parse command linePreferences:
…
[pred] forcepartial 'iTunes/sentinel' = false
[pred] preferpartial 'iTunes/sentinel' = false
<>!Illegal instruction: 4
$
```

Contents of media.prf:
```
# Unison preferences file
root = /Volumes/media-1
root = /Volumes/media
path = iTunes

ignore = Name {.DS_Store,*archive*}
#ignore = Name { archive}
ignore = Name .FBCIndex
ignore = Name .FBCLockFolder
ignore = Name .FBCLockFolder]
ignore = Name .Apple*
ignore = Name {Cache*,.Trash*,.VolumeIcon.icns,.HSicon,Temporary*,.Temporary*,TheFindByContentFolder}
ignore = Name {TheVolumeSettingsFolder,.Metadata,.filler.idsff,.Spotlight,.DS_Store,.CFUserTextEncoding}
ignore = Path .*
ignore = Name .*
ignore = Name Thumbs.db
ignore = Name *.tmp
ignore = Name misc

fastcheck = true
sortnewfirst = true
confirmbigdeletes = true
mountpoint = iTunes
times = true
#rsrc = false

#to test
confirmmerge = true
perms = 0
dontchmod = true
links = false

copythreshold = 1000000

#speed up initial comparison; run only once
fastercheckUNSAFE = true
ignorelocks = true

log = true
#debug = verbose
debug = all
```

**Comment by bcpierce00** [comment]
And this doesn't happen if you take away the fastercheckUNSAFE flag but leave everything else the same?

**Comment by tehfink** [comment]
Yes, that's correct. Interestingly, I ran the process with the fastercheckUNSAFE multiple times (it would crash each time), and on the 4th run it completed successfully. (maybe because "ignorelocks" was set to "true"?)

**Comment by bcpierce00** [comment]
Sounds like the issue may be related to timing, then.  The fastercheckUNSAFE behavior itself seems unlikely to cause a crash (though it may cause wrong synchronization outcomes if its assumptions are not satisfied, which is why it is marked unsafe).
