### ISSUE TITLE
Add Windows Binary to 2.51.2 Release

### ISSUE THREAD

**Issue by jayfo** [bcpierce00/unison#202]
I managed a Windows text interface build based on the work of @delmartechdude in #159 and @yannickmodahgouez in #195.  The binary has now worked in my 3-machine configuration, resolving a bug I was hitting with 2.48.4 (i.e., the most recent Windows binary I could otherwise find).

I've attached the resulting binary.  Obviously there's no way for me to "vouch" for it except to promise that all I did was compile it. Posting in case @bcpierce00 and @brabalan want to add it to the release.

[unison-windows-2.51.2-text.zip](https://github.com/bcpierce00/unison/files/2065040/unison-windows-2.51.2-text.zip)

**Comment by igpit** [comment]
had a bug in UNISON 2.50.0 (OCAML 4.02.1) on windows, see below, and this version solved it :)
THX!

```
Uncaught exception Sys_error("Invalid argument")
Raised at file "./lwt/lwt.ml", line 126, characters 22-23
Called from file "./lwt/win/lwt_unix_impl.ml", line 211, characters 8-23
...
```

**Comment by bcpierce00** [comment]
Thanks for contributing this binary -- I've added it to the release.

**Comment by mintsoft** [comment]
@jayfo which build instructions did you follow to build this? I've been trying to get Unison to build from source and keep hitting a brick wall!

**Comment by jayfo** [comment]
Above I linked the two issues I worked through at the time.  I didn't really keep any other records.
