### ISSUE TITLE
symlink workaround breaks again for 4.06.0 (worked for 4.05.0)

### ISSUE THREAD

**Issue by jxy** [bcpierce00/unison#203]
5ac68ace9b036c0ac619bde4a4c4fffa3d9f510d actually breaks for ocaml version 4.06.0.  Reverting it makes it compile.

**Comment by gdt** [comment]
Can you test with modern, supported ocaml versions?   4.06 seems like it is too old to pay attention to.

(30 day timer to close)

**Comment by jxy** [comment]
what shall we expect from a 2 year-old issue?
