### ISSUE TITLE
Sync via MTP for Android devices

### ISSUE THREAD

**Issue by emakei** [bcpierce00/unison#205]
Would be great to deal with device like 'unison mtp://192.168.xxx.xxx/folder'

**Comment by gdt** [comment]
It seems obvious (which means I may well be wrong) that there should be some sort of FUSE method to mount MTP into the host filesystem, and then unison could simply be used.  The UNIX way is to have the VFS/filesystem abstraction, for programs to use the filesystem, and for each kind of filesystem to be mapped into a VFS/mountpoint.

So I wonder if there is a good reason why that won't work, and it would be architecturally sensible to add MTP support into unison?  The null hypothesis is that this should be done by mapping MTP into the local filesystem.

**Comment by gdt** [comment]
The hypothesis that MTP should be mapped into the filesystem, where unison can just work straightforwardly, is accepted.
