### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by adam3e8** [bcpierce00/unison#210]
I have been using Unison for a while, and it had been working great.  Starting today, I get a segmentation fault.  If I use the GTK version, both the main window and the one showing the ssh connection goes away.  If I run the text version, I get this.

```
$ ./unison\ 2.50\ text.exe Laptop_to_Desktop_-_SSH
Unison 2.50.0 (ocaml 4.02.1): Contacting server...
Connected [//xxxxxxxxxxxxx/C:/ -> //xxxxxxxxxxxxx/C:/]
Looking for changes
Segmentation fault

```

My setup is that my laptop which runs the client is using the Windows binaries from https://www.irif.fr/~vouillon/unison/.  It is running cygwin for ssh.

My desktop that I'm connecting to is running cygwin as the ssh server, and the Windows binaries from the same location.  In cygwin, my /bin/unison is a symlink to c:\program files\Unison\unison 2.50\unison 2.50 text.exe.

Both machines are running the same version of Unision.  I've tried several other versions, keeping the laptop and desktop the same, but get the same behavior in all cases.  Both machines are running Win10.

I didn't change anything myself with either unison or cygwin.  The IT department periodically applies updates, and I know one was applied recently on both my desktop and laptop.

Looking for any help.  If there is anything I can do to help diagnose, please let me know.

**Comment by gdt** [comment]
Please see #375, and retest with 2.51.2 that are built with the same ocaml version.   Please use the mailinglist for getting help and the tracker only if you can articulate a rationale for a bug.
