### ISSUE TITLE
-unsafe-string option causes build failure of 2.48.15v4 with Ocaml4.01.0-22.7.el7_2 on Centos 7.3 with 

### ISSUE THREAD

**Issue by mirkov** [bcpierce00/unison#211]
Hello,

I am trying to build unison 2.48 with Ocaml4.01 on Centos 7.3.

I get an error about invalid option "-unsafe-string" (see below).  I also noticed that OSTYPE is undefined.

Are my Unison and Ocaml versions incompatible or is there a simple fix I should try?  I installed Ocaml using yum.

Thank you,

Mirko

Here is the trace:

[mirkov@hal9000 unison-2.48.15v4]$ sudo make UISTYLE=text
[sudo] password for mirkov:
make -C src Makefile.ProjectInfo
make[1]: Entering directory /export/Build/unison/unison-2.48.15v4/src
make[1]: Nothing to be done for Makefile.ProjectInfo.
make[1]: Leaving directory /export/Build/unison/unison-2.48.15v4/src
make -C src
make[1]: Entering directory /export/Build/unison/unison-2.48.15v4/src
UISTYLE = text
Building for Unix
NATIVE = true
THREADS = false
STATIC = false
OSTYPE =
OSARCH = Linux
ocamlopt: ubase/rx.mli ---> ubase/rx.cmi
ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -c /export/Build/unison/unison-2.48.15v4/src/ubase/rx.mli
/bin/ocamlopt: unknown option -unsafe-string.

**Comment by mirkov** [comment]
I get the same error trying to build unison-2.51.2

**Comment by brabalan** [comment]
Your version of OCaml is too old. You could either try to install a more recent version of OCaml (that supports this option), or change line 101 of `src/Makefile.OCaml` to remove the `-unsafe-string` option.

**Comment by mirkov** [comment]
After commenting out the `-unsafe-string` option as you suggested, I was able to build the text version of unison 2.48.15.  I tested Unison by synchronizing a folder.

Thank you.
