### ISSUE TITLE
How can I Speed-Up the "Looking for changes" Process

### ISSUE THREAD

**Issue by kerner1000** [bcpierce00/unison#212]
I would like to know how I can speed up this process.

I have most of the time very few changes and also files that have changed, are most of the time not very large. So I would be happy if the "Looking for changes" would take less time to complete, even if that would mean, that during the actual synchronization more data, e.g. the complete file, is transferred.

In other words:
Can I trade off time spent when "Looking for changes" for the amount of data transferred later on?

**Comment by maharjun** [comment]
You could possibly set the `fastcheck` option to true in order to avoid checking file contents each time but only use dates to check for changes.

**Comment by hevanaa** [comment]
I solved this by running two different jobs. One with fastcheck and one without. The one with fastcheck runs every few minutes and the one without every hour. I use systemd services and timers to schedule and run the jobs. They each run a 'flock' process that launches a script containing the actual unison commands (flock prevents the command from being started multiple times, i.e. only one instance allowed).

**Comment by gdt** [comment]
This is not a defect report or feature request.
