### ISSUE TITLE
downloads link on Unison webpage is out of date

### ISSUE THREAD

**Issue by jefftemplon** [bcpierce00/unison#214]
Google search for Unison leads here:

https://www.cis.upenn.edu/~bcpierce/unison/

From there, clicking first Downloads and then Binaries I end up here:

http://unison-binaries.inria.fr/

I first missed the important note at the top (not a larger font size so scanning brain ignored it and went straight for Mac OS X) and then wondered why the newer releases were nowhere to be found.  

I suggest updating the Binaries link to point to

https://github.com/bcpierce00/unison/releases

Thanks

**Comment by gdt** [comment]
Updated.
