### ISSUE TITLE
Overwriting a file instead of deleting and copying?

### ISSUE THREAD

**Issue by Linkandzelda** [bcpierce00/unison#215]
This is quite hard to describe. I'm using unison to sync a WebDAV folder mounted, to another local folder. The WebDAV folder is a nextcloud server.

Nextcloud has a thing called versions and activity, which shows who edited a file and provides versions to restore from the past. The problem is, when syncing with unison, those versions are lost. Upon investigating it seems like unison is deleting the file and copying the new one in its place whenever a change in the local folder is synced to the remote mount folder.

When I do a simple `cp` from the local folder to the remote the versions are kept. I've tried using `-copyprog cp` but this didn't have any effect.

I've run it with `-debug` and I can see why this happens, it's most likely due to archiving as the files are renamed to temp files and then the other file is copied, then renamed to the real name. I can imagine that nextcloud sees this as a delete and a create. Is there any way to prevent this?

**Comment by bcpierce00** [comment]
> I've run it with -debug and I can see why this happens, it's most likely due to archiving as the files are renamed to temp files and then the other file is copied, then renamed to the real name. I can imagine that nextcloud sees this as a delete and a create. Is there any way to prevent this?

No easy way, I’m afraid.  

    - B

**Comment by gdt** [comment]
In my view creating a temp file and using rename is very normal, and the standard approach for writing  a new file (to avoid mixed content in case of crash during the write).   So perhaps nextcloud should recognize this?

I don't see this as a unison bug, so am closing.
