### ISSUE TITLE
Compile binary for CentOS/RedHat/OEL 6.latest ;;; /usr/bin/ocamlopt: unknown option `-unsafe-string'.

### ISSUE THREAD

**Issue by MarekUniq** [bcpierce00/unison#216]
Hi,

Is it possible to compile unison for REDHAT / CENTOS / OEL 6.latest

$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="6.10"
ID="ol"
VERSION_ID="6.10"
PRETTY_NAME="Oracle Linux Server 6.10"

$ uname -a
Linux xxx.xxx.xxx 4.1.12-124.17.2.el6uek.x86_64 #2 SMP Tue Jul 17 20:31:11 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux

$ wget https://github.com/bcpierce00/unison/archive/v2.48.15v4.tar.gz
$ tar zxvf v2.48.15v4.tar.gz
$ cd unison-2.48.15v4/
$ make UISTYLE=text
make -C src mkProjectInfo
make[1]: Entering directory `/root/unison-2.48/unison-2.48.15v4/src'
ocamlc -o mkProjectInfo unix.cma str.cma mkProjectInfo.ml
make[1]: Leaving directory `/root/unison-2.48/unison-2.48.15v4/src'
make -C src Makefile.ProjectInfo
make[1]: Entering directory `/root/unison-2.48/unison-2.48.15v4/src'
make[1]: Nothing to be done for `Makefile.ProjectInfo'.
make[1]: Leaving directory `/root/unison-2.48/unison-2.48.15v4/src'
make -C src
make[1]: Entering directory `/root/unison-2.48/unison-2.48.15v4/src'
UISTYLE = text
Building for Unix
NATIVE = true
THREADS = false
STATIC = false
OSTYPE =
OSARCH = Linux
ocamlopt: ubase/rx.mli ---> ubase/rx.cmi
ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -c /root/unison-2.48/unison-2.48.15v4/src/ubase/rx.mli
/usr/bin/ocamlopt: unknown option `-unsafe-string'.
Usage: ocamlopt <options> <files>
Options are:
  -fPIC  Generate position-independent machine code (default)
  -fno-PIC  Generate position-dependent machine code
  -a  Build a library
  -annot  Save information in <filename>.annot
  -c  Compile only (do not link)
  -cc <comp>  Use <comp> as the C compiler and linker
  -cclib <opt>  Pass option <opt> to the C linker
  -ccopt <opt>  Pass option <opt> to the C compiler and linker
  -compact  Optimize code size rather than speed
  -config  print configuration values and exit
  -dtypes  (deprecated) same as -annot
  -for-pack <ident>  Generate code that can later be `packed' with
     ocamlopt -pack -o <ident>.cmx
  -g  Record debugging information for exception backtrace
  -i  Print inferred interface
  -I <dir>  Add <dir> to the list of include directories
  -impl <file>  Compile <file> as a .ml file
  -inline <n>  Set aggressiveness of inlining to <n>
  -intf <file>  Compile <file> as a .mli file
  -intf-suffix <file>  Suffix for interface files (default: .mli)
  -intf_suffix <file>  (deprecated) same as -intf-suffix
  -labels  Use commuting label mode
  -linkall  Link all modules, even unused ones
  -noassert  Don't compile assertion checks
  -noautolink  Don't automatically link C libraries specified in .cmxa files
  -nodynlink  Enable optimizations for code that will not be dynlinked
  -nolabels  Ignore non-optional labels in types
  -nostdlib  do not add standard directory to the list of include directories
  -o <file>  Set output file name to <file>
  -output-obj  Output a C object file instead of an executable
  -p  Compile and link with profiling support for "gprof"
     (not supported on all platforms)
  -pack  Package the given .cmx files into one .cmx
  -pp <command>  Pipe sources through preprocessor <command>
  -principal  Check principality of type inference
  -rectypes  Allow arbitrary recursive types
  -shared  Produce a dynlinkable plugin
  -S  Keep intermediate assembly file
  -thread  Generate code that supports the system threads library
  -unsafe  No bounds checking on array and string access
  -v  Print compiler version and standard library location and exit
  -version  Print compiler version and exit
  -verbose  Print calls to external commands
  -w <flags>  Enable or disable warnings according to <flags>:
     C/c enable/disable suspicious comment
     D/d enable/disable deprecated features
     E/e enable/disable fragile match
     F/f enable/disable partially applied function
     L/l enable/disable labels omitted in application
     M/m enable/disable overriden methods
     P/p enable/disable partial match
     S/s enable/disable non-unit statement
     U/u enable/disable unused match case
     V/v enable/disable overriden instance variables
     Y/y enable/disable suspicious unused variables
     Z/z enable/disable all other unused variables
     X/x enable/disable all other warnings
     A/a enable/disable all warnings
     default setting is "Aelz"
  -warn-error <flags>  Treat the warnings of <flags> as errors, if they are
     enabled.  See option -w for the list of flags.
     Default setting is "a" (warnings are not errors)
  -where  Print location of standard library and exit
  -nopervasives  (undocumented)
  -dparsetree  (undocumented)
  -drawlambda  (undocumented)
  -dlambda  (undocumented)
  -dcmm  (undocumented)
  -dsel  (undocumented)
  -dcombine  (undocumented)
  -dlive  (undocumented)
  -dspill  (undocumented)
  -dsplit  (undocumented)
  -dinterf  (undocumented)
  -dprefer  (undocumented)
  -dalloc  (undocumented)
  -dreload  (undocumented)
  -dscheduling  (undocumented)
  -dlinear  (undocumented)
  -dstartup  (undocumented)
  - <file>  Treat <file> as a file name (even if it starts with `-')
  -help  Display this list of options
  --help  Display this list of options
make[1]: *** [ubase/rx.cmi] Error 2
make[1]: Leaving directory `/root/unison-2.48/unison-2.48.15v4/src'
make: *** [src] Error 2

Regards,
Marek

**Comment by brabalan** [comment]
Yes, see #211

**Comment by MarekUniq** [comment]
Thank you. This helped further.
Now there is another error message: 

$ make UISTYLE=text
...
ocamlopt: fsmonitor/linux/watcher.ml ---> fsmonitor/linux/watcher.cmx
ocamlopt -g -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -c /root/unison-2.48/unison-2.48.15v4/src/fsmonitor/linux/watcher.ml
**File "/root/unison-2.48/unison-2.48.15v4/src/fsmonitor/linux/watcher.ml", line 55, characters 5-10:
Error: Syntax error**
make[1]: *** [fsmonitor/linux/watcher.cmx] Error 2
make[1]: Leaving directory `/root/unison-2.48/unison-2.48.15v4/src'
make: *** [src] Error 2

Regards,
Marek
