### ISSUE TITLE
Compile binary for CentOS/RedHat/OEL 6.latest ;;; File "/root/unison-2.48/unison-2.48.15v4/src/fsmonitor/linux/watcher.ml", line 55, characters 5-10: Error: Syntax error

### ISSUE THREAD

**Issue by MarekUniq** [bcpierce00/unison#217]
Next issue after #216
After commenting out the "-unsafe-string" option as suggested in issue #216 the make did more work and ended up with the following error:

$ make UISTYLE=text
...
ocamlopt: fsmonitor/linux/watcher.ml ---> fsmonitor/linux/watcher.cmx
ocamlopt -g -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -c /root/unison-2.48/unison-2.48.15v4/src/fsmonitor/linux/watcher.ml
**File "/root/unison-2.48/unison-2.48.15v4/src/fsmonitor/linux/watcher.ml", line 55, characters 5-10:
Error: Syntax error**
make[1]: *** [fsmonitor/linux/watcher.cmx] Error 2
make[1]: Leaving directory `/root/unison-2.48/unison-2.48.15v4/src'
make: *** [src] Error 2

Regards,
Marek

**Comment by bcpierce00** [comment]
You only need the filesystem watcher if you are using the -watch preference.  You could try just commenting everything to do with the fsmonitor subdirectory out of Makefile.OCaml.

**Comment by brabalan** [comment]
I agree this is the best approach. We are indeed using a (fairly) recent syntax in that file.

**Comment by MarekUniq** [comment]
**I did the following changes in file Makefile.OCaml**

```
$ diff ORIGINAL/src/Makefile.OCaml NEW/src/Makefile.OCaml

< CAMLFLAGS+=-g -unsafe-string
---
> #CAMLFLAGS+=-g -unsafe-string
> CAMLFLAGS+=-g
310,316c311,317
< ifeq ($(OSARCH),Linux)
< -include fsmonitor/linux/Makefile src/fsmonitor/linux/Makefile
< endif
<
< ifeq ($(OSARCH),win32gnuc)
< -include fsmonitor/windows/Makefile src/fsmonitor/windows/Makefile
< endif
---
> #ifeq ($(OSARCH),Linux)
> #-include fsmonitor/linux/Makefile src/fsmonitor/linux/Makefile
> #endif
>
> #ifeq ($(OSARCH),win32gnuc)
> #-include fsmonitor/windows/Makefile src/fsmonitor/windows/Makefile
> #endif
318c319
< INCLFLAGS+=-I fsmonitor -I fsmonitor/linux -I fsmonitor/windows
---
> #INCLFLAGS+=-I fsmonitor -I fsmonitor/linux -I fsmonitor/windows
```

**And as result of make commad the following binary was produced**
```
$ ls -l src/unison
-rwxr-xr-x 1 root root 2472100 Sep  3 20:25 unison

$ ./unison -version
unison version 2.48.15
```

**Comment by MarekUniq** [comment]
Right now I got the needed binary, thank you.

Question: is there a place where compiled binaries for different platforms are available?
This time I found red hat version 2.40 and fedora version 2.48 but they does not work together.

> I agree this is the best approach. We are indeed using a (fairly) recent syntax in that file.

Using recent syntax is good. If compiled binaries are not avaiable then it would be good to have some primitive instructions how to compile.

**Comment by bcpierce00** [comment]
I don't know anyplace where Linux binaries are available (other than the usual package installers on each flavor of Linux).  However, it's worth keeping in mind that, if you're able to install stuff on both machines, recompiling Unison from source is pretty easy.  (Actually, it's _very_ easy if you don't care about the graphical front end.  Just requires OCaml, which itself is quite easy to install.)

**Comment by MarekUniq** [comment]
thank you
