### ISSUE TITLE
rsync --append-verify option not available on OS X 10.13.6 (High Sierra)

### ISSUE THREAD

**Issue by valankar** [bcpierce00/unison#220]
--copyprogrest by default uses:

rsync --partial --append-verify --compress

However, on OS X 10.13.6 (High Sierra), the bundled rsync does not have an --append-verify option:

```
Virajs-iMac-2:~ virajalankar$ rsync --append-verify
rsync: --append-verify: unknown option
rsync error: syntax or usage error (code 1) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/main.c(1337) [client=2.6.9]
Virajs-iMac-2:~ virajalankar$ uname -a
Darwin Virajs-iMac-2.fritz.box 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
Virajs-iMac-2:~ virajalankar$ rsync --version
rsync  version 2.6.9  protocol version 29
````

**Comment by gdt** [comment]
macOS 10.13 has rsync 2.6.9 release in November 2006, and is missing 3.0.0 release in March of 2008.   Therefore it's a bug to use 10.13 without having a newer rsync, and not a bug that unison doesn't accomodate code that is 14 years out of date.
