### ISSUE TITLE
-times fails to sync time of 0 (ie 1970-01-01 00:00:00)

### ISSUE THREAD

**Issue by steffiefee** [bcpierce00/unison#223]
When using -times, if a file has an actual modification time of unix epoch 0, unison will fail to synchronize the time. So eg:

    mkdir a b
    touch -d "1970-01-01 00:00:00 +0000" test
    unison -root a -root b -times

will fail with:

> Failed: Failed to set modification time of file /home/foo/b/.unison.test.ec13104661b0c45e358568993443eacc.unison.tmp to 1970-01-01 at  1:00:00 (0.000000): the time was set to 2018-10-10 at  4:02:27 (1539140547.897847) instead
Failed [test]: Failed to set modification time of file /home/foo/b/.unison.test.ec13104661b0c45e358568993443eacc.unison.tmp to 1970-01-01 at  1:00:00 (0.000000): the time was set to 2018-10-10 at  4:02:27 (1539140547.897847) instead

Epoch time 0 is fairly common for temporary or immutable files (eg Rust's package manager cargo uses it a lot for its internal package database). 

(I tried looking at the source because I assumed something like, unison uses 0 as the null value and tries to detect a failure to adjust the time by checking if the file has something besides the null value, but unfortunately the null value is itself a valid value, so unison should skip that check if the desired time value is 0 anyway. But I can't make sense of the time syncing logic, so I don't know if that's true. :/)

**Comment by bcpierce00** [comment]
The code that sets the modtime is in props.ml.  It is basically just a call to the Posix st_mtime function, followed by a check that the result (the time that it actually got set to, apparently) is "close enough" to what was intended (exactly the same, off by exactly one second or two seconds, etc.).

Looks like maybe the OS is not allowing the time to be set to 0?

**Comment by bcpierce00** [comment]
Aha!  Very interesting.

So a workaround would be to replace line 560 of props.ml with something that tests whether both values are 0 and, if so, chooses a nonzero value (e.g., now) for the access time.

**Comment by bruceg** [comment]
I too have been running into this. Certain files generated by Rust's cargo tool will be created with a timestamp of 0, causing unison to choke when trying to sync them.

I have proposed a fix with them, but arguably it is unison (via OCaml) that is getting it wrong here.

**Comment by gdt** [comment]
I don't follow.  It seems like ocaml has a bizarre implementation, and unison is failing to work around it.    Is that what you mean?

**Comment by glondu** [comment]
> So a workaround would be to replace line 560 of props.ml with something that tests whether both values are 0 and, if so, chooses a nonzero value (e.g., now) for the access time.

Using now does not seem right. `Float.succ 0.` seems more correct.
