### ISSUE TITLE
Unison 2.51.2 with Ocaml 4.07.1

### ISSUE THREAD

**Issue by domenic87** [bcpierce00/unison#225]
Hi everyone,
I'm trying to compile unison 2.51.2 on a CentOS 7 machine, on which I already compiled (successfully I think) ocaml 4.07.1.

Once I try to compile unison, as with previous versions (make NATIVE=true UISTYLE=text THREADS=true), I get lots of:

```
Warning 3: deprecated: Stdlib.String.set
Use Bytes.set instead.
```
in different files, than a it performs the linking and stops, without creating the "unison" executable.

Is there a problem with ocaml 4.07.1 ? 

I made the update because on my Mac the mac port version of unison has been updated with ocaml 4.07.1, and runs without any issues, and I need the mac-linux versions to run with the same Ocaml compiler!

Thank you for any suggestions!

**Comment by bcpierce00** [comment]
One possible workaround: Have you tried with OCaml 4.06?  (4.06 and 4.07 should interoperate just fine.)

   - B

**Comment by domenic87** [comment]
If you tell me they can interoperate without problem I'll proceed to compile with OCaml 4.06, I have to be sure not to encounter any problem, as I'm synchronising important files :-)

**Comment by bcpierce00** [comment]
Different versions of OCaml should not be a problem, as long as both are from the last few years.  And incompatible versions will show up as not working at all, not as anything subtle.

**Comment by domenic87** [comment]
I tried also to recompile the old version of OCaml 4.05.0, and unison compilation fails in the same way, so there is something different at play I think...
I don't know how that's possible, as I am using the same procedure as always.
The only change is the use of gcc version 7.3.1 while previously I was using the 6.3.1!

**Comment by domenic87** [comment]
Quick-update: it seems that unison can be found in the src directory after the compilation, and the file seems working fine... I don't know if I can use it as it is, can you confirm it's all right?

**Comment by DavidOliver** [comment]
For what it's worth, I also compiled with these versions yesterday on x86-64 and armhf, got the deprecated warnings, and syncing seems to be working okay. I don't know anything about OCaml and when `Stdlib.String.set` was deprecated in favour of `Bytes.set`, but has this not been changed in Unison to retain support for older versions of OCaml compilers?

As an aside, am I right in thinking that `THREADS=true` is no longer required when compiling as multiple files being transferred at once is no longer experimental?

**Comment by knixeur** [comment]
> Quick-update: it seems that unison can be found in the src directory after the compilation, and the file seems working fine... I don't know if I can use it as it is, can you confirm it's all right?

That's correct, it's all right. The binaries are left in src/ after building, they're copied to INSTALLDIR if you do make install (by default $(HOME)/bin)

**Comment by gdt** [comment]
It seems like this issue is no longer representing an actual problem, in that the submitter is able to build and use unison.  i suggest it be closed.

**Comment by bcpierce00** [comment]
Good idea.
