### ISSUE TITLE
Local backupcurr is not saving the backup file into the same directory as original file after resolving merge conflict

### ISSUE THREAD

**Issue by vovcacik** [bcpierce00/unison#226]
Hi,
I have found out that `unison` configured to

- take a backup of current file (`backupcurr`)
- with local backup location (`-backuplocation local`)

will not make local backup (i.e. the `bak` file is in same directory as original file) when there was a merge conflict resolved in external merge program. Instead it saves the backup file within a directory tree in the local directory. The directory tree duplicates relative path of a file to the replica root.

---

Here is abstract example. First is a test file, then correct backup file path and finally actual backup file path:

- `rootPath/relativePath/test.txt`
- `rootPath/relativePath/.bak.0.test.txt` (**expected**)
- `rootPath/relativePath/relativePath/.bak.0.test.txt` (**actual**)

---

You can reproduce the problem with this script:

```
@echo off
setlocal

set TEMP_DIR=%TMP%\bug_reproduction_%RANDOM%
set UNISON_OPTS=-backupcurrent "Name test.txt" -backuplocation local -merge "Regex .* -> cmd /c notepad CURRENT1 & notepad CURRENT2 & notepad CURRENTARCH & notepad NEW"
REM if you have some merge program installed you may want to use the line below
REM set UNISON_OPTS=-backupcurrent "Name test.txt" -backuplocation local -merge "Regex .* -> merge CURRENT1 CURRENT2 NEW CURRENTARCH"

REM Test set up
mkdir %TEMP_DIR%
pushd %TEMP_DIR%

mkdir a\foo\bar
mkdir b\foo\bar
echo common line > a\foo\bar\test.txt
unison a b %UNISON_OPTS% -batch



REM Test run
echo conflicting line a\foo\bar >> a\foo\bar\test.txt
echo conflicting line b\foo\bar >> b\foo\bar\test.txt
cls
unison a b %UNISON_OPTS%



REM Test tear down
pause
cls
popd

set /P _=Test finished, continue (Enter) to remove temporary files...
rmdir /S /Q %TEMP_DIR%
```

The problem is that the backup after resolving the conflict will be

- located in `%TMP%\bug_reproduction_1234\a\foo\bar\foo\bar\.bak.0.test.txt`
- instead of `%TMP%\bug_reproduction_1234\a\foo\bar\.bak.0.test.txt`
- since the original file is `%TMP%\bug_reproduction_1234\a\foo\bar\test.txt`

---

I think the verbose log reveals the cause of this problem. Here is the interesting part of log when I did non-conflicting change of one file and sync

```
# this is normal log for comparison purposes

[pred] backupcurr 'foo/bar/test.txt' = true
[pred] backupcurrnot 'foo/bar/test.txt' = false
[stasher] stashCurrentVersion of foo/bar/test.txt (drawn from foo/bar/test.txt) in C:/Users/Admin/AppData/Local/Temp/_/b
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/b/foo/bar/test.txt: true 1540832437.000000 1540836143.000000
[fileinfo+] get: FILE
[stasher] stashed [C:/Users/Admin/AppData/Local/Temp/_/b / foo/bar/.bak.0.test.txt] = ABSENT is not equal to new [C:/Users/Admin/AppData/Local/Temp/_/b / foo/bar/test.txt] = 593616de15330c0fb2d55e55410bf994 (or one is a dir): stash!
[stasher+] backupPath f foo/bar/test.txt 0
[stasher+] mkdirectories C:/Users/Admin/AppData/Local/Temp/_/b foo/bar
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/b: false 1540832168.000000 1540832442.000000
[stasher+] mkdirectories C:/Users/Admin/AppData/Local/Temp/_/b foo
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/b: false 1540832168.000000 1540832442.000000
[stasher+] mkdirectories C:/Users/Admin/AppData/Local/Temp/_/b
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/b: false 1540832168.000000 1540832442.000000
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/b/foo: false 1540832437.000000 1540832437.000000
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/b/foo/bar: false 1540832437.000000 1540836143.000000
[copy] Copy.localFile C:/Users/Admin/AppData/Local/Temp/_/b / foo/bar/test.txt to C:/Users/Admin/AppData/Local/Temp/_/b / foo/bar/.bak.0.test.txt
```

and here is conflicting merge resolved with external merge program

```
# this is log of the problematic behaviour

[pred] backupcurr 'foo/bar/test.txt' = true
[pred] backupcurrnot 'foo/bar/test.txt' = false
[stasher] stashCurrentVersion of foo/bar/test.txt (drawn from .unison.mergearch-test.txt) in C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar/.unison.mergearch-test.txt: true 1540836583.000000 1540836590.000000
[fileinfo+] get: FILE
[stasher] stashed [C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar / foo/bar/.bak.0.test.txt] = ABSENT is not equal to new [C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar / foo/bar/test.txt] = ABSENT (or one is a dir): stash!
[stasher+] backupPath f foo/bar/test.txt 0
[stasher+] mkdirectories C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar foo/bar
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar: false 1540832428.000000 1540836590.000000
[stasher+] mkdirectories C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar foo
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar: false 1540832428.000000 1540836590.000000
[stasher+] mkdirectories C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar
[fileinfo+] C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar: false 1540832428.000000 1540836590.000000
[copy] Copy.localFile C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar / .unison.mergearch-test.txt to C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar / foo/bar/.bak.0.test.txt
```

The third and the last line is interesting. The latter illustrates the problem and the first shows imho the culprit. If you diff the two logs you can see that [stashCurrentVersion][] is called with different [fspath][stashCurrentVersion] parameter. Pseudocode:

- The working log is equivalent to

```
let stashCurrentVersion(fspath, path, sourcePathOpt);
stashCurrentVersion(
  "C:/Users/Admin/AppData/Local/Temp/_/b",
  "foo/bar/test.txt",
  "foo/bar/test.txt"
);
```

- and the problematic log goes like this

```
let stashCurrentVersion(fspath, path, sourcePathOpt);
stashCurrentVersion(
  "C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar",
  "foo/bar/test.txt",
  ".unison.mergearch-test.txt"
);
```

The problem is that the `fspath` ends with `/foo/bar`. My guess is that later the `fspath` is concat with `path` parameter to create absolute path for stashing the file resulting in `C:/Users/Admin/AppData/Local/Temp/_/a/foo/bar/foo/bar/.....`.

I don't know OCaml at all, but from looking into the code I think once a file is stashed and no longer needed you

- test if the original file should be backed up
- if so, you turn the stashed file into backup
- hence misconfigured paths for stashing influence also the backups

---

I think this can be fixed if you change

- [files.ml#L1074][] `Stasher.stashCurrentVersion workingDirForMerge localPath1 (Some workingarch);`
- to something like `Stasher.stashCurrentVersion fspath1 localPath1 (Some workingarch);`

---

My environment
- Windows 10 Pro
- `unison version 2.51.2 (ocaml 4.06.1)`
- `.unison` profile dir was removed before testing (but you don't need to do that to reproduce)

[stashCurrentVersion]: https://github.com/bcpierce00/unison/blob/v2.51.2/src/stasher.ml#L410
[files.ml#L1074]: https://github.com/bcpierce00/unison/blob/v2.51.2/src/files.ml#L1074

**Comment by tleedjarv** [comment]
@vovcacik your analysis and also the proposed fix are completely correct. I will open a PR with a fix. After all this time, are you still willing to test the fix?
