### ISSUE TITLE
Unison installer setup

### ISSUE THREAD

**Issue by philippmeisberger** [bcpierce00/unison#229]
I use the great Unison for several years on Linux which works like a charm. Thanks for that! Now I want to synchronize between Linux and Windows. It was hard to get install Unison (GUI) run on Windows. To simplify this process I created an installer using Inno Setup. I packaged GTK 2.24.10 and plink (for SSH connection) into the setup. If you are interested ;)

**Comment by philippmeisberger** [comment]
I uploaded the setup for 2.48.4 to: https://www.pm-codeworks.de/media/downloader.php?file=unison2.48.4_setup.exe

I can provide you the setup source via PR if you want.

**Comment by bcpierce00** [comment]
That sounds like it might be quite useful for some people.  Where in the repo would it live?

**Comment by philippmeisberger** [comment]
I would create a `setup` directory and place the .iss file and some required files there. The setup binary could be placed as an asset. I create a PR for setup sources ;)

**Comment by bcpierce00** [comment]
Thank you!
