### ISSUE TITLE
Feature Request: allow overriding the temporary directory

### ISSUE THREAD

**Issue by mwpastore** [bcpierce00/unison#234]
I'm attempting to sync `/Volumes/foo` (a separate, case-sensitive APFS volume) and `ssh://remote//foo`, with unison initiated on a macOS system, running as a regular user. However, the initial sync fails because the user does not have write access to create a `/Volumes/.unison.foo.deadbeef.unison.tmp` directory. To fix this, I'd like to configure unison to create its tmpdirs elsewhere.

**Comment by gdt** [comment]
I think this is a defect, as unison cannot assume that it has permissions outside the given roots.  Assuming hard until explained otherwise.

**Comment by gdt** [comment]
Please re-verify on 2.51.2 or git master.

**Comment by gdt** [comment]
Feedback timeout.  Feel free to file a new issue with a repro recipe with 2.53.1 or newer.
