### ISSUE TITLE
Lost connection with server: auto retry

### ISSUE THREAD

**Issue by justanotheranonymoususer** [bcpierce00/unison#237]
I'm not sure if that's possible, but I didn't find a solution. I'm using the command-line version to mirror a folder between two Windows computers. My connection is not perfect, and sometimes the connection is lost, so I get this error message. How do I ask unison to reconnect automatically? If possible, reusing my private key password?

I tried using -retry, but that didn't help unfortunately.

**Comment by justanotheranonymoususer** [comment]
Here's a workaround which seems to work:
https://superuser.com/a/280573/269897

**Comment by gdt** [comment]
Dup of #333
