### ISSUE TITLE
Cannot build GTK+2 UI on Debian Sid

### ISSUE THREAD

**Issue by russel** [bcpierce00/unison#240]
The text version built from master/HEAD builds fine and reports version 2.51.2. Trying to build the GTK+2 UI though leads to:
```
ocamlopt: uigtk2.ml ---> uigtk2.cmx
ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -I /usr/lib/ocaml/lablgtk2 -c /home/users/russel/Repositories/Git/Forks/Unison/src/uigtk2.ml
File "/home/users/russel/Repositories/Git/Forks/Unison/src/uigtk2.ml", line 26, characters 24-41:
Warning 3: deprecated: String.capitalize
Use String.capitalize_ascii instead.
File "/home/users/russel/Repositories/Git/Forks/Unison/src/uigtk2.ml", line 97, characters 5-29:
Error: Unbound value Gpointer.region_of_bytes
make: *** [Makefile.OCaml:421: uigtk2.cmx] Error 2
```

**Comment by bcpierce00** [comment]
I tried compiling with “make UISTYLE=gtk2” on OSX, and everything worked (though the executable does give some warnings when it runs).  One possible difference in setup was that I installed labkgtk with “spam install lablgtk” (which installed version lablgtk 2.18.6, and apparently everything else that was needed).

**Comment by russel** [comment]
Debian Sid has:
```
ii  liblablgtk2-ocaml-dev 2.18.5+dfsg-2 amd64        OCaml bindings to Gtk+ version 2
```
it would be good if the build problem goes away with an upgrade – if/when it happens. Might though it be the version of OCaml?
```
ii  ocaml          4.05.0-10+b1 amd64        ML language implementation with a class-based object system
```

**Comment by bcpierce00** [comment]
Maybe so — I’m running OCaml 4.07.0 on this machine.

**Comment by knixeur** [comment]
It seems to be lablgtk related, it's explained here  https://www.onwebsecurity.com/configuration/its-about-the-journey-compiling-64-bit-unison-gtk2-on-windows.html (scroll down to lablgtk errors)

**Comment by gdt** [comment]
Seems like this can be closed, perhaps with an update to the requirements in the build instructions.  It's really clear that there is not enough support bandwidth to be able to support old versions of ocaml and other dependencies, so I'd suggest simply not doing so.
