### ISSUE TITLE
Copyconflict automatic file names not VFat compatible, even if -fat switch is added

### ISSUE THREAD

**Issue by highsciguy** [bcpierce00/unison#243]
The filenames automatically generated for conflicting copies if the -copyconflict option is added to the unison command line (tested with 2.48 and current master) violate vfat file name constraints and thus lead to errors on sync. They contain a "(copy: conflict on ...)" string which obviously stems from the format string
" (copy: conflict%s on %04d-%02d-%02d)"
found at only one instance in src/files.ml
If that string would be changed to something like
"_conflict%s_on_%04d-%02d-%02d)"
the generated file names would be more compatible across file systems.
Note that unison also shows this behaviour when the -fat switch is there.

**Comment by bcpierce00** [comment]
As you say, that's an easy one to fix.  I've done so and will make a PR for it shortly.
