### ISSUE TITLE
Unison ocaml version 

### ISSUE THREAD

**Issue by AireagoirSteam** [bcpierce00/unison#248]
I'm having issues with unison say on disconnecting to a ubuntu vm. 

I've compiled both versions with the same ocaml version and yet it says I haven't.

For windows I followed these instructions except updating lablgtk. 

https://www.onwebsecurity.com/configuration/its-about-the-journey-compiling-64-bit-unison-gtk2-on-windows.html

Each unison version reports ocaml 4.04.0

**Comment by AireagoirSteam** [comment]
I've recompiled unison using ocaml for Windows which uses cygwin. Successful build and I've used the exact same ocaml version on an ubuntu vm those versions being 4.07.1.

I've checked this using unison -version and both match. However when trying to connect over ssh unison says the linux version was compiled by a different version of ocaml.

@bcpierce00 any ideas?

**Comment by gdt** [comment]
I would run "./unison -version" directly on the ubuntu machine, and then search for all other unison binaries and remove them.  Also check your paths for ssh commands.

This is not a bug; I suggest asking on the mailinglist.

This issue should be closed.

**Comment by AireagoirSteam** [comment]
I've also done the same on two windows machines copying the exact same file and still get issues

**Comment by gdt** [comment]
Please follow up on the list.  Make sure that you have exactly one copy of unison on the entire system, and run ./unison -version as requested.
