### ISSUE TITLE
How to let fsmonitor react only on close_write 

### ISSUE THREAD

**Issue by Uatschitchun** [bcpierce00/unison#249]
Hi, more a question or a feature wish...

My scanner (hp officejet) is able to scan into network folders. So far, so good. 
Problem is, if a scan consists of more than one page, it opens the file after the first page and keeps it open, until the last page is scanned, writing each scanned page into the file after the page is scanned. 
I like to feed these documents into my DMS' Scaninput folder, but the DMS seems to be watching for on_create. So it fetches the files, although they aren't finished. 
To accomplish this, I thought of scanning into a tmp folder, use Unison to watch for changes and sync when a on_write_close is received. But unfortunately, union's fsmonitor seems to also react to on_create, making it sync unfinished files :-(

Question:
Is there a way to let fsmonitor react only on events like close_write, on_delete, etc, but not on_create? 

I tested with inotifywait and am sure, if watching for on_write_close, the file gets processed only when the last page is scanned. 

Right now I do use incron together with Unison, as incron is able to watch for on_write_close 

I've had a look into the sources and from what I see, it should be possible. 

Is fsmonitor missing things, if _not_ watching for on_create?

Any tips?

**Comment by gdt** [comment]
This feels like asking for a feature in unison to work around a bug in some other software.  Or perhaps it's a support question.  Please follow up on the mailinglist.
