### ISSUE TITLE
Change hub in star topology

### ISSUE THREAD

**Issue by zabudskyi** [bcpierce00/unison#250]
Currently we have one hub and two spokes. What should we do if we decide to replace hub with new server or with spoke? Is it enough just to define new cron tasks at new hub server. Or is it safer to remove `~/.unison/*` and `/sync_path/.unison*` before?

**Comment by bcpierce00** [comment]
No need to remove anything as long as the new machine(s) have different names from the old one(s).  Unison will resynchronize everything.

**Comment by gdt** [comment]
This can be closed.  It was a question and not a bug, and it was answered.
