### ISSUE TITLE
unmarshiling error

### ISSUE THREAD

**Issue by AireagoirSteam** [bcpierce00/unison#253]
I get a fatal disconnect after trying to get to my windows 10 laptop running the windows 10 openssh server. The unison versions are the exact same file that i compiled in cygwin with ocaml for windows.

![image](https://user-images.githubusercontent.com/22620774/53833674-047ad280-3f81-11e9-827c-95fc24ba8f2c.png)

any help appreciated.

**Comment by gdt** [comment]
See #375
