### ISSUE TITLE
Add titlebar showing roots (or something) in GTK UI

### ISSUE THREAD

**Issue by JMarianoIFSTTAR** [bcpierce00/unison#254]
Hi

Say that you launch several "quick and dirty" unison instances, like
unison-gtk   dir1/.../a  dir2/.../a
unison-gtk  dir1/.../b  dir2/../b
...

Then you got several gui instances named "Unison [default]" (title bar) which are almost anonymous since you can't distinguish instance "a" from instance "b" from ... because the widths of the dirs column are to small too show the effective names of the concerned directories (you only can read something like "dir1/..." and "dir2/..." 
Extending the window (full-screen width) doesn't solve the problem since the column widths are fixed and remain too small. And there is no "hover" mouse  information (which would be interesting)

Is there any way to identify who's who ? 
(this is very confusing when there is no need  define a profile)

thanks

**Comment by tleedjarv** [comment]
There's a simple patch to fix this. It'll display the roots exactly as specified by user (directly or in profile). I didn't choose the canonical forms because these tend to become too long for title bar.
```diff
diff --git a/src/uigtk2.ml b/src/uigtk2.ml
index 194be63..1d677d2 100644
--- a/src/uigtk2.ml
+++ b/src/uigtk2.ml
@@ -2658,9 +2658,11 @@ let createToplevelWindow () =
       | "default", _  -> label
       | _             -> Format.sprintf "%s (%s)" p label
     in
+    let roots = String.concat " ↔ " (Globals.rawRoots ()) in
+    let roots = if roots = "" then "" else "   |   " ^ roots in
     toplevelWindow#set_title
       (if s = "" then myNameCapitalized else
-       Format.sprintf "%s [%s]" myNameCapitalized s);
+       Format.sprintf "%s [%s]%s" myNameCapitalized s roots);
     let s = if s="" then "No profile" else "Profile: " ^ s in
     profileLabel#set_text (transcode s)
   in

```

Happy to open a PR if this seems acceptable.
