### ISSUE TITLE
New files permissions

### ISSUE THREAD

**Issue by spajak** [bcpierce00/unison#257]
Hi, 

I have a question: how to change new files default permissions to always be 0777? So far new files created by unison have 0600 with is not what I want.
I'm using local Linux roots.

Best regards

**Comment by brabalan** [comment]
The permissions depend on the OS used for synchronization (see https://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#perms).  You could try using the `dontchmod` option so see if it helps.

**Comment by fenugrec** [comment]
I'm in a similar situation, and I don't see a clear solution.

- change the umask (at both ends ?) => can't really change it just for unison, and possibly not desirable to have permanently set to 0777 by default for the user
- make an ssh wrapper that runs on the server that changes umask only for the duration of the sync ? yuck
- setfacl on the remote directory ? I tried this, with dontchmod=1 and perms=0, and it's still not working (group perms is still 0)

**Comment by fenugrec** [comment]
Ah. Ok, so setfacl is a usable solution. Here's what I did (**warning !**  this may allow wider access than desired (any group ?), I'm not very familiar with ACLs. Use with caution)

I ran these lines on both ends (local and remote):

```
# change default ACL recursively
$> sudo setfacl -Rdm g::rwx synced_folder/

# change current ACL recursively
$> sudo setfacl -Rm g::rwx synced_folder/
```

**Comment by gdt** [comment]
This does not seem to be a defect or feature request.  Please follow up on the mailinglist.
