### ISSUE TITLE
Unison crash if it is not able to connect to server

### ISSUE THREAD

**Issue by Mannshoch** [bcpierce00/unison#259]
In Unison 2.51.2 from snap-store and in Unison 2.48.4 from ubuntu store. If Unison is not able to connect to server and Prompt me a pop-up Unison is crashing after click on close.

**Comment by gdt** [comment]
Please explain if this is gui vs text, and the connection method you are using.

**Comment by Mannshoch** [comment]
Sorry I not anymore remembering using this tool since it not worked as wished in 2019/04

**Comment by gdt** [comment]
If someone is able to test what happens when connection is refused or times out, that would be helpful.

**Comment by tleedjarv** [comment]
Such connection errors occur (intentionally) often during my own testing. The error is reported correctly in both TUI and GUI and closing is graceful, no crash.

Could be something related to snap.

**Comment by gdt** [comment]
Seems like this is resolved or was a snap-only problem.  Anyone should feel free to reopen or file a new issue with a repro recipe.
