### ISSUE TITLE
Mixing Versions 2.48.4 and 2.51.2

### ISSUE THREAD

**Issue by wrogner** [bcpierce00/unison#261]
I try to migrate from Ubuntu to MacOS, leaving my Ubuntu Server in place.
On Ubuntu version 2.48.4 is installed by default (both client and server)
On Mac, due to the new APFS file system, version 2.51.2 seems the way to go.

Unfortunately I cannot connect from the Mac to my Ubuntu server (Ubuntu -> Ubuntu works like charm)

Q: Is 2.51.2 backward compatible in file format or do I need to compile and install a new unison 2.51.2 on the server (which would make keeping both versions in sync a tedious task)

**Comment by wrogner** [comment]
did some more fiddling. Love this error message:

unison -testServer  -ui 'text' c.v ssh://wolf@s4//home/wolf/c.v
2019-04-28 16:47:06.026 Unison[3903:70346] Calling nonGuiStartup
Unison 2.51.2 (ocaml 4.04.0): Contacting server...
Password: 
Fatal error: Received unexpected header from the server:
 expected "Unison 2.51 with OCaml >= 4.01.2\n" but received "Unison 2.48\n\000\000\000\000\017", 
which differs at "Unison 2.4".
This can happen because you have different versions of Unison
installed on the client and server machines, or because
your connection is failing and somebody is printing an error
message, or because your remote login shell is printing
something itself before starting Unison.

However, I would still like to run under this scenario

**Comment by brabalan** [comment]
The major number (`2.48` or `2.51`) need to be the same on both machines.
