### ISSUE TITLE
Unison 2.51.2

### ISSUE THREAD

**Issue by wrogner** [bcpierce00/unison#263]
Unison for macOS = 2.51.2
Is there a .deb package for Ubuntu/Debian that matches this version?
If so, where can one find it

**Comment by xraynaud** [comment]
Hello, I have forked this rep yesterday to add everything to build a deb package: https://github.com/xraynaud/unison. It should work for debian testing. Please open an issue there if you have problem
@bpierce: I can make a pull request if you are interested.

**Comment by bcpierce00** [comment]
Hi Xavier,

I’m happy to include the stuff needed to build a deb package in the main repo, if that makes things easier for you.  (I assume it won’t introduce much clutter.)  If both ways are equally easy, then I suppose it’s slightly cleaner to leave the packaging infrastructure out of the main repo, since Unison gets packaged for several distributions.

**Comment by xraynaud** [comment]
Hi Benjamin, 
At the moment, it might then be better to keep things separated as debian has an old lablgtk lib and I had to revert commit 2e7ea9 to compile the gtk2 interface. Thanks for this wonderful software.

**Comment by melikyuksel** [comment]
Hi Xavier and Benjamin,

Is the reason Debian still has version 2.48 of this application because it still has an old library dependency? How could we go about solving this?

**Comment by mintsoft** [comment]
@melikyuksel II would assume that's on Debian 9; it's probably fine on Debian 10. I'd guess that the package is out of date on debian as the maintainer is unaware of the new releases as they've moved to Github, it might be worth raising it against the package and the maintainer can make a determination then: https://packages.debian.org/buster/unison

**Comment by gdt** [comment]
I would suggest closing this; it seems to be a Debian issue not a unison issue.

**Comment by bcpierce00** [comment]
Thanks
