### ISSUE TITLE
Add an option to place backups only on server

### ISSUE THREAD

**Issue by simeonkr** [bcpierce00/unison#268]
The combination of preferences
```
backupcurrent = Name *
backuplocation = central
backupdir = /path/to/backup/dir
```
places backups in the path `/path/to/backup/dir` of all replicas. This is inconvenient because not all replicas might have such a path (thus forcing the user to use symlinks) and also the user might only want a backup in one location only (I personally do not need local backups on my personal computer, just on my server).

Since it might be too much of a mess to have separate backup paths for each root, I think a good compromise would be to have at least an option which ensures that (`central`) backups are created only on the server.

For some reason I was able to emulate this behavior by using a path which only exists on the server, but this only worked when the `backupcurrent` option was not used. (I am not sure what the intended behaviour is supposed to be in this case.)

**Comment by donjan** [comment]
I'm also interested in this feature.
Using a home server to bidirectionally sync multiple (five) devices in a star setup, I don't care about adding the additional disk space or hunting down to restore old versions on each one of them.
`backuplocation = local` apparently only creates a backup on the destination machine, but depending on the direction this sprawls backup files everywhere.
Having a "merged" history just on the server, which has plenty of space and backs up on an off-site mounted share, should be enough.

**Comment by gdt** [comment]
Please bring this up on unison-hackers.   I can't understand precisely what's being asked for, and I suspect others will have some useful thoughts.

**Comment by gdt** [comment]
Linked to https://github.com/bcpierce00/unison/wiki/Feature-Requests
