### ISSUE TITLE
Offical unison docker image

### ISSUE THREAD

**Issue by mhubig** [bcpierce00/unison#274]
Hi @bcpierce00, I thought it would be very nice if there was an offical unison docker image on docker hub. So I prepared a dockerfile repo for this purpose. If this is ok with you, i'll try to submit it to https://github.com/docker-library/official-images.

**Comment by bcpierce00** [comment]
Sounds like a good idea!  Thanks for doing this.

    - Benjamin

**Comment by gdt** [comment]
@mhubig If you have done this, please submit some kind of patch to the web/docs to point to it.

As this PR does not describe an in-scope feature request, I'll likely close it on submission of doc change request or timeout.

**Comment by gdt** [comment]
Please do submit a web/docs patch when you've submitted this.   I don't see a reason to have this issue open now.
