### ISSUE TITLE
Reads data without writing it

### ISSUE THREAD

**Issue by Pascal666** [bcpierce00/unison#275]
I mounted two 10TB USB drives.  Each had about 4.5TB of data in around 10,000 files, with around 20MB/100 files in common (so the vast majority on each drive was unique data & filenames).  All files either only existed on one side or were identical on both.  I needed to copy all files that did not already exist on both drives, to the other one.

I ran the command "unison 10tb 10tb2".  I watched it spend about an hour reading from one of the drives without writing any data to the other one, before I killed it.  I've attached output of "unison 10tb 10tb2 -debug all" and "unison 10tb 10tb2 -debug verbose".  I ended up running "cp -rpn" in each direction.

unison version 2.40.128
CentOS Linux release 7.6.1810

[unison.debug.txt](https://github.com/bcpierce00/unison/files/3462576/unison.debug.txt)

**Comment by bcpierce00** [comment]
You probably just didn't wait long enough -- the first thing Unison does is to scan the contents of the entire replica on both sides, and 4.5Tb takes quite a while to process.  If you are certain there are no files that exist on both sides but have different contents, you can use various options to speed things up -- see the manual.

**Comment by Pascal666** [comment]
I do not have 4.5TB of ram.  There is no reason for it to read in a file that does not already exist on both sides, without writing it out to the other side at the same time.
