### ISSUE TITLE
unison does not build with ocaml 4.08.1 (on mac)

### ISSUE THREAD

**Issue by samfu1994** [bcpierce00/unison#277]
looks like the ocaml is breaking the build.

```
4c327596e4c3:lib hafu$ ocaml -vnum
4.08.1


4c327596e4c3:lib hafu$ brew install --build-from-source unison
==> Downloading https://github.com/bcpierce00/unison/archive/v2.51.2.tar.gz
Already downloaded: /Users/hafu/Library/Caches/Homebrew/downloads/558b42a95b847ce902780f27b7bc703d8c70b855f07b629a826abc807b99949c--unison-2.51.2.tar.gz
==> make UISTYLE=text
Last 15 lines from /Users/hafu/Library/Logs/Homebrew/unison/01.make:
ocamlopt: system.ml ---> system.cmx
ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -ccopt -mmacosx-version-min=10.5 -c /private/tmp/unison-20190827-30585-11nowv6/unison-2.51.2/src/system.ml
File "/private/tmp/unison-20190827-30585-11nowv6/unison-2.51.2/src/system.ml", line 1:
Error: The implementation /private/tmp/unison-20190827-30585-11nowv6/unison-2.51.2/src/system.ml
       does not match the interface system.cmi:
       Values do not match:
         val link : ?follow:bool -> string -> string -> unit
       is not included in
         val link : fspath -> fspath -> unit
       File "/private/tmp/unison-20190827-30585-11nowv6/unison-2.51.2/src/system/system_intf.ml", line 70, characters 0-35:
         Expected declaration
       File "/private/tmp/unison-20190827-30585-11nowv6/unison-2.51.2/src/system/system_generic.ml", line 50, characters 4-8:
         Actual declaration
make[1]: *** [system.cmx] Error 2
make: *** [text] Error 2

```

**Comment by bcpierce00** [comment]
Sigh.

Which Unison version is this?

  - Benjamin

**Comment by llelf** [comment]
FWIW, `master` (2b1ad6c4c11a31ed88c04fb78c733011f4b554f9) works for me [NB I don’t use brew]
```bash
~/S/unison--bcpierce00› ./src/unison -version
unison version 2.51.2 (ocaml 4.08.1)
```

**Comment by mvhulten** [comment]
I get the same error for Unison 2.51.2 with OCaml 4.09.0 (on RHEL7).

**Comment by jbclements** [comment]
This problem affects users of MacPorts (like me!); cf. 

https://trac.macports.org/ticket/58852

The commit history contains a provocatively named commit, 23fa129254a3304902739fc9899, with the comment

"Compatibility with OCaml 4.08".

Maybe time for a new release?

**Comment by josh-berry** [comment]
Also seeing this same compiler error building Unison 2.51.2 on Linux with OCaml 4.09.

It looks like Arch Linux patched Unison to work around this problem: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/unison&id=53430f5c9032dd19506dce6479840be4e768a0fe

**Comment by erezny** [comment]
This issue was fixed in https://github.com/bcpierce00/unison/pull/255 when the author of the Arch linux patch submitted the patch to this repo. 
https://github.com/bcpierce00/unison/commit/23fa129254a3304902739fc989950cc747d1e0b3

**Comment by drmuelr** [comment]
> This issue was fixed in #255 when the author of the Arch linux patch submitted the patch to this repo.
> [23fa129](https://github.com/bcpierce00/unison/commit/23fa129254a3304902739fc989950cc747d1e0b3)

Concur; I was seeing the same issue trying to build on RHEL7 with OCaml 4.08.1. Applying a cherry-pick of 23fa129254a3304902739fc989950cc747d1e0b3 onto [v2.51.2](0176188107aa9fb82657ed9fcd92081f5a61c76a) fixed the problem for me.

**Comment by gdt** [comment]
Is this still an issue, with the latest release?

(4.08 seems quite old; it seems like everyone should be on 4.09 by now.)

**Comment by samfu1994** [comment]
sorry, looks like it was fixed, closing.
