### ISSUE TITLE
Write some progress into log indicating possible ETA

### ISSUE THREAD

**Issue by teneri66** [bcpierce00/unison#28]
Especially useful when unison is running with "-repeat watch" setting in the background. While in the foreground progress it displays what file/directory is currently being processed. On large roots or high system load it can take 10-20 minutes to accomplish.

Having some periodic information in the log is preferable to ensure it's running properly and when to expect new changes applied.

**Comment by bcpierce00** [comment]
Happy to include this if someone wants to submit a pull request.
