### ISSUE TITLE
"No space left on device" message not helpful

### ISSUE THREAD

**Issue by WyseNynja** [bcpierce00/unison#280]
I was syncing from my laptop to my server with `unison -prefer newer $local $remote` and started getting this error: `Error: Io(Os { code: 28, kind: Other, message: "No space left on device" })`

As far as I can tell, I have plenty of space on both destinations.
Local:
```
$ unison -version
unison version 2.51.2 (ocaml 4.07.0)

$ df -h .
Filesystem     Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1  466Gi  378Gi   86Gi    82% 2823365 9223372036851952442    0%   /
```

Remote:
```
$ unison -version
unison version 2.51.2 (ocaml 4.05.0)

$ df -h .
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/tank--vg-root  468G  7.7G  436G   2% /
```

Is there any way to get more information on this error? It would be helpful to know on what host and in what directory it is trying to write.

**Comment by WyseNynja** [comment]
I just realized my ocaml versions are different. Could that be related?

**Comment by bcpierce00** [comment]
Unlikely to be related to different OCaml versions.  

Best way to get more information about what’s happening when it fails is to add “-debug all” to the command line.

**Comment by WyseNynja** [comment]
I ran with "-debug all" and noticed that the problem is actually with unison-fsmonitor. I was experimenting with it and didn't realize that changing `-repeat=watch` to `-repeat=1` doesn't set `watch=false`. Once I changed it to `-watch=1 -repeat=false` it started working again.

**Comment by nvartolomei** [comment]
Got the same error today. Fixed by bumping the `fs.inotify.max_user_watches` sysctl. The message would have been much more helpful if it included a stacktrace or at least an annotation about the executed operation when error happened.

```sh
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
```

**Comment by nvartolomei** [comment]
I'm using https://github.com/autozimu/unison-fsmonitor as fsmonitor. Is it possible that the error is actually coming from that rust binary?

**Comment by gdt** [comment]
@nvartolomei Please make sure you are running 2.51.3 or later before reporting bugs, and please describe the version.   I have no idea what's in the autozimu repo; problems with that should probably be reprorted there.

**Comment by nvartolomei** [comment]
I was able to confirm that the cause of the error is not unison but the 3rd party unison-fsmonitor replacement. The confusion/ambiguity comes from the fact that unison just streams stderr e2e without any additional context.
