### ISSUE TITLE
Linking against lbigarray fails (Mac OS 10.14.6, Unison 2.51.2, Homebrew)

### ISSUE THREAD

**Issue by heipei** [bcpierce00/unison#282]
Hey folks, hitting an issue compiling Unison 2.51.2 on Os X 10.14.6. I've downloaded the source from here, applied the same patches as macports and a 4.08 compatibility-patch from Arch Linux.

Running this command:
`MACOSX_DEPLOYMENT_TARGET=10140 THREADS=true UISTYLE=mac14 make all`
This is what I get:

```
Ld /Users/jojo/Downloads/unison-2.51.2/src/uimac14/build/Default/Unison.app/Contents/MacOS/Unison normal x86_64 (in target: uimac)
    cd /Users/jojo/Downloads/unison-2.51.2/src/uimac14
    export MACOSX_DEPLOYMENT_TARGET=10.14
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/Users/jojo/Downloads/unison-2.51.2/src/uimac14/build/Default -F/Users/jojo/Downloads/unison-2.51.2/src/uimac14/build/Default -F/Users/jojo/Downloads/unison-2.51.2/src/uimac14 -filelist /Users/jojo/Downloads/unison-2.51.2/src/uimac14/build/uimacnew.build/Default/uimac.build/Objects-normal/x86_64/Unison.LinkFileList -mmacosx-version-min=10.14 -Xlinker -object_path_lto -Xlinker /Users/jojo/Downloads/unison-2.51.2/src/uimac14/build/uimacnew.build/Default/uimac.build/Objects-normal/x86_64/Unison_lto.o -fobjc-link-runtime -L/usr/local/lib/ocaml -lunix -lthreadsnat -lcamlstr -lbigarray -lasmrun -framework Cocoa -framework Security -framework ExceptionHandling -Xlinker -dependency_info -Xlinker /Users/jojo/Downloads/unison-2.51.2/src/uimac14/build/uimacnew.build/Default/uimac.build/Objects-normal/x86_64/Unison_dependency_info.dat -o /Users/jojo/Downloads/unison-2.51.2/src/uimac14/build/Default/Unison.app/Contents/MacOS/Unison
ld: library not found for -lbigarray
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I do have the file `/usr/local/lib/ocaml/bigarray.a` on my system. Any hints? Any further info needed?

**Comment by heipei** [comment]
I eventually figured it out, just had to add a symlink from libbigarray.a to bigarray.a in that directory.

**Comment by alanshutko** [comment]
I think we should reopen this. This is a good workaround, but we should try to figure out how to compile this without requiring the user to add symlinks.

**Comment by bcpierce00** [comment]
Agreed!

**Comment by lucasmacad** [comment]
> I eventually figured it out, just had to add a symlink from libbigarray.a to bigarray.a in that directory.

Same fix helped me out trying to install megam on OSX Catalina for some NLTK work I was doing.  Many thanks!
L

**Comment by mroi** [comment]
I believe 23bf53e has fixed this issue. I still had this problem with the 2.51.3 release version, but current HEAD builds without any bigarray workarounds.

**Comment by gdt** [comment]
@mroi Thanks for pointing that out and linking to the commit.

**Comment by walzter** [comment]
Hello! @heipei Thank you for sharing this! I had a similar issue with MEGAM, and getting the "zsh: exec format error". The steps I did to resolve this were as follows:

1. Install ocaml with brew 
2. Download the MEGAM from this [link](http://hal3.name/megam/megam_src.tgz)
3. Untar the file & cd into the directory 
4. In the Makefile edited the following: 

- WITHSTR =str.cma -cclib -lcamlstr (this is the one I used) 
- WITHBIGARRAY =bigarray.cma -cclib -L/usr/local/lib/ocaml -cclib -lbigarray (I had to tell it to look for the lbigarray file one folder down, from ~/caml, so ~/ocaml
- WITHCLIBS =-I /usr/local/lib/ocaml/caml/ (the path to where to find the caml files)

6. Run "make opt" (in my case, this is what I needed) 
7. The resulting file will be in the untared megam directory with the name "megam.opt" 

This took me a while to figure out, but I hope it helps, I didn't have to symlink the files, rather tell megam where the other files where located.
