### ISSUE TITLE
Add support for creating symlinks on Windows (from symlinks on POSIX, when syncing)

### ISSUE THREAD

**Issue by BenMorel** [bcpierce00/unison#283]
Hi, first of all thanks for this great piece of software!

I'm syncing my Windows 10 machine with a Fedora Linux VM. Everything works as expected, expect that symlinks are not propagated:

> skipped: example.com/vendor/bin/doctrine (path /home/ben/Projects/example.com/vendor/bin/doctrine is a symbolic link)

Now that Windows supports symlinks (through `mklink`), is there any reason why these can't be propagated to Windows?

**Comment by bcpierce00** [comment]
I'd be happy to consider a PR for this if someone wants to implement it.  The main thing to check is whether the Windows support for symlink has made it into OCaml's posix library by now.

**Comment by zommuter** [comment]
Sounds great! However make sure that permissions are considers if this is implemented, e.g. network shares may or may not permit them, and even locally admin rights might be necessary depending on domain setup.

**Comment by rbresalier** [comment]
I have been able to use unison with symbolic links in Windows. I have documented how I do it here: http://robsnotebook.com/symbolic-links-in-windows-with-unison/

**Comment by tleedjarv** [comment]
Windows symlink support was added in OCaml 4.03. I may give a Unison implementation a try (of course, the limitations indicated by other comments will remain).

**Comment by tleedjarv** [comment]
You may want to test PR #535. This works without Cygwin. You may have to manually set the preference `links` to `true` (there is some trivial auto-detection but it is unable to cover all cases). Special privileges are required.
