### ISSUE TITLE
Issues when removing / recreating huge dirs

### ISSUE THREAD

**Issue by BenMorel** [bcpierce00/unison#284]
I'm synchronizing a Windows host with a Linux Fedora guest VM. The Unison server is on Linux, client on Windows.

Sometimes, if inside the Linux guest I remove the `vendor` directory of a PHP project, and recreate it shortly after using `composer install`, I get into one of the following issues:

- sometimes the window suddenly freezes in the middle of the transfer, in a state like `71%  00:25 ETA`; waiting does not help, and `unison` does not respond to `Ctrl+C`; I have to force-quit it from the task manager;
- sometimes I get the following error:
    > Fatal error: Server: Filesystem watcher error: file '/home/ben/Projects/example.com/vendor/composer/7894921e/symfony-translation-4e3e39c/Resources' does not exist

This is, even though I'm waiting for the sync to complete after `rm -rf vendor` and before `composer install`.

Note that I'm using a mix of `prefer` and `preferpartial` to always resolve conflicts automatically in one way or another (this is configured per-directory). In this case, `vendor` "belongs" to the guest, and is always resolved in favour of the guest.

Is there any way I can dump a full log while doing a repro, to help you figure out where the problem lies?

**Comment by gdt** [comment]
Please retest with 2.52.2 or master,and explain your versions.

However, it is likely you are reporting a real bug that still exists.

**Comment by gdt** [comment]
feedback timeout.  Feel free to reopen with high-quality bug data on the most recent release.
