### ISSUE TITLE
Configure how hostnames are displayed

### ISSUE THREAD

**Issue by nthiery** [bcpierce00/unison#286]
We are using `unison` to help our students synchronize their work between our computer labs and a separate web server (JupyterHub) that they use to work from home (alas the two systems use independent home directories). This goes through the text UI, and since they are beginners, they get easily confused. Two sources of confusion are that:

- Since they run unison from the web server, the name "local" for the local host actually refers to the web server which, for them, does not appear as local.
- The machine from the computer lab `unison` connects to has an obscure name.

Would it be possible to configure how the unison text UI *displays* the local and remote host names?
In this case, we would want to have something like:
```
    jupyterhub                          computer lab
                         <---- dir          xxxxx  [f]
```

Thanks in advance! (and thanks a lot for unison in the first place!)

**Comment by bcpierce00** [comment]
The most efficient way to proceed would be to just grab the source code and make this change yourself for local use.  If you are just using the text UI, all you need is the basic OCaml compiler (version 4.07 may work better than 4.08).  Should be fairly easy.
