### ISSUE TITLE
Support `includes` as well as `excludes`

### ISSUE THREAD

**Issue by stevebaxter** [bcpierce00/unison#288]
We have a complex, legacy cross-platform source hierarchy with code for Mac, Windows and Emscripten. We want to dockerise the Emscripten build, but it's very slow, hence we want to use docker-sync.

Our problem is that if we exclude folders using sync_excludes we would have hundreds of entries. It would also require constant maintenance, as every time someone adds a new folder that isn't relevant to the Emscripten code we would want to exclude it.

We have raised this issue with the docker-sync team, unfortunately they can't do this because Unison doesn't support this:

https://github.com/EugenMayer/docker-sync/issues/680

Would it be possible to add an "includes" property that controls what is included in the sync? "Excludes" should still be honoured (so we should include all files that match "includes" and that don't match "excludes").

**Comment by bcpierce00** [comment]
I'm not 100% clear on what behavior you are missing.  E.g., have you considered using the path preference or using a very general exclude pattern with some more specific exclude not patterns?

**Comment by stevebaxter** [comment]
Thanks for the quick reply! Is it possible to exclude everything and then "not exclude" specific paths? That would probably get us to where we need to be.

**Comment by bcpierce00** [comment]
Yep
