### ISSUE TITLE
release 2.48 identifies itself as 2.47

### ISSUE THREAD

**Issue by olafhering** [bcpierce00/unison#289]
While trying to upgrade the rpm package from version `md5 5334b78c7e68169df7de95f4c6c4b60f  unison-2.48.4.tar.gz` to the current git tag v2.48.15v4, commit add890624885445558d9bf079f36dffaaa36c7b4, I noticed this diff between old and new:
````
diff -p -purNx .gitignore src/strings.ml unison-2.48.15/strings.ml   
--- src/strings.ml      2016-05-23 18:40:05.000000000 +0200
+++ unison-2.48.15/strings.ml   2017-12-18 13:23:54.000000000 +0100  
@@ -4,7 +4,7 @@
 let docs =
     ("about", ("About Unison",
      "Unison File Synchronizer\n\
-      Version 2.48.4\n\
+      Version 2.47.4\n\
       \n\
       "))
 ::
````

I suggest to fix this properly in the `unison-2.48` branch, and cut a new maintenance release with the fix for ocaml 4.09.

**Comment by gdt** [comment]
As I understand it 2.48 is not longer being supported, so I would suggest that the caution about old releases be strengthened and this issue be closed as applying to an unsupported version.

**Comment by gdt** [comment]
2.48 is not supported.
