### ISSUE TITLE
2.51.2 for Synology

### ISSUE THREAD

**Issue by seguri** [bcpierce00/unison#290]
Hello everyone,

Can anybody please help me compiling a binary for my Sinology DS216SE?

	uname -a
	Linux nas 3.2.40 #24922 Mon Aug 19 12:09:30 CST 2019 armv7l GNU/Linux synology_armada370_216se

I've currently tried with:

	docker run -it -v ~/tmp/ocaml:/home/opam/src ocaml/opam2-staging:debian-9-ocaml-4.08-linux-arm32v7
	curl -L https://github.com/bcpierce00/unison/archive/v2.51.2.tar.gz | tar xz
	cd unison-2.51.2
    git apply from https://git.archlinux.org/svntogit/packages.git/plain/trunk/4.08-compatibility.patch?h=packages/unison
	make UISTYLE=text

But when I run `unison nas` from my mac (2.51.2), I get:

    Proceed with propagating updates? [] g
    Propagating updates

    UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 19:55:18.76 on 12 Oct 2019
    [BGN] Copying  from /a to //nas//a
    Failed: Fatal error during unmarshaling (input_value: ill-formed message),
    possibly because client and server have been compiled with differentversions of the OCaml compiler.
    Fatal error: Fatal error during unmarshaling (input_value: ill-formed message),
    possibly because client and server have been compiled with differentversions of the OCaml compiler.

**Comment by seguri** [comment]
I've taken a closer look at unison for macOS:

	unison version 2.51.2 (ocaml 4.06.1)

And changed the image I was using:

	docker run -it -v /tmp/unison:/home/opam/src ocaml/opam2-staging:debian-10-ocaml-4.06-linux-arm32v7
	cd ~/src
	curl -L https://github.com/bcpierce00/unison/archive/v2.51.2.tar.gz | tar xz
	cd unison-2.51.2
	make UISTYLE=text STATIC=true

Back to my host:

	scp /tmp/unison/unison-2.51.2/src/unison synology:/usr/bin

This now seems to work, but I'd be glad if someone could validate what I've done before trusting this binary with my data :)

**Comment by bcpierce00** [comment]
Not sure about the details, but if it seems to be working, you should be fine -- there are plenty of safety checks when Unison changes any data.

**Comment by ACGarland** [comment]
I've been trying to build a version of unison for synchronizing my Synology DS418 with my MBP (running Catalina 10.15.4).  I was able to build a version for the DS418 following seguri's tips using docker with the default 'debian' container, after updating the package manager and installing curl, make, and ocaml.  That produced `unison version 2.51.2 (ocaml 4.05.0)`

Unfortunately, it wouldn't work against the brew-installed version of unison (also 2.51.2, but built against ocaml 4.08.1).  I ran into the fatal ill-formed message error.  (As an aside, it is pretty confusing/frustrating that matching versions of unison can't talk to one another--as with the introduction of ocaml the external version number is no longer sufficient to indicate compatibility.)

So I embarked on building unison and ocaml on my MBP.  ocaml built just fine, but I ran into a linking problem--which I have yet to understand (below)--for unison 2.51.2 under Catalina.

I was able to successfully build a matching `unison version 2.51.2 (ocaml 4.05.0)` on another mac I have running High Sierra--and that seems to work OK against the matching version on the DS418. But I'm still unable to sync against my Catalina machine (simply running the High Sierra-built binary on Catalina doesn't work reliably--it will spit out the version fine, but during a real-world sync it hits the fatal ill-formed message error).

Any tips or pointers would be appreciated...

The linker error building unison 2.51.2 against ocaml 4.05.0 on Catalina is as follows
`Linking unison
ocamlopt -verbose -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -ccopt -mmacosx-version-min=10.5 -o unison   unix.cmxa str.cmxa bigarray.cmxa ubase/rx.cmx unicode_tables.cmx unicode.cmx bytearray.cmx system/system_generic.cmx system/generic/system_impl.cmx system.cmx ubase/projectInfo.cmx ubase/myMap.cmx ubase/safelist.cmx ubase/util.cmx ubase/uarg.cmx ubase/prefs.cmx ubase/trace.cmx ubase/proplist.cmx lwt/pqueue.cmx lwt/lwt.cmx lwt/lwt_util.cmx lwt/generic/lwt_unix_impl.cmx lwt/lwt_unix.cmx uutil.cmx case.cmx pred.cmx fileutil.cmx name.cmx path.cmx fspath.cmx fs.cmx fingerprint.cmx abort.cmx osx.cmx external.cmx fswatch.cmx props.cmx fileinfo.cmx os.cmx lock.cmx clroot.cmx common.cmx tree.cmx checksum.cmx terminal.cmx transfer.cmx xferhint.cmx remote.cmx globals.cmx fswatchold.cmx fpcache.cmx update.cmx copy.cmx stasher.cmx files.cmx sortri.cmx recon.cmx transport.cmx strings.cmx uicommon.cmx uitext.cmx test.cmx main.cmx linktext.cmx osxsupport.o pty.o bytearray_stubs.o
+ clang -arch x86_64 -c -o '/tmp-tony/camlstartup196b3b.o' '/tmp-tony/camlstartupa35299.s'
+ gcc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT -Wl,-no_compact_unwind -o 'unison'   '-Llwt' '-Lubase' '-Lsystem' '-Lfsmonitor' '-Lfsmonitor/linux' '-Lfsmonitor/windows' '-Lsystem/generic' '-Llwt/generic' '-L/usr/local/lib/ocaml' -mmacosx-version-min=10.5 '/tmp-tony/camlstartup196b3b.o' '/usr/local/lib/ocaml/std_exit.o' 'linktext.o' 'main.o' 'test.o' 'uitext.o' 'uicommon.o' 'strings.o' 'transport.o' 'recon.o' 'sortri.o' 'files.o' 'stasher.o' 'copy.o' 'update.o' 'fpcache.o' 'fswatchold.o' 'globals.o' 'remote.o' 'xferhint.o' 'transfer.o' 'terminal.o' 'checksum.o' 'tree.o' 'common.o' 'clroot.o' 'lock.o' 'os.o' 'fileinfo.o' 'props.o' 'fswatch.o' 'external.o' 'osx.o' 'abort.o' 'fingerprint.o' 'fs.o' 'fspath.o' 'path.o' 'name.o' 'fileutil.o' 'pred.o' 'case.o' 'uutil.o' 'lwt/lwt_unix.o' 'lwt/generic/lwt_unix_impl.o' 'lwt/lwt_util.o' 'lwt/lwt.o' 'lwt/pqueue.o' 'ubase/proplist.o' 'ubase/trace.o' 'ubase/prefs.o' 'ubase/uarg.o' 'ubase/util.o' 'ubase/safelist.o' 'ubase/myMap.o' 'ubase/projectInfo.o' 'system.o' 'system/generic/system_impl.o' 'system/system_generic.o' 'bytearray.o' 'unicode.o' 'unicode_tables.o' 'ubase/rx.o' '/usr/local/lib/ocaml/bigarray.a' '/usr/local/lib/ocaml/str.a' '/usr/local/lib/ocaml/unix.a' '/usr/local/lib/ocaml/stdlib.a' '-lbigarray' '-lcamlstr' '-lunix' 'osxsupport.o' 'pty.o' 'bytearray_stubs.o' '/usr/local/lib/ocaml/libasmrun.a'
0  0x1098809a4  __assert_rtn + 127
1  0x109889d69  ld::passes::stubs::arm::StubHelperAtom::StubHelperAtom(ld::passes::stubs::Pass&, ld::Atom const&, ld::Atom const*, bool) (.cold.1) + 0
2  0x10983d1ca  ld::passes::stubs::x86_64::classic::StubHelperAtom::StubHelperAtom(ld::passes::stubs::Pass&, ld::Atom const&, ld::Atom const&, bool) + 168
3  0x10983d0b5  ld::passes::stubs::x86_64::classic::LazyPointerAtom::LazyPointerAtom(ld::passes::stubs::Pass&, ld::Atom const&, bool, bool) + 135
4  0x10983cfea  ld::passes::stubs::x86_64::classic::StubAtom::StubAtom(ld::passes::stubs::Pass&, ld::Atom const&, bool, bool) + 92
5  0x10983b210  ld::passes::stubs::Pass::makeStub(ld::Atom const&, bool) + 1776
6  0x10983b91b  ld::passes::stubs::Pass::process(ld::Internal&) + 1215
7  0x10983bcc9  ld::passes::stubs::doPass(Options const&, ld::Internal&) + 105
8  0x109761658  main + 892
A linker snapshot was created at:
        /tmp/unison-2020-03-22-145854.ld-snapshot
ld: Assertion failed: (targetAtom != NULL), function Fixup, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-556.6/src/ld/ld.hpp, line 785.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
make[1]: *** [unison] Error 2
make: *** [text] Error 2`

I'm pretty new to building packages on macOS so maybe I'm overlooking something obvious?

**Comment by ACGarland** [comment]
Some additional information from the linker snapshot that was created after the failure:


```
$ cat orig_command_line
cd /System/Volumes/Data/garland/users/shared/bin-osx/unison_build/macos_catalina/unison-2.51.2/src
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -arch x86_64 -platform_version macos 10.5.0 10.15.4 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -o unison -lcrt1.10.5.o -Llwt -Lubase -Lsystem -Lfsmonitor -Lfsmonitor/linux -Lfsmonitor/windows -Lsystem/generic -Llwt/generic -L/usr/local/lib/ocaml -no_compact_unwind /tmp-tony/camlstartup0b3e15.o /usr/local/lib/ocaml/std_exit.o linktext.o main.o test.o uitext.o uicommon.o strings.o transport.o recon.o sortri.o files.o stasher.o copy.o update.o fpcache.o fswatchold.o globals.o remote.o xferhint.o transfer.o terminal.o checksum.o tree.o common.o clroot.o lock.o os.o fileinfo.o props.o fswatch.o external.o osx.o abort.o fingerprint.o fs.o fspath.o path.o name.o fileutil.o pred.o case.o uutil.o lwt/lwt_unix.o lwt/generic/lwt_unix_impl.o lwt/lwt_util.o lwt/lwt.o lwt/pqueue.o ubase/proplist.o ubase/trace.o ubase/prefs.o ubase/uarg.o ubase/util.o ubase/safelist.o ubase/myMap.o ubase/projectInfo.o system.o system/generic/system_impl.o system/system_generic.o bytearray.o unicode.o unicode_tables.o ubase/rx.o /usr/local/lib/ocaml/bigarray.a /usr/local/lib/ocaml/str.a /usr/local/lib/ocaml/unix.a /usr/local/lib/ocaml/stdlib.a -lbigarray -lcamlstr -lunix osxsupport.o pty.o bytearray_stubs.o /usr/local/lib/ocaml/libasmrun.a -L/usr/local/lib -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/lib/darwin/libclang_rt.osx.a
```

```
$cat link_command
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld -Z -demangle -lto_library data_files/libLTO.dylib -dynamic -arch x86_64 -platform_version macos 10.5.0 10.15.4 -no_compact_unwind -filelist objects/filelist dylibs/libSystem.tbd archive_files/stdlib.a archive_files/bigarray.a archive_files/str.a archive_files/unix.a archive_files/libasmrun.a archive_files/libbigarray.a archive_files/libunix.a archive_files/libcamlstr.a`
```

**Comment by ACGarland** [comment]
OK - I finally obtained a solution.

I gave up on trying to build unison 2.51.2 against ocaml 4.05.0 on macOS Catalina--due to the previously-mentioned link error.

I took the opposite approach: going back to the brew-provided unison installations for both my High Sierra and Catalina macs (and pinning them). This provides unison 2.51.2 (ocaml 4.08.1). Then rebuild the Synology DS418 version in the default debian docker container, but against ocaml 4.08.1.

Interestingly, unison 2.51.2 fails to compile against ocaml 4.08.1 within the debian container (various compiler errors).  So I moved to unison 2.51.3 which, thankfully, successfully compiled against ocaml 4.08.1.

That left me with the following combination:

DS418 `unison 2.51.3 (ocaml 4.08.1)`
macOS: `unison 2.51.2 (ocaml 4.08.1)`

Even though the unison versions mismatch, since it is in the minor digit, that portion seems to be compatible. More importantly, the ocaml versions match exactly and these versions are working compatibly so far.

Thanks to seguri who contacted me off-channel and provided me with a set of compatible binaries for macOS and Synology based on unison 2.51.2.  By that time, I was close to my final solution--but will greatly appreciate those binaries if my versions show any incompatibilities going forward.

**Comment by seguri** [comment]
Hi Tony, if I understand the [brew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/unison.rb) correctly, it describes how to patch 2.51.2 to be compiled with OCaml 4.08 and later. Maybe with that you can have 2.51.2 for your Sinology, even if I also think there should be no problems using 2.51.3.

**Comment by ACGarland** [comment]
Thanks Marco!  Knowing more about how `brew` works has been on my todo list for some time... so this is good info.

FWIW, my systems did a bunch of synchronization overnight (Synology DS418 as hub in configuration, syncing with three MBP and one cloud service) all using the newly built unison binaries. It all seemed to work perfectly.

I rely heavily on unison in my usage here--I've tried lots of other syncing solutions over the years, but they all have different issues that end up being inferior to unison.  A key one, for my use, is that I rely on symlinks quite a bit and most solutions don't handle them as well.

I appreciate the time you've spent helping me with this.  Hopefully I can remain with these binaries for a long time to come.

**Comment by falcon4ever** [comment]
@seguri Thanks for letting me know about this issue. I've created a new guide on how to build Unison for Synology NAS systems: http://www.multigesture.net/articles/how-to-compile-unison-for-a-synology-nas-dsm-6-2/

The version should be compatible with Unison installed via brew on macOS
