### ISSUE TITLE
unison does not handle extended attributes

### ISSUE THREAD

**Issue by rmrnc** [bcpierce00/unison#291]
## Problem

`unison` doesn't pick up changed extended attributes.

## Reproducing steps

On macOS

1. create file
1. assign multiple (!) tags and/or a finder comment
![image](https://user-images.githubusercontent.com/8008083/67095055-4fb2c000-f1b5-11e9-8e1f-76442bb9e14c.png)
1. check corresponding extended attributes on replicas , i.e., `com.apple.metadata:_kMDItemUserTags` and `com.apple.metadata:kMDItemFinderComment` with 
```bash
> xattr -l <file>
```

```
> xattr -l <src>/A/a.txt 
com.apple.FinderInfo:
00000000  00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000020
com.apple.metadata:_kMDItemUserTags:
00000000  62 70 6C 69 73 74 30 30 A2 01 02 55 52 65 64 0A  |bplist00...URed.|
00000010  36 57 47 72 65 65 6E 0A 32 08 0B 11 00 00 00 00  |6WGreen.2.......|
00000020  00 00 01 01 00 00 00 00 00 00 00 03 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00 00 00 00 19              |............|
0000003c
com.apple.metadata:kMDItemFinderComment:
00000000  62 70 6C 69 73 74 30 30 5F 10 16 48 45 52 45 20  |bplist00_..HERE |
00000010  49 53 20 41 20 43 4F 4D 4D 45 4E 54 21 21 21 21  |IS A COMMENT!!!!|
00000020  21 08 00 00 00 00 00 00 01 01 00 00 00 00 00 00  |!...............|
00000030  00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000040  00 21                                            |.!|
00000042

# replica
xattr -l <dst>A/a.txt 
com.apple.FinderInfo:
00000000  00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000020
```

Note: `rsrc = true`

**Comment by bcpierce00** [comment]
This is a known deficiency.  I'd be happy to consider a PR if someone wants to work on fixing it, but it would be a bit of work.

**Comment by etziperman** [comment]
I cannot sync .webloc files on mac os x, unless I do xattr -c to them, seems a related problem...

**Comment by tleedjarv** [comment]
@rmrnc and @eli-tziperman if you have the possibility, could you test the code in PR #368. I'm hoping it will solve the issue.
Enable preference `xattrs` in profile or on command line (and keep the `rsrc` preference set as well).
Note that the archive and wire format has changed in the PR, it is not compatible with previous unison versions.

**Comment by eli-tziperman** [comment]
that problem went away for me a while ago, perhaps when I upgraded to
catalina...? Eli

**Comment by gdt** [comment]
Indeed "effort-high" was apt.  2  years and a lot of code!

@rmrnc Please test the tip of master; there should be CI build artifacts.
