### ISSUE TITLE
Unable to install unison for mac-Linux synchronization

### ISSUE THREAD

**Issue by alex4200** [bcpierce00/unison#292]
I have been trying to install `unison` on a Linux box and on a Mac, but the versions seem to be incompatible (that of `ocaml`), and I cannot sync. 
Is there ANY simple way to ensure that I have a `unison` with that the sync works? Or do I have to try to install the right versions of `unison`, `ocaml` etc, and recompile `unison`?

**Comment by Hwwipp** [comment]
Hi,

i have seen this too (see this thread
<https://groups.yahoo.com/neo/groups/unison-users/conversations/topics/12462>).

Try this hint from Benjamin first before starting to build unison:
"A little investigation led me to discover that, on my system, the
culprit is not actually the network format, but rather the format of the
fingerprint cache file that Unison uses to avoid rescanning the local
filesystem.

Greg, could you please have a look in your .unison directory (on both
client and server) and remove (or move someplace else) any recently
written files you find there whose names begin with “fp” followed by a
long string of nonsense? Then try syncing again and let us know if it
goes better / different."

I build unison (2.51) on Ubuntu with ocaml 4.08 (to be in sync with
arch) and now it works for me.

Am 24.10.19 um 11:20 schrieb alex4200:

**Comment by AesSedai** [comment]
@alex4200 I ran into the same issue and ended up compiling ocaml-4.08.1 for OSX and Centos7, then compiling unison for each system.

Fortunately, @alanshutko has a branch of unison that compiled on OSX (Mojave 10.14.6, XCode 11.3.1) without issue: https://github.com/alanshutko/unison/tree/xcode-upgrade

**Comment by alanshutko** [comment]
It might be time to do some serious testing on the branch and merge it. There’s still some deprecated stuff in there, but the changes are more complicated and I’m not as familiar with them.

**Comment by AesSedai** [comment]
This is my first real foray into using unison, and I have no ocaml experience whatsoever so I'm afraid I'm of no real help. Unison is just a much better utility than the RubyMine Remote Deployment "feature" I was using before :)

**Comment by bcpierce00** [comment]
I am also having trouble compiling the OS X GUI at the moment.  If you (Alan) or anyone else has a working solution, it would be great to merge it.

**Comment by gdt** [comment]
unison relies on ocmal's serialization and therefore unison binaries built with different ocaml versions do not necessarily interoperate.   So you need to build them consistently.   Please use the mailinglist to ask for help about that.
