### ISSUE TITLE
Handle percent-encoding in remote root specifiers

### ISSUE THREAD

**Issue by joaopizani** [bcpierce00/unison#294]
The user manual says that the syntax of remote roots are "based on that of URIs (described in RFC 2396)". However, an important part of URI syntax is not handled by Unison, namely percent-encoding.

One example use case that I have is whenever users desire to have an alias in `.ssh/config` for a frequently-accessed host, while also using this alias as the host part of the remote root specifier in Unison config.

Example:

* **In .ssh/config:** `Host %bigmach ... Hostname bigmach.example.com`
* **In .unison/big.prf:**  `root = ssh://%25bigmach//path/to/replica`

Yes, I know that one can simply avoid using "weird" characters or simply use underscore as the "alias notation char", but i think it would be better to have a "proper URI" in the root syntax instead of something "based in URI".

Especially considering that functions like "urlencode" and "urldecode" must already be readily-available and easy-to-use in OCaml.

**Comment by tleedjarv** [comment]
I agree that current roots parsing is overly restrictive when it comes to characters allowed in the authority part of the URI. In PR #647 I've added `%` to the allowed characters so that your example will work as `root = ssh://%bigmach//path/to/replica`. It is not support for percent-encoding, it just accepts `%` as a character.

(if this issue gets closed by PR being merged) Please re-open if you think this is not sufficient. I will then consider adding full percent-decoding. (But even then it will not be something for the next release because we are in a sort of semi-feature-freeze already.)

**Comment by tleedjarv** [comment]
Here is a patch (on top of #647) to decode percent-encoded characters in the user and host parts (it will intentionally not decode any path parts) -- if someone wants to use it for their own build. Or if it is decided that this is the correct thing to do then it can be lifted to a PR.

```diff
diff --git a/src/clroot.ml b/src/clroot.ml
index 8d0371fd..8e5bf92a 100644
--- a/src/clroot.ml
+++ b/src/clroot.ml
@@ -66,6 +66,34 @@ type uri = protocol       (*   - a protocol *)
          * int option     (*   - an optional port *)
          * string option  (*   - an optional path *)
 
+(* Decode percent-encoded characters *)
+let unquote s =
+  let hex_char c =
+    match c with
+    | '0'..'9' -> Char.code c - Char.code '0'
+    | 'a'..'f' -> Char.code c - Char.code 'a' + 10
+    | 'A'..'F' -> Char.code c - Char.code 'A' + 10
+    | _        -> invalid_arg "invalid percent-encoding"
+  in
+  let l = String.length s in
+  let n = ref 0 in
+  for i = 0 to l - 1 do if s.[i] = '%' then incr n done;
+  if !n = 0 then s else begin
+    let u = Bytes.create (l - 2 * !n) in
+    let j = ref 0 in
+    for i = 0 to l - 2 * !n - 1 do
+      let c = s.[!j] in
+      if c = '%' then begin
+        Bytes.set u i (Char.chr ((hex_char s.[!j + 1]) lsl 4 + hex_char s.[!j + 2]));
+        j := !j + 3
+      end else begin
+        Bytes.set u i c;
+        incr j
+      end
+    done;
+    Bytes.to_string u
+  end
+
 (* Regular expressions, used in parsing *)
 let protocolColonSlashSlashRegexp = Str.regexp "[a-zA-Z]+://"
 let protocolColonRegexp = Str.regexp "[a-zA-Z]+:"
@@ -105,7 +133,7 @@ let getProtocolSlashSlash s =
     | _ -> None
   else None
 
-let userAtRegexp = Str.regexp "[-_a-zA-Z0-9.]+@"
+let userAtRegexp = Str.regexp "[-_a-zA-Z0-9%.]+@"
 let getUser s =
   if Str.string_match userAtRegexp s 0
   then
@@ -113,7 +141,7 @@ let getUser s =
     let len = String.length userAt in
     let afterAt = Str.string_after s len in
     let beforeAt = String.sub userAt 0 (len-1) in
-    (Some beforeAt,afterAt)
+    (Some (unquote beforeAt), afterAt)
   else (None,s)
 
 let ipv6Regexp = "[a-f0-9:.]+\\(%[-_a-zA-Z0-9~%.]+\\)?"
@@ -125,7 +153,7 @@ let getHost s =
     let host = Str.matched_string s in
     let host' = try Str.matched_group 1 s with Not_found -> host in
     let s' = Str.string_after s (String.length host) in
-    (Some host', s')
+    (Some (if host'.[0] <> '{' then unquote host' else host'), s')
   else (None,s)
 
 let colonPortRegexp = Str.regexp ":[^/]+"
```

**Comment by tleedjarv** [comment]
Having thought about it some more, I don't see this being useful. True, the range of accepted characters in the user and host part could (and should? what are the objections?) be extended, but they don't need to be percent-encoded for that.
