### ISSUE TITLE
Unison freezes on sync

### ISSUE THREAD

**Issue by russoisraeli** [bcpierce00/unison#295]
I have the following: unison version 2.51.2 (ocaml 4.05.0)
I was syncing two roots for a while every 5 minutes.
The sync is done through socket (over SSL), running as root.
At some point of time, random files stopped getting synced (not all - skipping/selecting only certain files would work for them only). During sync, it would freeze until ctrl+c.

Here's a -debug all, for a single file:

[update] updateArchive /usr/local/autom apid/apid.py
[pred] ignore 'apid/apid.py' = false
[files] copyRec apid/apid.py --> .unison.apid.py.a1cca0ec746cfd5706db14a110d3d902.unison.tmp  (really to apid.py)
[abort] Checking line 2
[copy] copyRegFile(/usr/local/autom,apid/apid.py) -> (//autom101l.domainname//usr/local/autom,apid.py,/usr/local/autom/apid,.unison.apid.py.a1cca0ec746cfd5706db14a110d3d902.unison.tmp,modified on 2019-10-28 at 11:31:24  size 26718     rwxrwxr-x user=drevil group=networking)
[abort] Checking line 2
Terminated!

Anything else I can do to debug this?

Many thanks.

**Comment by gdt** [comment]
We know there are memory issues, but without specific versions and a repro recipe this bug report does not help us find the problem.
