### ISSUE TITLE
Add to conda

### ISSUE THREAD

**Issue by tdegeus** [bcpierce00/unison#296]
I have always experienced getting (the correct version) of unison a bit of a hassle. It would be great if unison could be added to [conda-forge](https://conda-forge.org/#page-top)!

**Comment by jedfrechette** [comment]
Conda builds of Unison would indeed be fantastic. Especially if they made it easier to build on Windows.

**Comment by bcpierce00** [comment]
This sounds like a good idea, if someone wants to work on it.

**Comment by tdegeus** [comment]
I have experience with conda-forge feedstocks but I have never built unison. If you have clear build instructions I'm willing to give it a try.

**Comment by bcpierce00** [comment]
Check out the INSTALLATION section of the user manual...

**Comment by gdt** [comment]
conda is one of many packaging systems and therefore unison being in conda should be worked on within the context of conda, which would presumably store control files for this, like other packaging systems do.  If there is something wrong with unison's build process which makes building within conda unreasonably difficult, please open a specific ticket about that failing.

**Comment by niklasl** [comment]
For anyone ending up here, there is now a https://github.com/conda-forge/unison-feedstock.

**Comment by gdt** [comment]
@niklasl Thanks!   I have added a link to that in the wiki page that lists other packaging systems.

**Comment by niklasl** [comment]
@gdt Thank you!
