### ISSUE TITLE
show speed MB/s (also Yahoo Groups)

### ISSUE THREAD

**Issue by reagle** [bcpierce00/unison#297]
I'm wondering if it's possible to see how fast the transfer is while using unison on the terminal. I went to the Yahoo Group and see they are now defunct. So this issue could be taken as a feature request for such a thing, and/or a bug about the documentation still referring to Yahoo Groups...

**Comment by bcpierce00** [comment]
Yahoo groups still claim to exist at the moment, as far as I can tell.

(As for the actual request, I'd be happy to consider a PR...)
