### ISSUE TITLE
macos reports 'case-insensitive file system' even when not

### ISSUE THREAD

**Issue by williamspatrick** [bcpierce00/unison#298]
Synchronizing a Linux kernel tree between a MacOS and a Linux system results in a message such as:
```
Two or more files on a case-sensitive system have names identical except for case.  They cannot be synchronized to a case-insensitive file system.
```
I am synchronizing on a Case-sensitive APFS volume so this is not true.  Does Unison on MacOS still automatically assume it is on a case-insensitive file system?

**Comment by bcpierce00** [comment]
Did you try running with ignorecase=false?

**Comment by williamspatrick** [comment]
Thank you.  That seems to have solved it.  I had expected it to self-detect.

**Comment by tsouanas** [comment]
Sorry for resurrecting this, but at the very least the message is wrong, since it implies that the filesystem is case-insensitive even when it isn't.  Maybe adding a small text suggesting this "fix" and admitting a possible misdetection would be useful, like "if this is indeed a case-sensitive filesystem, try running with ignorecase=false".

**Comment by gdt** [comment]
Error message improved.  Sorry, but I'm not willing to cross into adding random hints to all error messages as that leads to lots of text that, while it seemed critical to someone, will be excessive to many others.

Please file a bug with Apple that macOS should be case-sensitive by default, and then we can remove the special case.

**Comment by tsouanas** [comment]
Aaah, then the problem would persist: claiming to detect a filesystem's sensitivity when in reality it just checks what the default sensitivity of such system is and assumes that "therefore it must be the default".  And I guess that it's better to err on the safe side, mistaking a sensitive FS for an insensitive one than vice-versa.

Anyway, I think the new error improves a lot the situation!  Thanks!

**Comment by gdt** [comment]
See also #1062.
