### ISSUE TITLE
Meta-issue: Help needed responding to Unison issues

### ISSUE THREAD

**Issue by bcpierce00** [bcpierce00/unison#299]
Unison still (in 2019!) seems to be useful to quite a few people — so many, indeed, that the volume of questions, issue reports, etc. is often more than I can keep up with, as I have only a few cycles to spend on Unison these days.  A number of people have been helping stay on top of things, but if there is anyone else that could lend a hand it would be greatly appreciated.  

If you’re up for this, you just need to notice when issues and questions are posted, and respond if you’re able.  (If you are feeling ambitious and think you might want to spend some time helping keep the repo itself organized — e.g., deleting old issues, etc. — please talk to me!)

Many thanks,

    - Benjamin

**Comment by igrep** [comment]
How about pinning this issue? https://help.github.com/en/enterprise/2.19/user/github/managing-your-work-on-github/pinning-an-issue-to-your-repository

**Comment by bcpierce00** [comment]
Sounds like a good idea!  But I am having trouble finding the “Pin issue” button to click — is this feature available in all GitHub repos, or only enterprise?

    - B

**Comment by bcpierce00** [comment]
OK, found it now!

Thanks again,

   - B

**Comment by gdt** [comment]
I would be happy to hit close on issues that shouldn't be open, but I don't have permission.

In particular, I think unison should not permit "please package unison in $LINUX_PACKAGING_FLAVOR_OF_THE_WEEK" issues, as those should be filed in $FLAVOR's tracker.

**Comment by bcpierce00** [comment]
Thanks, Greg.  Your help curating issues here is gratefully accepted!

**Comment by gdt** [comment]
"Responding to issues" is now under control, thanks to @tleedjarv and others.   We still have a problem that very few are providing code fixes, missing docs, or even testing pre-releases, but I don't think this issue being open is going to lead to solving that....
