### ISSUE TITLE
-backupcur causes failure when symlink is replaced with a directory

### ISSUE THREAD

**Issue by ian-kelling** [bcpierce00/unison#30]
Here is an example script which demonstrates the problem.
-batch and -auto are just for convenience of the script.
# !/bin/bash

set -x
d=$(mktemp -d)
cd $d
mkdir -p root1/dir/bin
touch root1/dir/bin/bin
ln -s /usr/bin/bin root1
x="/usr/bin/unison-2.48 -root root1 -root root2"
HOME=$PWD $x -backupcurr "Regex ._" -batch
tree -a # just to show what files exist
rm root1/bin
mv root1/dir/bin root1
HOME=$PWD $x -backupcurr "Regex ._" -batch -auto
echo $? # prints 2
tree -a # files synced despite error, but backup dir is unchanged
touch root1/otherfile # test syncing some file now
HOME=$PWD $x -backupcurr "Regex .*" -batch -auto
echo $? # prints 3
tree -a # now files did not sync, backup dir is unchanged
cd; rm -rf $d # cleanup temp dir

**Comment by bcpierce00** [comment]
Your script doesn't quite work on my (OS X) machine.  (Mostly for silly reasons, like I don't have mktemp.  But I wonder if you wrote exactly what you meant to -- is the first call to unison really with "Regex ." rather than "Regex .*"?  And perhaps Regex .* is not what's wanted either, given that * doesn't match / separators in paths...)  In any case, it would help if you could add "-debug all" to the calls to unison and post the r chine.

**Comment by ian-kelling** [comment]
"Regex ." is supposed to be "Regex .*". I will run with -debug in a few hours and put the output here.

**Comment by ian-kelling** [comment]
Here is the output, just up to the first error. The second error is just a repeat, showing that it affects subsequent runs.


++ mktemp -d
+ d=/tmp/tmp.zesY0VkDEj
+ cd /tmp/tmp.zesY0VkDEj
+ mkdir -p root1/dir/bin
+ touch root1/dir/bin/bin
+ ln -s /usr/bin/bin root1
+ x='/usr/bin/unison-2.48 -root root1 -root root2'
+ HOME=/tmp/tmp.zesY0VkDEj
+ /usr/bin/unison-2.48 -root root1 -root root2 -backupcurr 'Regex .*' -batch
Contacting server...
Looking for changes
Warning: No archive files were found for these roots, whose canonical names are:
	/tmp/tmp.zesY0VkDEj/root1
	/tmp/tmp.zesY0VkDEj/root2
This can happen either
because this is the first time you have synchronized these roots, 
or because you have upgraded Unison to a new version with a different
archive format.  

Update detection may take a while on this run if the replicas are 
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted: 
http://www.cis.upenn.edu/~bcpierce/unison

Reconciling changes
dir      ---->            /  
root1        : dir                modified on 2016-07-20 at 22:32:26  size 0         rwxrwxrwx
root2        : absent
Propagating updates
UNISON 2.48.3 started propagating changes at 22:32:27.23 on 20 Jul 2016
[BGN] Copying  from /tmp/tmp.zesY0VkDEj/root1 to /tmp/tmp.zesY0VkDEj/root2
[END] Copying 
UNISON 2.48.3 finished propagating changes at 22:32:27.23 on 20 Jul 2016
Saving synchronizer state
Synchronization complete at 22:32:27  (1 item transferred, 0 skipped, 0 failed)
+ tree -a
.
├── root1
│   ├── bin -> /usr/bin/bin
│   └── dir
│       └── bin
│           └── bin
├── root2
│   ├── bin -> /usr/bin/bin
│   └── dir
│       └── bin
│           └── bin
├── .unison
│   ├── ar04634ef13e45293507f412720b780f69
│   ├── ar5834ea3f3b3ca249b780368a06278f05
│   ├── backup
│   │   ├── bin -> /usr/bin/bin
│   │   └── dir
│   │       └── bin
│   │           └── bin
│   ├── default.prf
│   ├── fp04634ef13e45293507f412720b780f69
│   └── fp5834ea3f3b3ca249b780368a06278f05
└── unison.log

10 directories, 12 files
+ rm root1/bin
+ mv root1/dir/bin root1
+ HOME=/tmp/tmp.zesY0VkDEj
+ /usr/bin/unison-2.48 -root root1 -root root2 -backupcurr 'Regex .*' -batch -auto -debug all
[startup] Preferences:
ui = graphic
host = 
server = false
prefsdocs = false
doc = 
version = false
silent = false
dumbtty = false
testserver = false
showprev = false
selftest = false
confirmmerge = false
retry = 0
repeat = 
contactquietly = false
key = 
label = 
expert = false
height = 15
auto = true
maxthreads = 0
maxsizethreshold = -1
prefer = 
force = 
sortnewfirst = false
sortbysize = false
keeptempfilesaftermerge = false
diff = diff -u CURRENT2 CURRENT1
copyonconflict = false
backupcurr = Regex .*
backupdir = 
maxbackups = 2
backups = false
backupsuffix = 
backupprefix = .bak.$VERSION.
backuploc = central
copymax = 1
copyquoterem = default
copythreshold = -1
copyprogrest = rsync --partial --append-verify --compress
copyprog = rsync --partial --inplace --compress
rsync = true
fastcheck = default
ignorelocks = false
dumparchives = false
showarchive = false
rootsName = 
ignorearchives = false
fastercheckUNSAFE = false
fat = false
allHostsAreRunningWindows = false
someHostIsRunningWindows = false
confirmbigdel = true
batch = true
root = root2
root = root1
killserver = false
halfduplex = false
stream = true
addversionno = false
servercmd = 
sshargs = 
rshargs = 
rshcmd = rsh
sshcmd = ssh
xferbycopying = true
sshversion = 
clientHostName = treetowl
ignoreinodenumbers = false
links-aux = true
links = default
times = false
group = false
owner = false
numericids = false
dontchmod = false
perms = 1023
watch = true
rsrc-aux = false
rsrc = default
maxerrors = 1
unicodeCS = false
unicodeEnc = false
unicode = default
someHostIsInsensitive = false
ignorecase = default
timers = false
terse = false
logfile = /tmp/tmp.zesY0VkDEj/unison.log
log = true
debugtimes = false
debug = all
addprefsto = 
Contacting server...
[globals] Checking path '' for expansions
[startup] Roots: 
        root1
        root2
  i.e. 
        root1
        root2
  i.e. (in canonical order)
       /tmp/tmp.zesY0VkDEj/root1
       /tmp/tmp.zesY0VkDEj/root2

[props] Setting permission mask to 1777 (1777 and 7777)
[stasher] initBackupsLocal
[stasher] d = /
[stasher] Prefix and suffix regexps for backup filenames have been updated
[stasher] initBackupsLocal
[stasher] d = /
[stasher] Prefix and suffix regexps for backup filenames have been updated
Looking for changes
[ui] temp: Globals.paths = 
[update] Loading archive from /tmp/tmp.zesY0VkDEj/.unison/ar5834ea3f3b3ca249b780368a06278f05
[update] Setting archive for //treetowl//tmp/tmp.zesY0VkDEj/root1
[update] Loading archive from /tmp/tmp.zesY0VkDEj/.unison/ar04634ef13e45293507f412720b780f69
[update] Setting archive for //treetowl//tmp/tmp.zesY0VkDEj/root2
[update] findOnRoot /tmp/tmp.zesY0VkDEj/root1
[update] findLocal /tmp/tmp.zesY0VkDEj/root1 ()
[fpcache] opening cache file /tmp/tmp.zesY0VkDEj/.unison/fp5834ea3f3b3ca249b780368a06278f05 for input
[fpcache] read chunk of 1 files
[fpcache] opening cache file /tmp/tmp.zesY0VkDEj/.unison/fp5834ea3f3b3ca249b780368a06278f05 for output
[pred] ignore '' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root1
[pred] immutable '' = false
[pred] ignore 'bin' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root1/bin
[update]   buildUpdate -> New directory
[pred] immutable 'bin' = false
[pred] ignore 'bin/bin' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root1/bin/bin
[update]   buildUpdate -> New file
[fpcache] cache miss for path bin / bin
[pred] ignore 'dir' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root1/dir
[pred] immutable 'dir' = false
[pred] ignore 'dir/bin' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root1/dir/bin
[update]   buildUpdate -> Deleted
[update] Setting archive for //treetowl//tmp/tmp.zesY0VkDEj/root1
[update] findOnRoot /tmp/tmp.zesY0VkDEj/root2
[update] findLocal /tmp/tmp.zesY0VkDEj/root2 ()
[fpcache] opening cache file /tmp/tmp.zesY0VkDEj/.unison/fp04634ef13e45293507f412720b780f69 for input
[fpcache] opening cache file /tmp/tmp.zesY0VkDEj/.unison/fp04634ef13e45293507f412720b780f69 for output
[pred] ignore '' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root2
[pred] immutable '' = false
[pred] ignore 'bin' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root2/bin
[pred] follow 'bin' = false
[update]   buildUpdate -> Symlink /usr/bin/bin (unchanged)
[pred] ignore 'dir' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root2/dir
[pred] immutable 'dir' = false
[pred] ignore 'dir/bin' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root2/dir/bin
[pred] immutable 'dir/bin' = false
[pred] ignore 'dir/bin/bin' = false
  dir/bin/bin
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root2/dir/bin/bin
[update] checkContentsChange: archStamp is inode (1070386) / info.inode (1070386) / times: 1469079147.000000 = 1469079147.000000... true / lengths: 0 - 0
[update] Setting archive for //treetowl//tmp/tmp.zesY0VkDEj/root2
Reconciling changes
[recon] reconcileAll
[recon] reconcile: 2 results
[update] Marking 0 paths equal
[pred] sortlast 'bin' = false
[pred] sortlast 'dir/bin' = false
[pred] sortfirst 'bin' = false
[pred] sortfirst 'dir/bin' = false
[sort] bin <= dir/bin --> -1
[pred] forcepartial 'bin' = false
[pred] preferpartial 'bin' = false
[pred] forcepartial 'dir/bin' = false
[pred] preferpartial 'dir/bin' = false
new dir  ---->            bin  
deleted  ---->            dir/bin  
Propagating updates
UNISON 2.48.3 started propagating changes at 22:32:28.24 on 20 Jul 2016
[BGN] Copying bin from /tmp/tmp.zesY0VkDEj/root1 to /tmp/tmp.zesY0VkDEj/root2
[files] copy /tmp/tmp.zesY0VkDEj/root1 bin ---> /tmp/tmp.zesY0VkDEj/root2 bin 
[pred] follow 'bin' = false
[fspath] Os.findWorkingDir(/tmp/tmp.zesY0VkDEj/root2,bin) = (/tmp/tmp.zesY0VkDEj/root2,bin)
[update] updateArchive /tmp/tmp.zesY0VkDEj/root1 bin
[pred] ignore 'bin' = false
[files] copyRec bin --> .unison.bin.04634ef13e45293507f412720b780f69.unison.tmp  (really to bin)
[files] Creating directory /tmp/tmp.zesY0VkDEj/root2/.unison.bin.04634ef13e45293507f412720b780f69.unison.tmp
[abort] Checking line 0
[files] copyRec bin/bin --> .unison.bin.04634ef13e45293507f412720b780f69.unison.tmp/bin  (really to bin/bin)
[abort] Checking line 0
[copy] copyRegFile(/tmp/tmp.zesY0VkDEj/root1,bin/bin) -> (/tmp/tmp.zesY0VkDEj/root2,bin/bin,/tmp/tmp.zesY0VkDEj/root2,.unison.bin.04634ef13e45293507f412720b780f69.unison.tmp/bin,modified on 2016-07-20 at 22:32:26  size 0         rw-rw-rw-)
[copy] Copy.localFile /tmp/tmp.zesY0VkDEj/root1 / bin/bin to /tmp/tmp.zesY0VkDEj/root2 / .unison.bin.04634ef13e45293507f412720b780f69.unison.tmp/bin
[props] Setting permissions for /tmp/tmp.zesY0VkDEj/root2/.unison.bin.04634ef13e45293507f412720b780f69.unison.tmp/bin to rw-rw-rw- (666/1777)
[props] Setting permissions for /tmp/tmp.zesY0VkDEj/root2/.unison.bin.04634ef13e45293507f412720b780f69.unison.tmp to rwxrwxrwx (777/1777)
[files] rename(root=/tmp/tmp.zesY0VkDEj/root2, pathOld=.unison.bin.04634ef13e45293507f412720b780f69.unison.tmp, pathNew=bin)
[update] checkNoUpdates /tmp/tmp.zesY0VkDEj/root2 bin
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root2/bin
[pred] follow 'bin' = false
[update]   buildUpdate -> Symlink /usr/bin/bin (unchanged)
[files] Renaming .unison.bin.04634ef13e45293507f412720b780f69.unison.tmp to bin in /tmp/tmp.zesY0VkDEj/root2; root is /tmp/tmp.zesY0VkDEj/root2
[files] rename: moveFirst=true
[files] moving /tmp/tmp.zesY0VkDEj/root2/bin to /tmp/tmp.zesY0VkDEj/root2/.unison.bin..001..04634ef13e45293507f412720b780f69.unison.tmp
[stasher] backup: /tmp/tmp.zesY0VkDEj/root2 / bin
[pred] follow 'bin' = false
[fspath] Os.findWorkingDir(/tmp/tmp.zesY0VkDEj/root2,bin) = (/tmp/tmp.zesY0VkDEj/root2,bin)
[pred] backup 'bin' = false
[stasher] Path /tmp/tmp.zesY0VkDEj/root2 / bin does not need to be backed up
[files] Writing commit log: renaming /tmp/tmp.zesY0VkDEj/root2/.unison.bin.04634ef13e45293507f412720b780f69.unison.tmp to /tmp/tmp.zesY0VkDEj/root2/bin via /tmp/tmp.zesY0VkDEj/root2/.unison.bin..001..04634ef13e45293507f412720b780f69.unison.tmp
[os] rename /tmp/tmp.zesY0VkDEj/root2/bin to /tmp/tmp.zesY0VkDEj/root2/.unison.bin..001..04634ef13e45293507f412720b780f69.unison.tmp
[files] rename /tmp/tmp.zesY0VkDEj/root2/.unison.bin.04634ef13e45293507f412720b780f69.unison.tmp to /tmp/tmp.zesY0VkDEj/root2/bin
[os] rename /tmp/tmp.zesY0VkDEj/root2/.unison.bin.04634ef13e45293507f412720b780f69.unison.tmp to /tmp/tmp.zesY0VkDEj/root2/bin
[files] Deleting commit log
[pred] backupcurr 'bin' = true
[pred] backupcurrnot 'bin' = false
[stasher] stashCurrentVersion of bin (drawn from bin) in /tmp/tmp.zesY0VkDEj/root2
[stasher] Stashing recursively because file is a directory
[pred] ignore 'bin/bin' = false
[pred] backupcurr 'bin/bin' = true
[pred] backupcurrnot 'bin/bin' = false
[stasher] stashCurrentVersion of bin/bin (drawn from bin/bin) in /tmp/tmp.zesY0VkDEj/root2
[stasher] stashed [/tmp/tmp.zesY0VkDEj/.unison/backup / bin/bin] = ABSENT is not equal to new [/tmp/tmp.zesY0VkDEj/root2 / bin/bin] = d41d8cd98f00b204e9800998ecf8427e (or one is a dir): stash!
[copy] Copy.localFile /tmp/tmp.zesY0VkDEj/root2 / bin/bin to /tmp/tmp.zesY0VkDEj/.unison/backup / bin/bin
[exn] Converting a Unix error to Transient:
Error in copying locally:
No such file or directory [open(/tmp/tmp.zesY0VkDEj/.unison/backup/bin/bin)]
[exn] In stashCurrentVersion: Propagating Transient error
[exn] In stashCurrentVersion: Propagating Transient error
Failed: Error in copying locally:
No such file or directory [open(/tmp/tmp.zesY0VkDEj/.unison/backup/bin/bin)]
Failed [bin]: Error in copying locally:
No such file or directory [open(/tmp/tmp.zesY0VkDEj/.unison/backup/bin/bin)]
[BGN] Deleting dir/bin from /tmp/tmp.zesY0VkDEj/root2
[files] deleteLocal [/tmp/tmp.zesY0VkDEj/root2] (None, dir/bin)
[update] checkNoUpdates /tmp/tmp.zesY0VkDEj/root2 dir/bin
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root2/dir/bin
[pred] immutable 'dir/bin' = false
[pred] ignore 'dir/bin/bin' = false
[update] buildUpdateRec: /tmp/tmp.zesY0VkDEj/root2/dir/bin/bin
[update] checkContentsChange: archStamp is inode (1070386) / info.inode (1070386) / times: 1469079147.000000 = 1469079147.000000... true / lengths: 0 - 0
[update]   archive digest = (d41d8cd98f00b204e9800998ecf8427e,)   current digest = (d41d8cd98f00b204e9800998ecf8427e,)
[stasher] backup: /tmp/tmp.zesY0VkDEj/root2 / dir/bin
[pred] follow 'dir/bin' = false
[fspath] Os.findWorkingDir(/tmp/tmp.zesY0VkDEj/root2,dir/bin) = (/tmp/tmp.zesY0VkDEj/root2/dir,bin)
[pred] backup 'dir/bin' = false
[stasher] Path /tmp/tmp.zesY0VkDEj/root2 / dir/bin does not need to be backed up
[update] replaceArchiveLocal /tmp/tmp.zesY0VkDEj/root2 dir/bin
[update] Setting archive for //treetowl//tmp/tmp.zesY0VkDEj/root2
[update] replaceArchiveLocal /tmp/tmp.zesY0VkDEj/root1 dir/bin
[update] Setting archive for //treetowl//tmp/tmp.zesY0VkDEj/root1
[END] Deleting dir/bin
UNISON 2.48.3 finished propagating changes at 22:32:28.24 on 20 Jul 2016
Saving synchronizer state
[update] Updating archives
[update] Saving archive in /tmp/tmp.zesY0VkDEj/.unison/sc5834ea3f3b3ca249b780368a06278f05
[update] Saving archive in /tmp/tmp.zesY0VkDEj/.unison/sc04634ef13e45293507f412720b780f69
[update] Copying archive /tmp/tmp.zesY0VkDEj/.unison/tm5834ea3f3b3ca249b780368a06278f05 to /tmp/tmp.zesY0VkDEj/.unison/ar5834ea3f3b3ca249b780368a06278f05
[update] Copying archive /tmp/tmp.zesY0VkDEj/.unison/tm04634ef13e45293507f412720b780f69 to /tmp/tmp.zesY0VkDEj/.unison/ar04634ef13e45293507f412720b780f69
[update] Removing archive /tmp/tmp.zesY0VkDEj/.unison/tm5834ea3f3b3ca249b780368a06278f05
[update] Removing archive /tmp/tmp.zesY0VkDEj/.unison/tm04634ef13e45293507f412720b780f69
Synchronization incomplete at 22:32:28  (1 item transferred, 0 skipped, 1 failed)
  failed: bin
+ echo 2
2
+ tree -a
.
├── root1
│   ├── bin
│   │   └── bin
│   └── dir
├── root2
│   ├── bin
│   │   └── bin
│   └── dir
├── .unison
│   ├── ar04634ef13e45293507f412720b780f69
│   ├── ar5834ea3f3b3ca249b780368a06278f05
│   ├── backup
│   │   ├── bin -> /usr/bin/bin
│   │   └── dir
│   │       └── bin
│   │           └── bin
│   ├── default.prf
│   ├── fp04634ef13e45293507f412720b780f69
│   └── fp5834ea3f3b3ca249b780368a06278f05
└── unison.log

10 directories, 10 files
/a/opt $
