### ISSUE TITLE
lost connection to server error with exact same binaries on both ends

### ISSUE THREAD

**Issue by norbusan** [bcpierce00/unison#300]
Recent updates on Debian have broken sync between stable and sid. To circumvent this, I have on all my computers (laptop, desktop, server) the very same packages from Buster installed. So the binaries are bitwise the same on all machines. Still, I get the dreaded "lost connection to server" error when syncing between  laptop and desktop (both running sid).

All bug reports indicate that this happens when different versions of OCaml are used, but this is not the case, since the binaries are bitwise the same.

Are there any ways to debug what is happening? I have already tried `-debug all` but it doesn't indicate anything special in the log files.

This is with 2.48.4 (from Debian/buster)

**Comment by gdt** [comment]
Please use the mailinglist for support requests.

(Also, watch the connections with tcpdump.)
