### ISSUE TITLE
Watch directories instead of individual files on Linux

### ISSUE THREAD

**Issue by cachapa** [bcpierce00/unison#301]
I tried synching a huge directory with the watch flag on, but it failed due to exceeding the system's maximum number of monitored files.

Looking at the source code for fsmonitor it seems that it's watching every single file. However I briefly tested directory-level monitoring with the `watch` command-line on Linux and it seemed to do everything fsmonitor needs while using a lot fewer resources.

Could anyone more knowledgeable about inotify comment if this is viable?

**Comment by bcpierce00** [comment]
I cab't comment on the Linux viability, but please feel free to have a crack at this.

**Comment by tleedjarv** [comment]
Please make sure you are not using `fsmonitor.py`. Use the `unison-fsmonitor` binary instead (if you have both in the path then the latter should be picked up before the former). I don't know about `fsmonitor.py` but `unison-fsmonitor` works as you'd expect, watching directories, not every individual file.

**Comment by gdt** [comment]
Given @tleedjarv's comment, this seems like not a bug.   Please reopen with a reproduction recipe against the most recent release (or master) if you are still seeing this.
