### ISSUE TITLE
unison and XCode on MacOS 10.14.6

### ISSUE THREAD

**Issue by jotjot** [bcpierce00/unison#302]
Just wanted to leave a note saying that the XCode project file that comes with the project should not be opened with the up-to-date version of XCode. If that happens the Build will fail, as XCode tries in vain to update the project. 
Using the command line "make UISTYLE=mac" works fine and creates a working Application. I have tried the release versions and they did not work, I always got some error messages during the scanning.

**Comment by bcpierce00** [comment]
Do you (or does anyone) have a clear idea what needs to be done to update the Xcode project file?

**Comment by alanshutko** [comment]
I will give it a try, no promises yet.

**Comment by alanshutko** [comment]
What is the oldest macOS we'd like to support? Some of the changes that are recommended won't work on 10.7 or 10.8.

**Comment by bcpierce00** [comment]
Those are pretty old!  My guess is that people will either be happy with existing stable/old setups or else looking to set up new configurations with up to date OSs.  I.e., supporting previous macOS versions beyond the past couple is not worth a lot of effort.

**Comment by alanshutko** [comment]
I have the initial "make it compile" changes done at https://github.com/alanshutko/unison/tree/xcode-upgrade . There are a lot of extra deprecations I would like to correct before merging.

**Comment by bcpierce00** [comment]
Great!

**Comment by gdt** [comment]
I'm going to close this as it's more of an xcode bug report (that xcode is not capable of just letting things be) than a unison bug report.   Probably the discussion about mac versions belongs on the list.

My $0.02 is that it' s reasonable for people to want new unison (to interoperate with other new unison) on somewhat older operating systems.   However, absent funding from Apple :-), it's not reasonable to expect maintenance from unison to support ancient things (or really anything).   Having used macs, and old macs, I'd say:
 * 10.13 and up should be supported, as 10.13 receives security updates, and a lot of perfectly good hardware is stuck on 10.13
 * 10.11 perhaps, as while it's out of support, there is still significant amounts of working hardware stuck on 10.11
 * before 10.11, no - it's really too crufty

I should clarify that I mean "we shouldn't merge things that break the build on 10.13 (or maybe 10.11)", not supporting any affirmative duty to fix bugs.
