### ISSUE TITLE
Unison crashes with 'Assertion failed'

### ISSUE THREAD

**Issue by AxelMKlein** [bcpierce00/unison#303]
Today I recognized that when running Unison with 'sudo' I get the following error messages:

```
Uncaught exception Gtk.Error("GtkMain.init: initialization failed\nml_gtk_init: initialization failed")
Raised by primitive operation at file "gtkMain.ml", line 42, characters 1-14

Fatal error: exception File "/build/unison-Y9EcQW/unison-2.48.4/uigtk2.ml", line 144, characters 14-20: Assertion failed
Raised at file "/build/unison-Y9EcQW/unison-2.48.4/uigtk2.ml", line 144, characters 14-26
Called from file "/build/unison-Y9EcQW/unison-2.48.4/uigtk2.ml", line 677, characters 27-46
Called from file "/build/unison-Y9EcQW/unison-2.48.4/main.ml", line 241, characters 2-257
Called from file "/build/unison-Y9EcQW/unison-2.48.4/linkgtk2.ml", line 19, characters 18-40
```
Unison works for years without any problems. This is new on my side.

Thanks in advance for your feedback

**Comment by bcpierce00** [comment]
I haven't seen this, unfortunately -- I don't use the GTK UI.  Hopefully someone else will have some insight.

As a workaround, remember you can use the text UI.

**Comment by AxelMKlein** [comment]
Thank you for he comment.
I will do so and use the text-GUI.
Perhaps someone has an idea why this happens after so long a time that it worked.

**Comment by gdt** [comment]
@AxelMKlein  Please test with 2.51.2.   Please say what unison version, ocaml version, etc.   Please also be clear about whether things work when run as a non-root user, as root, or if the only issue is with sudo.  Keep in mind that sudo tends to clean the environment.

**Comment by AxelMKlein** [comment]
Thank you for coming back to the bug I filed.

I need to admit that since I upgraded to Ubuntu 20.04, Unison works as before without problems. 
Interestingly it still shows version 2.48.4. Hmm...

I think you can close this bug since I don't experince any problem anymore.

Thank you and best regards

**Comment by gdt** [comment]
Thanks for following up - that's very helpful.
