### ISSUE TITLE
Using -repeat watch yield Filesystem error

### ISSUE THREAD

**Issue by fmiqbal** [bcpierce00/unison#306]
Environment:
Host:
- Windows 10 1909
- Unison 2.51.2 (ocaml 4.09.0)
- unison-fsmonitor present

![image](https://user-images.githubusercontent.com/8409391/70843922-5f284f80-1e6c-11ea-90f9-8ba7de37c517.png)

Remote:
- Arch linux with Linux 5.4.2
- Unison 2.51.2 (ocaml 4.09.0)
- unison-fsmonitor present

![image](https://user-images.githubusercontent.com/8409391/70843931-7c5d1e00-1e6c-11ea-8d65-03fcceb7a712.png)

Connected by LAN cable, and using `unison -socket 3939` but using ssh is also yield error

I have this profile
```
root = E:/
root = socket://192.168.138.2:3939//mnt/Master

...
```

Its fine using normal sync but when I use -repeat watch, it yield `Fatal error: Filesystem watcher error: Error while starting to watch for changes: No such file or directory [open(/cygdrive/e)]`, this happen both when using profile or just command line `λ unison E:\ socket://192.168.138.2:3939//mnt/Master -repeat watch`, full output on fail

```
λ unison master@rest -repeat watch
Unison 2.51.2 (ocaml 4.09.0): Contacting server...
Connected [//ruby//mnt/Master -> //violet//cygdrive/e]
Looking for changes
Fatal error: Filesystem watcher error: Error while starting to watch for changes: No such file or directory [open(/cygdrive/e)]


The watcher can be disabled by setting preference 'watch' to false
```

and this one if I use normal sync
```
λ unison master@rest
Unison 2.51.2 (ocaml 4.09.0): Contacting server...
Connected [//ruby//mnt/Master -> //violet//cygdrive/e]
Looking for changes
  Waiting for changes from server
Reconciling changes
Nothing to do: replicas have not changed since last sync.
```

Anything I miss?

EDIT1 : somehow I try repeat using number also error

**Comment by tleedjarv** [comment]
The issue seems related to Cygwin. It may be a build issue.
Could you try with a latest release from GitHub and report results here?

**Comment by gdt** [comment]
Feel free to reopen with a  repro recipe from 2.51.4rc3 or later.
