### ISSUE TITLE
Unison for Windows: Sync does not work in both ways, on one location i just get crap like `.unison.nano.lnk.ecd045.unison.tmp...?

### ISSUE THREAD

**Issue by jayjupdhig** [bcpierce00/unison#307]
For example, i copied the "Nano" editor desktop link to èach one of both spaces... on one server, that resulted in a file name i wrote in the title?!

Unison profile on C:\Users\user1\.unison\default.prf:

```
# Unison preferences file
root = W:/
root = X:/

# Paths to synchronize
#path = ./


auto=true
batch=true
confirmbigdel=true
#fastcheck=true
#silent=true
#times=true
```

Batch file on C:\Tools\unison_task.bat:

```
"C:\Tools\unison 2.48.4\unison 2.48.4 text.exe" default
@ping -n 1 localhost> nul
C:\Tools\unison_task.bat
```

Unison service command, created with "srvman" (https://sysprogs.com/legacy/tools/srvman/):

```
"C:\Tools\srvman-1.0\srvman.exe" /RunAsService:unison_test_service C:\Windows\System32\cmd.exe /c C:\Tools\unison_task.bat
```

-> When i copy a file "test.txt" (with WinSCP SFTP) to the remote location that is mapped on the DEDICATED SYNC SERVER (a server in the middle, just for sync which has sshfd-mapped drives W: and X: ...) to drive W, it works...

-> When i copy the same file (with WinSCP SFTP too) to the remote location that is mapped on the DEDICATED SYNC SERVER (a server in the middle, just for sync which has sshfd-mapped drives W: and X: ...)  to drive X, i get crap on drive W like `.unison.test.txt.ecd045.unison.tmp`...

Why?

Do i need a create 2 profile, A to B and B to A ?? That would not be a REAL clean bidirectional sync in my opinion. That's just a hack...

Thx for feedback!!

With best regards, Jan

**Comment by martijintro** [comment]
Question: Why your application need (mandatory) settings in user profile. Imho it's a design flaw. Many situations would require that your app runs as a service...

(Because of that, i need to run the service as `user1` security contenxt (admin rights), i think if i run as "local system service", it will get a problem with its profile on C:\users\...\.unison\blabla)

**Comment by martijintro** [comment]
-> when i run it directly (user-action by clicking the batch-file) it seems to work without that issues..?

**Comment by martijintro** [comment]
Tested again: Yes, it doesnt have that problem when i run it directly, 100%... then the file will be synced correct in both dirs.

Service does also not work when i change .bat file to:

```
C:
cd \
cd Tools
cd "unison 2.48.4"

"unison 2.48.4 text.exe" default
@ping -n 1 localhost> nul

cd..
unison_task.bat
```

**Comment by martijintro** [comment]
The server where the strange filename will be written is a well-configured, untouched plesk obsidian server. So that can't be the issue!

And other solutions (e.g. commercial ones like "GoodSync") work well with. But your tool not. Log is attached.
[debug.zip](https://github.com/bcpierce00/unison/files/3984065/debug.zip)

**Comment by martijintro** [comment]
and there is also NO RESON for write permission problem, when i copy it direct with win explorer the the drive, not a problem

**Comment by gdt** [comment]
2.48 is no longer maintained.   Please update to 2.51.2.  Also, please remove your mounting-both sync server from the test scenario so we can debug a minimal unison issue.  Probably best to file a new issue if this recurs, so I'll close.

**Comment by jayjupdhig** [comment]
Anwser after almost 1 year....? Problem is solved since months - by not-using your product!! ;-)
