### ISSUE TITLE
Cannot build GUI on Ubuntu 19.04

### ISSUE THREAD

**Issue by spacecataz** [bcpierce00/unison#308]
Greetings.

I am trying to build Unison 2.51.2 from source on Ubuntu 19.04 Disco.  No matter what I do, however, I cannot get the gui to build.  The compilation happens no problem and the text UI works, but even when I set UISTYLE explicitly, the makefile does not seem to find the GTK libs.

I am carefully following the instructions in the docs, but the following library, which seems to be the key, is not found by apt: liblablgtk-extras-ocaml-dev  It appears that this package does not exist outside of Ubuntu 16 and 18.

Is there an alternate name or new location for the libraries in this package?

**Comment by gdt** [comment]
Please use the mailinglist for support questions.   Also, unison does not maintain packages in Ubuntu, so problems with missing packages in your version of Ubuntu should be addressed to Ubuntu.
