### ISSUE TITLE
2.51.3 make UISTYLE=gtk2

### ISSUE THREAD

**Issue by quiricada** [bcpierce00/unison#309]
make works ok:
unison version 2.51.3 (ocaml 4.08.0)

problem on
make UISTYLE=gtk2 

UISTYLE = gtk2
Building for Unix
NATIVE = true
THREADS = false
STATIC = false
OSTYPE =
OSARCH = Linux
ocamlopt: uigtk2.ml ---> uigtk2.cmx
ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -I /usr/lib64/ocaml/site-lib/lablgtk2 -c /home/db/Downloads/unison-master/src/uigtk2.ml
File "/home/db/Downloads/unison-master/src/uigtk2.ml", line 26, characters 24-41:
26 | let myNameCapitalized = String.capitalize Uutil.myName
                             ^^^^^^^^^^^^^^^^^
Alert deprecated: Stdlib.String.capitalize
Use String.capitalize_ascii instead.
File "/home/db/Downloads/unison-master/src/uigtk2.ml", line 1:
Error: /usr/lib64/ocaml/site-lib/lablgtk2/pango.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
make: *** [Makefile.OCaml:412: uigtk2.cmx] Error 2

**Comment by gdt** [comment]
2.52.2 builds for me on NetBSD with pkgsrc.  It looks like you have files with mixed ocaml versions.  You really need to ensure everything is built with only one version.

Please follow on the mailinglist if you need more help.
