### ISSUE TITLE
mailinglist subscription doesn't work

### ISSUE THREAD

**Issue by buhtz** [bcpierce00/unison#31]
I tried to subscribe to the mailinglist but it doesn't work.
Please see the error messag from mailserver

> <unison-users-subscribe@groups.yahoo.com>: connect to
>     groups.yahoo.com[188.125.93.101]:25: Connection timed out

**Comment by buhtz** [comment]
What is the status about that problem?

**Comment by bcpierce00** [comment]
I was unable to replicate it just now.  Is it repeatable for you?

**Comment by buhtz** [comment]
I am trying. But it will take some days because the error-mail will get back some days later. ;)

**Comment by buhtz** [comment]
The problem is still there

```
                   The mail system

<unison-users-subscribe@groups.yahoo.com>: connect to
    groups.yahoo.com[188.125.93.100]:25: Connection timed out

Return-Path: <c.buhtz@posteo.jp>
Received: from submission-encrypt01.posteo.de (unknown [10.0.0.75])
	by mout02.posteo.de (Postfix) with ESMTPS id 60C7820A08
	for <unison-users-subscribe@groups.yahoo.com>; Fri, 19 Aug 2016 10:52:19 +0200 (CEST)
Received: from customer (localhost [127.0.0.1])
	by submission (posteo.de) with ESMTPSA id 3sFxYG4mBgz105s
	for <unison-users-subscribe@groups.yahoo.com>; Fri, 19 Aug 2016 10:52:17 +0200 (CEST)
Date: Fri, 19 Aug 2016 10:52:16 +0200
From: <c.buhtz@posteo.jp>
To: unison-users-subscribe@groups.yahoo.com
Subject: subscribe
X-Mailer: Claws Mail 3.14.0 (GTK+ 2.24.30; i686-pc-linux-gnu)
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
```

**Comment by bcpierce00** [comment]
Yes, I'm getting the same behavior.  Not sure what's going on with groups.yahoo.com.  It's the same mail server that accepts postings to the list (IIUC), so I guess I can try posting a test message to see if the list accepts it.  Beyond that, I'm not sure what's the next step.

**Comment by buhtz** [comment]
The mailadress on **your** website is `unison-users-subscribe@groups.yahoo.com`.

But it should be `unison-users-subscribe@yahoogroups.com`. Please fix that and say thank you to my mail provider [Posteo](https://posteo.de).

**Comment by bcpierce00** [comment]
Aha — thanks!  Will do.
