### ISSUE TITLE
Wildcards in Path?

### ISSUE THREAD

**Issue by DocMAX** [bcpierce00/unison#312]
i would like to do something like

path = home/docmax/.local/share/applications/menulibre-*
path = home/docmax/.gnome/apps/menulibre-*

but that doesnt work. also tried:

ignorenot = Path home/docmax/.local/share/applications/menulibre-*
ignorenot = Path home/docmax/.gnome/apps/menulibre-*

how can i sync all files beginning with "menulibre-" in those two paths?

**Comment by igrep** [comment]
According to my unison config, this should work:

```
ignorenot = Path {home/docmax/.local/share/applications/menulibre-*}
ignorenot = Path {home/docmax/.gnome/apps/menulibre-*}
```

Note the braces.

**Comment by DocMAX** [comment]
Thanks, but doesn't work for me.

**Comment by johandalabacka** [comment]
Hi

What is your root? Is it / ?
Do you have `ignore = Path home/docmax/.local...` for som path above  home/docmax/.local/share/applications/menulibre-*?

The braces given above is used then specifing multiple elements on one row. Like this:

> {a,bb,ccc} matches any one of a, bb, or ccc. (Be careful not to put extra spaces after the commas: these will be interpreted literally as part of the strings to be matched!)

See https://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#ignore

**Comment by gdt** [comment]
Please use the mailinglist for support questions.
