### ISSUE TITLE
Unison 2.48.3 rescan speed

### ISSUE THREAD

**Issue by stdedos** [bcpierce00/unison#313]
_Disclaimer: I cannot find a package / statically,self-contained executable. I am happy to take pointers as to where to find them (https://github.com/xraynaud/unison aka #263 does not have any artifacts)
Disclaimer: unison-users@groups.yahoo.com is broken. Kindly update it on the original site at least._

I was wondering what are the rules that Unison (usually run through GUI) decides when to fully re-scan a directory structure or partially.

I am synchronizing a very big directory (351304 items, totalling 18,7 GB) at regular intervals.
It used to be so that, from the previous day to the next (e.g. after me sleeping), usually Unison ran full scans, whereas within a "small interval" (15 mins (or less) to 1 hour) the scanning was partial (I know that purely from the time it takes to complete the scan, plus the directories I see (while waiting) traversed)

However, recently (I don't know what triggered that change, unfortunately) it is usual that even ~10 minutes of idle-ness would be enough to retrigger full scan.
My own work is usually focused under one directory (which is about half of the inodes and size), and then even more focused; but I still see Unison traversing directories I willingly have not even `touch`ed.

I would appreciate some insight into this.

**Comment by bcpierce00** [comment]
Unison considers each file each time it runs.  What affects the speed is whether it rescans the actual contents of the file (which takes some time, especially if many files are rescanned) or just uses a saved fingerprint (which is very fast).  The manual has some more information on how this works, I believe.

What’s wrong with unison-users?

**Comment by stdedos** [comment]
As an advanced user, can I somehow display statistics on which files are marked using fingerprints, and which are not (potentially with a reason)?

> What’s wrong with unison-users?
![image](https://user-images.githubusercontent.com/133706/72740978-67805280-3baf-11ea-9e6b-564ee26573e3.png)

**Comment by alanshutko** [comment]
I think Yahoo Groups got killed off.

**Comment by bcpierce00** [comment]
You can run with debugging turned on (easiest from the command line — see the manual), but best to do that with a small number of files.

I’ll try to check on unison-users…

   - B

**Comment by bcpierce00** [comment]
Yes, I can log into the membership management page at Yahoo Groups, but I can’t send a message to the group.

**Comment by bcpierce00** [comment]
Update: My test message to the group did go through.  So it still seems to be basically functioning.  I grabbed a backup copy of the group members just in case.

**Comment by gdt** [comment]
yahoo is now ancient history.  Please try to stick to one item per issue as muliple is harder for me as ticket gardener to keep after.

2.48 is no longer supported, and absent fswatcher the notion that unison has to stat every file to look for changes is unsurprising.  Please upgrade and file a new bug against 2.51.3 if you can articulate why it's broken.
