### ISSUE TITLE
Unison failed: Uncaught exception Failure("input_value: bad bigarray kind")

### ISSUE THREAD

**Issue by selinger** [bcpierce00/unison#32]
Just updated to unison-2.48.3, which comes with Ubuntu 16.04. Getting this behavior reliably:

$ unison puffin 
Contacting server...
Connected [//firefly//home/selinger -> //puffin.mathstat.dal.ca//home/selinger]
Looking for changes
  Waiting for changes from server                                       
Reconciling changes

local          puffin.ma...       
changed  ---->            docs/info.txt  [f] 
         <---- changed    docs/magellan/20160818/log  [f] 
         <---- changed    docs/magellan/20160818/m-index.html  [f] 
changed  ---->            hint  [f] 
changed  ---->            root/root-log-firefly  [f] 
changed  ---->            vital/pins.cpt  [f] 
changed  ---->            vital/todo  [f] 

Proceed with propagating updates? [] y
Propagating updates

UNISON 2.48.3 started propagating changes at 16:41:08.60 on 18 Aug 2016
[BGN] Updating file docs/info.txt from /home/selinger to //puffin.mathstat.dal.ca//home/selinger
[BGN] Updating file docs/magellan/20160818/log from //puffin.mathstat.dal.ca//home/selinger to /home/selinger
[BGN] Updating file docs/magellan/20160818/m-index.html from //puffin.mathstat.dal.ca//home/selinger to /home/selinger
Unison failed: Uncaught exception Failure("input_value: bad bigarray kind")
Raised by primitive operation at file "/tmp/unison-2.48.3/remote.ml", line 453, characters 18-45
Called from file "/tmp/unison-2.48.3/remote.ml", line 459, characters 23-61
Called from file "/tmp/unison-2.48.3/lwt/lwt.ml", line 75, characters 20-23
Re-raised at file "/tmp/unison-2.48.3/lwt/lwt.ml", line 135, characters 12-13
Called from file "list.ml", line 73, characters 12-15
Called from file "/tmp/unison-2.48.3/lwt/lwt.ml", line 31, characters 2-37
Called from file "/tmp/unison-2.48.3/lwt/lwt.ml", line 83, characters 17-46
Called from file "/tmp/unison-2.48.3/lwt/generic/lwt_unix_impl.ml", line 147, characters 6-40
Called from file "/tmp/unison-2.48.3/main.ml", line 202, characters 6-24
Called from file "/tmp/unison-2.48.3/main.ml", line 131, characters 4-9

Fatal error: Lost connection with the server

**Comment by bcpierce00** [comment]
Looks like the dreaded "OCaml compiler version mismatch" error.  The Unison on your server and the one on your client both need to be compiled with OCaml <= 4.02.1 (IIRC) or both with newer versions of OCaml.  There was an incompatible change to the OCaml marshaling library at around that point.

**Comment by phillord** [comment]
I am getting this issue reliably also. Both server and client are on Ubuntu 16.04.01. AFAICT, they should be running the same ocaml version (in fact this is why I updated the server to 16.04).

How can I tell which version of ocaml was used to compile?

**Comment by phillord** [comment]
I've compiled 2.48.4 from source, and put that one both sides and it appears to be working. Still I am confused why this error is happening from the 2.48.3 binary direct from ubuntu. I definately have the same version on both sides; the two binaries appear identical (same md5).

Hadn't realised unison was so easy to build. Should have done that years ago.

**Comment by bcpierce00** [comment]
Hmm -- yes, I don't understand that either.

**Comment by aklaver** [comment]
Just went through same thing. Best guess is that at some point before you updated the server you ran  a sync between versions of Unison that where not compiled with compatible versions of OCaml.  That seems to work once, but you end up with a 'corrupted' something(have not figured out what that is) that subsequent syncs choke on.

**Comment by danyill** [comment]
Despite Ubuntu 17.04 having version `2.48.3` and Debian Stretch having `2.48.3-1` I am having the same issue. If this is a critical aspect of using Unison and this issue could possibly recur, then I'd suggest `unison -version` include some relevant information to assist with diagnostics.
