### ISSUE TITLE
Availability of Windows GUI version

### ISSUE THREAD

**Issue by nengxu** [bcpierce00/unison#321]
Where can we find the latest Windows GUI version? The listed Windows download site is still at 2016:
https://www.irif.fr/~vouillon/unison/

There was an tutorial on build windows version:
https://www.onwebsecurity.com/configuration/its-about-the-journey-compiling-64-bit-unison-gtk2-on-windows.html

But it would be beneficial to have official Windows GUI version. Thanks.

**Comment by kiefer256** [comment]
I compiled [this](https://github.com/bcpierce00/unison/files/4396710/src.zip) based on the guide I wrote [here](https://github.com/bcpierce00/unison/pull/330).
It contains the Windows GUI and text versions of Unison made from the latest commit on master.
If you don't trust my build, feel free to follow the guide and compile it yourself.

**Comment by nengxu** [comment]
@kiefer256 Sorry for replying late. Just installed your version, worked well. Thank you very much!

**Comment by gdt** [comment]
The project does not really distribute binaries.

**Comment by rivy** [comment]
It should, especially the windows builds. They are quite difficult for non-experts (even experts?) to build.

GHA can be configured to automatically add binaries to any tagged release and I've added that feature to several projects ([rivy/less](https://github.com/rivy/less/releases), [uutils/coreutils](https://github.com/uutils/coreutils/releases), [sharkdp/bat](https://github.com/sharkdp/bat/releases), ...).

I'm currently working on a correct and complete windows build recipe. Ultimately, my goal is to provide an automated/no-touch build/release script which provides all of the binary releases.

**Comment by gdt** [comment]
@rivy  If you are able to figure out a way to automate this, and/or provide better instructions (as a PR that can be easily reviewed to convince the reviewer it doesn't affect anything else - because I at least know close to nothing about Windows), that sounds great.   Really I just meant that the project does not have an adopted policy of distributing binaries, and that it's clear there are not spare resources.

**Comment by rivy** [comment]
@gdt , @nengxu , I've gotten automated builds and packaging working. PR #380 contains the necessary modifications automated, no-touch releases for all platforms. In the meanwhile, you can download a build of the pending v2.53.1 release from my fork (see [GH:rivy/unison/releases](https://github.com/rivy/unison/releases)). The windows packages include all necessary dependencies and should work without installing Cygwin or GTK.

**Comment by rivy** [comment]
@gdt , @nengxu  , @IzumiRaine , @mintsoft , PR's are merged and it looks like automated builds are now fully working (see [`unison` Releases](https://github.com/bcpierce00/unison/releases)). 🚀

**Comment by mintsoft** [comment]
Awesome 👍
