### ISSUE TITLE
URLs in PDF version of manual run off end of line and are truncated

### ISSUE THREAD

**Issue by rickhg12hs** [bcpierce00/unison#325]
It would be nice if all URLs in the PDF document were readable.  After building docs from master branch (March 2020), I get unfortunate chopped URLs.

![Screenshot from 2020-03-07 23-21-30](https://user-images.githubusercontent.com/6000188/76153310-7cb33100-60ca-11ea-8784-47adb306ba7c.png)

**Comment by vaukai** [comment]
There are some more "Overfull" lines: (ebuild is from https://github.com/gentoo/gentoo/pull/17989/commits/e2d1e06)
USE='doc gtk' ebuild unison-2.51.3_p20201024.ebuild clean compile | grep Overfull | sort | uniq
Overfull \hbox (109.6327pt too wide) in paragraph at lines 806--812
Overfull \hbox (1.46704pt too wide) in paragraph at lines 2113--2121
Overfull \hbox (1.86284pt too wide) in paragraph at lines 125--126
Overfull \hbox (219.5766pt too wide) in paragraph at lines 119--121
Overfull \hbox (22.49097pt too wide) in paragraph at lines 1339--1339
Overfull \hbox (27.74092pt too wide) in paragraph at lines 1339--1339
Overfull \hbox (61.6224pt too wide) in paragraph at lines 319--322
Overfull \hbox (93.30688pt too wide) in paragraph at lines 1044--1050
