### ISSUE TITLE
memory leak with sync, rescan, and inotifyd -- unclear exactly where

### ISSUE THREAD

**Issue by jstolarek** [bcpierce00/unison#33]
I have two external drives that I use for backup. The intention is that both drives have identical content. Yesterday I had to re-create their synchronization profile. Each drive stores ~320GB of data, so the scanning took several hours. Synchronizing them went quite fast, as most files were identical. In the process Unison's memory usage went up to 1GB. I suppose that given the amount of synchronized data this might be justified. Then I made changes on one of the disks and decided to re-scan the profile for changes. Surprise: Unison did not free that 1GB of allocated memory but instead began allocating more memory. Is this expected? Does Unison keep the result of previous scans in memory to make subsequent scans faster? Or is it an unintended memory leak?

**Comment by bcpierce00** [comment]
I'm surprised by this too: As far as I can remember, nothing big should be getting cached.  However, I wonder whether it can be explained just by supposing that the second scan didn't run for long enough to encounter a garbage collection point...?

**Comment by jstolarek** [comment]
I did this on a machine with only 2GB of RAM, so when Unison started allocating more I had to kill it at one point because the system ran out of physical memory. So the second scan didn't complete but it ran for about 10 minutes. I think this should be enough for GC to trigger.

For the record: when syncing this profile Unison allocates around 740MB of RAM. The profile files are 60MB each.

Why was the bug report closed? I don't think this is fixed. :-)

**Comment by bcpierce00** [comment]
OK, so then I'm mystified too.  

I'll re-open the bug report, but I'm not sure how to make further progress (which is why I closed it :-).

**Comment by jstolarek** [comment]
Keeping this ticket open at least gives hope that someone someday will investigate this :-)

**Comment by wicope** [comment]
Hi. I try with option watch. #24 
Now with unison 2.48.4
It's related unison - option watch - inotify ?

[analysis.txt](https://github.com/bcpierce00/unison/files/715928/analysis.txt)
[ram-analysis.txt](https://github.com/bcpierce00/unison/files/715934/ram-analysis.txt)

Difficult task. Grab a debugger/memory profiler like Valgrind and run the programs one after one in it. Soon or later you will find the program that leaks and can tell it the devloper or fix it yourself.
[valgrind_manua](http://valgrind.org/docs/manual/valgrind_manual.pdf)

**Comment by einnet** [comment]
I can test it, I am using:

```
[root@server ~]# unison -version
unison version 2.48.3
```

... to sync 200GB of data (~ 100000 files and dirs with ACLs) @ XFS filesystem. I regularly use this to prevent memory leaks:

```
[root@server ~]# cat /etc/cron.daily/restart-unison 
#!/bin/bash

sleep 200
/usr/bin/killall -v -s TERM unison >> /var/log/unison.log 2>&1
sleep 2
/root/unisond.sh >> /var/log/unison.log &
```

Or maybe you're interested in gathering some data first?

**Comment by thunfischbrot** [comment]
Is there an inherent issue with large datasets containing small files? I consolidated several unison processes which were synchronizing subfolders into one via the path=-directive. The initial scan has been going on for two days now, there are two unison processes running with about 800 MB memory each, using almost no CPU at about 1-2% but reading files at 10-15 M/s. Network traffic is near zero (5-30 K/s). I started the scan a couple hours after rebooting the server, so the uptime is roughly the time unison has been running. The dataset is a little over 3TB overall, with lots of small files.

![kitty_2018-02-22_13-06-41](https://user-images.githubusercontent.com/583358/36537962-0b37eef0-17d2-11e8-8545-e7e6d124f82a.png)
This is the weaker server of the two, a Synology Diskstation 415+.

Are there ways do troubleshoot and find out why it is taking that long?

**Comment by gdt** [comment]
Please test with 2.51.3_rc2 or later.  There has been a memory fix (proper tail recursion), although it is likely this issue remains.

**Comment by tleedjarv** [comment]
It is quite certain that the memory leak issues stem from fswatcher. To verify this, you can try in your respective scenarios by setting `watch = false` and not using `-repeat watch`.

Additionally, if you are using text UI, you may be interested in testing out PR #402. To make it very simple, you can download binaries directly from GitHub https://github.com/bcpierce00/unison/actions/runs/311264574

**Comment by gdt** [comment]
Timed out, and sort of a dup.  Feel free to re-open with recent data.
