### ISSUE TITLE
How to download old binary file (not the GUI)?

### ISSUE THREAD

**Issue by KyleFromOhio** [bcpierce00/unison#332]
I need to sync with a server running 2.48.3 (from a Mac to a Linux server)
When i go to the Release page the only option is to download the Mac GUI "App". Attempting to "Install command line tool" from the GUI fails. It appears to just do nothing. All I want is the unison binary so i can run it from console. Is my only option compiling myself from source?

**Comment by ostrolucky** [comment]
https://eric.blog/2019/01/12/install-unison-2-48-4-on-mac-os-x-with-homebrew/

**Comment by igrep** [comment]
Is there what you're looking for? http://unison-binaries.inria.fr/

**Comment by gdt** [comment]
Please use the mailinglist for support requests.

The unison project basically publishes sources, and not binaries.  The main page does have a link to binaries, but it is not being updated.  So yes, compiling it yourself appears to be the best plan.
