### ISSUE TITLE
GUI does not re-open connection to server, if it has gotten closed

### ISSUE THREAD

**Issue by JoelLeach** [bcpierce00/unison#333]
I am using Unison GTK on Windows to sync between my home (client) and work (server) computers.  I am using a socket connection over a VPN to perform the sync.  I routinely sync throughout the day, and it works great.  However, if I leave the Unison client idle for some period of time (15-30 minutes?) then click the Rescan button, I get the "Lost connection to server" error.  This forces me to restart the client, although the server remains functional.  Is there some way to keep the connection alive, either by extending the idle timeout or periodically doing an automatic rescan?  I have tried versions 2.48.4 and 2.51.2, and both have the same issue.  Thanks!

**Comment by JoelLeach** [comment]
For what it's worth, I tried using SSH instead of a socket connection, and it has the same issue.

**Comment by gdt** [comment]
This is almost certainly an OS/network issue caused by a misbehaving firewall, rather than about unison.   See the documentation about TCP keepalives for your OS.

I'm hijacking this to be about what I think is actually wrong:

unison should reopen the server connection if it is closed, when the user asks to sync.

**Comment by avollmerhaus** [comment]
Until this is fixed, you might want to try setting `ServerAliveInterval nn` in your SSH client config.
This makes SSH send a keepalive-packet every `nn` seconds.
Depending on what is causing your disconnects, this might prevent them - assuming there is an active SSH connection at all.

**Comment by JoelLeach** [comment]
> Until this is fixed, you might want to try setting `ServerAliveInterval nn` in your SSH client config.

This appears to be working and preventing the lost connection.  On my Windows 10 client, I added a file name "config" to the %homepath%\\.ssh directory with the following contents:

```
Host *
    ServerAliveInterval 60
```

Of course, this is only for SSH connections.  I don't know if I am able to control the keepalive signal on socket connections established by Unison.  If there is a way, I'd probably have to configure it globally.  I will likely move my socket connections to SSH.  Thanks for the help!

**Comment by tleedjarv** [comment]
I have created a PR with a proposed solution. Please test if it works in your scenario (you can download build binaries from GitHub Actions).
