### ISSUE TITLE
Syncing filenames that contain spaces to Windows causes false detection of (not allowed) trailing space

### ISSUE THREAD

**Issue by alexanderharm** [bcpierce00/unison#335]
unison version 2.51.2 (ocaml 4.06.1)

I have this version installed on a Synology NAS (BTRFS filesystem) and a Windows 2016 Server (NTFS filesystem). I'm trying to sync one-way from Linux to Windows using the `force` parameter. I seem to experience some issues with files containing whitespaces like

```
The name of this Unix file is not allowed under Windows.  (File 'Dermapharm/013165/zwi/013165_27556_41955_1_PU_2019-09-02_Fexofenaderm 120 mg Filmtabletten/var/013165_27556_41955_1_PU_1_2019-09-02_Fexofenaderm ')
```

which indicates a file ending on whitespace which is indeed not allowed in Windows. However, when I descend into the dir, there is NO such file ending with whitespace! A `ls -la` yields

```
013165_27556_41955_1_PU_1_2019-09-02_Fexofenaderm 120 mg Filmtabletten.rtf
```

I cannot determine a clear pattern, because this seem to happen only for a few files... How can I solve this?

**Comment by tleedjarv** [comment]
@alexanderharm if this is still a valid issue for you, you can start collecting more information by adding `-debug update+` on the command line (or `debug = update+` in the profile).

You can paste or attach the debug output here but make sure that you don't have private information in there. If you'd rather not post this information in public then we can arrange a different way.

**Comment by gdt** [comment]
Feedb ack label added, starting 30-day timer for updating to 2.52.0, retesting, and debug logs.  (So far nobody else has reported this.)

**Comment by tleedjarv** [comment]
@alexanderharm could you try with a more recent version?

**Comment by gdt** [comment]
This has timed out from feedback label on May 4.   Please feel free to reopen if the issue can be reproduced on latest release or master and you can post the requested debug output
