### ISSUE TITLE
ubuntu 20.04 ocaml error and slow start

### ISSUE THREAD

**Issue by kr1979** [bcpierce00/unison#337]
After a fresh install of Ubuntu 20.04 I tried to sync with another machine running ubuntu 18.04. After hitting go I get the following:
`Server: Fatal error during unmarshaling (input_value: ill-formed message),
possibly because client and server have been compiled with differentversions of the OCaml compiler.`

And second on 20.04 it takes unison ages to start.

**Comment by clomipax** [comment]
Hi,
Exactly same isue.
Slow start -> I've the problem with other apps in Ubuntu 20.04. So not only for unison-gtk

Ocaml compiler issue to build the package, as usual :(

Im syncing a repertory with 3 computers 18.04 20.04 Ubuntu with ssh on and a server Raspbian Buster :  

Package version in ubuntu 20.04 : 2.48.4
Package version in ubuntu 18.04 : 2.48.4
Package in Raspbian Buster : 2.48.4

Same version, but not same Ocalm compiler.

In ubuntu 20.04 I find this :
```
unison (2.48.4-3) unstable; urgency=medium

  This version is compiled with a new version of OCaml (4.08.1) and
  is incompatible with previous versions of unison shipped in Debian,
  in particular the one in Debian 10 (buster).

 -- Stéphane Glondu <glondu@debian.org>  Tue, 03 Dec 2019 11:38:54 +0100
```

So What to do ?

**Comment by glondu** [comment]
Concerning the slow startup: as said, it doesn't seem specific to unison-gtk. The text UI doesn't seem affected by this issue.

Do the Ubuntu 18.04 and Raspbian Buster interoperate? I think they should. If so, I would suggest to copy the Ubuntu 18.04 unison(-gtk) executable to the Ubuntu 20.04 box somewhere, and use it directly (if the client is the Ubuntu 20.04 box), or make `servercmd` point to it in your profile (if the server is the Ubuntu 20.04 box).

I am very sorry for this situation, and I am trying to improve stuff but this will take time.

**Comment by twin7** [comment]
> Do the Ubuntu 18.04 and Raspbian Buster interoperate? I think they should. If so, I would suggest to copy the Ubuntu 18.04 unison(-gtk) executable to the Ubuntu 20.04 box somewhere, and use it directly (if the client is the Ubuntu 20.04 box), or make `servercmd` point to it in your profile (if the server is the Ubuntu 20.04 box).

This does not work for me, I get the following error (running unison on the Ubuntu box, the server is raspbian buster):

```
Uncaught exception Failure("input_value: ill-formed message")
Raised at file "/build/unison-Y9EcQW/unison-2.48.4/lwt/lwt.ml", line 126, characters 16-23
Called from file "/build/unison-Y9EcQW/unison-2.48.4/lwt/generic/lwt_unix_impl.ml", line 102, characters 8-23
Called from file "/build/unison-Y9EcQW/unison-2.48.4/update.ml" (inlined), line 2096, characters 2-69
Called from file "/build/unison-Y9EcQW/unison-2.48.4/uitext.ml", line 700, characters 16-56
Called from file "/build/unison-Y9EcQW/unison-2.48.4/uitext.ml", line 788, characters 6-90
Called from file "/build/unison-Y9EcQW/unison-2.48.4/uitext.ml", line 810, characters 19-66
Called from file "/build/unison-Y9EcQW/unison-2.48.4/uitext.ml", line 870, characters 21-43
```

**Comment by twin7** [comment]
> > Do the Ubuntu 18.04 and Raspbian Buster interoperate? I think they should. If so, I would suggest to copy the Ubuntu 18.04 unison(-gtk) executable to the Ubuntu 20.04 box somewhere, and use it directly (if the client is the Ubuntu 20.04 box), or make `servercmd` point to it in your profile (if the server is the Ubuntu 20.04 box).
> 
> This does not work for me, I get the following error (running unison on the Ubuntu box, the server is raspbian buster):

After deleting the cache file (fp...), this combination (Ubuntu 18.04/Raspbian Buster) finally works for me.

**Comment by clomipax** [comment]
I confirm :
* import exec files unison-2.48.4 and unison-2.48.4-gtk from Ubuntu 18.04 to Ubuntu 20.04 in /usr/bin/
* Clean all cache files in .unison directory on all machines
And it works !

For slow startup, installation (and dependencies) :
`sudo apt-get install appmenu-gtk2-module`
Reboot

**Comment by kr1979** [comment]
For slow startup, installation (and dependencies) :
`sudo apt-get install appmenu-gtk2-module`
Works for me, thanks for the reply.

**Comment by clomipax** [comment]
Thank's too

About slow startup. I don't have default on all my computers.
This default occurs for old style Xorg sessions. (typically Computers with Nvidia non free driver)
No default in Wayland sessions.

**Comment by nickma82** [comment]
Is one able to figure out the OCaml version with which unison was compiled?

**Comment by nickma82** [comment]
OCaml versions (change) should be encoded directly into the unison version string. Such that the downstream version (incompatibility) is immediately visible to the user.

**Comment by jeltz** [comment]
Ideally Unison should use a serialization format which does not depend on OCaml version (and if possible also works across different versions of Unison) but that could be quite a bit of work.

**Comment by micksulley** [comment]
I have Unison version 2.48.4 running on my desktop, Mint 20, and my server Ubuntu Server 19.10
I just went through the tutorial and it fails at the Remote Shell Method with the message
Fatal error: Server: Fatal error during unmarshaling (input_value: ill-formed message),
possibly because client and server have been compiled with different versions of the OCaml compiler.

Unison was installed from repository in both cases.  What can I do to get this to work again?
Mick

**Comment by glondu** [comment]
> Ideally Unison should use a serialization format which does not depend on OCaml version (and if possible also works across different versions of Unison) but that could be quite a bit of work.

I've made two forks that do not depend on OCaml version: https://github.com/glondu/unison/tree/protobuf and https://github.com/glondu/unison/tree/bin_prot . But they have more dependencies. I've been using the first one for months without harm, but it won't work on 32-bit platforms with large repositories. The second should, but has not been that much tested.

They depend on https://github.com/bcpierce00/unison/pull/351 , so I'm waiting for @bcpierce00 to process it before going further.

**Comment by micksulley** [comment]
I don't believe that my problem is mismatch of OCaml versions.  Both Mint20 and Ubuntu Server 19.10 are running Unison 2.48.4 and both were downloaded from the Ubuntu repository, so they should be identical.  Is there anything I can try to confirm this?

**Comment by clomipax** [comment]
Don't forget, you MUST clear all Unison traces and logs in ".unison" directories on all devices.

**Comment by glondu** [comment]
> I don't believe that my problem is mismatch of OCaml versions. Both Mint20 and Ubuntu Server 19.10 are running Unison 2.48.4 and both were downloaded from the Ubuntu repository, so they should be identical. Is there anything I can try to confirm this?

This can be seen in build logs.

Mint20 is based on Focal, whose Unison is compiled with OCaml 4.08.1 (I could not find build logs of Mint). Ubuntu Server 19.10 is Eoan, whose Unison is compiled with OCaml 4.05.0.

**Comment by micksulley** [comment]
So what is the solution?  Do I need to build it myself?  I'm happy to give it a go but are there any instruction to do that?

**Comment by glondu** [comment]
If both systems are the same architecture, you can copy the binary from one system to the other so that you use the same binary everywhere.

**Comment by sergey1369** [comment]
You can use binary from old deb package: 
https://packages.ubuntu.com/bionic/unison

uname -m 
# Must be x86_64 for example below.

wget http://mirrors.kernel.org/ubuntu/pool/universe/u/unison/unison_2.48.4-1ubuntu1_amd64.deb
sudo dpkg -r unison
sudo dpkg -i unison_2.48.4-1ubuntu1_amd64.deb
sudo apt-mark hold unison

**Comment by micksulley** [comment]
Many thanks Sergy, it now works fine!!  

> You can use binary from old deb package:
> https://packages.ubuntu.com/bionic/unison
> 
> uname -m
> # Must be x86_64 for example below.
> 
> wget http://mirrors.kernel.org/ubuntu/pool/universe/u/unison/unison_2.48.4-1ubuntu1_amd64.deb
> sudo dpkg -r unison
> sudo dpkg -i unison_2.48.4-1ubuntu1_amd64.deb
> sudo apt-mark hold unison

**Comment by nickma82** [comment]
> uname -m
> # Must be x86_64 for example below.
> 
> wget http://mirrors.kernel.org/ubuntu/pool/universe/u/unison/unison_2.48.4-1ubuntu1_amd64.deb

More generic:
```
wget "http://mirrors.kernel.org/ubuntu/pool/universe/u/unison/unison_2.48.4-1ubuntu1_$(dpkg --print-architecture).deb"
sudo dpkg -r unison
sudo dpkg -i unison_2.48.4-1ubuntu1_amd64.deb
sudo apt-mark hold unison
```

**Comment by gdt** [comment]
This bug report seems to be basically
  * a symptom of "unison needs to have matching ocaml versions" #375 
  * some ubuntu issues that are not about unison (startup)
  * a (valid) lament about lack of prebuilt binaries

I don't find anything actionable not captured elsewhere, so am closing it.

**Comment by hlovdal** [comment]
It's an [old issue](https://github.com/bcpierce00/unison/issues/94) and an even older problem. But I am glad that there currently seems to be some work ongoing to fix it.
