### ISSUE TITLE
unison-fsmonitor ignores system python configuration

### ISSUE THREAD

**Issue by tidux** [bcpierce00/unison#339]
The pyinotify module is installed in /usr/lib/python2.7/dist-packages/ but fsmonitor.py is doing something nonstandard and ignoring it.  This is Ubuntu 18.04.

```
$ python
Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyinotify
>>> 
$ unison -ui text
Contacting server...
Connected [//remote.host//path/to/workspaces -> //local.host//workspaces]
Looking for changes
  Waiting for changes from server
Traceback (most recent call last):
  File "/home/tidux/bin/unison-fsmonitor", line 213, in <module>
    import pyinotify
ImportError: No module named pyinotify
Fatal error: Server: File monitoring helper program not running
$ 
```

Adding a debug print to `fsmonitor.py` reveals that `sys.path` does include the directory `/usr/lib/python2.7/dist-packages`.  Running that file with the system python interpreter does **NOT** throw a missing import error.  The problem is with whatever terrible nonstandard way Python is being invoked from inside the `unison` binary.  Please correct this.

**Comment by tidux** [comment]
Even with an alternate `unison-fsmonitor` implementation in the same directory, unison keeps creating what appears to be a fake Python script file on top of it in the same directory as the unison binary.  This is malware behavior.

**Comment by tidux** [comment]
Adding another symlink from $HOME/bin/unison-fsmonitor to $HOME/bin/unison-fsmonitor-$UNISONVERSION shows even odder behavior.

```
Traceback (most recent call last):
  File "$INSTALL_PATH_ON_REMOTE_SERVER/bin/unison-fsmonitor", line 213, in <module>
\ .venv/bin/activate.fish    import pyinotify
ImportError: No module named pyinotify
  Waiting for changes from server                                       
Fatal error: Server: File monitoring helper program not running
```
I am not running fish on the remote server, nor do I have any Python venvs active.  What the hell?

**Comment by gdt** [comment]
To fix, almost certainly needs understanding and changing the build system, to remove the need for the hack that seems to exist.

**Comment by gdt** [comment]
Please retest with 2.51.3.  Please explain if when invoking the python interpreter in the script, one can import pynotify without contortions, and if not, why this is a unison bug -- it seems obvious that the system python library path should be included by default.

**Comment by gdt** [comment]
Feedback timeout.
