### ISSUE TITLE
make test /selftest fails on Windows (MSYS2 / mingw32)

### ISSUE THREAD

**Issue by PeterMosmans** [bcpierce00/unison#34]
Hi, when cloning the repo, and building on Windows 10 using msys2 / mingw32, the build process succeeds. However, the test (-selftest) seems to fail.

build commands:
`make OSARCH=win32gnuc`

The build succeeds, the tests don't:
```
% src/unison.exe -version
unison version 2.50.0 (ocaml 4.02.3)
 % src/unison.exe -selftest
The system cannot find the path specified.
Uncaught exception End_of_file
Raised at file "pervasives.ml", line 384, characters 20-31
Called from file "./uicommon.ml", line 499, characters 13-26
Called from file "./uicommon.ml", line 553, characters 17-41
Called from file "./uicommon.ml", line 736, characters 2-86
Called from file "./uitext.ml", line 839, characters 4-543
```
compiler / OS versions:
```
% gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 6.1.0
 % uname
MINGW32_NT-10.0
% ocaml -version
The OCaml toplevel, version 4.02.3
```

Am I doing something wrong here ?

Thanks in advance,

Peter

**Comment by bcpierce00** [comment]
Running with "-debug verbose" may give some insight into how far it's getting. 

However, the self tester may never have been exercised on Windows, so the fact that it is not working may or may not be an indication of real problems.  (E.g., it may just be trying to open some temp directory with a unixy name.)  It is not in a very useful state at the moment anyway, BTW -- on my system it currently just runs one test!

**Comment by PeterMosmans** [comment]
Thanks, then I'll ignore the selftest on Windows. Adding `-debug verbose` to the selftest doesn't show anything different BTW.
Would it be an idea to keep this issue open, as it is more or less a bug ? Who knows who will dive into this... :wink:
