### ISSUE TITLE
Uncaught exception Failure("input_value: ill-formed message")

### ISSUE THREAD

**Issue by DamianMalik** [bcpierce00/unison#343]
After upgrading notebook to Ubuntu 20.04 LTS, I am unable to sync a path between my notebook and my desktop pc, that worked well for years. I get the error "Fatal error. Lost connection with the server." 

Trying to sync the opposite direction from desktop pc to Notebook (same path), I get following error message: 

```
Fatal error

Uncaught exception Failure("input_value: ill-formed message")
Raised at file "/build/unison-WhGSf0/unison-2.48.3/lwt/lwt.ml", line 126, characters 22-23
Called from file "/build/unison-WhGSf0/unison-2.48.3/lwt/generic/lwt_unix_impl.ml", line 102, characters 8-23
Called from file "/build/unison-WhGSf0/unison-2.48.3/update.ml", line 2096, characters 2-69
Called from file "/build/unison-WhGSf0/unison-2.48.3/uigtk2.ml", line 3381, characters 16-32
Called from file "/build/unison-WhGSf0/unison-2.48.3/uigtk2.ml", line 156, characters 18-22
Called from file "/build/unison-WhGSf0/unison-2.48.3/uigtk2.ml", line 3919, characters 4-37
Called from file "/build/unison-WhGSf0/unison-2.48.3/uigtk2.ml", line 4276, characters 4-16
```

**Comment by pselkirk** [comment]
I'm seeing the same thing, going from Mac (unison 2.48.15, unchanged) to Ubuntu (2.48.4-1ubuntu1 upgraded to 2.48.4-4ubuntu1).

I eventually installed the 2.51.2 binary on Mac (ocaml 4.04.0), and built Unison from tag v2.51.2 with ocaml from Bionic (4.05.0) - closest I could get to 4.04 without building ocaml from source as well - and it STILL fails:
```
Unison server failed: Uncaught exception Failure("input_value: ill-formed message")
Raised at file "/home/pselkirk/unison/src/lwt/lwt.ml", line 135, characters 6-13
Called from file "list.ml", line 85, characters 12-15
Called from file "/home/pselkirk/unison/src/lwt/lwt.ml", line 31, characters 2-37
Called from file "/home/pselkirk/unison/src/lwt/lwt.ml" (inlined), line 83, characters 17-46
Called from file "/home/pselkirk/unison/src/lwt/generic/lwt_unix_impl.ml", line 55, characters 6-23
Called from file "/home/pselkirk/unison/src/lwt/generic/lwt_unix_impl.ml", line 147, characters 6-40
Called from file "/home/pselkirk/unison/src/main.ml", line 204, characters 6-24
Called from file "/home/pselkirk/unison/src/main.ml", line 132, characters 6-11
```

**Comment by jodysankey** [comment]
I'm also seeing this between LTS Ubuntu (unison 2.48.4) and Debian (2.48.3). Also note a previous Fedora bug for the same issue (https://bugzilla.redhat.com/show_bug.cgi?id=1768019) and other bugs here (https://github.com/bcpierce00/unison/issues/337, https://github.com/bcpierce00/unison/issues/334).

After previously suffering through a year of backports to keep unison working after the last OCaml change its a little disheartening to be back here again. It seems very brittle for a program designed for communication between computers to assume both ends were built with an identical version of OCaml rather than defining its own serialization. Is there any work towards a more structural solution? Would more resources, either donations or time, help?

**Comment by igrep** [comment]
@jodysankey At least time of the author lacks. https://github.com/bcpierce00/unison/issues/299

**Comment by nickma82** [comment]
https://github.com/bcpierce00/unison/issues/337#issuecomment-628639325

**Comment by pselkirk** [comment]
Revisiting this after reading #337, I deleted all archive and cache files on both machines, and now it works, at least with 2.51.2.

**Comment by antofthy** [comment]
Still is a problem between FC29 and FC31  and again between FC31 and FC32
It was only after I deleted all 'fp' files and copied the FC31 compilation to FC32, was I able to get around this error.

**Comment by gdt** [comment]
Dup with #375, I think.  Reopen if not.
