### ISSUE TITLE
unison reads HOME from environment, and this is in conflict with "setcap" on Linux

### ISSUE THREAD

**Issue by aldennisa15** [bcpierce00/unison#344]
(This is with v2.48.4, as shipped in Debian 10 'Buster', but the tip source looks the same in this area.)

I've run Unison for many years with `-socket 873` on a central machine to serve a handful of clients.

In order to do so, I've had to do `setcap 'cap_net_bind_service=+ep' <path for unison>` to give it the capability to bind to a system socket (i.e. < 1024). This causes it to run in "secure execution mode" (`AT_SECURE=1`) - see [`man getauxval`](http://man7.org/linux/man-pages/man3/getauxval.3.html).

Ocaml 4.04.2+ uses [`secure_getenv`](http://man7.org/linux/man-pages/man3/secure_getenv.3.html) to access the environment variables ([`sys getenv`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Sys.html)). This returns `null` in secure execution mode and was introduced by [Ocaml issue #7557 - local privilege escalation issue with ocaml binaries](https://github.com/ocaml/ocaml/issues/7557). In Unison, this results in `Fatal error: exception Util.Fatal("Environment variable HOME not found")`, even though `HOME` is correctly set. This can be confirmed by creating a copy of the `unison` binary, one with and one without the `setcap` set and running each in the same environment etc with `-version`. Without the `setcap` it runs normally, with the `setcap` it reports it can't find `HOME`.

[The Ocaml issue](https://github.com/ocaml/ocaml/issues/7557#issuecomment-473069783) suggests that "suid programs should not read `HOME` (to avoid being tricked into writing preference files into `/etc/init.d`), and should instead use `Unix.getpwuid`."

Maybe Unison should use this method to determine the home directory and hence avoid having to access the `HOME` env var (and any other env vars) which wont be accessible to it when running with a `setcap` active, e.g. for running with `-socket`.

**Comment by aldennisa15** [comment]
To avoid breaking existing installations that use a custom HOME env var, maybe when getenv returns null, Unison should then try the getpwuid method to determine the home directory, rather than just stopping with this error, as it does now. That would fix this problem of no longer being able to apply setcap to Unison.

(This does assume that Unison is content to live with the underlying security vulnerability of continuing to allow use of the HOME env var at all.)

**Comment by glondu** [comment]
The problem with getpwuid is that you cannot change it just for one process. I would prefer to use `Unix.unsafe_getenv "HOME"`, or (maybe) introduce a (new?) command-line option to explicitly specify `HOME`.

**Comment by gdt** [comment]
Rereading, I think the real issue is that unison should not be run with elevated privileges.  It has not been designed for or audited for that purpose.


It seems that if somebody needs a workaround, then adding a command-line argument to specify the HOME location (or perhaps the unison directory) would be reasonable.

**Comment by gdt** [comment]
Meant to add in the previous:  I don't really want to start down the path of making unison work setuid before it's been audited properly, and it's really obvious that isn't going to happen.

**Comment by gdt** [comment]
Documentation updated to say that Unison is not designed for elevated privileges:

https://github.com/bcpierce00/unison/commit/f0551000e89c46a1c070a799a9c3175965892513

I suggest using a different port, if you can't configure your system to allow a low port without blocking environment variables.
