### ISSUE TITLE
Variable in .prf file

### ISSUE THREAD

**Issue by aescott** [bcpierce00/unison#346]
Is there an easy way to use a variable in the .prf file? I have

```
follow·=·Path·Path·DirOfInterest/build⬎⬎
ignorenot·=·Path·DirOfInterest/a/b/whatever
```
... etc. PathOfInterest changes several times a day. Can I use a variable in here, env or local or otherwise so I can only change it in one place, easily & quickly?

**Comment by bcpierce00** [comment]
Not directly, but you could use a little shell script to generate the .prf file from a template…

**Comment by aescott** [comment]
Ok thanks. Thought it might be some F# wizardy but it's just text parsing AFAICS.
