### ISSUE TITLE
Is most current version 2.51.2 or 2.51.3?

### ISSUE THREAD

**Issue by thehunmonkgroup** [bcpierce00/unison#347]
https://github.com/bcpierce00/unison/commit/c2f3b76a11b593d37ee595065b212dd4c495f4ba seems to indicate a version 2.51.3, but the git tags and official releases show 2.51.2 -- curious if a 2.51.3 tag/release was missed?

**Comment by rickhg12hs** [comment]
Looking at the tagging/development scheme used in this project, it seems the version number is bumped  (c2f3b76a11b593d37ee595065b212dd4c495f4ba version 2.51.3) sometime after tagging/releasing (01761881 version 2.51.2).

So, if you build from branch master sometime after a tag/release, the version number will advance.

**Comment by pascalandy** [comment]
related to https://github.com/bcpierce00/unison/issues/245

**Comment by gdt** [comment]
Please use the mailinglist for support questions.  The issue tracker is only for actionable feature requests and defects.
