### ISSUE TITLE
make does not yield a gtk-version

### ISSUE THREAD

**Issue by mauricemeyer** [bcpierce00/unison#35]
I just set up everything needed to build the software (gtk2, lablgtk2).

When running `make`, I get the desired result: An unison executable.
But when I run `make UISTYLE=gtk2`, I get the following output:

``` bash
[maurice unison]$ make UISTYLE=gtk2
make -C src UISTYLE=text
make[1]: Verzeichnis „/home/maurice/dev/unison/src“ wird betreten
UISTYLE = text
Building for Unix
NATIVE = true
THREADS = false
STATIC = false
OSTYPE =
OSARCH = Linux
make tags
make[2]: Verzeichnis „/home/maurice/dev/unison/src“ wird betreten
if [ -f "`which etags`" ]; then \
    etags *.mli */*.mli *.ml */*.ml */*.m *.c */*.c *.txt \
          ; fi 
which: no etags in (/home/maurice/Android/android-studio/bin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/maurice/.gem/ruby/2.3.0/bin/)
make[2]: Verzeichnis „/home/maurice/dev/unison/src“ wird verlassen
make[1]: Verzeichnis „/home/maurice/dev/unison/src“ wird verlassen
```

What I don't understand is why it's still called with `UISTYLE=text` although I specify gtk2.

I'm running an up-to-date Arch system.
Did I miss something or?

**Comment by bcpierce00** [comment]
cd to the src directory first and it will work better.  (The top-level makefile builds a text version by default.  I agree that this is confusing and will change it.)
