### ISSUE TITLE
`make test` fails on git master branch when compiled for GUI

### ISSUE THREAD

**Issue by rickhg12hs** [bcpierce00/unison#350]
`make test` after successful `make` and `make install` pops-up the "Profile Selection" dialog.  There are no profiles after install and so the test fails.

Incomplete configuration?

**Comment by bcpierce00** [comment]
"make test" was intended to work with a text UI.  Sounds like here it's compiled so that the GUI is the default...?

**Comment by rickhg12hs** [comment]
@bcpierce00 Yes, it was compiled to use the GUI.

Executing,
```bash
./src/unison -ui test -selftest
```
... just returns the help options, etc.

But,
```bash
./src/unison -selftest -ui text
```
... runs all the tests and completes successfully!

**Comment by glondu** [comment]
> @bcpierce00 Yes, it was compiled to use the GUI.
> 
> Executing,
> 
> ```shell
> ./src/unison -ui test -selftest
> ```
> 
> ... just returns the help options, etc.

It's `-ui text` (and not `-ui test`).

**Comment by rickhg12hs** [comment]
@glondu Oops, you're right!

Still, shouldn't `make test` "just work" when compiled for the GUI?

**Comment by gdt** [comment]
There is perhaps a build system bug lurking; it seems that the CUI should always be built, and the GUI if requested.   But that is perhaps a "back when I was young, the VT52 was awesome because it not only had 24x80 but also lower case!" kind of comment.

**Comment by bcpierce00** [comment]
The sad truth is that “make test” is not used (or maintained) as much as it should be...

**Comment by rickhg12hs** [comment]
Maybe for starters just change:

https://github.com/bcpierce00/unison/blob/ec65329df28074e28d2831087460a7d4a430e3ad/Makefile#L9

to
```
     ./src/unison -selftest -ui text
```

**Comment by gdt** [comment]
This still fails in 2.51.3_rc2 despite having a valid DISPLAY (xdpyinfo works), NetBSD 8 amd64.

```
./src/unison -selftest
Uncaught exception Gtk.Error("GtkMain.init: initialization failed\nml_gtk_init: initialization failed")
Raised by primitive operation at file "gtkMain.ml", line 42, characters 1-14

Fatal error: exception Util.Fatal("Main window not initialized; check your DISPLAY setup")
Raised at file "/tmp/work/net/unison-snapshot/work/unison-2.51.3_rc2/src/uigtk2.ml", line 144, characters 14-88
Called from file "/tmp/work/net/unison-snapshot/work/unison-2.51.3_rc2/src/uigtk2.ml", line 677, characters 27-46
Called from file "/tmp/work/net/unison-snapshot/work/unison-2.51.3_rc2/src/uigtk2.ml", line 4310, characters 31-61
Called from file "/tmp/work/net/unison-snapshot/work/unison-2.51.3_rc2/src/main.ml", line 243, characters 2-256
Called from file "/tmp/work/net/unison-snapshot/work/unison-2.51.3_rc2/src/linkgtk2.ml", line 19, characters 18-40
gmake: *** [Makefile:9: test] Error 2
*** Error code 2
```
