### ISSUE TITLE
Possible race condition error when trying to rename/set permission/modification time of duplicate paths 

### ISSUE THREAD

**Issue by daaugusto** [bcpierce00/unison#355]
Simplifying my case, suppose I have two .path files: one (`parent.path`) which contains the directory
`foo` and the second (`child.path`) which contains the subdirectory `foo/bar`. These two files are
included by two .prf files: the first (`partial.prf`) includes just the file `child.path`, and the
second (`full.prf`) includes both `parents.path` and `child.path`. This is because sometimes I need to
perform a full synchronization and sometimes just a partial synchronization. (There is a reason why
I need to have this setup of path files, which may not seem obvious in this simplified scenario.)

Then, if I change something in `foo/bar/` and invoke `unison full` (i.e. full synchronization), unison
would do something like that (in this case I created the file `baz`):

```
   local                     remote
   new file ---->            foo/bar/baz
   new file ---->            foo/bar/baz
Proceed with propagating updates? []
```

The problem is that if I proceed with the synchronization, unison will fail like so:

```
UNISON 2.48.4 started propagating changes at 02:59:37.68 on 12 Jul 2020
[BGN] Copying foo/bar/baz from /home/user to //remote//home/user
[BGN] Copying foo/bar/baz from /home/user to //remote//home/user
/home/user/foo/bar/baz has already been transferred
[END] Copying foo/bar/baz
Failed: Error while renaming /home/user/foo/bar/.unison.a.fbeb972bbfa4c9c2696418e43d01130f.unison.tmp to /home/user/foo/bar/baz -- source file has disappeared!
100%  00:00 ETAFailed [foo/bar/baz]: Error while renaming /home/user/foo/bar/.unison.a.fbeb972bbfa4c9c2696418e43d01130f.unison.tmp to /home/user/foo/bar/baz -- source file has disappeared!
UNISON 2.48.4 finished propagating changes at 02:59:37.74 on 12 Jul 2020

Saving synchronizer state
Synchronization incomplete at 02:59:38  (1 item transferred, 0 skipped, 1 failed)
  failed: foo/bar/baz
```

It seems that two threads are trying to rename (or set permission/modification time, depending on
the type of synchronization) the same file at the same time! Evidence of this is that when I set
-maxthreads 1 then no error occurs. Unless I'm missing something here, I thing this is a bug. To
begin with, I think unison should detect that it is trying to sync the same file twice! Moreover,
some sort of mutex should be employed to prevent data race like this, or at least fall back
automatically to single thread when the same path appears multiple times in the synchronization
list.

I'm using UNISON 2.48.4.

Best regards

**Comment by gdt** [comment]
Please retest with 2.51.2 or newer (really, once 2.51.3 is out I'll want testing with that, and git master is a good proxy for htat today).   2.48 is not supported.

**Comment by vincentbernat** [comment]
I hit this problem with 2.51.3. It's easy to reproduce by just having:

```
path = foo
path = foo
```

**Comment by daaugusto** [comment]
Hi Vincent, thanks for confirming it on a newer unison version.
