### ISSUE TITLE
unison does not support the Windows-only filesystem feature "junction"

### ISSUE THREAD

**Issue by stdedos** [bcpierce00/unison#356]
Windows 10 1909 (18363.836), UNISON 2.51.2 (OCAML 4.06.1)

Syncing is done within the same Windows system, so duplicating the junction should be enough.

**Comment by gdt** [comment]
There is a deep question behind this PR, in terms of support for POSIX filesystems as the norm, and how non-POSIX features are mapped into POSIX.   I would tend to say unison should avoid crossing the line into non-POSIX features, at least without a design rationale for how that would work, which would be an appropriate topic for the mailinglist.

**Comment by gdt** [comment]
It would also help to explain what "junction" means, and how it relates to anything defined in POSIX.

**Comment by bcpierce00** [comment]
Yes, these are deep waters!

**Comment by stdedos** [comment]
I am not sure if I can be more helpful than those articles:

https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions
https://docs.microsoft.com/en-us/windows/win32/fileio/symbolic-links

**Comment by gdt** [comment]
This issue needs a clear statement of what ought to be, and that probably involves an analysis of how unison responds to hard links that on one replica are within a filesystem and on other are not.   I suspect there is woe there, and that deserves a separate issue.

This issue probably then turns into "when on widnows, recognize junctions and treat them semantically as hardlinks" and "when trying to create a hardlink and the two paths are on different filesystems, use a function".

**Comment by bcpierce00** [comment]
Hard links was something that we explicitly chose not to deal with at the very beginning of Unison’s design, because they fundamentally change the data model (from a tree to a graph).  So addressing them would mean truly going all the way back to the drawing board and figuring out what it means to synchronize a graph.  Not impossible, and certainly interesting, but not a simple project at all.

**Comment by stdedos** [comment]
I am no expert by no means, I'll just roll the conversation speaking my mind.

The reason I am calling `Junctions` "`Soft-links`" (and why I am asking this as a "relatively easy addition to make"), is that I don't understand how hard-link directories work (from a practical standpoint, not a theoretical) nor have I seen any. I was under the impression that they were explicitly forbidden, to forbid filesystems to mutate to a graph model.

Basically what am proposing would be roughly:

```python
	if (os.name == 'nt' && os.path.isjuction(item.path)):
		os.system('mklink /j %s %s' % (
			os.path.join(other_syncpath(item.path), strip_syncpaths(item.path)), 
			os.readjunction(item.path))
		)

```
(https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)

Nothing more, nothing less.

I don't remember what the behavior was when I reported this - if "fixing" this is a (much) more complicated matter, then by all means feel free to ignore this.
If they are "troublesome" in any regard, then maybe kindly ignore them implicitly or explicitly from any sync-views.

**Comment by gdt** [comment]
In Unix (and hence POSIX), hardlinks are only allowed for files, not directories.     This has been true since Sixth Edition at least.   If a junction is sort of like a hardlink but can be on directories, that's a massive departure from the model, and seems pretty scary.

**Comment by stdedos** [comment]
> In Unix (and hence POSIX), hardlinks are only allowed for files, not directories. This has been true since Sixth Edition at least. If a junction is sort of like a hardlink but can be on directories, that's a massive departure from the model, and seems pretty scary.

I just tried it out. I don't think that "junction is sort of like a hardlink", because it is not able to "sustain" deletion of the originator directory. Even WSL is presenting this as a symlink:
```console
$ ls -lah desktop/remove_elisions_2\ -\ Junction
lrwxrwxrwx 1 stdedos stdedos 56 Sep 14 21:11 'desktop/remove_elisions_2 - Junction' -> '/mnt/e/remove_elisions_2'
```

I think "junction is sort of like a softlink but Microsoft is calling it a hardlink-derivative idk why".
Also that may help: https://superuser.com/questions/343074/directory-junction-vs-directory-symbolic-link

**Comment by tleedjarv** [comment]
Support for syncing symlinks in Windows was added in version 2.51.5.

**Comment by gdt** [comment]
Given that unison supports symlinks on Windows, and that after discussion we still didn't really understand what should happen, I'm going to close this.   @stdedos please feel free to write up a full design and post to unison-hackers@ if you would like to pursue this.  By full design, I mean not only an explanation of what junctions are, but what unison should do in every case, including syncing something with junctions to a POSIX filesystem, and syncing symlinks to windows on a system where the user does not have symlink permission but does have junction permission, and what happens on windows in a mixed junction/symlink environment.

I should warn you that this seems like an obscure case and I am probably not going to be willing to accept much complexity to support it.  And, nobody contributing to unison maintenance really uses Windows, and definitely neither of us are missing junction support -- so after a design the next step is somebody contirbuting code.

Thanks for the discussion, but I think this is beyond what the project can cope with.
