### ISSUE TITLE
Windows paths with '\' are allowed as roots, but not as `-ignore` arguments

### ISSUE THREAD

**Issue by stdedos** [bcpierce00/unison#357]
Wrong:
```
E:\PortableApplications\Syncing\unison-windows-2.51.2-text\unison.exe "C:\Program Files\Portable Apps" "E:\PortableApplications\#Release" -auto -ignore "BelowPath Sublime Text 3\_Data\Sublime Text 3"
```

Correct:
```
E:\PortableApplications\Syncing\unison-windows-2.51.2-text\unison.exe "C:\Program Files\Portable Apps" "E:\PortableApplications\#Release" -auto -ignore "BelowPath Sublime Text 3/_Data/Sublime Text 3"
```

**Comment by tleedjarv** [comment]
This is not trivial.

The manual includes this caveat:
```
The path separator in path patterns is always the forward-slash character “/” — even when the client
or server is running under Windows, where the normal separator character is a backslash. This makes
it possible to use the same set of path patterns for both Unix and Windows file systems.
```

On top of this, the real blocker is that these are not _paths_ but regexp or glob expressions. This means that backslashes are escape characters.

I'm not saying you should close the issue. On the contrary, I believe a solution would be nice for Windows users. It's just unlikely that anyone is going to work on this any time soon.

**Comment by gdt** [comment]
I'm leaving DISCUSS because there is no path forward that is clearly correct and better than other approaches.

It seems the APIs in Windows allow /, so perhaps we should just document that unison always uses POSIX-compliant paths.

I am curious if @stdedos can confirm if configuring unison with root specifications using / works.  Then the -ignore arguments would match :-)

I'm happy to listen if there is a proposed way forward that does not involve any semantic uncleanliness or other awkwardness, and someone wants to write code to do it.   But I don't use windows, and this isn't something that seems to be causing real trouble, hence my WONTFIX label.

**Comment by stdedos** [comment]
Then, please document such behavior. 

It's always nice to understand what are you expected to do, when you don't want to start using the GUI to learn the TUI.

**Comment by gdt** [comment]
Things get improved because people contribute.  Please feel free to file a PR with documentation improvements.

**Comment by tleedjarv** [comment]
> Then, please document such behavior.

What exactly are you referring to?

There is the passage I quoted above. Then there is also this:
```
Note that the path separator character is
always a forward slash, no matter what operating system Unison is running on. Forward slashes are converted
to backslashes as necessary when paths are converted to filenames in the local filesystem on a particular host.
```

I think there is some converting going on (I haven't check where exactly, but as you said, you can use '\\' in the root specification). But those are literal paths, not regular expressions or "glob" expressions; and this is an undocumented feature as far as I can see.

**Comment by gdt** [comment]
I think we've arrived at
  - this isn't really a bug as much as a choice
  - given regex/glob, \ is awkward as the regex world sees that as an escape character
  - the rule about using / even on windows for paths is documented
  - the rules for Ignore patterns are documented
 
So if there's anything left, it's perhaps to tighten up accepting \ in path specifiers, perhaps to document it, and perhaps to leave it as a reasonable choice for what is formally undefined behavior.   (Perhaps we need a regression test for POSIX that verifies root specifications work for directories that contain \, but surely people avoid doing that.)

This has been useful to me, as I had previously not understand this issue at all (I don't use Windows).

So I think we've arrived at time to close.  Any reason not to?

**Comment by acolomb** [comment]
Agree on closing. The behavior is sensible and documented. Roots need to be whatever the OS understands. Everything else handles root-relative paths which are specified to use forward slash. All good from my perspective.

**Comment by stdedos** [comment]
> I am curious if @stdedos can confirm if configuring unison with root specifications using / works. Then the -ignore arguments would match :-)

It seems that this is possible, indeed. "It's just a little weird" on Windows (but then again, this isn't the first time I've seen it).

> The manual includes this caveat:
> 
> ```
> The path separator in path patterns is always the forward-slash character “/” — even when the client
> or server is running under Windows, where the normal separator character is a backslash. This makes
> it possible to use the same set of path patterns for both Unix and Windows file systems.
> ```

Oh yeah, silly me 😓
I assumed that _the manual_ mentioned Unison's building blocks, not _Unison itself_.

I'd "guard" Windows users, by catching "regex escapes with no reason" and issue a message like:
"Did you mean to use `/` instead of `\`?"

In Perl regex, there is _an absurd amount of regex escapes_, but not "so many" on other variants.
IIRC, e.g. `\A` is not a regex escape; instead, it is parsed literally as `\A`.

However, this might be tricky too. If it's "complicated" to allow `\` for paths, then I guess this is dead.

Thank you everyone for your contributions 😄
