### ISSUE TITLE
Support building GUI with lablgtk3 instead of lablgtk (which is gtk2), perhaps only lablgtk3

### ISSUE THREAD

**Issue by glondu** [bcpierce00/unison#358]
GTK 2 is [deprecated](https://bugs.debian.org/967788). Please port to lablgtk3.

**Comment by piegamesde** [comment]
Gtk 2 is end of life for over a year now (https://blog.gtk.org/2020/12/16/gtk-4-0/), and distributions are starting to remove applications that haven't migrated.

In the meantime, is there a possibility to build unison without the GUI (i.e. only a command line interface)?

**Comment by gdt** [comment]
See #566 and help would be appreciated. 

Please see the docs for how to build unison, and I build it all the time with no gui.  Followup to questions belongs on the unison-users mailinglist.

**Comment by gdt** [comment]
Targeted for 2.53.0
