### ISSUE TITLE
Can't compile on ubuntu 20.04

### ISSUE THREAD

**Issue by lesshaste** [bcpierce00/unison#363]
I am trying to make a static compile of 2.48.15v4 on Ubuntu 20.04 as I can't find any statically compiled binaries online. 

However make fails with:
```

ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -c /home/user/Downloads/unison-2.48.15v4/src/system.ml
File "/home/user/Downloads/unison-2.48.15v4/src/system.ml", line 1:
Error: The implementation /home/user/Downloads/unison-2.48.15v4/src/system.ml
       does not match the interface system.cmi:
       Values do not match:
         val link : ?follow:bool -> string -> string -> unit
       is not included in
         val link : fspath -> fspath -> unit
       File "/home/user/Downloads/unison-2.48.15v4/src/system/system_intf.ml", line 70, characters 0-35:
         Expected declaration
       File "/home/user/Downloads/unison-2.48.15v4/src/system/system_generic.ml", line 50, characters 4-8:
         Actual declaration
make[1]: *** [Makefile.OCaml:435: system.cmx] Error 2
```

OCaml version 4.08.1

How can I get around this?

**Comment by diemort** [comment]
Thanks, I give it a try. In the meantime I cloned the github repo and compiled what is named 2.51.3 with OCaml 4.08.1. It works, although the install step is trying to copy the executables to /root/bin instead of /usr/bin. Is there any incompatibility in syncing between 2.51.2 and 2.51.3 having the same OCaml version?

**Comment by glondu** [comment]
> Is there any incompatibility in syncing between 2.51.2 and 2.51.3 having the same OCaml version?

Yes. It has just been reported yesterday on the unison-users mailing list.

**Comment by gdt** [comment]
Please use the mailinglist for support requests.

2.48 is no longer maintained, so bug reports that it doesn't build with new ocmal are out of scope.
