### ISSUE TITLE
Suggestion: Provide Unison as monolithic AppImage for Linux

### ISSUE THREAD

**Issue by stsichler** [bcpierce00/unison#370]
Since I have several different Ubuntu versions at home now (16.04 / 18.04 / 20.04), it is now impossible for me to keep my files in sync with Unison because of different OCaml versions.
Is it possible that bundling Unison together with its dependent OCaml libraries in a monolithic [AppImage](https://appimage.org/) would be a desirable solution?

**Comment by glondu** [comment]
What I do in your situation is copy the oldest unison binary everywhere and use it via the `servercmd` preference.

Creating an AppImage would be basically equivalent, but one still would have to choose the oldest supported distro.

**Comment by stsichler** [comment]
Hm. Copying the oldest binary to the newer system is what I tried in the first place, but that didn't help. Still I had a communication error caused by different OCaml versions.
Are there any OCaml Libraries loaded from the system? Setting `LD_DEBUG=all` when starting Unison did not show any.

Regarding the AppImage: This seems not to be true in general: I recently built an AppImage (my first one...) of a Qt5 App on Ubuntu 20.04 and it ran flawlessly on 18.04.

**Comment by glondu** [comment]
> Still I had a communication error caused by different OCaml versions.

This can't be. Are you sure you're specifying the right binary with the `servercmd` preference, so that the same binary runs on both sides?

> Are there any OCaml Libraries loaded from the system?

All OCaml libraries are linked statically. The only runtime dependencies are system libraries (libc, gtk...).

> Regarding the AppImage: This seems not to be true in general: I recently built an AppImage (my first one...) of a Qt5 App on Ubuntu 20.04 and it ran flawlessly on 18.04.

It is the converse: an AppImage built on a newer system _may_ work on an older system (this is what you're observing), but this is not true in general. You have to build your AppImage on the oldest (especially w.r.t the kernel) supported system.

**Comment by stsichler** [comment]
I'm sure that I'm calling the correct binary, because Unsion is not installed on the 20.04 system. The only binary that is available is the one copied from the 18.04 system.
When I try to run a synchronization, I get:
```
Unison failed: Uncaught exception Failure("input_value: ill-formed message")
Raised at file "/build/unison-Y9EcQW/unison-2.48.4/lwt/lwt.ml", line 135, characters 6-13
Called from file "list.ml", line 85, characters 12-15
Called from file "/build/unison-Y9EcQW/unison-2.48.4/lwt/lwt.ml", line 31, characters 2-37
Called from file "/build/unison-Y9EcQW/unison-2.48.4/lwt/lwt.ml" (inlined), line 83, characters 17-46
Called from file "/build/unison-Y9EcQW/unison-2.48.4/lwt/generic/lwt_unix_impl.ml", line 55, characters 6-23
Called from file "/build/unison-Y9EcQW/unison-2.48.4/lwt/generic/lwt_unix_impl.ml", line 147, characters 6-40
Called from file "/build/unison-Y9EcQW/unison-2.48.4/main.ml", line 202, characters 6-24
Called from file "/build/unison-Y9EcQW/unison-2.48.4/main.ml", line 131, characters 4-9
```
Btw. the 20.04 is an upgrade installation from 18.04. Before that upgrade, the Unison synchronization worked properly between these systems.

Any ideas?

**Comment by glondu** [comment]
> Any ideas?

Were the files synchronized with the same version of Unison in the past?

If not, it is possible that the archive is incompatible. Try removing the corresponding archive (i.e. the file in ~/.unison starting with "ar" and whose second line describes your situation) on both sides.

**Comment by stsichler** [comment]
> If not, it is possible that the archive is incompatible. Try removing the corresponding archive (i.e. the file in ~/.unison starting with "ar" and whose second line describes your situation) on both sides.

Ah, yes. There was one unsuccessful synchronization attempt with the Unison that came with 20.04, before I manually downgraded to the binary from 18.04.
Deleting the corresponding "fp...." file did the trick. So for now, my acute problem is solved and I can finally synchronize again!
THANK YOU!

Nevertheless, I believe that packaging Unison as AppImage could generally improve usability.

**Comment by gdt** [comment]
unison provides source releases.  packaging in packaging systems is up to each packaging system.  Please file requests for unison in packaging system $foo with $foo.
