### ISSUE TITLE
2.51.2 and git master do not interoperate

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#374]
There have been mailinglist reports that 2.51.2, the latest release, and 2.51.3, meaning the latest version in git, do not interoperate.  This is very serious and should be fixed before a new release can happen.  (Normally, protocol compatibility breaks only when jumping branches, and sometimes when using different ocaml versions.)

**Comment by glondu** [comment]
I've fixed the suspected source of incompatibility in https://github.com/glondu/unison/tree/prepare-release-2.51.3 (more precisely in https://github.com/glondu/unison/commit/b011cf78582f1931dc7897b3115ce305b048beaa).

**Comment by gdt** [comment]
Great!  Reports from testing git master against 2.51.2, from anyone that is able, are most welcome.

**Comment by glondu** [comment]
> Reports from testing git master against 2.51.2, from anyone that is able, are most welcome.

Note that the fix is not in master yet... It is in the pull request #376, and comments should be given there.

**Comment by gdt** [comment]
Thanks for the fix.

I built a pkgsrc package from the rc, and it interoperates.  There have been no reports to the contrary.
