### ISSUE TITLE
OCaml Version Requirement is not documented in src/NEWS

### ISSUE THREAD

**Issue by hmeine** [bcpierce00/unison#381]
As mentioned in #245, the version requirement with respect to ocaml changed in 4a74472df70ebfe7e1b62c41e0171f3f532ec302 due to the StdLib.  Of course, that's not a problem per se, but `doc/changes.tex` and `src/NEWS` still refer to OCaml 4.06.

I tested with 4.05 (even older than 4.06), which would compile 2.51.2 fine, but no version after the above change.

Furthermore, I wonder if the next release should bump the minor version or if it is ok to change requirements within a patch level release (from the viewpoint of semantic versioning).

**Comment by gdt** [comment]
Sorry to be dense, but can you explain what you believe to be the oldest ocaml version that works with the current tree?

I am not particularly concerned with minor version numbers vs ocaml requirement changes.   unison has lots of things that need to be in versions and it's just too messy.  The ocaml world itself is not stable and this need to adapt to language changes drives the code changes and loss of abilty to work with old versions.   So really this is a consequence of a bug in ocaml culture.

**Comment by hmeine** [comment]
@glondu wrote:
> Yes, the use of Stdlib indeed raises the minimum needed OCaml version to 4.07.0. In your case, I would suggest you to install a more recent version of ocaml (using e.g. opam) before building unison.

I have not tried with 4.07.0 (and I do not have the resources to do so), but that statement is enough for me to "believe" that this is the new minimum requirement.

**Comment by ich777** [comment]
Can someone tell me which version of OCaml I have to use to compile it on Debian?
I tried 4.05, 4.07 and 4.08 and none is working it.

I always get that error (or at least that it is for a newer version):

`File "/root/Unison/Unison-v2.51.2/src/system/system_generic.ml", line 1:
Error: /usr/lib/ocaml/string.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.`

**Comment by glondu** [comment]
> Can someone tell me which version of OCaml I have to use to compile it on Debian?
> I tried 4.05, 4.07 and 4.08 and none is working.

Being on Debian should not matter. Debian stable has OCaml 4.05.0, so you have to compile your own version of OCaml. The easiest way is to install opam, and to create a switch with e. g. 4.11.1 (or the same version that was used on your remote end).

> I always get that error (or at least that it is for a newer version):
> 
> `File "/root/Unison/Unison-v2.51.2/src/system/system_generic.ml", line 1: Error: /usr/lib/ocaml/string.cmi is not a compiled interface for this version of OCaml. It seems to be for an older version of OCaml.`

Your installation is somehow broken. But this is not the right place to discuss this. Please seek support on the unison-users mailing-list.

**Comment by ich777** [comment]
> Being on Debian should not matter. Debian stable has OCaml 4.05.0, so you have to compile your own version of OCaml. The easiest way is to install opam, and to create a switch with e. g. 4.11.1 (or the same version that was used on your remote end).

I compile OCaml 4.05.0 again and try it again.


> Your installation is somehow broken. But this is not the right place to discuss this. Please seek support on the unison-users mailing-list.

You mean the OCaml installation or am I wrong?
I will try it again and report back.
Thanks for the quick response.

**Comment by ich777** [comment]
> Being on Debian should not matter. Debian stable has OCaml 4.05.0, so you have to compile your own version of OCaml. The easiest way is to install opam, and to create a switch with e. g. 4.11.1 (or the same version that was used on your remote end).

My issue was that I've pulled the tarball from the relase 2.51.2 and doesn't clone the repository.
After that I compiled and installed OCaml 4.11.1 and then compilation of Unison works just fine.

However when i switch from 2.51.3 to 2.51.2 and try to compile it I get this error:

`File "/root/Unison/unison/src/system.ml", line 1:
Error: The implementation /root/Unison/unison/src/system.ml
       does not match the interface system.cmi:
       Values do not match:
         val link : ?follow:bool -> string -> string -> unit
       is not included in
         val link : fspath -> fspath -> unit
       File "/root/Unison/unison/src/system/system_intf.ml", line 70, characters 0-35:
         Expected declaration
       File "/root/Unison/unison/src/system/system_generic.ml", line 50, characters 4-8:
         Actual declaration`

Is there another dependencie for version 2.51.2 that I've missed or do i need to install another version of OCaml?

**Comment by gdt** [comment]
I am using ocaml 4.09.1 and that worked with the release and the recent RC.

**Comment by glondu** [comment]
> However when i switch from 2.51.3 or better speaking the master branch to 2.51.2 and try to compile it I get this error:
> 
> `File "/root/Unison/unison/src/system.ml", line 1: Error: The implementation /root/Unison/unison/src/system.ml does not match the interface system.cmi: Values do not match: val link : ?follow:bool -> string -> string -> unit is not included in val link : fspath -> fspath -> unit File "/root/Unison/unison/src/system/system_intf.ml", line 70, characters 0-35: Expected declaration File "/root/Unison/unison/src/system/system_generic.ml", line 50, characters 4-8: Actual declaration`
> 
> Is there another dependencie for version 2.51.2 that I've missed or do i need to install another version of OCaml?

It is known that version 2.51.2 has a maximum OCaml version requirement (I don't remember which one, but it is <= 4.08.1), and that it certainly does not compile with 4.11.1.

**Comment by gdt** [comment]
I was confused; pkgsrc patches 2.51.2 to build with recent ocaml.

**Comment by tleedjarv** [comment]
@hmeine could you test PR #385 in your environment?

**Comment by glondu** [comment]
There are reports of PR #385 working with OCaml 4.05.0. I've merged it. Can this issue be closed now?

**Comment by hmeine** [comment]
I think so, yes.

**Comment by gdt** [comment]
Well, the question remains if things are adequately documented.   arguably NEWS isn't right if there isn't a min version change.  We have another issue open for build instructions not being in the sources.

**Comment by hmeine** [comment]
I only found `doc/changes.tex` and `src/NEWS` referencing the OCaml version. Build instructions would be an obvious location.

**Comment by gdt** [comment]
> I only found `doc/changes.tex` and `src/NEWS` referencing the OCaml version. Build instructions would be an obvious location.

Yes, and that's implicitly in #382, still open.
