### ISSUE TITLE
Update scanning does not seem to obey ignore lines?

### ISSUE THREAD

**Issue by Jimi-James** [bcpierce00/unison#384]
Arch Linux / Armbian, unison 2.51.2 (ocaml 4.09.1)

I have a homemade NFS that I'm using as both backup and cloud storage. I back up my entire home directory, and have certain things that live only locally or only on the cloud.

For example, I have ~/folder-A containing many files inside the home folder backup on the NFS, but on my local system, ~/folder-A is just an empty folder that I mount the remote folder to using sshfs.

To avoid any mishaps with massive deletions or file transfers, my sync profile has `ignore=Path folder-A`. When syncing, unison does successfully follow that ignore line when it comes to propagating changes. However, during update detection, every single file and folder within ~/folder-A seems to be getting scanned. This is not ideal, as scanning over sshfs is of course very slow, and more importantly I do not want or need those files to be scanned on the local machine anyway. The only way to avoid it is to unmount the sshfs mount on ~/folder-A before running unison.

Is this intended? Is there a way to avoid it? (I would need any solutions to also respect ignorenot lines, as I have some important instances in which an `ignore=Path example-folder/*?` is overriden by one or more counts of `ignorenot=Path example-folder/something-I-don't-want-ignored`)

**Comment by gdt** [comment]
Please use the mailing list for questions.   If you want to file a bug asserting there is a defect relative to what the docs say, or what the docs ought to have said if they thought about it, that's fine.

I think you are saying that while the sync semantics are correct, there is a missing and important optimization, and further that really it's a bug that the optimization is missing.  Is that what you mean?

**Comment by Jimi-James** [comment]
Yeah, that matches up with what I'm saying.

**Comment by Jimi-James** [comment]
Although, before I commit to my statement that the optimization is missing, actually it's looking like unison has suddenly stopped respecting just this one single ignore line for this one single folder, despite respecting all the other ignore lines in that file. It actually is trying to delete the items on the NFS (that is, inside ~/folder-A/) that do not exist on the local machine.

I'll need some time to finish the rest of this sync to confirm so I can more easily watch this and pay attention to its behavior. Right now I'm baffled. because I can't spot a single typo, and this line was respected until a day or two ago, and I haven't modified that file since.

Either way this might turn out to be either my error or a completely different bug.

**Comment by gdt** [comment]
OK.  Please start fresh when you are clear on things.  (Don't mean to be nasty, just pushing work onto you to keep things clean for people who look at the tracker.)
