### ISSUE TITLE
UI preference is a compile time setting

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#394]
One can build with UISTYLE=text, or UISTYLE=gtk2.  This sets the default way the unison binary behaves, and results in unwanted behavior from scripts wanting to use the text ui (as -auto) if the system-wide build of unison is built for GUI.

Building GUI or not should be separate from how the default invocation works.   Arguably there should be a separate executable "xunison" or some other name that runs GUI mode for those that want it, or some other way to have the unison command run the comand-line UI regardless of build setting.

(This bug probably doesn't make sense to those who build unison only for themselves, vs build it in a packaging system where it will be installed for multiple users of a timesharing system.)

**Comment by rivy** [comment]
I'm not sure this is really a problem as most installations install the text-only UI as `unison` and the GUI UI under a different name such as `unison-gui` or `unison-gtk`. Additionally, the text UI is always available from either type of build by using the `-ui text` command line option. That is, using `unison -ui text ...` will always use the text UI no matter what GUI type is installed.

**Comment by glondu** [comment]
> I'm not sure this is really a problem as most installations install the text-only UI as `unison` and the GUI UI under a different name such as `unison-gui` or `unison-gtk`.

Indeed, this is what is done in Debian, for example.

**Comment by gdt** [comment]
If most distributions build the text only as unison and the GUI under a different name, then it seems like this notion should be hoisted into unison proper, both to make things easier, and to have uniformity of command names for users.   Right now the build system does one thing and some packaging systems are doing something else.

**Comment by gdt** [comment]
And also the comment by @rivy indicates that Linux packagers think that typing unison (vs unison-gtk) should result in a text ui without having to ask for it.  That's really what I was getting at.

**Comment by rivy** [comment]
The just merged GHA build/packaging system is building the text-only UI to `unison` and the text/graphic UI (when buildable) to `unison-gtk2`. Both are packaged into the "bin" directory with `unison-fsmonitor` (again, when buildable). If desired, a less specific name such as `unison-gui` could be used as an alternative.

**Comment by gdt** [comment]
Thanks - I will have a look.  I would like to see whatever controls are used to do that merged to the main build and be default, rather than having special stuff in the GHA builds.   At least what you describe seems not to happen if you just run make.

**Comment by gdt** [comment]
This appears related to the need for https://github.com/bcpierce00/unison/pull/427

**Comment by gdt** [comment]
Thanks for the comments; they were useful to understand but I'm calling this a dup of #667.
