### ISSUE TITLE
GHA-built binaries have unclear names and portability status

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#397]
There are now binaries at https://github.com/bcpierce00/unison/releases which is great.

However, some are labeled "linux", which is very underspecified.  It's not clear to me where these can be run.   Are they for i386 or amd64?  Surely GNU/LInux runs on a number of other CPU types.  I'm not really suggesting the project build even more, but just that clearer labeling would be nice.  It's also not clear if these run on Debian or other non-Ubuntu Debian derivatives, and on FC-world distributions.

For mac, presumably these are amd64-mode, but then there's the question of which version of macOS.  It seems obvious that going  to older versions would be good, to enable those with old but perfectly good hardware, who have been left in the lurch by Apple's forced-obsolescense policies, to use the binaries.   Specifically, there is a lot of entirely-ok hardware stuck on 10.13.  As I understand macOS, a 10.13 binary will run just fine on later versions.

Similar questions arise for windows.  What versions of windows?  back to 7?  only 10?  It might be good to use explicit mingw64 even if that's the default to get the labels to say that.

(This issue is really about lack of clarity, but if fixing that addresses any of the other issues, i think that's fine.)

**Comment by rivy** [comment]
All builds are 64-bit unless otherwise indicated (ie, "unison-v2.51.3_rc2+ocaml-4.10.1+mingw32.windows.zip" is 32-bit). 32-bit builds could likely be done using the `ocaml-...+32bit` compiler variant, but I have no idea of how to build the GTK2 GUI for it.

All of the windows builds are either static builds or include any needed DLLs, so they should run on any 64-bit Windows machine back to at least Win7 (and likely WinXPsp3, but that's hard to test). "unison-v2.51.3_rc2+ocaml-4.10.1+mingw32.windows.zip" should run on either 32-bit or 64-bit hosts variants of the same hosts.

The usual "linux" builds are all built on Ubuntu, 64-bit, and require host library support (`ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=9198aa216dad90e6d3a2e4cabb1f7d4c13e587b1, stripped`). They should run on any AMD64 POSIX glib host with the prereqs installed (for the GUI).

The "unison-v...+ocaml-...+musl+static+flambda" build is fully static (`ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped`) and should run on all Debian/Ubuntu-esque machines and, likely, most AMD64 POSIX-compatible hosts (although I've only shown it to work on QNAP and Synology NASes). The static build doesn't contain a GUI build (again, not sure how or if it can be built).

The MacOS builds all produce the "standard" 64-bit executable and I have no experience executing them to know which machines they are able to run on... And I don't believe there are any MacOS build images on GHA that can build a 32-bit executable any longer.

I'm happy to modify the CICD workflow to make the artifact names more clear, such as labelling them with the architecture (x32, x64, ...). The naming schema is really fairly easy to change; just give me some idea of how you'd like them to be labelled.

Hope that helps.

**Comment by gdt** [comment]
I'm not sure exactly what to ask for.   I am just trying to put myself in the shoes of someone coming to the release page and wanting to know "will this work on my system".

It seems the norm in the Windows world is for software to run on 7 and up.  If it runs on older, that's special and explained, and if it needs 10, that's deficient and explained.  So the builds you set up working on 7 and up meet the default expectations.

As for macOS, my experience is that when you build for a given version, it can run on that version or later.  And, you build with an SDK, rather than what you'd think of as native, so it is often possible to set the SDK version to something lower than the host machine.  It may be possible to build for 10.13 on the 10.15 host, and if so, I think that would be good.   Some hardware is stuck on 10.11, but that hardware is getting very old (2008-2010 vintage), and typically doesn't have enough memory to be usable today.  I will look at the binaries and the recipe and see if I have any useful thoughts.

I have a bias, perhaps not widely shared, that "32-bit" and "64-bit" are not ok terms, because they presuppose that all the world is x86.  Perhaps that's ok in the context of Windows, but it isn't true in BSD/Linux, and it didn't used to be true in mac and soon won't be true any more.  (I realize that in Windows and Linux culture these terms are normal.)

So I guess my incremental suggestions are:
 * name the mac builds to include x86_64 macOS10.15 (numbers, not the  apple names that don't sort :-)
 * adjust the windows builds to say mingw64 even though that's the default, so people can understand them better while knowing less about GHA defaults.  Or call them i386 and x86_64 and leave mingw out as an implementation detail.
  * add x86_64 to the names of the Linux builds

  * create a wiki page (I am pretty sure you can just do that) that has the information about what builds are what beyond what is obvious from the names.   That may end up being mostly about Linux.

**Comment by rivy** [comment]
> It seems the norm in the Windows world is for software to run on 7 and up. If it runs on older, that's special and explained, and if it needs 10, that's deficient and explained. So the builds you set up working on 7 and up meet the default expectations.

👍 

> As for macOS, my experience is that when you build for a given version, it can run on that version or later. And, you build with an SDK, rather than what you'd think of as native, so it is often possible to set the SDK version to something lower than the host machine. It may be possible to build for 10.13 on the 10.15 host, and if so, I think that would be good. Some hardware is stuck on 10.11, but that hardware is getting very old (2008-2010 vintage), and typically doesn't have enough memory to be usable today. I will look at the binaries and the recipe and see if I have any useful thoughts.

👍 

> I have a bias, perhaps not widely shared, that "32-bit" and "64-bit" are not ok terms, because they presuppose that all the world is x86. Perhaps that's ok in the context of Windows, but it isn't true in BSD/Linux, and it didn't used to be true in mac and soon won't be true any more. (I realize that in Windows and Linux culture these terms are normal.)

> So I guess my incremental suggestions are:
> 
> * name the mac builds to include x86_64 macOS10.15 (numbers, not the  apple names that don't sort :-)

I'll update the naming for macOS to include the mac platform version.

> * adjust the windows builds to say mingw64 even though that's the default, so people can understand them better while knowing less about GHA defaults.  Or call them i386 and x86_64 and leave mingw out as an implementation detail.
> * add x86_64 to the names of the Linux builds
> * create a wiki page (I am pretty sure you can just do that) that has the information about what builds are what beyond what is obvious from the names.   That may end up being mostly about Linux.

How about "x86" and "x86_64" for (32-bit vs 64-bit) designations for all platforms? Notably, currently, only Windows is building a 32-bit version. I do think that unless MSVC versions are being built (which isn't possible currently that I know of...) that the "MinGW" designation in the name is superfluous. I'll just use the "x86" / "x86_64" designation if that's acceptable.

I start work on a PR for this...

**Comment by gdt** [comment]
The token "x86" usually refers to the Intel family including what GNU autoconf calls i386 and x86_64.   Sometimes people use IA32 to refer to the i386-compatible family.    But that actually raises a good question about the compiler flags for -mcpu etc.   Some systems assume fairly modern processors, and some compile for 486+.   So I'd see what the -m flags are for the i386/i686 build and use that name.   I hope it isn't using -mnative.

**Comment by rivy** [comment]
I don't see any architecture specification flags in the build logs. Here is the relevant link step output:

```
ocamlopt -verbose -g -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -o unison   unix.cmxa str.cmxa bigarray.cmxa ubase/rx.cmx unicode_tables.cmx unicode.cmx bytearray.cmx system/system_generic.cmx system/generic/system_impl.cmx system.cmx ubase/projectInfo.cmx ubase/myMap.cmx ubase/safelist.cmx ubase/util.cmx ubase/uarg.cmx ubase/prefs.cmx ubase/trace.cmx ubase/proplist.cmx lwt/pqueue.cmx lwt/lwt.cmx lwt/lwt_util.cmx lwt/generic/lwt_unix_impl.cmx lwt/lwt_unix.cmx uutil.cmx case.cmx pred.cmx fileutil.cmx name.cmx path.cmx fspath.cmx fs.cmx fingerprint.cmx abort.cmx osx.cmx external.cmx fswatch.cmx props.cmx fileinfo.cmx os.cmx lock.cmx clroot.cmx common.cmx tree.cmx checksum.cmx terminal.cmx transfer.cmx xferhint.cmx remote.cmx globals.cmx fswatchold.cmx fpcache.cmx update.cmx copy.cmx stasher.cmx files.cmx sortri.cmx recon.cmx transport.cmx strings.cmx uicommon.cmx uitext.cmx test.cmx main.cmx linktext.cmx osxsupport.o pty.o bytearray_stubs.o -cclib -lutil
+ as  -o '/tmp/camlstartup4853ec.o' '/tmp/camlstartup0e6ecf.s'
+ gcc -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -Wl,-E -o 'unison'  '-Llwt' '-Lubase' '-Lsystem' '-Lfsmonitor' '-Lfsmonitor/linux' '-Lfsmonitor/windows' '-Lsystem/generic' '-Llwt/generic' '-L/home/runner/.opam/4.11.1/lib/ocaml'  '/tmp/camlstartup4853ec.o' '/home/runner/.opam/4.11.1/lib/ocaml/std_exit.o' 'linktext.o' 'main.o' 'test.o' 'uitext.o' 'uicommon.o' 'strings.o' 'transport.o' 'recon.o' 'sortri.o' 'files.o' 'stasher.o' 'copy.o' 'update.o' 'fpcache.o' 'fswatchold.o' 'globals.o' 'remote.o' 'xferhint.o' 'transfer.o' 'terminal.o' 'checksum.o' 'tree.o' 'common.o' 'clroot.o' 'lock.o' 'os.o' 'fileinfo.o' 'props.o' 'fswatch.o' 'external.o' 'osx.o' 'abort.o' 'fingerprint.o' 'fs.o' 'fspath.o' 'path.o' 'name.o' 'fileutil.o' 'pred.o' 'case.o' 'uutil.o' 'lwt/lwt_unix.o' 'lwt/generic/lwt_unix_impl.o' 'lwt/lwt_util.o' 'lwt/lwt.o' 'lwt/pqueue.o' 'ubase/proplist.o' 'ubase/trace.o' 'ubase/prefs.o' 'ubase/uarg.o' 'ubase/util.o' 'ubase/safelist.o' 'ubase/myMap.o' 'ubase/projectInfo.o' 'system.o' 'system/generic/system_impl.o' 'system/system_generic.o' 'bytearray.o' 'unicode.o' 'unicode_tables.o' 'ubase/rx.o' '/home/runner/.opam/4.11.1/lib/ocaml/bigarray.a' '/home/runner/.opam/4.11.1/lib/ocaml/str.a' '/home/runner/.opam/4.11.1/lib/ocaml/unix.a' '/home/runner/.opam/4.11.1/lib/ocaml/stdlib.a' '-lcamlstr' '-lunix' 'osxsupport.o' 'pty.o' 'bytearray_stubs.o' '-lutil' '/home/runner/.opam/4.11.1/lib/ocaml/libasmrun.a' -lm -ldl 
```

The individual ocaml compiler steps give no indication of architecture.

The resultant file is seen as "ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, stripped" by `file`. 

The windows files are seen as "PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows" for 32-bit and "PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows" for 64-bit.

I have a preliminary set of packages with updated names building now (see <https://github.com/rivy/unison/releases/tag/v2.51.3_rc2.1>).

**Comment by rivy** [comment]
I like <https://github.com/rivy/unison/releases/tag/v2.51.3_rc2.3> a bit better.

**Comment by gdt** [comment]
In general I like it.

I still don't like x86, because it doesn't imply a particular CPU instruction set architecture.   I had forgotten about 8086, but wikipedia reminded me:  https://en.wikipedia.org/wiki/X86
That's why I suggested i386 as the normal abbreviation for IA-32 which almost no one relates to.  https://en.wikipedia.org/wiki/IA-32

**Comment by gdt** [comment]
> The resultant file is seen as "ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, stripped" by `file`.

Sorry, I steered you wrong.  The i386/i486/i686 notions of which instruction set is used is limited to the IA-32 architecture.  With x86_64, there are still vector extensions on some but not others, but it's not handled the same way.

> The windows files are seen as "PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows" for 32-bit and "PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows" for 64-bit.

So the Windows one would run on a true i386, and not use i486-only instructions, I think.  Not surprising.

**Comment by rivy** [comment]
So, "i386" for the 32-bit windows suffix?

How about a suffix for linux 32-bit (ie, from ocaml 4.10.0+32bit)? (CICD is not building that, but I can include it in for possible future use.)

**Comment by gdt** [comment]
Yes, I think i386 is good for Windows Intel-architecture 32-bit.

Linux runs on a number of CPUs with 32-bit word length.   This definitely includes i386 and armv6/armv7 (RPI).  It used to and probably still includes some of sparc, ppc, m68k, mips.   So saying "Linux 32-bit" doesn't actually describe the CPU type.  Here too I think "i386" is good, unless the binaries are built for a higher CPU type (i686) as shown by file, in which case use that (because if built for "i686" those binaries will not run on a true i386).

I'm sure you have noticed that I'm particularly cranky about this.   Before using an i386 computer, I used vax, m68k, mips at least, and have since used 32-bit CPU types ppc, arm, and sparc, something from CDC, some IBM types, and probably more that I've forgotten.   So I have always objected to "32-bit" when people specifically mean IA-32.  I realize it's common in the Windows and Linux world, but I think that's an error in usage.   In NetBSD, we have much more of a culture of many CPU types.

Insert tilted windmill smiley here -- I don't try to fix people in their own forums but am sort of taking the "not on my watch" view about this usage issue.

Probably the biggest thing would be to get a build of a different operating system, such as one of the BSDs or illumos.  I'm guessing that's not supported by GHA.

**Comment by rivy** [comment]
Alright, I'll use "i386" for the 32-bit builds. I'm a platform polyglot myself, and I'm sympathetic to the cause of increasing clarity and avoiding sloppy terminology. If it happens that a build requires a different 32-bit architecture notation, it's really very easy to change.

As for builds on GHA, MacOS (currently 10.15 [looks like 11.0 was just released for use]), ubuntu (16.04, 18.04, and 20.04), and windows (Windows Server 2019) are the only platforms available for builds (see [Supported runners ...](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources). Private/self-hosted runners are possible, but I haven't seen any in use and don't have *any* experience with them. Such a thing would probably require significantly more developer resources to support. The current setup is more "fire-and-forget" with GitHub shouldering most of the heavy "keeping it running" burden and costs. 

Cross-platform compilation is possible (and done routinely for compilers/languages which easily support it [eg, `rust`, `go`, ...]). If it can be cross-compiled on ubuntu, it should be do-able, but I don't know the hows of OCaml for that type of compilation.

**Comment by gdt** [comment]
Thanks for explaining.  It's too bad github is so narrow, but I completely get it that going beyond what they offer is a new level of hard.   Sounds like we will soon be in a good place (assuming you make a PR, which I will be happy to hit merge on as soon as 2.51.3 is actually released -- I am trying really hard not to change  much until then unless not changing  them causes real problems.

**Comment by rivy** [comment]
Here's a [release with the most updated names](https://github.com/rivy/unison/releases/tag/v2.51.3_rc2.5).

It's currently on top of the PR #398, renaming the workflow to CICD. Given the ease of release builds (just push the tag), you can easily update it after version 2.51.3, although if you're going for minimal confusion, you might want to merge it first. It's only changing the CICD workflow, so there should be no impact on the actual `unison` final product. If you think that's a good idea, I'll push it formally to PR #398 so that you can merge it. Then a simple `git tag v2.51.3 && git push v2.51.3` should trigger the release with all the well-named builds.

**Comment by gdt** [comment]
I am happy with the new names; thanks for doing this and being cooperative  about all my complaints.

I've merged the other PR, and the other low-impact/typo/NEWS stuff.  So please put the commit in a new PR, and I'll give it a quick look and merge it.

**Comment by rivy** [comment]
Done; see PR #403.

**Comment by gdt** [comment]
Thanks for doing the work to fix this!
