### ISSUE TITLE
Feature Request: Host binaries on github

### ISSUE THREAD

**Issue by hrj** [bcpierce00/unison#40]
As a first-time user of unison, it was a little difficult to find the latest Windows binaries. (For my debian systems it was easy to get from the distribution). The binaries are strewn across various websites. There is also the issue of trusting a third-party. I had to check the website details and eventually came to realize that they are contributors to this project.

It would be easier if the binaries were hosted here on github itself. FYI, the [releases page](https://github.com/bcpierce00/unison/releases) allows you to attach files to every release, along with change descriptions.

As the files can only be attached by contributors they are easy to trust, and as they reside near the code they are easy to find.

**Comment by brabalan** [comment]
As maintainer of the unison-binaries site, I really like this idea. However many binaries are compiled by non-contributors, so we either need to vet them or make them contributors.

Is it possible to attach new files to old releases? Looking quickly at the releases page does not answer this question.

**Comment by hrj** [comment]
> Is it possible to attach new files to old releases? Looking quickly at the releases page does not answer this question.

Yes you can add or remove file attachments to any release, new or old. If I catch your drift, this will allow you to attach contributed binaries as and when they arrive.

**Comment by brabalan** [comment]
This is good news. @bcpierce00 what do you think? I could add the binaries from unison-binaries and from Jérôme’s page on the github release page.

**Comment by alkuzad** [comment]
@hrj yep it's definetelly brilliant idea, it's actually easy to get 2.40 version from repositories but 2.48.3 is very hard to get if you don't know how to find it :)

**Comment by bcpierce00** [comment]
Sounds like a great plan!

**Comment by brabalan** [comment]
OK. I’m going to need some help. I want to add this file http://unison-binaries.inria.fr/files/Unison-OS-X-2.48.15.zip which corresponds to this commit e4536168396bb15529acf26bcb5129c8048cf9c0. I don’t know how to do that in the releases page. @hrj can you tell me where I need to click?

Also, for older release, do we want to figure out the exact commit that corresponds to the file, or should I associate them to big versions (such as 2.17)?

**Comment by hrj** [comment]
@brabalan You will first need to add a git tag to that commit. Then push the tags to the repo. Something along the lines of:

```
cd unison
git tag -a 2.48.15 e453616
git push --tags origin master
```

The tag should then appear on the github releases page. Click the tag, then press Edit. You should then be able to add a description and upload files.

**Comment by brabalan** [comment]
Thanks, I see how it goes now.

Should I attach several files per platform for one release, or do one release per platform?

**Comment by hrj** [comment]
> Should I attach several files per platform for one release, or do one release per platform?

I think multiple binaries per release is preferred when the binaries are based on the same code. As a user, it's easier to see the change log and associated binaries in a single place. And it will be easier for the maintainers to edit as well.

**Comment by brabalan** [comment]
I’ve started doing this for recent versions. How far back should I go?

**Comment by bcpierce00** [comment]
My guess is 2.40 is enough.

**Comment by hrj** [comment]
Thanks for the quick responses.

For windows build, the devs can probably use https://www.reactos.org/ for building and testing.

**Comment by brabalan** [comment]
I had not closed this as there are a few binaries I still want to add. But as it's in my todo list, I can still do it once I have the time.
