### ISSUE TITLE
Is the unison-gui-2.48.3 compatible with 2.51.3-static CLI?

### ISSUE THREAD

**Issue by stdedos** [bcpierce00/unison#406]

**Comment by gdt** [comment]
This is not a bug report.   But see #407; we had not previously had the cross-version lack of compat in the issue tracker.

**Comment by stdedos** [comment]
Technically it's not, but it is an easy way to get in touch with "this repository" :-D.
(and there are other repos that use issues like that; or nowadays discussions seem to come up).

For the user base of this repository it is not an issue (maybe), but I am stuck in Ubuntu 16.04 (and no wish to roll out compiling from sources), which makes updating "wanted, but troubling".

Thank you for your response in any case!
