### ISSUE TITLE
Question: How do you install 2.51.3 release files on a Mac?

### ISSUE THREAD

**Issue by melyux** [bcpierce00/unison#409]
The 2.51.2 release included the actual .app file that made it trivial to install, but how does one go about installing the 2.51.3 files? I download e.g. `unison-v2.51.3+ocaml-4.11.1+x86_64.macos-10.15.tar.gz` and I see the `unison` and `unison-gtk2` files inside, but I don't know what to do with those.

**Comment by gdt** [comment]
The issue tracker is for bugs and features.  Please use the mailinglist for questions.

**Comment by rivy** [comment]
@gdt, if it helps, I'm happy to add logic to the CICD including the ".app" file if that eases MacOS installations. Not using MacOS, I'm somewhat clueless about the file and it's use, and I've not been asked this for other `rust`-generated executables. But, including it is possible; I just need to know how/where it's generated and how/where it should be included in in the package.
