### ISSUE TITLE
manual build fails (html/havea)

### ISSUE THREAD

**Issue by vaukai** [bcpierce00/unison#411]
What I did:
git clone https://github.com/bcpierce00/unison foobar && cd $_ && make all docs > /tmp/unison_log 2>&1

Something wrong with "make all docs" or "make all && make docs"?

What I've got: https://gist.github.com/1440e1abebeeaa50405c19498eb8d7c0

**Comment by gdt** [comment]
Seems like a bug.  Are you building from git master (if not, please do).   Also please specify OS, version, havea version.

**Comment by vaukai** [comment]
> Seems like a bug. Are you building from git master (if not, please do). Also please specify OS, version, havea version.

git clone https://github.com/bcpierce00/unison foobar && cd $_ && git status
Cloning into 'foobar'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 9186 (delta 14), reused 21 (delta 7), pack-reused 9137
Receiving objects: 100% (9186/9186), 14.30 MiB | 1.86 MiB/s, done.
Resolving deltas: 100% (6985/6985), done.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by tleedjarv** [comment]
The problem is introduced by https://github.com/bcpierce00/unison/commit/a521dc7f3799e81c29d824aec476c5fde2ae36d1
Interestingly, the commit itself claims to be a fix.

**Comment by gdt** [comment]
Could you retest with 2.51.4rc3 and either close if ok or update?  Seems to build for me.

**Comment by gdt** [comment]
Worked again for me.  Feel free to reopen with a repro recipe from a clean checkout.  I have found that building docs without a clean sometimes have issues.
