### ISSUE TITLE
Building in doc with HEVEA=false still calls hevea

### ISSUE THREAD

**Issue by vaukai** [bcpierce00/unison#416]
When compiling with "HEVEA=false" the second  "hevea unison-manual.tex" in [doc/Makefile](https://github.com/bcpierce00/unison/blob/master/doc/Makefile#L53-L55) still calls hevea.

What is the purpose of the "ifdef HEVEA ..."?

**Comment by gdt** [comment]
I realize we had not documented this clearly, but the plan is for the issue tracker to be for bugs and feature requests, and specifically not for questions.   Your contributions to figuring things out are very welcome and I would like to invite you to join the unison-hackers mailinglist.

These wiki pages didn't exist when you filed the issue, but now describe the lists and what goes where.
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests

**Comment by gdt** [comment]
In this case, your question is really a bug report and I have retitled it.
