### ISSUE TITLE
Syncing between Mac and Linux sometimes fails with marshaling problem [same unison/ocaml versions]

### ISSUE THREAD

**Issue by josh-berry** [bcpierce00/unison#424]
If I run Unison with a profile that has no changes, everything works fine—I get: `Nothing to do: replicas have not changed since last sync.`

However, if I run it with a profile that DOES have changes, it runs through the reconciliation process, and then either partway through or at the end (I'm not sure which), it fails like so:

```
Unison 2.51.3 (ocaml 4.10.0): Contacting server...
Connected [{REDACTED} -> {REDACTED}]
Looking for changes
  Waiting for changes from server
Reconciling changes
Fatal error: Server: Fatal error during unmarshaling (input_value: ill-formed message),
possibly because client and server have been compiled with differentversions of the OCaml compiler.
```

* On my Linux system, I have: `unison version 2.51.3 (ocaml 4.10.0)`
* On my Mac system, I have: `unison version 2.51.3 (ocaml 4.10.0)`

Both unisons were built from source (the `v2.51.3` tag on Git) using ocaml built from source. (When I originally hit this problem, the Mac had unison/ocaml installed through Homebrew, but then I built everything from source just to check/eliminate the possibility of a Homebrew issue.)

Reverting to commit acfa10529e1ef073e6f951666159d89e1bda282c (which is the first commit after v2.51.2 that builds on Mac) shows the same symptoms. So it seems the issue was introduced somewhere in `v2.51.2..acfa1052`.

I skimmed through the commits in this range, and this is the only one that stood out to me:

```
commit b203a37508fb0673214b943d2d8af02185ad6935
Author: G.raud <graud@gmx.com>
Date:   Wed Feb 7 18:55:40 2018 +0100

    Main: catch and transform exception IllegalValue from the server into Fatal

    This catches a discrepancy between server and client in the parsing of a
    preference string and prints the error instead of the backtrace.

    Even if such a discrepancy is probably best avoided by incompatible
    version numbers, it could occur between development versions with the
    same version, or because of a mistake or a local backport of new
    features.
```

I'm wondering if there was some inadvertent wire-protocol discrepancy or cross-platform issue that was introduced before this commit, which this commit only now surfaces? I'm not sure where to go from here to continue investigating, but would appreciate it if someone could take a look. Thanks!

**Comment by gdt** [comment]
I have a post-2.51.3 snapshot on NetBSD and 2.51.3rc3 on Mac, built the unix way and used via the command line, and they are working fine.  Both are ocaml 4.09.1. 

 *  I wonder how you are building, if its as if the Mac were a normal unix computer or via some mac.app build.
 * Turning on debugging and looking at the bytes is probably the way forward, albeit hard.
 * I am guessing both machines are x86_64, but if not say what they are.

**Comment by josh-berry** [comment]
Both machines are x86_64. I used the exact same process on both Mac and Linux to build (the standard Unix-style build process, `make UISTYLE=text`), and the same process to build ocaml itself (with `--disable-force-safe-string`).

However, after I posted this, I just realized I made a mistake--I had a servercmd pointing to an explicit version of unison that wasn't what I was expecting, and the ocaml versions were indeed different. I'm going to fix my setup and I'll close this once I can confirm it was indeed my fault. :) Sorry for the noise!

**Comment by josh-berry** [comment]
Yup, my bad--turned out to be different ocaml versions after all. Sorry again for the noise!

**Comment by gdt** [comment]
No problem - not that much noise :-)   And not to be mean, but I'm glad you were wrong.  That's much easier on this end!

**Comment by josh-berry** [comment]
hehe, I'm glad I was wrong too--I depend on Unison for all kinds of things and was worried I would have to come up with a workaround. It's a great piece of software and I would be absolutely lost without it. Thanks again!
