### ISSUE TITLE
Allow fastcheck on excel files (feature request)

### ISSUE THREAD

**Issue by xverges** [bcpierce00/unison#43]
I have to deal with a large amount of excel files that I know that have not been modified. Unfortunately, I have no way to tell unison about the files being safe for fastcheck.

A brave/dirty [hex-edition of the binary has helped this user](http://serverfault.com/questions/461619/is-there-anything-more-than-fastcheck-to-speed-up-unison) but I could not make it work for me, since Windows must keep some checksum that prevented the dirty hack from running.

**Comment by hrj** [comment]
Note that fastcheck doesn't seem to be reliable. (I could open a separate issue for that if required).

I just found that a particular file refused to sync although their MD5 sum was different on the source and destination. After adding `-fastcheck false` the files synced fine.

Version of unison on WIndows: 2.48.4
Version of unison on Linux: 2.48.3

**Comment by xverges** [comment]
@hrj Thanks for the warning. I would definitely open a different issue: this one is about a low priority feature requests, while your report seems to imply an important bug.

**Comment by alkuzad** [comment]
@xverges most propably you should modify this function:
https://github.com/bcpierce00/unison/blob/master/src/fpcache.ml#L203

To not use hardcoded value but use Prefs to get the extensions needed to be blocked (and leave by default current values)

**Comment by bcpierce00** [comment]
Or, if you just want a version of Unison that works for you, just remove the .xls line, compile, and you're set to go!
