### ISSUE TITLE
Please check for virus in i386windows.zip - Sophos finds virus in zip

### ISSUE THREAD

**Issue by bunk3m** [bcpierce00/unison#430]
I downloaded unison-v2.51.3+ocaml-4.10.1-i386.windows.zip from from [https://github.com/bcpierce00/unison/actions/runs/352740603](url) to test on my PC.

During Sophos run it found 'Mal/EncPK-ANR'.  
[https://www.sophos.com/en-us/threat-center/threat-analyses/virus-and-spyware/Mal~EncPk-ANR/detailed-analysis.aspx](url)

Can you please check?

**Comment by gdt** [comment]
First, I can't find that file at that URL.

Virus scanners are known to have many false positives, and frequently incorrectly flag open source code as having malware.  Please follow up with sophos and if they can confirm that there really is a problem, please file an issue.   Not trying to be unkind, but you have not provided evidence of a real problem.

**Comment by bunk3m** [comment]
Hello @gdt .  No problem.  I understand about false positives and appreciate that it might not be an issue.  The screenshot below shows what I saw.  The link to Sophos site explains about what the virus installs and what changes it does to the HK???.  I haven't installed this version to test so don't know if it actually does install something.  My note was more of a warning to have a look.
This is what I got from the scan.
![image](https://user-images.githubusercontent.com/3494567/98854112-2439ed80-2428-11eb-9e5e-ae25c783c6e1.png)

**Comment by gdt** [comment]
I ran clamscan and a proprietary scanner against it (not on windows) and no hits.

I think it's entirely reasonable for someone to check this.  My point is that this is an open source project and a proprietary tool is making an accusation, so the onus is on the proprietary tool to provide real evidence, not on the open source project to prove that the proprietary tool is buggy.

If I thought that the a priori probability of a real infection in a GHA-generated tarball from unison sources was even 10% of the a priori probability of a false alarm from a commercial virus scanner, I wouldn't just tell you to ask sophos for their proof.   But this happens all the time.

If anybody else gets this with a different scanner, that would be interesting.

**Comment by rickhg12hs** [comment]
VirusTotal didn't detect anything.

https://www.virustotal.com/gui/url/8002cb5252aa747ad539a3de4e43972b830bd618cddfda3299fbae10736055c8/detection
