### ISSUE TITLE
Do we have to use glibc 2.7?

### ISSUE THREAD

**Issue by baibinghere** [bcpierce00/unison#438]
Lots of servers are not using such latest glibc.
E.g. On relatively new SLES12SP5 server, the official latest glibc version is still:
glibc-2.22-100.15.4.x86_64

I tried below versions and they both use latest glibc 2.7

- unison-v2.51.3+ocaml-4.10.1
- unison-v2.51.3+ocaml-4.11.1

**Comment by gdt** [comment]
Please use the mailinglist for questions.  The issue tracker is only for bugs.

When you post, please include enough background so that someone familiar with the issue can understand the situation.
