### ISSUE TITLE
CI-built macos Unison.app fails to start on 10.13

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#439]
Downloading ``Unison-4713e608.ocaml-4.09.1.macos-10.15.app.tar.gz``, unpacking, and running ``Unison.app/Contents/MacOS/Unison`` results in
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/tmp/U/Unison.app/Contents/MacOS/Unison
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/tmp/U/Unison.app/Contents/MacOS/Unison
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

The ``unison`` binary from the non-app macOS build does run.

**Comment by tleedjarv** [comment]
Unison.app itself is built with `-mmacosx-version-min=10.6` OCaml compiler is not. `____chkstk_darwin` is being pulled in by ocaml libs.

I think the issue can be solved by, when building OCaml by opam, passing `-mmacosx-version-min=10.6` to C compiler and `-ccopt -mmacosx-version-min=10.6` to ocaml compiler. Perhaps @rivy you know how to do this?

**Comment by rivy** [comment]
Sorry @tleedjarv, I don't have an answer for you. MacOS is a bit out of my zone of experience...

If you can tell me what incantation to use with `opam` and OCaml, I might be able to integrate it into 'CICD-tools/ghactions-ocaml.toolchain' (or preferably, get it included in the original action, [avsm/setup-ocaml](https://github.com/avsm/setup-ocaml)).

Unfortunately, I don't have any MacOS hosts to test and iterate upon.

**Comment by mroi** [comment]
I can prevent the inclusion of the `____chkstk_darwin` symbol by building the OCaml compiler with this environment variable set:
```
MACOSX_DEPLOYMENT_TARGET=10.6
```
I have set this in my shell before running `./configure` in `ocaml-4.09.1`. Maybe this can be included in the CICD builds?

**Comment by gdt** [comment]
Thanks @mroi for the confirmation of that.

I wonder slightly why you pick 10.6, or maybe that's just the oldest supported by the SDK and it works ok, so why not?  Or maybe that's what the other build has...

**Comment by tleedjarv** [comment]
I don't have access to macOS either. I was experimenting a little with GHA macOS environments.

I did try setting environment variables, including the one @mroi mentioned. It does not seem to be honoured by the GHA action that builds OCaml. Could it be that opam intervenes?

It seems that GitHub has made changes to their macos-10.15 environment and now I get errors about some objects being built for arm64 and some for x86_64.

As to why 10.6, there is no particular reason, it was just what uimac was already specifying.

**Comment by tleedjarv** [comment]
> I have set this in my shell before running `./configure` in `ocaml-4.09.1`. Maybe this can be included in the CICD builds?

Do you have possibility to try this with opam? I have started to think that it could be opam that is making this simple thing harder than it should be.

**Comment by mroi** [comment]
I was building `ocaml-4.09.1` directly. Never used opam before, but I will have a look.

I am also seeing the errors about arm64. If we don’t plan on universal binaries (yet), then I would recommend whitelisting x86_64 in the Xcode project only. I can make a PR if that is the way to go.

**Comment by tleedjarv** [comment]
> I am also seeing the errors about arm64. If we don’t plan on universal binaries (yet), then I would recommend whitelisting only x86_64 in the Xcode project. I can make a PR if that is the way to go.

I was thinking of doing that, but that would prevent people building on arm64 on their own. For now, I've made a PR with a different approach: #449 

It's the OCaml side that is preventing universal binaries.

**Comment by mroi** [comment]
I have not personally worked with GitHub actions yet, but the way I read the current action configuration, OCaml is pulled in using [CICD-tools/ghactions-ocaml.toolchain](https://github.com/CICD-tools/ghactions-ocaml.toolchain), which apparently just uses the homebrew version on macOS. To get more control over the OCaml build process, I only see the option of compiling a custom version as part of the CICD.

**Comment by tleedjarv** [comment]
Yes, OCaml is pulled in using that action. But it does not use OCaml by homebrew, it builds a fresh compiler every time with opam. I don't know opam at all, but as much as I have investigated this issue, opam seems to offer no way of controlling the build process. Just setting the env variable does not work either (but I have no access to macOS, so I'm just testing with GHA), whether it is opam's doing or not.

**Comment by mroi** [comment]
I have built an OCaml compiler using `opam init` and opam does respect the `MACOSX_DEPLOYMENT_TARGET=10.6` environment variable. The linked PR fixes this issue for me.

**Comment by tleedjarv** [comment]
Have you tested the resulting binaries on 10.13 (or older)? I don't have access to macOS, but just by looking at the binaries, it seems the `____chkstk_darwin` symbol is still there as dependency.

**Comment by gdt** [comment]
I tried to run "unison" from the merge on 10.13 and got the __chkstk_darwin error, unfortunately.

**Comment by mroi** [comment]
I did not run the binaries on an older machine (since I have none), but I did check that the symbol is gone when I downloaded the resulting binary from my GitHub clone of the repo. I see that the Action workflow can cache the `.opam` directory, but for this change to work, a fresh `.opam` needs to be built. Maybe this is what is happening here?

**Comment by mroi** [comment]
This was exactly what was going on any I fell into that trap myself during my own testing. Sorry about that, I am just learning about GitHub Actions. I am working on an actual fix right now.

**Comment by tleedjarv** [comment]
> This was exactly what was going on and I fell into that trap myself during my own testing. Sorry about that, I am just learning about GitHub Actions. I am working on an actual fix right now.

(facepalm) I completely missed this! I tried with the environment variable some weeks ago and failed. Presumably because of this caching then.

To flush the cache, you just have to increase the version number in the cache ID in workflow file.

**Comment by mroi** [comment]
[These binaries](https://github.com/mroi/unison/actions/runs/456624632) should work now. You mean increasing the cache version [like this](https://github.com/mroi/unison/commit/46de31ff447e932c3e76fa0c1d2e84aa87f54f52)?

**Comment by tleedjarv** [comment]
> [These binaries](https://github.com/mroi/unison/actions/runs/456624632) should work now.

I can't test but the symbol list looks good to me.

> You mean increasing the cache version [like this](https://github.com/mroi/unison/commit/46de31ff447e932c3e76fa0c1d2e84aa87f54f52)?

Yes.

**Comment by mroi** [comment]
Alright. I made a new PR: #461. I hope this creates correct binaries now.

**Comment by gdt** [comment]
I downloaded the 4.09 unison (non-App) CI build, and it ran the command-line unison.   The gtk build and the App build fail, but I'm 95%+ sure that's not about OS version.   Thanks @mroi for the fix.
