### ISSUE TITLE
Uncaught exception when clicking "Open" in Mac GUI

### ISSUE THREAD

**Issue by Phosphor303** [bcpierce00/unison#44]
Steps to reproduce:
1. Open Unison
2. Click "Open" button
3. Get this.

![bildschirmfoto 2016-10-22 um 22 06 04](https://cloud.githubusercontent.com/assets/5774545/19622181/0cec119e-98a4-11e6-84ca-9af8240da84b.png)

OS X 10.11.6
Unison 2.48.15 binary retrieved from GitHub right now.

**Comment by bcpierce00** [comment]
Hmm.  That assertion failure indicates that there are either too few or too many "roots." 

Has Unison ever been used on this system?

Can you run it from the command line with debugging enabled -- e.g., something like this?

    .../Unison.app/Contents/MacOS/Unison -debug verbose

**Comment by bcpierce00** [comment]
Ah.  If you click "New" instead of "Open", does something better happen?

**Comment by Phosphor303** [comment]
Yes, I can create a profile. And if I click "Open" when a profile exists, it actually tries to connect. Should've been more precise about this.

**Comment by bcpierce00** [comment]
OK, so the fact that it dies when Open is clicked first thing does indeed look like a bug.  Thanks for reporting it.

**Comment by wamatt** [comment]
I can confirm this issue is happening to me too. osx 10.11.6, unison 2.48.15

`Uncaught exception File "/Users/schmitta/src/unison/branches/2.48/src/globals.ml", line 83, characters 9-15: Assertion failed`

**Comment by brabalan** [comment]
I was able to reproduce this, and I committed a version where this no longer happens ("Open" with no profiles selected will do nothing). If you can compile Unison, can you give it a try?

**Comment by Klemart3D** [comment]
Same for me on macOS 10.12.4 and binaries Unison 2.48.15. Appear when I open a profile named "[internal error!]" :

![unison-internal-error](https://cloud.githubusercontent.com/assets/7419525/24750675/0021e466-1ac7-11e7-9539-f6d5f3ca7e29.jpg)

![unison-fatal-error](https://cloud.githubusercontent.com/assets/7419525/24750679/03593d96-1ac7-11e7-88e7-f77e2feb67c6.jpg)

And same command-line warning as @Phosphor303 :

> CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces, or set CA_ASSERT_MAIN_THREAD_TRANSACTIONS=1 to abort when an implicit transaction isn't created on a main thread.

@brabalan, what is your commit ref ?

**Comment by bcpierce00** [comment]
I guess Alan fixed this.  Closing issue.

**Comment by brabalan** [comment]
Yes it was fixed in https://github.com/bcpierce00/unison/commit/ced2484abe650006dbcba0c66f908989819256c1 (with additional commits to revert some changes I did to the xib and should not have committed).
