### ISSUE TITLE
CI-built mac unison-gtk depends on gtk from elsewhere, not adequately documented

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#440]
The unison-gtk executable from the CI (non-App) mac build is linked against gtk2, which is not provided.  That's ok, but the instructions for how to use it are missing from https://github.com/bcpierce00/unison/wiki/CI-Binary-instructions#macos

**Comment by gdt** [comment]
See also #467 for details, but the central point is that CI-built binaries are bound to a particular version of a particular packaging system, and trying to use them with any differing environment is unsound.

**Comment by liyishuai** [comment]
Is it worth providing some `unison-cli` package that doesn't depend on GTK? I was trying to add a package that depends on Unison command line tool in coq/opam-coq-archive#2126, but the CI failed because no GTK was on that machine.

**Comment by gdt** [comment]
The entire "what are we packaging and why" is certainly open to discussion.   However, to first order, packages should be provided by packaging systems, and unison CI is for CI.   This issue is about lack of clarity about the current situation, and fixing that is a precondition for some larger redesign.

**Comment by liyishuai** [comment]
I meant `-cli` package that only includes the command line interface, and probably a `-gtk` package for the GUI. Doesn't seem too hard, say, tweaking build and installation scripts?

**Comment by tleedjarv** [comment]
I think things got mixed up here. @liyishuai is probably talking about opam and/or dune (see #658).

The CI provided binaries and binaries from most repositories separate CLI and GUI with CLI binaries not having any dependencies to gtk. I would expect those to be packaged separately but that may not always be the case.

**Comment by gdt** [comment]
This is part of #602, and the wiki page already points out that it is unknown where the gtk libs come from.
