### ISSUE TITLE
Log line wrap position length

### ISSUE THREAD

**Issue by turgs** [bcpierce00/unison#446]
Hello

Is there a way to prevent the log/console output that unison generates in linux from wrapping?

It seems to wrap somewhere around the 80-82 character point. Can that be disabled so it just wraps at the point of my terminal window?

Thanks
Tim

**Comment by gdt** [comment]
Please ask questions on the mailnglist; the issue tracker is only for bugs.

**Comment by gdt** [comment]
Pointer to lists is at https://www.cis.upenn.edu/~bcpierce/unison/lists.html
