### ISSUE TITLE
Is fastcheck reliable in all cases?

### ISSUE THREAD

**Issue by hrj** [bcpierce00/unison#45]
How does fastcheck work and is it stable in 2.48.3 (version in Ubuntu 16.04) and 2.48.4 (latest windows release)?

I just found that a particular file refused to sync although their MD5 sum was different on the source and destination. After adding `-fastcheck false` the file synced fine.

**Comment by alkuzad** [comment]
@hrj MD5 calculates it's sum by scanning whole file content so it will always show any change. Fastcheck however uses only file length and modification time (see http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html). This way if your file was modified in such way that length was not changed and modification time was not updated for some reason (excel does that) file will not be updated.

**Comment by hrj** [comment]
Ah, the documentation is clear about it: enabling fastcheck on Windows is not reliable.

In that case, I think the developers should disable fastcheck on Windows by default; expecting the user to read every part of the document is impractical. Moreover, even if one user (on Linux) does read the doc, they may not know whether the other user (on Windows) has read the docs. 

Further, I would say this type of fastcheck is unreliable on non-Windows systems as well; applications might change the timestamp for their own purposes and users may not be aware of it. This type of "fastcheck" shouldn't be a default on any system. Just my humble opinion.

**Comment by alkuzad** [comment]
@hrj this depends on other factors than only OS type. Windows is stated as "not-reliable" mostly because of FAT filesystem that lacks needed features. I'm using unison on windows with defaults and I never had problems (synchronizing NTFS with ext4 via ssh)

I advice you to elaborate more on your setup before making such big statements that Unison is wrong, not your setup. Please include:

1. Unison configuration that you are using
2. Log files from both machines (~/unison.log)
3. Test case for your invalid case

**Comment by hrj** [comment]
@alkuzad The documentation linked by you itself says that "Under Windows, this may cause Unison to miss propagating an update if the modification time and length of the file are both unchanged by the update." In other words, Unison's default configuration is unreliable on Windows, according to the docs you linked.

I can't share the test-case.. it is a confidential file. My unison configuration is default. I am complaining about the defaults. I have already mentioned the version numbers.

**Comment by alkuzad** [comment]
@hrj so look into the changelog to see the reasoning about changing it to default. It mentions why it was unreliable for Windows. I suspect you use either old fat or network based disk that does not properly log modification time which can be problematic but If you can not create test case for that I have to say that from my perspective it's bug on your setup.

**Comment by bcpierce00** [comment]
The problem with turning factcheck off by default is that this will make checking for changes enormously slower.  I'm willing to entertain this option if there's a lot of support for it, but IIRC, this is the first time someone has complained about the default being (arguably) wrong.

**Comment by bcpierce00** [comment]
The default is arguably "safe" in that it will never overwrite a change incorrectly.  But you're right that it may fail to detect a change.  I'll keep it the way it is for now, but if others would like to chime in in support of a change, please do...
