### ISSUE TITLE
Files getting skipped erroneously

### ISSUE THREAD

**Issue by cliquesoft** [bcpierce00/unison#456]
Also related to issue #455 (https://github.com/bcpierce00/unison/issues/455), it appears that some of the files are getting skipped by mistake. Here are two instances of the 

[CONFLICT] Skipping Common/OLD_E/2003 GSS JOB Numbers
  conflicting updates
[CONFLICT] Skipping Common/OLD_E/GSS 2003 JOB NUMBERS
  conflicting updates

The command line added that they were 'deleted'!  I looked through my backups of the "active" Windows server and can't seem to find either of those directories on it, they are only on the "backup" Windows server.  How can there be a conflict if those directories only exist on one of the servers?

Unison Info:
unison-f215b64e.ocaml-4.11.1.windows-latest

Unison "Client" Config:
# Unison preferences file - custom
root = D:\
root = socket://Server:2299/D:/
# Paths to include in the sync
path = Common\OLD_E
# Optional parameters to use
fastcheck = true
batch = true

Unison "Server" Started:
"C:\Program Files\Unison\unison.exe" -socket 2299

Server Info:
Server1 is Windows 2012 Essentials
Server2 is Windows 2019 Essentials
Both are using NTFS file systems
Attempted to sync ~87GB of data

**Comment by tleedjarv** [comment]
Based on discussions in the mailing list, I suspect that this may be an issue of old archive (and/or fingerprint) files left from previous runs. This itself does not automatically mean that this run should have failed. Unison usually takes quite good care in maintaining archive integrity. But with previous runs getting stuck and being forcefully closed, it may very well be the cause.

**Comment by gdt** [comment]
Do we think it is still valuable to have this bug open?

**Comment by tleedjarv** [comment]
I think there is too little to go by without the archive dumps and exact details of files on fs.

**Comment by gdt** [comment]
Timed out, feel free to reopen with a repro recipe.
