### ISSUE TITLE
Mailing list situation is unclear

### ISSUE THREAD

**Issue by bsammon** [bcpierce00/unison#458]
I would like to read the unison-users archive and I would like to subscribe to the list.
When I look at
https://www.cis.upenn.edu/~bcpierce/unison/lists.html
the unison-users link points at a google-group page.
1)  Lower on the page it says that list archives are publicly visible, but that google group appears to be private (for some value of "private") -- the unison page ought to clarify what is meant by "publicly visible".
2) I would like to subscribe to the unison-users list with a non-gmail email address.  It is unclear to me whether unison-users is fundamentally a google-group list or a @lists.seas.upenn.edu list.  Either way, it should be possible to subscribe with a non-gmail address (I've done it with other google-groups)  Through guesswork, I've found https://lists.seas.upenn.edu/mailman/listinfo/unison-users , and tried to subscribe there -- not sure if that's the way to go.

**Comment by bcpierce00** [comment]
Apologies -- the unison-users list can be found here (I'll fix the web
page):

https://groups.google.com/a/seas.upenn.edu/forum/?hl=en#!forum/unison-users

**Comment by bsammon** [comment]
When I try to follow that google-groups list, I get a "You don't have permission to access this content" page.
Is that what I should expect?

**Comment by bcpierce00** [comment]
Oof -- sorry -- that was the old link, not the new one!  Try this:

https://lists.seas.upenn.edu/mailman/listinfo/unison-users

**Comment by bsammon** [comment]
I just tried to subscribe by following the instructions at https://github.com/bcpierce00/unison/wiki/Mailing-Lists - via emailing unison-users+subscribe@seas.upenn.edu
I got an email response that pointed me at a Google page, that I was unable to access.

**Comment by bsammon** [comment]
Ah... okay... the email response also said I could reply to it as an alternative to visiting that inaccessible webpage.
Tried the reply route, and got another email that said "your subscription request is pending".
Now that I think of it, I think I previously did this process earlier this month, so I may have two subscription requests pending.

**Comment by bcpierce00** [comment]
Thanks for letting us know about this issue, and sorry for the long back
and forth.  Can you try going directly to

   http://lists.seas.upenn.edu/mailman/listinfo/unison-users

and see if it works better for you?  I am not seeing the pending request.
:-(

**Comment by bcpierce00** [comment]
Apologies again -- you were right the first time, and now I see your
subscription request on the google group.

I think I just approved the request, but I'm not certain -- the
confirmation email apparently couldn't be sent.

[image: image.png]

**Comment by stef204** [comment]
Trying to subscribe as well, Can you please check the queue?
(Didn't want to open a new ticket for this.)

**Comment by reagle** [comment]
Why not link to the list on <https://github.com/bcpierce00/unison/wiki/Mailing-Lists> ?

**Comment by gdt** [comment]
That wiki page documents the current situation, and this bug is closed.  if you think there's something wrong with the Mailing-Lists wiki page, please open a bug about that.
