### ISSUE TITLE
Provide support for appimages

### ISSUE THREAD

**Issue by kshenoy** [bcpierce00/unison#459]
Hello, would it be possible to create appimages for releases? 

Every time I try to build unison, I seem to hit some issue or the other with Ocaml. Even if I do manage to build it sync doesn't work if the ocaml version is different. I understand there might be good reasons for having these dependencies and requirements but it is quite cumbersome to walk through and deal with all of them. I hope it might be easier if I can download the same appimage on both machines.

**Comment by gdt** [comment]
There are a vast number of packaging systems and unison the project has not decided to in general provide support for all of these systems.   I don't even know an appimage is, but please ask the appimage people/community to package unison.

You probably noticed CI builds on github.  The primary purpose of those is to verify that proposed changes are ok.  Secondarily they are made available.  Perhaps they are helpful to you.   If you have questions about them, please use the mailinglist as the issue tracker is only for bugs and generally-useful feature requests.
