### ISSUE TITLE
OS X build documentation is dated

### ISSUE THREAD

**Issue by fingon** [bcpierce00/unison#47]
Correct steps would be (roughly)

- use 'make' for text UI
- use src/uimac14/*.xcodeproj (+ build in xcode) for graphical UI

Current documentation (and also Makefiles) have e.g. references to uimac09, uimacnew, both of which seem to be gone.

**Comment by brabalan** [comment]
It seems that if I do `make` in the toplevel directory I get a text UI, but if I go down to the `src` directory I get a uimac14 UI (it is selected automatically). Do you see the same?

**Comment by fingon** [comment]
Yes, actually (I did not even imagine src/ did something else than toplevel but live and learn :) )

**Comment by bcpierce00** [comment]
Yes, it looks like the makefile needs a haircut!  I've added this to a more recent issue.

**Comment by bcpierce00** [comment]
Yes, both the Makefile.OCaml and the documentation need to be updated to reflect current reality.
