### ISSUE TITLE
Sync'ing version 2.40 on CentOS with 2.51 on MacOS Catalina

### ISSUE THREAD

**Issue by natgoodman** [bcpierce00/unison#471]
I find myself trying to sync files from an ancient CentOS 6.x server to Mac running Catalina.  The server is running Unison 2.40 which won't run on Catalina. The Mac is running 2.51 which won't run on the server because its glibc is way out of date. I'm loathe to upgrade glibc on the server for fear of breaking something else. 

Any thoughts on how to make this work? For example, any chance of compiling 2.40 for Catalina?

Thanks,
Nat

**Comment by gdt** [comment]
Please use the mailinglist for questions.

**Comment by natgoodman** [comment]
Sorry. Thanks for pointing out my error. I should have known better. Yesterday was a long day...
