### ISSUE TITLE
Compared to syncthing/syncthing ?

### ISSUE THREAD

**Issue by elgalu** [bcpierce00/unison#476]
There are some comparisons already but what's the author opinion? or perhaps some power users?

> Unison is no longer under active development
https://github.com/bcpierce00/unison/blob/f28ef2f11/src/TODO.txt

> If unison fulfills your requirements, you should use unison instead of syncthing
https://forum.syncthing.net/t/syncthing-extremely-slower-than-unison/12196

> Unison simply relies on plain old ssh and has no support for device discovery, dynamic IPs, relays, transparently re-establish connections, etc
https://forum.syncthing.net/t/unison-as-optional-syncing-backend/12556

**Comment by gdt** [comment]
Please use the mailing list for things that do not belong in a bug tracker.
