### ISSUE TITLE
Add ability to sync folder pairs in different paths

### ISSUE THREAD

**Issue by loucurapt** [bcpierce00/unison#477]
This is a feature request.

Would it be possible to implement a way in Unison to sync a folder between two roots that are in different paths?

Let me explain with an example:
Suppose I want to sync my documents, pictures, videos, etc. between my computer (let's say Windows) and my Android phone (through a WebDav server installed in the phone, for example).
With the correct roots, folders like "Documents" and "Pictures" are on the same path in both operating systems.
But for videos, it's usually "Videos" on Windows and "Movies" on Android. (I know I can use "Videos" on Android and it's what I use, but this is an example).
Symlinks could be used on Linux to work around this, but no such luck on Windows and Android.

It would be awesome if I could add a "path" configuration like this in those cases:
```
path = Videos -> Movies
```
(Considering that the 1st root is Windows and the 2nd is Android in this case.)

Oh, and thank you for Unison! I've been using it for quite some time now, and it's great!

**Comment by gdt** [comment]
I'm interpreting your feature request as being about doing renames within roots; obviously one can sync Videos on one system with Movies on another as the two roots.

This seems like a step to a fair bit more complexity and I'm not sure that's a good tradeoff, so I've added "discuss".

**Comment by gdt** [comment]
Moved to https://github.com/bcpierce00/unison/wiki/Feature-Requests
