### ISSUE TITLE
No -servercmd equivalent for unison-fsmonitor executable?

### ISSUE THREAD

**Issue by GrqPnegre** [bcpierce00/unison#483]
I've build unison (native=true) on a server where I don't have permission configure the path for SSH, so I'm needing to specify `servercmd=/path/to/unison` to locate the unison executable.  

When I run with `-repeat watch` I get the following error:
```bash
0 $ unison default a.tmp ssh://myserver//home/user/a.tmp -repeat watch -times -logfile /tmp/unison.log
Unison 2.51.3 (ocaml 4.08.1): Contacting server...
---8<---
Fatal error: No file monitoring helper program found
```

If I had to guess, it looks like the fsmonitor isn't found on the SSH path (which will be for a non-interactive shell).  I've tried numerous things to work around this problem with no luck.  Help!

Is there a missing command like `-fsmonitorcmd`?

-G

**Comment by tleedjarv** [comment]
I created PR #484 to add more debugging information. Try a build from that PR (you can download the build artifacts from the 'Checks' section). Just run as you would normally and add `-debug fswatch`.

**Comment by GrqPnegre** [comment]
Thx.

Now I'm questioning whether I'm wrong about how the monitor is invoked.  I'm running the above command on macOS where now I realized the build didn't produce `unison-fsmonitor`.  I built `unison` via a custom macport portfile to get the right versions between my boxes and didn't take it from the port repo.

My assumption was that the monitor wasn't found on the remote, but it's probably the local machine.  Actually, does `-repeat watch` execute the monitor on the remote side as well?

**Comment by tleedjarv** [comment]
Yes, the monitor is executed on both hosts. I think on macOS the monitor is a Python script, not a native binary. So you have to make sure you have `fsmonitor.py` and whatever libraries it requires and that it actually works with your Python version. The added debugging information in the PR I mentioned is only for the binary fsmonitor.

**Comment by gdt** [comment]
This seems like a question, not a bug report, and after discussion I see no remaining issue.
