### ISSUE TITLE
Create folder if it's empty only on one replica

### ISSUE THREAD

**Issue by alkuzad** [bcpierce00/unison#49]
Would it be good to change default behaviour to create path if it does not exist on one replica ?

I usually want to just run unison on empty replica and I want to fetch all data from remote one and creating all paths first is problematic as there is no easy way to get path/root combination without merging all includes first. And because I want unison to be as efficient as I want I keep my profiles small and run 1-5 unisons in watch mode at the same time. So I have like 15 root/path combinations.

**Comment by bcpierce00** [comment]
I guess you mean "change default behavior to create nonexisting paths _and their enclosing directories back to the root_."  Yes, I suppose this would be good.  Happy to accept a patch.

**Comment by tleedjarv** [comment]
This works as expected in the latest version. I don't know if it has been fixed/changed in some version or it has always been working like this.

@alkuzad more information is needed. Perhaps you can post an example?

**Comment by gdt** [comment]
Starting 30 day timer to close unless a repro recipe for 2.51.3 or later arrives.

**Comment by alkuzad** [comment]
@tleedjarv I refuse to work on such old stuff, when VScode remote plugin went in I basically stopped using Unison.
