### ISSUE TITLE
i386 Windows release built only against ocaml-4.10.1

### ISSUE THREAD

**Issue by headbank** [bcpierce00/unison#490]
I see that the current set of release binaries for each release includes only one for win32, built with ocaml-4.10.1.

I cannot find any details about this so can I enquire why only this one build is being released for windows-i386, and why using this particular (2nd-from-latest) iteration of ocaml? Does 4.11.x not support win32, or is there another reason?

I have an armv7l Raspbian Linux server running unison-2.51.3.70 (ocaml 4.11.1) built locally with opam (the version available in APT is not keeping pace with other clients) and two Windows 10 32-bit clients. With them I tried the unison-v2.51.4_rc2+ocaml-4.10.1+i386.windows.zip release but it is crashing with unmarshaling error (as described in issue #435) which I assume is to be expected.

**Comment by gdt** [comment]
The real purpose of the builds is regression testing.   It's a happy accident that the binaries are useful.   I don't use windows, but my impression is that i386 mode windows is obsolete anyway.   We already have rather a lot of builds, and GHA is already showing signs of random nonrepeatable failures, which complicates deciding if something is safe to merge.

Feel free to bring up a notion that the win32 build should be switched to 4.11 as a PR (after it's passed in your repo), or for discussion on unison-hackers.  There may be some "GHA only supports X" kind of issue.

(Personally, I see it as a far bigger issue that there's no GHA target for any BSD or illumos, than another windows variant.)

But basically, "the set of CI builds doesn't include X" isn't really a bug.

**Comment by headbank** [comment]
I should say I'm only a user so most of your comment sails way over my head, but I think I get the message that availability of win32 builds is not something that is going to be able to be banked upon from here on out. That's a headache for me but I take your point about it being a very minor constituency (and thus priority) for the project. I can probably find an alternative approach such as a cygwin package, something with Windows Linux Subsystem (or whatever it's called) or have a go at building unison myself if it comes to it. Thanks for the info.

**Comment by gdt** [comment]
You should be able to fork the project, and find the GHA automations script that says 4.10 and change it to 4.11 and commit it, and your fork should run it.  I don't mind merging that if 1) you show it works and 2) nobody objects to the PR over a week.   But yes, you're likely going to need to build it yourself.

**Comment by headbank** [comment]
Yeah, still going over my head, sorry. I only have a github account in order to raise or contribute to tickets, but what you're suggesting (I think) amounts to more or less taking on stewardship, on the same level that you operate, of a facet of the project that you've just characterised as approaching obsolescence. Hardly appealing. I appreciate that this is how things get done if you want them done, but unison is already becoming less stable and more demanding for me as an end-user (I never encountered so many incompatibilities within the same minor-version until less than a year ago) and given what you've said above I think the resources I can spare for this are probably better spent (a) seeing if I can get reliable local builds happening on these clients, or (b) coming up with different sync strategy for them.

**Comment by tleedjarv** [comment]
All what's said above is correct, of course. But given that binaries for Windows have historically been hard to come by, I couldn't resist and will offer you a way forward. I did what @gdt suggested above.
Take all the DLLs from a release in this repo (since you tried the binary compiled with 4.10.1 then you should have them already) and then get the exe separately from here: https://github.com/tleedjarv/unison/actions/runs/669064245

**Comment by headbank** [comment]
@tleedjarv Thanks for doing that, can confirm your unison-gtk2.exe works when imported to the v2.51.4_rc2+ocaml-4.10.1+i386.windows distribution (after reinitialising the profile manually: sadly it seems the previous unmarshalling error left the affected profile unrecoverable).

From this PassMark Software [survey data](https://www.pcbenchmarks.net/os-marketshare.html) I see that 32-bit Windows 7+10 share is now at less than 0.7%, and with Win10 alone (7 being now unsupported) under 0.4% - of course these shares may be quite different among current unison users, but among _potential_ users one can assume reasonably representative. In other words, I wouldn't expect to count on the project devoting much attention to this platform going forward.

I can make do, with some more granular use of rsync and manually keeping track of some contextual details myself (the stuff unison allowed me to be lazy about, lol). It probably makes more sense for 32-bit users to start doing that now than wait for the end to come, which I imagine will be without much warning when it does. Even if that is still years away, the increasing stability issues are also a consideration.

**Comment by tleedjarv** [comment]
Yes, I can confirm it works. Tested against Linux.

**Comment by headbank** [comment]
Yes, me too! (Sorry I worded my comment carelessly: I meant *I can* confirm...)
