### ISSUE TITLE
v2.51.4_rc2 binaries don't run on Debian 10 (stable)

### ISSUE THREAD

**Issue by OnkV** [bcpierce00/unison#491]
It's not a bug but maybe you want to be aware about that:
```
% tar xzf unison-v2.51.4_rc2+ocaml-4.11.2+x86_64.linux.tar.gz
% ./bin/unison -version
./bin/unison: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./bin/unison)
```

**Comment by gdt** [comment]
If you could post to unison-hackers an explanation of the larger issue and how it interacts with things built with the options  provided by GHA that would likely be helpful.     I am curious if this is new, in other words do the rc1 binaries run on the same system?

**Comment by OnkV** [comment]
> I am curious if this is new, in other words do the rc1 binaries run on the same system?
The rc1 binaries run on Debian 10.

**Comment by EtaoinWu** [comment]
It also does not run on my Ubuntu 18.04 (with glibc 2.27) and 20.04 (with glibc 2.31).

**Comment by tleedjarv** [comment]
@EtaoinWu could you add which exact build you tried? It is important to know which OCaml version was used.

@EtaoinWu @OnkV could you try one of the builds with an older OCaml version?

**Comment by OnkV** [comment]
> @EtaoinWu @OnkV could you try one of the builds with an older OCaml version?

I tried them all - only `unison-v2.51.4_rc2+ocaml-4.10.0+x86_64.linux.static.tar.gz` works.  Unfortunately this package does not contain the GUI version, which is all I need (because I can't compile it myself since the build system doesn't find lablgtk in my `~/.opam` directory).

**Comment by tleedjarv** [comment]
Mystery solved. GHA switched Ubuntu build servers from 18.04 to 20.04.
I will create PR to get this fixed.

**Comment by OnkV** [comment]
Great, thank you!
