### ISSUE TITLE
Windows version opens console window in background

### ISSUE THREAD

**Issue by mvglasow** [bcpierce00/unison#496]
### To reproduce:

Launch Unison on Windows.

### Behavior observed:

A console window opens, then the two Unison GUI windows (the main one and the profile picker). Closing the console window will close Unison—this is fairly unexpected behavior for a GUI application on Windows (or other platforms, save for some very old or hackish Unix stuff).

### Behavior expected:

Just the two GUI windows appear. This is what happens on a Linux build.

### Versions:

Tested on 2.51.4-rc2, but I have observed the same behavior in earlier versions (as early as back in 2013).

### Additional comments:

As far as I know, Windows and Unix-like OSes differ in how the two platforms handle GUI apps writing to stdout, which can have implications here:

On Windows, each app declares itself as a console or GUI app.
* When launching a console app from a command line, Windows will wait for it to finish. stdout and stderr will be printed to wherever the command line is running.
* When launching a console app from a GUI (e.g. Explorer, including start menu), a console window is opened where any stdout/stderr data is printed.
* When launching a GUI app from a command line, the command line will continue right after launching the app (similar to appending `&` on a Unix shell). From a GUI, no console window is opened. Either way, stdout/stderr output is lost.

Unix has no such distinction. Any app can print output to the console that launched it, as well as launch a GUI window. When an app is launched from a command-line shell, it will wait for the process to finish (unless launched with `&`), and either way stdout/stderr goes to the same terminal (which can get a bit messy when launching a chatty app with `&`). When launching an app from a GUI, the GUI needs to provide a way to display stdout/stderr output. Most common is launching a separate terminal window, some older environments would open a message dialog every time something got printed to the console.

That would mean suppressing the console window on Windows would also suppress console output. If this is an issue, a solution might be to redirect output on Windows to a buffer and provide a console window which the user can launch with a special menu command.

**Comment by PeterMosmans** [comment]
Hi @mvglasow - I'm curious, which binary are you executing? Have you built Unison yourself? As far as I can tell this does not happen with versions built with MSYS2 on Windows.

**Comment by mvglasow** [comment]
@PeterMosmans no, I didn’t build it myself. I got one of the versions from the project’s Github Releases, but I would need to investigate which OCaml version it comes with.

**Comment by mvglasow** [comment]
@PeterMosmans Just checked, I downloaded unison-v2.51.4_rc2+ocaml-4.05.0+x86_64.windows.zip, and it opens the console window in the background. Minor glitch: the GUI reports its version as 2.51.3 (double-checked the .exe to ensure I am running what I think I am; timestamp and file size exactly match the one in the zip file).

**Comment by gdt** [comment]
Thanks for the confirmation.   2.51.4_rc2 identifying as 2.51.3 is not surprising as I probably didn't change the version for the rc.   (I suspect this is not related to ocaml version, but 4.05 is very old.)

I was surprised to see a discuss tag on a bug like this, but I see after reading more carefully that just flipping the setting to GUI app is not necessarily the right thing to do.    I wonder about doing that only if some debug flag is not given.

**Comment by acolomb** [comment]
AFAIK the console window is needed to answer an SSH prompt other than being asked for the password (which unison intercepts). Things such as whether a remote host key should be trusted e.g. Without the terminal window, all such prompts would need to be redirected to a custom terminal widget or similar (which could be hidden until something is printed).

**Comment by PeterMosmans** [comment]
This might or might not be what you're after, but if you use Windows Subsystem for Linux (WSL), and install Unison there, it's trivial to create a shortcut to `unison` which will start without a console window. An added bonus is that you can install it from package managers, e.g. under Debian with a `sudo apt install unison`
The same holds true for installing Unison on the MSYS2 subsystem.
