### ISSUE TITLE
Re-index just one side?

### ISSUE THREAD

**Issue by L3P3** [bcpierce00/unison#499]
Hello, I sync two huge filesystems with unison, multiple terabytes, billions of files.

Now, there were corruptions detected by btrfs on mirror A. Many files were modified without unison detecting it since the datestamp of these files did not change. On mirror B, all files are still correct. (Apparently)

Now, I want unison to scan through mirror A to detect all files that have a different checksum now (fastcheck). But when I disable fastcheck, it appears that mirror B also reads all the files which is very bad. I want to stress mirror B as least as possible. It would be very bad if while heavy loading mirror B, it would fail.

Question: How can I force unison to verify all files and their contents on mirror A without even touching mirror B, just using the existing index file?

**Comment by gdt** [comment]
Please use the mailinglist for questions.   The tracker is only for bug reports.

https://github.com/bcpierce00/unison/wiki/Mailing-Lists
