### ISSUE TITLE
Client-only preferences for better cross-version compatibility

### ISSUE THREAD

**Issue by bcpierce00** [bcpierce00/unison#5]
The fact that different unison versions can't inter-operate seems to create a lot of problems for people in practice.  This means in particular that every time we add a new preference, we break compatibility between the development version and whatever version other people may have installed.

Fixing this completely would be quite difficult because the low-level mechanisms that Unison uses to communicate preferences from client to server is based on untyped marshaling.  However, most new preferences are only needed on the client (because they affect only the GUI or the reconciliation process, not change detection or propagation), and there's no reason to bump the version number when they are added.  It would be fairly easy to mark such preferences as client-local where they are created and tell the preference dumping and reloading mechanism to ignore them.  (We'd want to make any dynamic references to them on the server side be fatal errors, just for the sake of paranoia.)  This way a client should be able to communicate with a slightly older (or, indeed, slightly newer) server without problems.

**Comment by g-raud** [comment]
Client-local preferences have been implemented since commit 06be21b9 (subitem "Added some support for making it easier to extend Unison without breaking backwards compatibility", 2009-07-19).  One only needs to pass optional argument `~local:true` to `Prefs.createBool`, `Pred.create` etc.

**Comment by bcpierce00** [comment]
Hey, that's true!  OK, closing this issue now.  Sorry it took so long to check.
