### ISSUE TITLE
Prefer xxHash over OCaml's Murmur3

### ISSUE THREAD

**Issue by legends2k** [bcpierce00/unison#502]
I suggest replacing [OCaml's Murmur3][4] hashing with xxHash.  Reasons:

1. Most decision making of Unison is based out of hashing (large amounts of) data; improvement to hashing function performance leads to direct improvement of Unison's performance
2. Benchmarks [here][1] and [here][2] show xxHash (`xxh3`, `xxh128`) is over 7 times faster than Murmur3
3. [xxHash has a wide variety of implementations][3] including OCaml (outdated though)

Both are non-cryptographic hashing functions, just to be clear.

[1]: https://github.com/rurban/smhasher
[2]: https://cyan4973.github.io/xxHash/
[3]: https://cyan4973.github.io/xxHash/#other-languages
[4]: https://github.com/ocaml/ocaml/pull/24

**Comment by gdt** [comment]
I think things like this -- questions about big picture decisions -- are best discussed on unison-hackers rather than github issues.

**Comment by legends2k** [comment]
I didn't know of other forums.  Just curious: why is this tagged high effort and low impact.  It'd be good to know the rationale/thinking behind it.

**Comment by gdt** [comment]
https://github.com/bcpierce00/unison/wiki/Mailing-Lists

**Comment by MystaraTheGreat** [comment]
I made a request to join about a week ago and still haven't been added.
But to add to the comment regarding "low impact", I ran a quick python script to iterate over my entire repository and create a hash using xxhash for each file.  It took roughly 24 hours as compared to the 60 hours that unison takes to build its archive.

Not an entirely fair test, but suggestive that their are significant gains to be made in terms of archive building speed.

**Comment by gdt** [comment]
I haven't seen your request on the maiilman admin interface.  We just click approve when they come in.

low impact doesn't mean there isn't a speedup to be had.    I meant that we are not getting reports of people having significant problems because of hash speed.   It just doesn't show up when one considers all the woes of users.   So addressing this won't help people much, in an overall sense - compared to the protocol dependence on ocaml problem, which combined with ocaml's lack of stability is causing enormous pain.

**Comment by MystaraTheGreat** [comment]
Regarding mailman/the mailing lists, the information I found seemed to point to a google group?

**Comment by gdt** [comment]
https://github.com/bcpierce00/unison/wiki/Mailing-Lists

**Comment by avollmerhaus** [comment]
> [...]  compared to the protocol dependence on ocaml problem, which combined with ocaml's lack of stability is causing enormous pain.

As a unison user of more than 10 years of almost daily usage, I can second this.
Dealing with the realities of having to keep your Ocaml versions tightly orchestrated across different Linux and FreeBSD installations is pain point number one for me and the biggest reason why I wasn't able to convert any of my friends to unison.

**Comment by gdt** [comment]
It turns out murmur3 is only used for archives, not for files, so the performance numbers are not measuring what matters.   The real question is "should we change md5 to ?" and that's fair on -hackers.
