### ISSUE TITLE
How to ignore error `Failed: Destination updated during synchronization`?

### ISSUE THREAD

**Issue by qysnn** [bcpierce00/unison#504]
I get the error message `Failed: Destination updated during synchronization` when trying to sync my working directories even if I set the `-prefer` option to have the files from `dir1` override `dir2` when conflict. Is there anyway I can make Unison ignore this and override anyway as indicated in the `prefer` option? Thanks!
The full commandline I use is `unison dir1 dir2 -batch -times -perms 0 -prefer dir1`

**Comment by gdt** [comment]
Please use the mailinglist for questions.  The tracker is only for bug
reports.

See https://github.com/bcpierce00/unison/wiki/Mailing-Lists
