### ISSUE TITLE
File/folder renaming?

### ISSUE THREAD

**Issue by MystaraTheGreat** [bcpierce00/unison#505]
This is probably more of a query than an issue per se.  How does unison handle file/folder renames?

From the user manual and the section on "renaming directories containing ignored files", it would appear that a rename is treated as a deletion of the old file/folder, followed by a creation of the new file/folder.  Clearly this would be frustrating when one of the repositories is remote.

In use, however, I often see mentions of shortcuts, which seems to suggest that unison is sometimes detecting that a file has moved.  Although if this is the case, I'm not entirely sure as to its reliability.

**Comment by gdt** [comment]
Please use the mailinglist for questions.  The tracker is only for bug
reports.

See https://github.com/bcpierce00/unison/wiki/Mailing-Lists
