### ISSUE TITLE
File times remain different after a merge

### ISSUE THREAD

**Issue by tleedjarv** [bcpierce00/unison#512]
From BUGS.txt. Not sure if it's still valid.
https://github.com/bcpierce00/unison/blob/1cca790ae8290026d5a5cd93bc36fa60a3093e8f/src/BUGS.txt#L18-L24
https://github.com/bcpierce00/unison/blob/1cca790ae8290026d5a5cd93bc36fa60a3093e8f/src/BUGS.txt#L91-L107

**Comment by gdt** [comment]
"feedback" in this case means that I'd like to see a test report with the most recent release, but my working belief is that this is likely still an issue so it doesn't mean "details or closed in 30 days" like usual.
