### ISSUE TITLE
unison -addversionno Received unexpected header from the server

### ISSUE THREAD

**Issue by fkbreitl** [bcpierce00/unison#52]
Following instructions in
https://unix.stackexchange.com/questions/233504/how-to-use-multiple-versions-of-unison-on-one-system
(How to use multiple versions of unison on one system?)

I have installed unison-all and used

unison -addversionno

to sync a Debian and Raspbian system. But I received this error

Contacting server...
Fatal error: Received unexpected header from the server:
 expected "Unison 2.48\n" but received "bash: unison-2.48: command not found\n", 
which differs at "b".
:

It seems like the same versions are found but misinterpreted as incompatible.

I assume unison could be improved to understands the version number correctly.

I have reported this problem also at

https://unix.stackexchange.com/questions/330870/unison-addversionno-received-unexpected-header-from-the-server

**Comment by alkuzad** [comment]
what do you get on server by using `whereis unison-2.48` and/or `which unison-2.48` ?

**Comment by fkbreitl** [comment]
`which unison-2.48`
`which: no unison-2.48 in (.:/home/...)`

`which unison`
`/home/fkbreitl/local/bin/unison`

`ls -l local/bin/unison`
`lrwxrwxrwx 1 user group 13 Dec 12 20:48 local/bin/unison -> unison-2.48.3`

**Comment by alkuzad** [comment]
This is problem, add version flag adds version number to called binary so
you have to have exactly this binary. Both commands I've gave you should to
return valid binary

16.12.2016 18:07 "Frank Breitling" <notifications@github.com> napisał(a):

**Comment by bcpierce00** [comment]
Remember that you're running these programs via ssh, not directly from a shell on the remote machine.  Maybe you're getting a different PATH this way.

**Comment by fkbreitl** [comment]
It is not clear to me what you suggest for a solution.
However both versions of unison are identical (2.48.3) since I copied it from the client to the server and
`unison -version`
reports correctly
`unison version 2.48.3`.
But the problem seems to arise at the client side by `-addversionno` which reports it incorrectly as 2.48 only.

Moreover, if I rename unison at the server to unison-2.48, it is found and works.
So it seems to me that the version checking by the `-addversionno` option is broken and needs to be fixed.

**Comment by alkuzad** [comment]
addversionno does indeed just add version number to binary that is called
on server. So you can't just have "unison" as binary - you  have to have
"unison-2.48'.

17.12.2016 00:02 "Frank Breitling" <notifications@github.com> napisał(a):

**Comment by fkbreitl** [comment]
I see. That also explains why the Debian package installs a link `unison-2.48 -> unison-2.48.3`.
However, it would be better if unison could chose the best version among those installed based on all version digits and without such links. It should not be too hard to implement.

Otherwise these details need to be documented somewhere including the:
- necessity of these links
- compatibility of versions
- example usage of -addversionno

The `unison -help` entry of `-addversionno` is currently not sufficient for this.

**Comment by alkuzad** [comment]
This is against what Linux administrators would expect. On the other side
links are used widely and known. You can always pass also binary path or
name manually without using addversionno flag.

I understand that this behavior was not clear to you, perhaps you can
contribute to documentation and add more examples? I bet bcpierce00 will be
happy to merge such changes.

17.12.2016 14:05 "Frank Breitling" <notifications@github.com> napisał(a):

**Comment by fkbreitl** [comment]
Ok, I have outlined the points that should be added to the documentation above.

I think bcpierce00 can answer and add them best himself. He can also use my answer from https://unix.stackexchange.com/questions/330870/unison-addversionno-received-unexpected-header-from-the-server .

Thank you and cheers!

**Comment by bcpierce00** [comment]
I improved the -addversionnumber documentation.  Happy to accept a PR if there are other changes that seem useful to the manual.

**Comment by fkbreitl** [comment]
Great, thank you. Its probably taking a while until it appears in my Debian testing.
