### ISSUE TITLE
fsmonitor immediate events considered harmful

### ISSUE THREAD

**Issue by tleedjarv** [bcpierce00/unison#525]
`fsmonitor` implementation makes a distinction and reports some events immediately and queues other events and reports them all together with a max delay of 0.5 seconds. I don't know what are the benefits of this design choice. But today when doing some `fsmonitor` testing on Windows I came across a situation where I think immediate event reporting is not only wasteful but outright dangerous.

Example directory structure:
```
 \ root dir
  |-- subA
  |-- subB
```
The action: Move subB into subA so that `root/subB` becomes `root/subA/subB`.
1. Deletion of `root/subB` gets reported immediately by `fsmonitor`.
2. Creation of `root/subA/subB` gets reported separately, as a non-immediate event (see code extract below).

This is also exactly how Unison synchronizes these changes, with two separate passes.
1. First synchronization. In other replica, `root/subB` is deleted.
2. Second synchronization. In other replica, `root/subA/subB` is created.

This is wasteful because creating `root/subA/subB` means re-transferring all files in it. That could be gigabytes or even terabytes. Had `root/subB` not been deleted yet then the "local copy" shortcut could have been used.

This is dangerous because deletion is completed first, before the creation in new location is even attempted. Even if second synchronization pass does not fail, it may be gigabytes or terabytes to transfer. During all this time the moved dir and all files in it are not usable in the other replica. In a single synchronization pass, Unison always executes deletes in the very end. Here we are dealing with two separate passes, one triggered by the immediate event from `fsmonitor` and the other by the non-immediate event.

The same design is used by inotify-based Linux `fsmonitor` but I have not checked if it is as dangerous.

https://github.com/bcpierce00/unison/blob/aff2e3f05833a41eabbddbb488bff0d766cbc001/src/fsmonitor/windows/watcher.ml#L50-L56

**The fix?**

I am inclined to remove the immediate events mechanism completely. But I am unable to fully judge the impact of the removal as I currently lack the understanding of why this feature exists.

**Comment by gdt** [comment]
Is there reordering going on, or just a division of the event stream by events marked immediate?

Does the 0.5s batching actually matter, or is this about an event being marked as the end of a group?

**Comment by tleedjarv** [comment]
> Is there reordering going on, or just a division of the event stream by events marked immediate?

According to my understanding, both are happening. Events marked immediate are separated from the others and then reported before the others. Depending on the exact moment of time (so, more then 0.5s has passed), the immediates _may_ be reported together with others (trying to recall from memory, didn't check the code to verify this).

> Does the 0.5s batching actually matter, or is this about an event being marked as the end of a group?

The latter, according to my understanding. The intention is to collect as big as possible group of events (the light and quick processing), with a max delay that looks reasonably "real-time" to a human, before reporting the whole thing to the Unison main process (which starts the heavy processing and thus shouldn't be invoked all too often).

**Comment by gdt** [comment]
So you are proposing:
  * drop concept of immediate vs non-immediate
  * henceforth, events will remain in order
  * keep some notion of batching, with a bunch of events being reported after some reasonable time, long compared to inter-event times, reasonable (but not necessarily short) compared to human expectations.   e.g. If I save a file and unison runs in 5s, that's IMHO totally ok.   0.5s seems like it is too fast, but if no real trouble, I don't object  - just thinking out loud

If that's what you mean, sounds good to me.

**Comment by tleedjarv** [comment]
Spot on, that's what I'm proposing. Additionally, this batching is required to keep move/rename events together because those are reported by OS as (at least) two separate events.

Sounds good to me as well. I'm just wondering, what was the initial idea behind the "immediate" events. I think there is a clear correctness issue right now and it must be fixed either way, but will some feature be lost in the process? (not that I can see by reading the code, at least) If no objections come in then I'll create a PR at some point.

**Comment by tleedjarv** [comment]
I have confirmed that the same issue exists on Linux and that the patch fixes the issue on all platforms.
