### ISSUE TITLE
Permission denied [mkdir(C:\WINDOWS\system32\config\systemprofile\.unison)]

### ISSUE THREAD

**Issue by cdadmin** [bcpierce00/unison#54]
I need to run unison with a user that does not have permissions to this folder.  Is it possible to specify a different folder?

**Comment by alkuzad** [comment]
Unison uses home folder for that and it seems you are using special system
account instead of your own. Can you use standard account with home in
c:\users?

20.12.2016 19:59 "cdadmin" <notifications@github.com> napisał(a):

**Comment by cdadmin** [comment]
Not really, the process is being kicked off by a web server.  Even if a local user is created and the web server is running as that user, it is still defaulting to that location instead of that users home directory.

**Comment by duncansmart** [comment]
@cdadmin This is not a Unison issue. Presumably you are using IIS, therefore you need to set the AppPool to load the user profile: https://blogs.msdn.microsoft.com/vijaysk/2009/03/08/iis-7-tip-3-you-can-now-load-the-user-profile-of-the-application-pool-identity/
