### ISSUE TITLE
build regression in 2.51.4_rc3: DEP_INCLFLAGS

### ISSUE THREAD

**Issue by olafhering** [bcpierce00/unison#541]
2e12fc4f41b39ca9a5e501d7df5c2c33a75d3b95 builds

eae947ee7a6076592ec711e4c090438ab6ead211 fails

````
....
[  100s] + cd unison-2.51.4_rc3
[  100s] + make UISTYLE=gtk2 NATIVE=true
[  100s] Makefile.OCaml:106: *** empty variable name.  Stop.
[  100s] error: Bad exit status from /var/tmp/rpm-tmp.ynZ1UD (%build)
````
It seems `DEP_INCLFLAGS::=$(INCLFLAGS)` is not understood by some variants of make, such as `make-1:3.82-24.el7` as included in [ScientificLinux_7](https://build.opensuse.org/package/show/Archiving:unison:next/unison) and a few others.

**Comment by gdt** [comment]
Was autoclosed by linked merge, but please speak up if not ok now.
