### ISSUE TITLE
Show progress when using copythreshold (GUI feature request)

### ISSUE THREAD

**Issue by evert-mouw** [bcpierce00/unison#549]
I'm using copythreshold and copyprog(rest) to invoke rsync for new files. (I'm not even sure if this is still advised; maybe the in-build transfer is up to speed nowadays?) I profit from the bandwidth control provided by rsync, but a disadvantage of using the copythreshold option is that the GUI doesn't show the progress in the "Status" column.

Maybe it would be possible to show the progress, e.g. by intercepting the output of `rsync --progress` ? This is a minor feature request, and please disregard this if the build-in transfer speed is nowadays on par with rsync (in that case the documentation might be updated).

![Screenshot_2021-06-21](https://user-images.githubusercontent.com/9323697/122751175-f1d65580-d27e-11eb-8c6a-068f222ad77f.png)

**Comment by gdt** [comment]
I added "discuss" because I think it's a good question if this external rsync mechanism should still exist.   I'd rather remove that than fix up how it works, if there's no good reason to keep it.  Perhaps you could experiment with not using it?

**Comment by evert-mouw** [comment]
Sorry for not replying earlier. Maybe next week I can test it over a gigabit LAN connection. Unfortunately my normal 2nd location has a very unstable internet connection, which makes it unsuitable for testing.

**Comment by gdt** [comment]
Could you test performance?   The null hypothesis is now that external rsync is not useful, and I'm more inclined to remove it that to make it work better.

(Please post results in plain text.)

**Comment by gdt** [comment]
Performance reports to unison-users are still wanted.

Especially with deprecation of external rsync, this has been moved to https://github.com/bcpierce00/unison/wiki/Feature-Requests
