### ISSUE TITLE
macOS 11.4 says "unison.app" is damaged and can't be opened

### ISSUE THREAD

**Issue by sunk818** [bcpierce00/unison#553]
<img width="447" alt="m 2021-06-23 at 9 11 56 AM" src="https://user-images.githubusercontent.com/6989799/123132081-2f63eb80-d403-11eb-8b54-73a09a6a58b3.png">

I downloaded the following file: Unison-v2.51.4_rc3.ocaml-4.12.0.macos-10.15.app.tar.gz

**Comment by gdt** [comment]
I see this also., on macOS 10.13.

Please file a bug with apple that the popup doesn't give any useful information :-)

It would be helpful to know if previous builds has this issue or not.   I don't use the GUI at all personally, and we seem to end up fighting with apple on various security schemes, identified developer sort of rules, etc.

**Comment by gdt** [comment]
See the wiki.  This is  known issue.

https://github.com/bcpierce00/unison/wiki/CI-Binary-instructions

**Comment by gdt** [comment]
And by known issue, I mean a bug in macOS.

**Comment by sunk818** [comment]
> And by known issue, I mean a bug in macOS.

You know this better than I do. I'm very inept and mostly unsuccessful at compiling anything for macOS.

I couldn't find the bin on the latest Unison.app RC3, but I do see it in the production version and was able to at least run the command line successfully. It already had the x so I didn't have to allow it to be executable: v2.51.3

Thanks for your help and clarification.

**Comment by gdt** [comment]
What I meant by mac bug, is that if mac has some security policy that is different than normal POSIX, and a program runs afoul of that, the user should be told something about security policy and pointed to rules and not given some vague damaged allegation.   I don't think unison is special here.   But it seems apple thinks it is a feature.
