### ISSUE TITLE
ocaml version to avoid "input_value: bad bigarray kind" fail? 

### ISSUE THREAD

**Issue by gicking** [bcpierce00/unison#58]
hello all,

unfortunately I have to bring up the topic up ocaml version issue again: My setup consists of 2x PC running Ubuntu 16.04LTS with a NAS running Raspbian Jessie. Most of the time syncing via Unison works great (thanks Benjamin!). However, for some files the operation fails consistently with "lost connection to server" and "input_value: bad bigarray kind". I understand that this might be due to a version mismatch of ocaml...?

For all I know the versions of Unison are identical:

- on both PCs unison-gtk was installed via Software Center from the standard repository. Output of "unison-gtk -version" is "unison version 2.48.3"
- on raspberry I installed via apt-get. Since the "stable" repository contains "2.40.102" I had to install from the "testing". Output of "apt list --installed unison" is "unison/testing,now 2.48.3-1 armhf [installed]"

In the past days I did a bit of digging and found that not only do the unison versions have to match, but also the ocaml versions. Since (again to best of my knowledge) ocaml is not installed on any of my machines, I assume the lib is statically linked into unison...? 

First of all, **how can I determine the respective ocaml versions on the different machines**? And, as a second step, how can I solve this issue, preferably without installing ocaml and then recompiling unison on each machine?

One remark: if my above assumption is correct, wouldn't it be better if the apt repositories contained a unison binary which uses dynamic libs? Then the issue could be solved within apt, i.e. keeping the system update mechanism intact.

In any case thanks a lot for your support!

Regards, 
Georg

**Comment by bcpierce00** [comment]
I’m afraid installing OCaml and recompiling Unison is probably your best bet for getting things working reliably.  Fortunately, both of these steps are usually pretty easy.

     - Benjamin

**Comment by mikepierce** [comment]
This may be relevant. I've noticed that it avoids some issues if you compile into bytecode instead of native code on ARM processors. So on your Raspberry try including the line `Native=false` in the Unison Makefile. See [this stackoverflow question](http://stackoverflow.com/questions/28400175/unison-issue-on-banana-pi-running-lubuntu) for details.

**Comment by gicking** [comment]
hello Benjamin, hi Mike,

thanks a lot for your fast and helpful response! 

But before I proceed, do you know which ocaml version is linked to the unison-gtk version in the Ubuntu 16.04LTS standard repository in the Software Center (see screenshot)? Because I would very much prefer to only compile the version on the Pi. Thanks a lot in advance!

Georg

![screenshot](https://cloud.githubusercontent.com/assets/10261226/21961855/4fc34fa6-db15-11e6-84ce-13be53662ba1.png)

**Comment by gicking** [comment]
hello again,

according to the [Debian package list](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=ocaml), the latest stable ocaml version for Raspian Jessie is 4.01.0-5. However, according to this [response](https://bugs.launchpad.net/ubuntu/+source/unison/+bug/1568459/comments/7) by Benjamin the issue occurred between 4.02.1 and 4.02.2 --> probably no use to compile unison manually - at least not with ocaml from the stable repository...? Does that mean I have to compile both ocaml and unison from source? If yes, do you have a instruction for doing so?

I have to admit that I am well out of my comfort zone, here. Sorry to bother you with this and thanks in advance!

Regards, Georg

**Comment by bcpierce00** [comment]
I believe there should be binary installers for OCaml for any major platform.  Once OCaml is installed, if you don’t care about a GUI, then building Unison is just a matter of unpacking the tar file and doing “make text”.

    - B

**Comment by gicking** [comment]
hi Benjamin,

thanks for your fast response! But may I bother you with two more questions? 

1) I would very much like to minimize manual installs in order to keep the update mechanism via apt intact. Thus I prefer installing OCaml via apt using the "testing" branch for version >= 4.02.2 (see screenshot). Is this also an option? If yes, I assume I required command is 
"sudo apt-get -t testing install ocaml=4.02.3-9+rpi1"...? 

![grafik](https://cloud.githubusercontent.com/assets/10261226/22007597/37cda382-dc74-11e6-8860-31b57a58a402.png)

2) again, trying to minimize the manual installs, I would like to avoid compiling on all PCs. However, since I don't know the details, do you know if/how I can determine the used OCaml versions, or which version is linked into unison 2.48.3 from the official Ubuntu 16.04LTS repository? 

3) and, last but not least, a general question. If such a dependency exists, wouldn't it be better to have the official unison packages (e.g. for apt) use dynamic linking to a OCaml lib instead of static? This should avoid people like me from bothering you...  ;-) 

Again, for your support thanks a lot in advance. I really appreciate your help! 

Regards, Georg

PS: it's such a shame that this issue exists! Because apart from it, IMHO unison is virtually perfect for syncing and allowed me to realize exactly what I wanted. Hope there will be a better solution than manual recompiling in the future.

**Comment by pmlt** [comment]
I'm also bumping into this issue and it is rather frustrating because I have to ensure unison works on three platforms with very different build processes (macOS, Windows, and Ubuntu Trusty).

Though I'm a seasoned developer, I'm not familiar with OCaml development. Is there a way to evolve the unison codebase in such a way as to avoid having to match compiler versions? I've tried researching the issue and it seems to be related to the way data is serialized and deserialized for transfer over the wire? Would you say that migrating to a platform-independent serialization format would solve the issue, or is there another obstacle to fixing this bug? I'd be willing to help.

This software is truly excellent but this bug seriously hinders its distribution. Keep up the good work!

**Comment by gicking** [comment]
hello Philippe,
well, since I'm a mere user and not an experienced developer, I suppose that question goes to Benjamin. Your proposal sounds plausible to me, but certainly means a HEAP of work... Instead why not make unison in the apt repositories dynamically link to ocaml. At least then the dependency is clear and (rather) easy to resolve.
 
In the meantime I tried (and failed) to compile unison on a Pi from source. Dunno what exactly I did wrong, but apparently I dist-upgraded my Pi from the "testing" repository -> now all SW is an unstable version :-(  Just now I am now restoring from the last backup. 

Now my last idea is to downgrade to unison 2.40 on all machines, hoping that this solves the ocaml incompatibility issue.
@Benjamin: did you make any essential changes between 2.40 and 2.48 which would make downgrading a stupid idea? Thanks a lot in advance!

Regards, Georg

**Comment by gicking** [comment]
hello,
on the RasPi manually replacing /usr/bin/unison-2.48.3 (installed via apt) with a binary I found on [https://www.devolve.net/blog/2015/10/13/unison-dependency-hell/](https://www.devolve.net/blog/2015/10/13/unison-dependency-hell/) seems to have solved the issue for me  :-)    
I'll mark this thread as "solved", even though this option probably is likely not ideal

Anyway, thanks again for all your great support! Have a nice day :-)

Regards, Georg

**Comment by gicking** [comment]
see above -> issue solved (for me)

**Comment by bcpierce00** [comment]
> @Benjamin <https://github.com/Benjamin>: did you make any essential changes between 2.40 and 2.48 which would make downgrading a stupid idea? Thanks a lot in advance!

There were some improvements in features, but very little in core functionality.  If 2.40 is working well for you, there’s no big reason to move up.

    - Benjamin

**Comment by bcpierce00** [comment]
> Though I'm a seasoned developer, I'm not familiar with OCaml development. Is there a way to evolve the unison codebase in such a way as to avoid having to match compiler versions? I've tried researching the issue and it seems to be related to the way data is serialized and deserialized for transfer over the wire? Would you say that migrating to a platform-independent serialization format would solve the issue, or is there another obstacle to fixing this bug? I'd be willing to help.
> 
> This software is truly excellent but this bug seriously hinders its distribution. Keep up the good work!
> 

Yes, this silly issue has caused a surprising amount of trouble.  Fortunately, it was a one-time thing: different OCaml versions will inter-operate just fine as long as both are from either before or after the breaking OCaml library change.  

I don’t see a lot of point in trying to fix Unison so that the OCaml version doesn’t matter.  If people are going to be compiling a new version (or using a new version that somebody else compiles), they can just use a new enough OCaml compiler.  

    - B
