### ISSUE TITLE
[Question] Syncing between NTFS & exFAT: any potential issues?

### ISSUE THREAD

**Issue by lolilolicon** [bcpierce00/unison#583]
Hello, I stumbled on unison while looking for a simple file synchronization software with an easy-to-use GUI for a non-technical Windows user. Unison seems to fit our purposes. However, before jumping in, I want to be sure we have the correct setup.

We want to keep 2 copies of the same data (documents, media) on two identical hard drives, in case one of them dies suddenly. Normally, we would just format the drives both as NTFS. But we also want interoperability with macOS, and therefore will want to use exFAT for at least one of the hard drives.

If we choose to format one drive NTFS and the other exFAT, will this cause any trouble for unison?

(Naturally, you may ask, why not use exFAT on both drives? Indeed, unless NTFS does have some advantage over exFAT for primarily Windows usage? which I would suppose the case given its official status... I apologize for my ignorance.)

**Comment by tleedjarv** [comment]
There shouldn't be any issues. You may want to set the `fat` preference to true but I don't know if that's even needed here.

**Comment by gdt** [comment]
Please use the mailinglist for questions.  The tracker is only for bug
reports.

See https://github.com/bcpierce00/unison/wiki/Mailing-Lists

**Comment by lolilolicon** [comment]
> See https://github.com/bcpierce00/unison/wiki/Mailing-Lists

Sorry, I mailed unison-users+subscribe@seas.upenn.edu, but got no reply. What's up?

**Comment by lolilolicon** [comment]
Actually, I'm going to use NTFS on both disks, and use an extra exFAT-formatted flash stick for file transfer from macOS.
I'm convinced NTFS is more robust & less prone to data corruption. Better safe than sorry, right?
Besides, I like symmetry :)

**Comment by gdt** [comment]
Sorry about the mailinglist issues.  Benjamin checked and it seems ok.  If you'd like, please followup with me by mail at gdt at lexort.com about how your list subscription isn't working and we can try to debug it.
