### ISSUE TITLE
OS X App version contains "damaged" executable

### ISSUE THREAD

**Issue by jefftemplon** [bcpierce00/unison#584]
The most recent version (2.51.4) of the "app" download contains a "damaged" executable.  When I unpacked it and tried to run it, OS X says "this Application is damaged" and offers to "move it to the bin".

The 2.51.2 version of the OS X release contains a working app.

**Comment by jefftemplon** [comment]
The package with this problem contains the string "10.15.app".  This may be related to the issue, as I am running MacOS 11.5.2.  It remains a mystery why the 2.51.2 Zip file doesn't have this problem.

**Comment by gdt** [comment]
Please see  https://github.com/bcpierce00/unison/wiki/CI-Binary-instructions and #469, and if this report is a dup of #469 close it.  If not, please provide more details and explain why it's not a dup.

If you can provide a patch to fix the actual problem, that would of course be very much appreciated.

**Comment by jefftemplon** [comment]
Hi,

It is almost a duplicate, the piece that is new is that it also does not work in MacOS 11.x series.  Thanks for illustrating the workaround, and I agree with your assessment that signing cltool is the way to go.
