### ISSUE TITLE
Spotted a typo-type tiny bug

### ISSUE THREAD

**Issue by lolilolicon** [bcpierce00/unison#585]
https://github.com/bcpierce00/unison/blob/2bd6bfca666d41d7e48e2dda405d9363f4529969/src/update.ml#L1063

`%s / %s` should be changed to `%s/%s`, <code>\`%s/%s'</code> or `'%s/%s'` depending on your style.

**Comment by gdt** [comment]
After a few minutes, please either review or test the fix just did in 586.  I don't like to merge my own PRs without some review, even if they are just a change in a string.
