### ISSUE TITLE
Support DOS device paths "\\?\Volume{GUID}" & UNC paths in Windows

### ISSUE THREAD

**Issue by ropery** [bcpierce00/unison#588]
In Windows, a volume mounted at `X:` can be addressed in a format called “[DOS device paths](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths)”, like these:

    \\?\X:
    \\?\Volume{b75e2c83-0000-0000-0000-602f00000000}\

The `\\?\Volume{GUID}\` form is useful, because it allows us to reliably identify a volume regardless of its drive letter.

I use Unison on Windows to keep removable disks in sync. For now, I’m using this in my profile:

    root = Y:\
    root = Z:\

I would like to be able to address them by GUID instead:

    root = \\?\Volume{b75e2c83-0000-0000-0000-602f00000000}\
    root = \\?\Volume{2c83b75e-0000-0000-0000-2f6000000000}\

Why is this desirable? Because although we can [assign a “permanent” drive letter](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-drive-letter) to removable volumes, the association is stored in the registry of the particular Windows system and therefore open to change, etc.; also, this assigned letter is not _guaranteed_ to this volume only: it gets the next unused letter if the assigned letter is in use. With GUID, however, we can be certain that we’re addressing the correct volume.

A further consideration if this gets implemented: in the GUI, displaying the roots (replicas) as GUID would be very human-unfriendly. Instead, it should display the filesystem Lable and/or the drive letter, e.g., `Seagate1 (X:)`; or maybe allow customization, via a syntax like `root = <root> -> <name>`.

PS For example, [TrueCrypt](https://superuser.com/a/465741) supports accessing a disk drive using volume ID instead of a drive letter in Windows.
PS [Example: get drive letter from volume GUID using `wmic`](https://superuser.com/a/1163674).

PPS Currently, trying to use `root = \\?\Volume{GUID}\` results in `Fatal Error: Cannot find canonical name of root directory //?/Volume{GUID}/ (Invalid argument)`. (Notice that `\`s are changed to `/`s.)

https://github.com/bcpierce00/unison/blob/470d36a47681e05f55802134eae9f80bf29a7798/src/fspath.ml#L257

**Comment by gdt** [comment]
If this  happens, seems like there should be a section that assigns names to GUID values (names sort of like you'd put in GPT fields) and then let  those names be used for roots.   E.g. FRED-1863-1 to match a label on a 2T external drive.    Arguably this should be an OS feature, but...     So I see this as a valid feature request awaiting a PR.

**Comment by tleedjarv** [comment]
There are a few bugs that prevent using these paths. I will open a PR fixing those bugs but it will have to receive testing by Windows users to be considered for inclusion in the next bugfix release (or even in next feature release).

Making this smooth and user-friendly is another task.

**Comment by tleedjarv** [comment]
@ropery if you'd like to test the fixes done in path processing, you can grab the latest dev builds at https://github.com/bcpierce00/unison/actions/runs/2973908569 (pick a package suffixed "-publish"). Nothing has been done in GUI so it may look ugly, but everything should actually work now.

Even though the builds should be stable, they will upgrade the archive files and you won't be able to downgrade again without rescanning. If you're going to reuse your existing archives then make sure you have a backup.

**Comment by gdt** [comment]
Feedback timeout.  Feel free to file a new issue with a repro recipe with 2.53.1 or newer.

**Comment by mircsicz** [comment]
I'ld like to give it a try (as of [#893](https://github.com/bcpierce00/unison/issues/893)) but it seems there's noting available at https://github.com/bcpierce00/unison/actions/runs/2973908569 as it's all timedout...

**Comment by tleedjarv** [comment]
This feature was included in release 2.53.0.
If you need to upgrade and get the latest binaries for 2.53.2 then you may have a look at https://github.com/bcpierce00/unison/actions/runs/4566969951 (these have some fixes on top of the actual release binaries which were retracted).

**Comment by mircsicz** [comment]
I'm on 2.53.2, so I probably only need to rewrite my prf file...

THX
