### ISSUE TITLE
SSH sync fails when there are changes on the server

### ISSUE THREAD

**Issue by mvglasow** [bcpierce00/unison#59]
### Setup
Workstation running Unison 2.48 on Ubuntu MATE 16.04 (from Ubuntu repo).
Server running Unison 2.48 (among others) on Raspbian (installed from Raspbian testing repo).

### Steps to reproduce
1. Set up sync between client and server like this:
```
# Unison preferences
label = Home dir
root = /home/me
root = ssh://me@fileserver//srv/file/me
sshargs = -C
addversionno = true
dontchmod = true
perms = 0
path = Documents
path = Pictures
```
2. Run sync once (using the GTK GUI) to ensure both roots are in sync.
3. Change a file on the workstation, then run sync and propagate changes.
4. Change a file on the server, then run sync and propagate changes.

### Expected and actual behavior
I’d expect changes to be detected and reported in each sync run, and to be propagated when I click **Go** in the GUI. This works correctly for (3). In step (4), changes are shown correctly (one file changed on the server). However, when I click **Go**, I get the following error:
```
Fatal error

Lost connection with the server.
```
Since both discovery of changes and client-to-server propagation work, I would rule out basic issues such as incorrect path names, SSH connectivity issues or a version mismatch. I suspect this to be a bug in Unison.

**Comment by bcpierce00** [comment]
If this is still a problem for you, please reopen the issue.  It would help to have a trace from running with "-debug all", so we can see what's happening.
