### ISSUE TITLE
-logfile not working

### ISSUE THREAD

**Issue by MystaraTheGreat** [bcpierce00/unison#594]
Unison 2.51.3 (with ocaml 4.11.1).  Logfile is not being created via command line.  See transcript below:

root@fileserver:~/temp# ls
directory1  directory2
root@fileserver:~/temp# unison directory1 directory2 -logfile log.log
Unison 2.51.3 (ocaml 4.11.1): Contacting server...
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
root@fileserver:~/temp# ls
directory1  directory2
root@fileserver:~/temp# unison directory1 directory2 -logfile ./log.log
Unison 2.51.3 (ocaml 4.11.1): Contacting server...
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
root@fileserver:~/temp# ls
directory1  directory2
root@fileserver:~/temp# unison directory1 directory2 -logfile /root/temp/log.log
Unison 2.51.3 (ocaml 4.11.1): Contacting server...
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
root@fileserver:~/temp# ls
directory1  directory2
root@fileserver:~/temp# unison directory1 directory2 -logfile=/root/temp/log.log
Unison 2.51.3 (ocaml 4.11.1): Contacting server...
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
root@fileserver:~/temp# ls
directory1  directory2

**Comment by gdt** [comment]
It would  be helpful if someone else could read the docs and try to use -logfile and comment.   It seems surprising if the `-logfile` arg is totally broken, but I've been surprised before.

**Comment by gdt** [comment]
This is stale, more than 30 days without a followup, and was 2.51.3 which is old.

Works for me, but beware that what goes in the logfile isn't much.  The startup line that used to appear in ~/.unison/unison.log appears in the path I gave to -log.

**Comment by gdt** [comment]
Feel free to reopen with up-to-date debugging data, and I suggest using ktrace/ktruss/whatever to see if unison is trying to open/write.

**Comment by tleedjarv** [comment]
Works for me. Couple of pointers:
 - if logfile argument is a relative path then it is relative to `UNISON` directory (by default `~/.unison`)
 - if you can, try also with 2.51.5; there was a change/fix for logfiles but I don't remember if it was in 2.51.3 or not
