### ISSUE TITLE
unison & thunderbird profile: very slow even when only tiny changes

### ISSUE THREAD

**Issue by pjotrek-b** [bcpierce00/unison#595]
I'm not sure if this is related to issue #65 " Add --inplace option for syncing e.g. 15G files with small changes, trading away safety for speed", but it behaves similarly:

I'm using Unison to synchronize Thunderbird profile folders between notebooks and stationary machines. With a ~14GB sized profile, it takes a very long time. The green "100% done" arrows appear very slowly for each file. Even if only 1 new plaintext email has been received.

I haven't monitored anything (net traffic, local I/O, ...) yet, but it shows 50-100MB/s transfer speeds.

The sync works like a charm, but I'd be curious if you could tell me why it is so, and if I could improve the speed?

Thanks in advance! :smile:

**Comment by gdt** [comment]
Please use the mailinglist for questions.  The tracker is only for bug
reports.

See https://github.com/bcpierce00/unison/wiki/Mailing-Lists

**Comment by pjotrek-b** [comment]
Roger that :)
Wasn't aware of that, especially since #65 sounded very similar.

Sorry.

**Comment by gdt** [comment]
I'm trying to manage the issue list with limited time, and while your question was sort of a bug report, it was more of a "please explain why".   I don't want to have open issues that do not capture a bug (failure to meet specs) or what I consider a valid feature request; a large list means that people, myself included, lose track.  And there's also the elephant in the room: github culture discourages mailinglists, and that leads to issue trackers being used for things that traditionally have been on lists.  Perhaps more importantly, there are a lot of people on the user's list, and often one of them has something helpful to say.   So I really did not mean "go away", I meant "join the list and bring it up for discussion there".

Given #65, I'd say that what you are seeing is not a bug, and I had already retitled #65 to be a feature request.   Stepping way back, it also strikes me that a program choosing to have a frequently-modified multi-GB file is likely to interact badly with many things (including backup, remote filesystems, and system crashes and power failures) and perhaps you should file a bug with thunderbird that their data representation doesn't play well with others.

**Comment by pjotrek-b** [comment]
I totally understand! :smile:
Never perceived your reply even close to "go away" - I also just wanted to let you know that I try to adhere to posting rules, therefore my apology.

Thanks for taking the time for this detailed and friendly and insight-providing response!
I'll follow your suggestions.

Have an amazing day and thanks again!
