### ISSUE TITLE
How to terminate unison gently when I'm logging-out (xsession shuts down)?

### ISSUE THREAD

**Issue by ardabro** [bcpierce00/unison#599]
I use unison for a couple of years in a simple model synchronizing desktop and laptop to one central repository on raspberry pi. My primary OS is Debian. Recently (since upgrade to bullseye?) I noticed a significant increase of "Fatal error: Warning: the archives are locked." events, and I have to manually delete lock file on my central server. After a small investigation, I realized that the problem reproduces in 100% when I'm logging out from my x-session (instead of shutting down the machine). 
I have no idea why it started to happen, but seems that unison, in this case, is brutally killed rather than requested to terminate.
BTW: I'm starting it from my .xsessionrc: 
(nice -n18 ionice -c2 -n7 unison <profilename>  &>/dev/null &)
What can I do about it? Is the way I'm starting unison correct? (I used it for last couple of years without issues).

**Comment by gdt** [comment]
(This seems like a Debian issue, not a unison bug.)

Please use the mailinglist for questions.  The tracker is only for bug
reports.

See https://github.com/bcpierce00/unison/wiki/Mailing-Lists
