### ISSUE TITLE
Folder convention - tar file should unpack to unison-m.nn.oo

### ISSUE THREAD

**Issue by Knusper** [bcpierce00/unison#60]
The 2.48.4 tarfile contains a tree `src/`, while 2.48.3 contained `2.48.3/`.  The latter format for the file tree in the archive should be preferred, i.e. `unison-m.nn.o`, where `m` is major version, `nn` is minor and `o` indicates bugfix versions.

**Comment by bcpierce00** [comment]
Also reported elsewhere...

**Comment by bcpierce00** [comment]
@brabalan Have we fixed it?

**Comment by brabalan** [comment]
I downloaded https://github.com/bcpierce00/unison/archive/2.48.4.tar.gz and I'm seeing the right thing (it expends to unison-2.48.4/…). Am I missing something?
