### ISSUE TITLE
unison: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by unison)

### ISSUE THREAD

**Issue by kanevbg** [bcpierce00/unison#601]
Hello,

let me first note that I have read the readme, the issues already reported and the wiki and did not found solution.

I got the binaries from github for unison 2.51.4, for windows (10) x64 and I am getting error

> unison: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by unison)
![unison-glibc_2 27-not-found](https://user-images.githubusercontent.com/11477130/142011858-a9f3d9fc-3aa5-45b7-807f-a0f21921c12a.jpg)

Please let me know why is this and what is the way to solve or work-around.

**Comment by gdt** [comment]
This is not a bug in unison, but something about the intended environment of the CI build and the environment of your machine.  Note that at https://github.com/bcpierce00/unison/wiki/CI-Binary-instructions the instructions are missing.

I thought there was a bug open that said that the CI builds didn't document their environments, but there wasn't, so I created #602.

Please feel free to ask on the  mailinglist about this; somebody there might have insight.
