### ISSUE TITLE
File corruption on macOS

### ISSUE THREAD

**Issue by ascherer** [bcpierce00/unison#606]
My configuration
* **unison version 2.51.4 (ocaml 4.12.0)**
* **macOS 10.13.6** and **macOS 11.6.1**
* intermediate medium **Kingston CANVAS Select Plus 32GB MicroSD**

More often than not I get
* **new** files not being detected and skipped on sync; this can be fixed with `-fastcheck=false`
* **binary** files (e.g., **dmg** packages or Affinity graphics files) corrupt after sync

**Comment by gdt** [comment]
Can you explain what your roots are, and if you are doing local from system to microsd (in some kind of card reader?), or via ssh, and if ssh, what the microsd has to do with it?

Are you running the watcher?  If so, please stop and let's debug without first.

You said "corrupt", but if you transport them and cmp -l, how different are they?    Is the corruption from mac to external, external to mac, or mac to mac via ssh? 

Please run hardware diagnostics including memory tests on both of your machines.  I have not seen other reports like that, which doesn't prove anything of course.   But it's enough to make me suspicious.

Overall, you are going to have to do a lot more detailed debugging if there is hope of fixing this.

**Comment by ascherer** [comment]
On both my Mac Minis (**Late 2014** running **macOS 10.13.6** at work and **M1 2020** runnig **macOS 11.6.1** at home) I have a `Download` directory where I store all external packages for installed software et al. I sync these `Download` hierarchies locally between the computers via the intermediate MicroSD card. Here are the two (different) profiles, first `Download-wkm.prf`
```
root = /Users/scherer/Downloads
root = /Volumes/NO NAME/Downloads

dontchmod=true
fat = true
perms=0

log = true
logfile = /Users/scherer/.unison/unison.log

ignore = Path .localized
ignore = Path .DS_Store
ignore = Name */.DS_Store

ignore = Path Projekte
ignore = Path Texturenpaket
ignore = Path Wacom

ignore = Name Tools/macOS High Sierra/Xcode*
```
and next `Download-home.prf`
```
root = /Users/andreas/Downloads
root = /Volumes/NO NAME/Downloads

fat = true

log = true
logfile = /Users/andreas/.unison/unison.log

ignore = Path .localized
ignore = Path .DS_Store
ignore = Name */.DS_Store

ignore = Path Adobe CS6
ignore = Path Affinity
ignore = Path Huion
ignore = Path Texturenpaket

ignore = Name MacTeX/GnuPG*
ignore = Path Tools/macOS High Sierra
```
----
A recent case for file corruption:

On Wednesday evening, I downloaded the latest version of the **Skype dmg** into the `Download` hierarchy on the **Mac at home** and synched it with the MicroSD card with `unison Download-home.prf`. The **dmg** file was perfectly fine for installation on **macOS 11.6.1**.

On Thursday morning, I synched the **Mac at work** with `Download-wkm-prf` and tried to install **Skype** on **macOS 10.13.6**. This failed both from the harddrive and from the MicroSD card with an error message from the Mac Installer (“package file damaged”). I downloaded the same **dmg** from the Skype homepage again to the `Downlioad` hierarchy on the harddrive and successfully installed the software from there. Then I synched with `Download-wkm.prf` to the MicroSD card. From there, the package file could also be opened with the Mac Installer.

On Thursday evening, I synched my **Mac at home** with `Download-home.prf` and Unison reported “the roots were changed in identical ways”, i.e., it claimed that the **dmg** file was identical to the version of Wednesday.

----
A recent case for an ignored **new** file:

On November 26, I downloaded **LibreOffice 7.2.3** to the `Download` hierarchy on my **Mac ar work** and installed it. And I deleted **LibreOffice 7.2.2** from `Download`. Then I synched with the MicroSD card.

In the evening, I synched my **Mac at home** with the MicroSD card and Unison suggested to delete **LibreOffice 7.2.2**, but did _not_ suggest to copy the new **LibreOffice 7.2.3**. After I manually copied the file with `cp -a` from the MicroSD card to the **Mac SSD**, Unison reported that “both roots were changed in identical ways”.

**Comment by gdt** [comment]
It would still help to "cmp -l" a file that wasn't copied right.  You might do "diff -ur" after sync and examine it, as you go.

Thanks, that helps a lot.  You might also get a new uSD and see if this stops.   It is hard for me to guess how unison could be doing a bulk copy with the wrong contents.   I suppose you could run this with dtrace and look at the system call contents.

I am unclear on the watcher, because I do not use it, and do not use the GUI.  But please make sure that is not running, and  if you are not invoking unison on this profile as a run-then-exit operation, please see if you can shift to that.  This case is probably more amenable to using dtrace or similar, as when it happens you can redo it with debugging and the volume of debug data will not be so vast.

It would be good for you to join the users list if not and ask if anyone else has seen similar issues.

**Comment by ascherer** [comment]
I'll try to apply your suggestions when the issue occurs again.

**Comment by ascherer** [comment]
I've set up a new transfer MicroSD (**Intenso MicroSDHC Class 10 32GB**). It seems to have a different **vfat** filesystem configuration by default, because this MicroSD auto-mounts with the name **INTENSO** (both on Linux and on macOS), while the **Kingston** had **NO NAME** (mac) resp. a **UUID** (Linux). Unfortunately, I still get problems with _large_ `zip` files:
```
Unison 2.51.4 (ocaml 4.12.0): Contacting server...
Looking for changes
Reconciling changes                           

andreas/D...   INTENSO/D...       
changed  ---->            Designer Workbook/whittler.zip  [f] 
changed  ---->            Designer Workbook/winecellar.zip  [f] 

Proceed with propagating updates? [] y
Propagating updates


Unison 2.51.4 (ocaml 4.12.0) started propagating changes at 10:48:50.96 on 04 Dec 2021
[BGN] Updating file Designer Workbook/whittler.zip from /Users/andreas/Downloads/Affinity to /Volumes/INTENSO/Downloads/Affinity
[END] Updating file Designer Workbook/whittler.zip
[BGN] Updating file Designer Workbook/winecellar.zip from /Users/andreas/Downloads/Affinity to /Volumes/INTENSO/Downloads/Affinity
Failed: Destination updated during synchronization
The contents of file Designer Workbook/winecellar.zip have been modified
  (if this happens repeatedly on a file that has not been changed, 
  try running once with 'fastcheck' set to false)
Failed [Designer Workbook/winecellar.zip]: Destination updated during synchronization
The contents of file Designer Workbook/winecellar.zip have been modified
  (if this happens repeatedly on a file that has not been changed, 
  try running once with 'fastcheck' set to false)
Unison 2.51.4 (ocaml 4.12.0) finished propagating changes at 10:51:55.50 on 04 Dec 2021, 184.539 s


Saving synchronizer state
Synchronization incomplete at 10:51:55  (1 item transferred, 0 skipped, 1 failed)
  failed: Designer Workbook/winecellar.zip
```
Both [`whittler.zip`](https://affin.co/whittlerDE) (**512904744 bytes**) and [`winecellar.zip`](https://affin.co/winecellarDE) (**369777366 bytes**) caused the standard archive utility from the **Finder** of macOS (**11.6.1**) to abort with “Error -1: No such process” (`unzip` on the console grokked them fine). Today I downloaded these two files anew and tried to synchronize the MicroSD with a fresh copy.

Running `unison -fastcheck=false` completes the transfer succesfully and with an intact file at the target medium

**Comment by gdt** [comment]
But when they are transferred wrong, and you use cmp -l, what is actually different?  Size?  contents in a lot of places?

**Comment by ascherer** [comment]
That case hasn't occurred with the new chip yet. I'll report on Monday when I try to sync the new MicroSD chip with my **Mac at work**. (Hope for the best, prepare for the worst.)

**Comment by gdt** [comment]
You showed an error message above.   What I mean is every time you sync, run diff -ur and see if it is really synced.   the zip errors are a more complicated error and in debugging the best approach is to inspect intermedate steps whenever that is reasonably easy to do.

**Comment by ascherer** [comment]
Sucess, at least almost. Transfer from the new **Intenso** MicroSD ran better than expected.

However, at least one `dmg` file is not OK, i.e., `AcroRdrDC_2100720099_MUI.dmg` can't be opened due to a “checksum error”:
![Bildschirmfoto 2021-12-06 um 09 39 35](https://user-images.githubusercontent.com/51143/144814728-6560a407-c141-4b55-8751-801b60334c7d.png)

After downloading the `dmg` file from Adobe, `cmp -l` produces more than half a MB of diagnostics:
[AR-cmp-l.gz](https://github.com/bcpierce00/unison/files/7659329/AR-cmp-l.gz)

**Comment by gdt** [comment]
Are you comparing from
 * the mac where you downloaded the file, on the normal disk
 * the uSD, immediately after you synced?
Or did you unmount, and you are comparing on another machine?

If those differ, there are several possibilities:
 * unison wrote the wrong content (and is thus buggy)
 * the mac OS is buggy
 * the uSD is buggy
 * something else

Looking at the cmp -l, it starts at 6324225, which is one byte past 193 32kB chunks.    Perhaps the non-wrong byte happens to match.  The last mismatch is at 6356992, which is 1 byte past 194 32kB chunks.   There are 32647 mismatches, and I would expect that 1 in 256 bytes match randomly, and thus expect 32640.   So this looks like one wrong 32kB chunk ended up in the file.

I would suggest you set up an experiment not using unison, where you create a directory with a dmg, and do
```
cat foo.dmg > /Volumes/uSD/foo.dmg
```
then unmount and remount and cmp, or mount on other machine and cmp.

**Comment by ascherer** [comment]
I guess it's “something else”: This particular `dmg` file came from a download on my **Mac at home** a few weeks ago and had been sync'ed with the **Kingston** MicroSD at that time (without checking with the MacOS installer). On the past weekend, I transferred the complete contents of the **Kingston** MicroSD to the **Intenso** MicroSD with `cp -a`.

Today, I noticed that `unison` added this particular `dmg` file to my **Mac at work** and that the MacOS installer complained about _both_ copies on the MicroSD and on the internal SSD.

After I downloaded a fresh copy to my **Mac at work** and did the `cmp -l`, the next steps all succeeded, i.e., `unison` sync'ed the file correctly to the **Intenso** MicroSD and just moments ago from there to my **Mac at home**. The final copy on the internal SSD can be opened with the MacOS installer just fine.

Moreover, `unison` correctly detected and transferred the latest **LibreOffice** `dmg` both **at work** this morning and **at home** this evening and it also was installed without problems, so the “new file skipped” issue seems to be gone, too.

I tend to begin to blame the **Kingston** MicroSD and its `vfat`/`exfat` file system for the whole hiatus. I'll keep you posted on the next attempts and maybe close this issue later.

**Comment by ascherer** [comment]
It seems to be a clash between **MacOS 10.13.6** and **MacOS 11.6.1** and the `FAT`/`MSDOS` filesystem on the MicroSD in between.

_Yesterday_, I doawnloaded and installed the latest **Skype 8.79.0.95 dmg** on my **Mac at work** and sync'ed it with the MicroSD, followed by a successful `diff -ur`. **At home**, the **Skype dmg** _failed_ to unpack, both after synchronization from my **Mac at home** and from the MicroSD. Downloading a fresh copy of the same **dmg** installed on my **Mac at home**, but showed maasive output from `diff -ur` and `cmp -l`. I sync'ed with the MicroSD again.

_Today_, neither `unison` nor `diff -ur` nor `cmp -l` show _any_ differences between the **Mac at work** and the MicroSD. `Nothing to do: replicas have not changed since last sync.`

**Comment by ascherer** [comment]
I'll pick a new MicroSD chip and try, e.g.,
```
rsync --dry-run -auv --exclude='Projekte' --exclude='Texturenpaket' --exclude='Wacom' --exclude='Tools/AcroRdrDC_*' --exclude='Tools/macOS High Sierra/Xcode*' --exclude='*.DS_Store' ~/Downloads/ /Volumes/INTENSO/Downloads/ | tee rsync.put
```

**Comment by gdt** [comment]
The fact that the file apparently changed from reading the uSD at work and then at home points nearly 100% to this being a mac/uSD bug and not a unison bug.

Two more things to check:
  * after syncing, run md5 or shasum on the downloaded file and the uSD copy, and save results
  * then, unmount the uSD, physically remove it, put it back, and run shasum again
  * on the new machine, run shasum before running unison.

**Comment by ascherer** [comment]
In the evening, the **Skype dmg** has identical `shasum` on all devices **at home**.

**Comment by ascherer** [comment]
It's not `unison`!

Today I downloaded `TorBrowser-11.0.2-osx64_de.dmg` **at work**, sync'ed with the MicroSD and stored the (identical) results of `shasum` for both copies on the **Mac at work** and the MicroSD.

No **at home**, _before_ I do anything with`unison`, I `shasum -c`heck and get
```
% shasum -c /Volumes/INTENSO/TorBrowser.shasum 
shasum: Downloads/Web Browser/TorBrowser-11.0.2-osx64_de.dmg: No such file or directory
Downloads/Web Browser/TorBrowser-11.0.2-osx64_de.dmg: FAILED open or read
/Volumes/INTENSO/Downloads/Web Browser/TorBrowser-11.0.2-osx64_de.dmg: FAILED
shasum: WARNING: 1 listed file could not be read
shasum: WARNING: 1 computed checksum did NOT match
```
