### ISSUE TITLE
Using filenames with % causes crash (with watcher, on macOS)

### ISSUE THREAD

**Issue by leshaker** [bcpierce00/unison#61]
I received the error
```
Fatal error Invalid argument: String.blit / Bytes.blit_string
```
after completing the first run of a local synchronisation on a Mac running 10.11.16 and Unison 2.48.15.

Any ideas?

**Comment by mhw** [comment]
So, I'm running into the same problem on macOS Sierra. I first saw the problem running the precompiled binary of 2.48.15 from http://unison-binaries.inria.fr but I've since installed OCaml 4.04 from homebrew and rebuilt Unison from the latest version of the source code - still the same error.

The error pops up straight after the 'No archive files were found for these roots' window and when the status bar still says 'Looking for changes' with no path name in it.

The odd thing for me is that the error only occurs for some profiles. For example, this profile succeeds:

```
root = /Users/mhw/webs
root = ssh://bigmac//Users/mhw/webs
```

while this gives me the error message

```
root = /Users/mhw
root = ssh://bigmac//Users/mhw

path = webs
```

The odd thing is that if I make a new directory called `/Users/foo` and copy the contents of `pkg` into it on both hosts, Unison will then run happily with a profile in which only the roots are changed (to `/Users/foo`).

Is there a way to get the program to print a backtrace of the call stack where the error occurs?

**Comment by leshaker** [comment]
for me it solved the problem to delete all cache files and run the profile from scratch...

**Comment by mhw** [comment]
Ah, yes - you're right. I found the archive file (the `.unison/ar<hash>` files) that listed the two roots in question, and then deleted (or moved out of the way) the corresponding `.unison/fp<hash>` file. After this the scan was able to run successfully.

I'll dig a bit more and see if I can find the source of the error. I got a backtrace out of Unison by setting `OCAMLRUNPARAM=b` in the environment, but it seems that the lightweight threads implementation is masking the true source:

```
2017-02-15 14:13:00.439 Unison[52182:3097781] Roots are not set on the command line
2017-02-15 14:13:02.553 Unison[52182:3097781] Connecting to beagle-pkg...
2017-02-15 14:13:02.791 Unison[33778:5029231] Calling nonGuiStartup
2017-02-15 14:13:02.888 Unison[52182:3097781] Connected.
Unison failed: Invalid argument: String.blit / Bytes.blit_string
Raised at file "/Users/mhw/src/unison/src/lwt/lwt.ml", line 135, characters 6-13
Called from file "list.ml", line 77, characters 12-15
Called from file "/Users/mhw/src/unison/src/lwt/lwt.ml", line 31, characters 2-37
Called from file "/Users/mhw/src/unison/src/lwt/lwt.ml" (inlined), line 83, characters 17-46
Called from file "/Users/mhw/src/unison/src/lwt/generic/lwt_unix_impl.ml", line 55, characters 6-23
Called from file "/Users/mhw/src/unison/src/lwt/generic/lwt_unix_impl.ml", line 147, characters 6-40
Called from file "/Users/mhw/src/unison/src/main.ml", line 202, characters 6-24
Called from file "/Users/mhw/src/unison/src/main.ml", line 131, characters 4-9
```

**Comment by mhw** [comment]
Ok, so I've had a bit more of a dig and I've found that the problem seems to be caused by a corrupt fingerprint cache file causing the path decompression code to fail. I'm not familiar with the internals of Unison, nor with OCaml. That said, the fingerprint files seem to be made up of chunks, each of which contains (compressed) paths and file information. Based on the trace I get from running against the corrupt fingerprint cache I have, it looks to me as though the file has chunks missing or re-ordered for some reason, suggesting the original problem might be in the code that writes the fingerprint cache.

The line of code that fails is [the first `String.blit` in the `decompress` function](https://github.com/bcpierce00/unison/blob/master/src/fpcache.ml#L54). I've added log statements to show the values of `st`, `i` and `path` just before the call to `String.blit` and also to log the backtrace from the exception. Here's the tail end of it:

```
st: {webs/xxxxxxxxxxxx/xxxxxxxxxxxxxxx/vendor/ruby/1.8/gems/rack-1.2.1/test/spec_content_length.rb}
i: 84
path: {type.rb}
st: {webs/xxxxxxxxxxxx/xxxxxxxxxxxxxxx/vendor/ruby/1.8/gems/rack-1.2.1/test/spec_content_type.rb}
i: 76
path: {deflater.rb}
<>![fpcache] read chunk of 5002 files
st: {webs/xxxxxxxxxxxx/xxxxxxxxxxxxxxx/vendor/ruby/1.8/gems/rack-1.2.1/test/spec_deflater.rb}
i: 89
path: {tip.png}
failed: Raised at file "pervasives.ml", line 33, characters 20-45
Called from file "/Users/mhw/src/unison/src/fpcache.ml", line 57, characters 2-25
Called from file "/Users/mhw/src/unison/src/fpcache.ml", line 96, characters 46-65
Called from file "list.ml", line 77, characters 12-15
Called from file "/Users/mhw/src/unison/src/fpcache.ml", line 145, characters 22-32
Called from file "/Users/mhw/src/unison/src/update.ml", line 1966, characters 2-71
Called from file "/Users/mhw/src/unison/src/update.ml", line 2048, characters 18-66
Called from file "/Users/mhw/src/unison/src/globals.ml", line 127, characters 36-39
Called from file "/Users/mhw/src/unison/src/lwt/lwt.ml", line 75, characters 20-23
```

(some path segments replaced by an equal number of characters).

The section before the `read chunk of 5002 files` log message are files from one directory, while the `tip.png` file and the index just after that log message seem to be referring to a completely different directory. As a result the value of `st` is shorter than the 89 characters expected.

I think that's about as far as I can dig into this, but hopefully that might help someone to track down where the issue might lie.

**Comment by bcpierce00** [comment]
Belated thanks for the detailed reports on this issue!  (Has it come up again?  Obviously, people are having trouble finding cycles to look at it, but if it's a recurring issue that would raise the priority...)

**Comment by iluvcapra** [comment]
I run into this problem as well, from the command line I get:

`Contacting server...
Looking for changes
Invalid argument: String.blit / Bytes.blit_string
Raised at file "pervasives.ml", line 33, characters 20-45
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/fpcache.ml", line 54, characters 2-25
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/fpcache.ml", line 93, characters 46-65
Called from file "list.ml", line 85, characters 12-15
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/fpcache.ml", line 142, characters 22-32
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/update.ml", line 1966, characters 2-71
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/update.ml", line 2048, characters 18-66
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/globals.ml", line 127, characters 36-39
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/lwt/lwt_util.ml", line 26, characters 9-12
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/globals.ml", line 126, characters 2-156
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/update.ml", line 2071, characters 5-404
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/update.ml", line 2052, characters 4-1023
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/update.ml" (inlined), line 2096, characters 2-69
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/uitext.ml", line 700, characters 16-56
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/uitext.ml", line 788, characters 6-90
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/uitext.ml", line 810, characters 19-66
Called from file "/private/tmp/unison-20170716-81206-j4vmhq/src/uitext.ml", line 870, characters 21-43`

**Comment by mmagnus** [comment]
Confirmed, the deletion of archives helped. 

Tip. On OSX there are here ` ~/Library/Application Support/Unison`

**Comment by gdt** [comment]
This appears to be an issue with 2.48 with no recent confirmation.

**Comment by grantx2016** [comment]
I am getting the same issue running unison version 2.51.4 (ocaml 4.12.0):

Looking for changes
Invalid argument: unquote
Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
Called from Fswatch.unquote in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/fswatch.ml", line 148, characters 63-82
Called from Fswatch.parseChanges in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/fswatch.ml", line 460, characters 36-50
Called from Update.findLocal in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml", line 1988, characters 10-49
Called from Update.findOnRoot.(fun) in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml", line 2057, characters 18-66
Called from Globals.allRootsMapWithWaitingAction.(fun) in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/globals.ml", line 127, characters 36-39
Called from Lwt_util.map_with_waiting_action.loop in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/lwt/lwt_util.ml", line 26, characters 16-19
Called from Lwt_util.map_with_waiting_action.loop in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/lwt/lwt_util.ml", line 27, characters 17-23
Called from Globals.allRootsMapWithWaitingAction in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/globals.ml", line 126, characters 2-156
Called from Update.findUpdatesOnPaths.(fun) in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml", line 2080, characters 5-404
Called from Update.findUpdatesOnPaths in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml", line 2061, characters 4-1023
Called from Update.findUpdates in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml" (inlined), line 2105, characters 2-69
Called from Uitext.Body.synchronizeOnce in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/uitext.ml", line 1074, characters 16-56
Called from Uitext.Body.synchronizePathsFromFilesystemWatcher.loop in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/uitext.ml", line 1133, characters 6-125
Called from Uitext.Body.synchronizeUntilDone in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/uitext.ml", line 1181, characters 8-47
Called from Uitext.Body.start in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/uitext.ml", line 1357, characters 21-43

**Comment by gdt** [comment]
@grantx2016 Thanks  for confirming with up-to-date code; I have reopened the issue.

**Comment by grantx2016** [comment]
I am new to unison so don't have much to offer as to the root cause. However, I can confirm that the presence of a simple illegal character '%' in any filename is what is causing unison to crash with the output as I previously provided. I've done a few tests and it fails the same way each time.

**Comment by gdt** [comment]
That is a lot to offer about cause!   Can you specify what OS/etc.?  It looks like Unix, but the /tmp pathnames are odd - but perhaps that's your test setup.

You said "illiegal character %" in a filename.  Presumably you mean in a data file that is being synced, not in a profile filename.   Why do you say % is illegal?   As far as I know it is not prohibited by POSIX.  Or is this a windows rule?

On a pair of systems, I just added a file "foo%" and ran unison and the file was synced to the other (macOS->NetBSD) and then deleted it and synced again and it was all fine.

**Comment by grantx2016** [comment]
> That is a lot to offer about cause! Can you specify what OS/etc.? It looks like Unix, but the /tmp pathnames are odd - but perhaps that's your test setup.

1. I provided full hostname info at the bottom of the error code above. In short, macOS Catalina.
1. Yes, that was a test setup.

> You said "illiegal character %" in a filename. Presumably you mean in a data file that is being synced, not in a profile filename. Why do you say % is illegal? As far as I know it is not prohibited by POSIX. Or is this a windows rule?

You are right. It is not a forbidden char so, to me at least, indicates there really is a bug in at least my installation of unison.

> On a pair of systems, I just added a file "foo%" and ran unison and the file was synced to the other (macOS->NetBSD) and then deleted it and synced again and it was all fine.

I did some more tests as follows:
1. When I add "foo$" it syncs to the other  folder expected.
2. When I changed the "$" to "%" it did not sync (or crash).
4. When I removed the "%", it synced "foo" to the other folder as expected.
3. When I add a new file named "foo%" it did not sync (or crash)
5. When I then add an ".md" extension to create "foo%.md" the same crash occurred with output as below.
6. If I re-run unison after the crash, "foo%" will sync to the other folder. 
7. If I then delete "foo%" it crashes again with output similar to below.

My current gut feel is that there is something wrong with the file system watcher on my macOS. I don't know anything about this stuff so sorry I cannot offer any real technical assistance.

---
Invalid argument: unquote
Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
Called from Fswatch.unquote in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/fswatch.ml", line 148, characters 63-82
Called from Fswatch.parseChanges in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/fswatch.ml", line 460, characters 36-50
Called from Update.findLocal in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml", line 1988, characters 10-49
Called from Update.findOnRoot.(fun) in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml", line 2057, characters 18-66
Called from Globals.allRootsMapWithWaitingAction.(fun) in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/globals.ml", line 127, characters 36-39
Called from Lwt_util.map_with_waiting_action.loop in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/lwt/lwt_util.ml", line 26, characters 16-19
Called from Globals.allRootsMapWithWaitingAction in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/globals.ml", line 126, characters 2-156
Called from Update.findUpdatesOnPaths.(fun) in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml", line 2080, characters 5-404
Called from Update.findUpdatesOnPaths in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml", line 2061, characters 4-1023
Called from Update.findUpdates in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/update.ml" (inlined), line 2105, characters 2-69
Called from Uitext.Body.synchronizeOnce in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/uitext.ml", line 1074, characters 16-56
Called from Uitext.Body.synchronizePathsFromFilesystemWatcher.loop in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/uitext.ml", line 1133, characters 6-125
Called from Uitext.Body.synchronizeUntilDone in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/uitext.ml", line 1181, characters 8-47
Called from Uitext.Body.start in file "/private/tmp/unison-20210625-4341-d2kld6/unison-2.51.4/src/uitext.ml", line 1357, characters 21-43

**Comment by gdt** [comment]
Can you run unison with the watcher?   (I don't use the watcher anywhere, and I don't use the GUI.)

Can anyone try to reproduce on a non-mac system that uses the watcher?

It seems like we should retitle this to be about the watcher only, and, for now, maybe macOS specific.

**Comment by grantx2016** [comment]
The results I provided were done with the watcher running and not using the GUI. I have since set it up without the watcher and running a cron job instead and the issues no longer occur (e.g. foo% now syncs). That seems to suggest the watcher is the issue. Unfortunately I only have macs so can't test on anything else.

**Comment by tleedjarv** [comment]
The issue @grantx2016 is seeing is not the same as the original issue reported here. @grantx2016 is seeing #338 and that is confirmed to be an issue with the watcher.

The original issue here is most likely the version-compatibility issue that is no longer relevant (but still actual for users of older versions) with the release of 2.52.0.
