### ISSUE TITLE
unison-fsmonitor not found on remote.

### ISSUE THREAD

**Issue by HolaYang** [bcpierce00/unison#613]
I got error message below while using unison sync remote things with `repeat = watch`:
`Fatal error: Server: No file monitoring helper program found`.
I specify `-servercmd` in my profile to specify the `path/to/unison` on remote. But I wondering if it is because I did not specify anything anything about `unison-fsmonitor` to tell the server where `unison-fsmonitor` is. It there any params for this ? And whtat's is principle unison looking for file monitoring helper program??

**Comment by gdt** [comment]
Please use the mailinglist for questions.  The tracker is only for bug
reports.

See https://github.com/bcpierce00/unison/wiki/Mailing-Lists
