### ISSUE TITLE
Windows CI broken, apparently cygwin

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#614]
An example is https://github.com/bcpierce00/unison/runs/4602017360?check_suite_focus=true

This seems to be a cygwin issue.

I put on the build tag, even though I don't have any reason to think this is a bug in unison.

**Comment by tleedjarv** [comment]
This seems to be the underlying issue: https://github.com/ocaml/setup-ocaml/issues/361

**Comment by gdt** [comment]
This bug seems fixed.

(As the continuing windows CI troubles  seem not about unison, I'm not going to open issues for them.)
