### ISSUE TITLE
On Linux, unison randomly deletes files issues

### ISSUE THREAD

**Issue by lieh1203** [bcpierce00/unison#616]
Hi,
I make the two-way file synchronization for the directory of name is "uploads" between the two machines, machine A is product server and machine B is disaster recovery server, usually no users will access web server of the machine B, also there is no operation to delete files in the system. The system has been online for more than a year, but recently I find some files have deleted randomly in this directory on every months. I think problem is on Unison, becuse only Unison is listening to this directory, so I exclude other softwares problems.

default.prf file config on the below

A machine：
root = /app/appcis/uploads/
root = ssh://cisapp@IP of Machine B//app/appcis/uploads/
batch = true 
maxthreads = 300
owner = true
group = true 
perms = -1 
fastcheck = false 
rsync = false 
sshargs = -C 
xferbycopying = true 
confirmbigdel = false 
log = true
logfile = /app/appcis/unison-2.51.2/unison.log

B machine：
root = /app/appcis/uploads/
root = ssh://cisapp@IP of Machine A//app/appcis/uploads/
batch = true 
maxthreads = 300
owner = true
group = true 
perms = -1 
fastcheck = false 
rsync = false 
sshargs = -C 
xferbycopying = true 
confirmbigdel = false 
log = true
logfile = /app/appcis/unison-2.51.2/unison.log

unison.sh file config of both machines on the below
#/bin/bash
src="/app/appcis/uploads/" 
/app/appcis/inotify-tools-3.14/bin/inotifywait -mrq -e create,delete,modify,move $src | while read line; do
/app/appcis/unison-2.51.2/bin/unison -servercmd=/app/appcis/unison-2.51.2/bin/unison
echo -n "$(date +%F-%T) $line" >> /app/appcis/inotify-tools-3.14/inotify.log
done

I am searching for a long time on net. But no solution.
Thanks, Any help would be appreciated.

**Comment by gdt** [comment]
Please use the mailinglist for questions and help request.  The
tracker is only for bug reports.

See
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists


In this case, you haven't shown evidence that there is a bug in unison.   On the list, I think people will give you advice on how to start monitoring to obtain this evidence.   If there does turn out to be evidence that there is a unison bug, certainly an issue is welcome.
