### ISSUE TITLE
Empty lockfile created when watching

### ISSUE THREAD

**Issue by acsysch** [bcpierce00/unison#620]
I'm syncing 2 directories between 2 local LAN-connected computers. Unison is launched via the cmdline using the appropriate profile and appending -repeat watch. I'm using the current version 2.51.5 on Windows. Directories are correctly synced until 1 file is changed where unison exit w/ the error code 3 and following log:
__Unison_ 2.51.5 (ocaml 4.12.0) finished propagating changes at 10:18:08.44 on 06 Jan 2022, 0.239 s_
_Synchronization complete at 10:18:08  (1 item transferred, 0 skipped, 0 failed)_
_Fatal error: Warning: the archives are locked._  
_If no other instance of unison is running, the locks should be removed._
_The file PATH\unison\lk98eb2f on host NAME should be deleted_
_Please delete lock files as appropriate and try again._

The lock file exists but is empty. Re-launching unison after deleting the lock file is successful. There is no other instance of unison running. So, why are such lock files created and how can eliminate the problem ?

**Comment by gdt** [comment]
You haven't explained where your unison profile dir is (in particular, if it is on a remote filesystem and shared).

Please try to reproduce without -repeat/watch.

**Comment by acsysch** [comment]
The unison profile is local. Also, the lock files are created after a while, typically when an update is detected or when the partner system becomes unavailable (off the network), so reproducing the problem w/o -watch wouldn't make sense.

I finally "fixed" the problem by using the -ignorelocks option, but I still don't understand why the lock files are being created in the first place.

**Comment by gdt** [comment]
Turn on debugging and save the logs.   It sounds like this is a real bug and it would be good to chase it down.

**Comment by tleedjarv** [comment]
Once the builds are finished, please grab a debug build from https://github.com/tleedjarv/unison/actions/runs/1713997704 (you get only the .exe so keep all .dll-s and everything else you already have) and use `-debug update -debug lock` to see if you can figure out what is going on.

You should see output like this:
```
[update] Trying to lock archives...
[lock] Acquiring lock PATH/lka53afb5c15d3f06d4a660672fc8c841c
[update] Trying to unlock archives...
[lock] Releasing lock PATH/lka53afb5c15d3f06d4a660672fc8c841c
```

Do note that seeing the "Releasing lock" output in the log does not mean that deleting the lock file actually succeeded. It is important to check by yourself if the file really was deleted when you see this line in the log.

**Comment by acsysch** [comment]
Hello,
Where can I find the Windows EXE-file ?

**Comment by acsysch** [comment]
Sorry, I guess I found it here: https://github.com/tleedjarv/unison/suites/4977029892/artifacts/145274171

**Comment by acsysch** [comment]
I redit the test but:
- the error does not reappear
- there's no additional logging although I used '-debug update -debug lock' and the unison executable is about double the size of the official windows release
- I noticed from the logs that this debug-version is based on ocaml 4.12.1, while the official Windows release is based on ocaml 4.12.**0**. I don't know whether that has any effect

**Comment by tleedjarv** [comment]
No, the 4.12.1 vs 4.12.0 does not play any role here (shouldn't).

Do you still use the -ignorelocks option? That may intervene with the test.

**Comment by acsysch** [comment]
No, ignorelocks isn't used. I'll keep an eye on this the next few days and let you know

**Comment by tleedjarv** [comment]
You say that there's no additional logging. `-debug update` should produce a lot of output even with the release version. Can you post the exact cmdline you are using? (ok to hide paths and hostnames)

**Comment by tleedjarv** [comment]
One more thought. The `-debug` options output to the console/terminal, not to the logfile. You may have to redirect outputs to a separate file or view them directly at console/terminal.

**Comment by acsysch** [comment]
That's an important remark, as I launch the program from a batch file. I guess I can't redirect the console output to the same logfile as it is locked by unison, right?
The cmd issued is: 
unison MyProfile.prf -repeat watch -debug update -debug lock -logfile %Log%
To get the console output, should I extend that to:
unison MyProfile.prf -repeat watch -debug update -debug lock -logfile %Log% 1> debug.log

**Comment by tleedjarv** [comment]
Yes, correct. (You can also redirect to the same logfile but you'll probably get unreadable overlapping)
The debug output is produced on stderr, I think, so you may have to use 2> debug.log

**Comment by acsysch** [comment]
No, there aren't 2 copies running. 
When debug logging is enabled, the problem does not arise. As soon as debugging is off, the problem is back. So, there must be some **timing issue**.
Furthermore, the problem only occurs when syncing a local Dropbox-folder w/ a remote (non-Dropbox-connected) folder. This folder also contains the unison subfolder which however is excluded from syncing (the unison log is written to another directory). Using the -ignorelocks option lets me avoid stopping the sync-operation which is ok for me. 
As far as I'm concerned, you can close the case. Thanks for helping me out w/ the debug option which is really great although not sufficiently documented in the manual where only few options are mentioned.

**Comment by gdt** [comment]
It would be great if you could figure out what it takes to make this fail a little more and to file a new bug with the details.   In what you describe above, there is the debug log issue, probably watcher, one root being dropbox, the other root being remote, and the .unison directory being in one or the other of those.   I wonder which aspects are necessary to trigger, and that might help figure it out.  You might also try ktrace/ktruss.  But I concur that closing this makes sense, as it seems to take very rare cirucmstances to trigger.    I will close, as at this point I think you startting a fresh bug now that your thoughts are organized would be more useful.  That's not meant as criticism; it's the nature of debugging to start out not undertanding much of anything and then gradually understand more and more until the bug is found.
