### ISSUE TITLE
Error in deleting directory causes repeated assertion failures

### ISSUE THREAD

**Issue by pjowers** [bcpierce00/unison#63]
Summary:
  Unison failed to remove a directory after a rename operation. This appeared to result in the archives being out of sync with the disk. Unison then crashed each time it ran until I manually deleted the directory that unison had failed to delete.  Normal operation then resumed.
Attached:
  Used profile (Sync.prf) and unison log file.
Configuration:
  Unison 2.48.4 compiled with OCaml 4.02.1 running on linux mint 17.2 as client
  Unison 2.48.4 binaries for windows downloaded from https://www.irif.fr/~vouillon/unison/ running on windows 10 as server
  Native client using attached profile Sync.prf via OpenSSH 6.6. Server (win10) running latest cygwin64 and unison windows native binaries (ie. not using cygwin).
  Client log file also attached.
Details:
  User renamed directory "2017_01_25" to "2017_01_25 - Long Tailed Tit".
  Unison responded as shown in the log file:
UNISON 2.48.4 started propagating changes at 14:15:44.69 on 25 Jan 2017
[BGN] Copying 2017_01_25 - Long Tailed Tit from /home/mispy/Pictures to //MJP-Images/D:/Magda/Pictures
Shortcut: copied D:/Magda/Pictures/2017_01_25 - Long Tailed Tit/IMG_0533.JPG from local file D:/Magda/Pictures/2017_01_25/IMG_0533.JPG
Shortcut: copied D:/Magda/Pictures/2017_01_25 - Long Tailed Tit/IMG_0539.JPG from local file D:/Magda/Pictures/2017_01_25/IMG_0539.JPG
Shortcut: copied D:/Magda/Pictures/2017_01_25 - Long Tailed Tit/IMG_0541.JPG from local file D:/Magda/Pictures/2017_01_25/IMG_0541.JPG
Shortcut: copied D:/Magda/Pictures/2017_01_25 - Long Tailed Tit/IMG_0542.JPG from local file D:/Magda/Pictures/2017_01_25/IMG_0542.JPG
Shortcut: copied D:/Magda/Pictures/2017_01_25 - Long Tailed Tit/IMG_0543.JPG from local file D:/Magda/Pictures/2017_01_25/IMG_0543.JPG
Shortcut: copied D:/Magda/Pictures/2017_01_25 - Long Tailed Tit/Long Tailed Tit IMG_0541.tif from local file D:/Magda/Pictures/2017_01_25/Long Tailed Tit IMG_0541.tif
[END] Copying 2017_01_25 - Long Tailed Tit
[BGN] Deleting 2017_01_25 from //MJP-Images/D:/Magda/Pictures
Failed: Error in deleting:
Directory not empty [rmdir(D:/Magda/Pictures/2017_01_25)]
UNISON 2.48.4 finished propagating changes at 14:15:49.70 on 25 Jan 2017
Synchronization incomplete at 14:15:49  (1 item transferred, 0 skipped, 1 failed)
  failed: 2017_01_25
UNISON 2.48.4 started propagating changes at 14:15:50.84 on 25 Jan 2017
[BGN] Copying 2017_01_25 from //MJP-Images/D:/Magda/Pictures to /home/mispy/Pictures
Uncaught exception File "/home/phil/Downloads/Unison/src/copy.ml", line 1007, characters 17-23: Assertion failed
Raised at file "/home/phil/Downloads/Unison/src/lwt/lwt.ml", line 126, characters 22-23
Called from file "/home/phil/Downloads/Unison/src/lwt/generic/lwt_unix_impl.ml", line 102, characters 8-23
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 490, characters 2-113
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 556, characters 38-66
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 718, characters 6-47
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 756, characters 6-125
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 804, characters 8-47
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 870, characters 21-43

UNISON 2.48.4 started propagating changes at 14:16:05.17 on 25 Jan 2017
[BGN] Copying 2017_01_25 from //MJP-Images/D:/Magda/Pictures to /home/mispy/Pictures
Uncaught exception File "/home/phil/Downloads/Unison/src/copy.ml", line 1007, characters 17-23: Assertion failed
Raised at file "/home/phil/Downloads/Unison/src/lwt/lwt.ml", line 126, characters 22-23
Called from file "/home/phil/Downloads/Unison/src/lwt/generic/lwt_unix_impl.ml", line 102, characters 8-23
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 490, characters 2-113
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 556, characters 38-66
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 718, characters 6-47
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 756, characters 6-125
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 804, characters 8-47
Called from file "/home/phil/Downloads/Unison/src/uitext.ml", line 870, characters 21-43

  Please note: a similar renaming operation completed successfully and may be seen in an earlier part of the log file.

  These failures continued each time unison was restarted (cron job) until I spotted the error and manually deleted the directory ("2017_01_25") on the windows machine.  It was empty at the time. At the end of the log file the result can be seen - unison recovers, suggesting that the archives state
 may have been the problem.

[unisonlog.txt](https://github.com/bcpierce00/unison/files/732359/unisonlog.txt)
[syncprf.txt](https://github.com/bcpierce00/unison/files/732373/syncprf.txt)

**Comment by bcpierce00** [comment]
I think this is fixed in newer versions of Unison.

**Comment by pjowers** [comment]
Thanks, will update.
