### ISSUE TITLE
Decide on pruning old ocaml support

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#653]
Unison currently supports ocaml 4.01 to 4.13 and seems to work on pre-release versions of 4.14 and 5.   Starting with 2.52.0, it will no longer be necessary to have matching ocaml versions, so part of the motivation for building with old ocaml (accomodating updates on old systems) will no longer apply.   See https://github.com/bcpierce00/unison/wiki/ocaml-versions for discussion.

There are pending changes to use GTK3 instead of GTK2.  GTK2 is unmaintained, and even GTK3 is "old stable".  It seems that lablgtk for GTK3 does not build with 4.01.

Besides GTK3, support for old ocaml clutters the code.

Therefore, after 2.52.0, and probably after confidence that a 2.52.n version is stable with no major isssues relative to 2.51.x, we should decide on a new minimum ocaml version for Unison.    In addition, we should understand if "you must have lablgtk 3 installed" is effectively an ocaml version requirement for those that wish to build the GUI.

**Comment by gdt** [comment]
Possibilities include:
 - require >= 4.05
 - require >= 4.08
 - require >= 4.09 implicitly for lablgtk3 (but that is very unclear)

I'm omitting moving to 4.11, as while that will surely happen eventually, this is about the next change, and it seems obvious to me that moving to >=4.11 in a few months is too aggressive.

**Comment by gdt** [comment]
Discussion on unison-hackers@ please; this sort of doesn't belong in the issue tracker but I wanted to have it on the record and to have something to point to.

**Comment by gdt** [comment]
The draft plan is 4.08, because lablgtk3 works with that.  Discussion still welcome on unison-hackers.  Merging version requirement changes is on hold until 2.52.1, happening in 2-6 weeks.

**Comment by gdt** [comment]
The major outliers from 4.08 seems to be:
  * perhaps very old RHEL/etc., but they also stay with old unison, so I think that's ok.  They'll just be stuck at 2.52.1 unless they also want to build ocaml before they build unison.
  * FreeBSD ports is at 4.06.  I emailed the maintainer and have not heard back.

If there are reasons other than those two, please explain.

**Comment by gdt** [comment]
We have decided: 4.08 is the new minimum.

**Comment by bcpierce00** [comment]
FWIW all this seems reasonable to me. 

       - Benjamin
