### ISSUE TITLE
Error when accessing macOS platform unison on non-macOS platform

### ISSUE THREAD

**Issue by johnpark82** [bcpierce00/unison#67]
This error seems to be caused by installing the unison executable in 
```/usr/local/bin/unison ```
instead of 
```/usr/bin/unison```
because of macOS's rootless mode.

**Non-macOS platform ----- (ssh) -----> macOS platform**

`` `
non-macOS $ ssh account @ macOS bash
unison

`` ``

If you run unison, it looks like you are browsing to / usr / bin rather than looking for an executable in / usr / local / bin.

**Comment by alkuzad** [comment]
@johnpark82 what error exactly ?

**Comment by johnpark82** [comment]
Proliant is Linux and johnpark82-MBP is a MacBook. So I am now in proliant trying to connect to johnpark82-MBP and sync to unison.

The following error occurs.

When I run unison by bash connecting with ssh for error debugging, I can not find unison installed in / usr / local / bin / unison.


 **johnpark82  proliant    ~  $  unison proliant_johnpark82-MBP.prf**

```
Contacting server...
bash: unison: command not found
Fatal error: Lost connection with the server
```

 **johnpark82  proliant    ~  $  ssh johnpark82-MBP bash**

```
> uname -a
Darwin johnpark82-MBP 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
unison
bash: line 2: unison: command not found
which unison
/usr/local/bin/unison -version
unison version 2.48.4
exit
```

MacOS The Darwin kernel is now in root-less mode, and the problem is that external programs are changing their default installation path to / usr / local / bin.

Unison When you synchronize, you will need an option to specify the location of the remote unison.

**Comment by alkuzad** [comment]
unison uses non-login shell so you can't use login shell to verify that unison is available. Check if adding /usr/local/bin to PATH in /etc/profile works.

**Comment by johnpark82** [comment]
I solved the problem.

In ssh remote shell mode, it appears that you can only see the PATH defined in the ~ / .bashrc file before the following syntax:

**vi ~/.bashrc**
```
  3 # System-wide .bashrc file for interactive bash(1) shells.
  4 if [ -z "$PS1" ]; then
  5    return
  6 fi
  7
```

Then, I've changed it 
```
  1 PATH=$PATH:/usr/local/bin:
  2
  3 # System-wide .bashrc file for interactive bash(1) shells.
  4 if [ -z "$PS1" ]; then
  5    return
  6 fi
```

It worked so well :)

http://stackoverflow.com/questions/940533/how-do-i-set-path-such-that-ssh-userhost-command-works

In a distribution like Ubuntu, this bashrc seems to be the default. It was an issue arising from my ignorance. Thank you for your response.

**Comment by alkuzad** [comment]
@johnpark82 oh, funny to know that what files bash reads in non-login mode is distribution dependent - on centos ~/.bashrc will not be consumed, this is why i had to use profile.

**Comment by brabalan** [comment]
An alternative fix could be to use the `servercmd` preference in your profile.

> **servercmd xxx**
>    This preference can be used to explicitly set the name of the Unison executable on the remote server (e.g., giving a full path name), if necessary.

**Comment by johnpark82** [comment]
@brabalan That's what I was searching. Thanks
