### ISSUE TITLE
Close result window for visual diff tools

### ISSUE THREAD

**Issue by mzuther** [bcpierce00/unison#68]
Hi!

I'm a long-time user of Unison.  Most often, I use a diff tool with a GUI such as meld:

    diff = meld --label="Local <-> Remote"

When showing the diffs, obviously meld opens its GUI and I can do the merging. However, when I leave, there is still an empty window left open.  This displays the results for a command line diff utility, but in my case it is superfluous (and a bit annoying when I have to do a lot of diffing).

I propose adding a new option `diff-ui` that runs the command, but does not open a result window.  Another idea would be to auto-close the result window, but I think that might easily mislead users in certain situations.

Thanks,

Martin

**Comment by bcpierce00** [comment]
Happy to accept a PR if someone wants to implement this.

**Comment by tleedjarv** [comment]
This is perhaps not a complete fix but a very simple patch is
```diff
diff --git a/src/uigtk2.ml b/src/uigtk2.ml
index 194be63..9ec50f4 100644
--- a/src/uigtk2.ml
+++ b/src/uigtk2.ml
@@ -3775,7 +3775,7 @@ lst_store#set ~row ~column:c_path path;
           initGlobalProgress len;
           startStats ();
           Uicommon.showDiffs item.ri
-            (fun title text ->
+            (fun title text -> if text <> "" then
                messageBox ~title:(transcode title) (transcode text))
             Trace.status (Uutil.File.ofLine i);
           stopStats ();
```

If this seems like an acceptable patch then I'm happy to open a PR.
