### ISSUE TITLE
Summary windows doesn't get focus

### ISSUE THREAD

**Issue by mzuther** [bcpierce00/unison#69]
Hi!

When you do a synchronisation with Unison and some files weren't synchronised, a summary window is opened.  This is great, but the summary window should get the focus.  Right now, you have to either use the mouse to close this window or, in order to use the ESC key, Alt-Tab away from Unison and then Alt-Tab back .  Could you please fix this?

Thanks!

Martin

**Comment by hlovdal** [comment]
This is very dependent on which window manager you are using and focus stealing settings. What are you using?

**Comment by mzuther** [comment]
I'm not sure whether I have this problem in Windows 7, but I'm certainly having it on Linux Mint 18 (Cinnamon).

**Comment by tleedjarv** [comment]
This has a very simple fix.
```diff
diff --git a/src/uigtk2.ml b/src/uigtk2.ml
index 194be63..e8b0381 100644
--- a/src/uigtk2.ml
+++ b/src/uigtk2.ml
@@ -2550,7 +2550,7 @@ let twoBoxAdvanced
 let summaryBox ~parent ~title ~message ~f =
   let t =
     GWindow.dialog ~parent ~border_width:6 ~modal:true ~no_separator:true
-      ~allow_grow:false ~focus_on_map:false () in
+      ~allow_grow:false ~focus_on_map:true () in
   t#vbox#set_spacing 12;
   let h1 = GPack.hbox ~border_width:6 ~spacing:12 ~packing:t#vbox#pack () in
   ignore (GMisc.image ~stock:`DIALOG_INFO ~icon_size:`DIALOG
```

I am happy to open a PR but I don't know if this is the correct way to do it. It must have been set to `false` for some reason. This is the commit: https://github.com/bcpierce00/unison/commit/17b77d0aea88883f2070f56e437c3e332f2276ad#diff-60533c2c386d33e32010448882b4d4338c30126000385333d19ca27604dc80e2L2615-R2617
