### ISSUE TITLE
Support Bitcoin/Lightning donations

### ISSUE THREAD

**Issue by micressor** [bcpierce00/unison#693]
I don't like paypal at all, but would love to donate to this project.

**Comment by gdt** [comment]
Currently, I don't see the project as having a way to accept donations at all.  I realize there is some notion of donations on the upenn site, but I don't understand the details.   Affiliation with a fiscal sponsor charity org is a  blocking issue to accepting donations (particularly in the brave new world of US tax law about virtual currencies), and then we'd be able to take what the org can process.
