### ISSUE TITLE
not seeing or syncing ACL permission changes

### ISSUE THREAD

**Issue by jmcisvt** [bcpierce00/unison#704]
I have two Samba file servers setup to use Windows ACLs. Unison is running on both. It seems to be working well for file syncronization but it isn't picking up on permissions changes. For example on a Windows computer if I deny a user read rights to a file or a folder on one file server, the change doesn't sync to the other server. Nothing happens. I've tried running unison with -repeat watch and manually.

**Comment by gdt** [comment]
Please use the mailinglist for support questions.
https://github.com/bcpierce00/unison/wiki/Mailing-Lists

For bug report guidance, please read:
https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests

And perhaps help test
https://github.com/bcpierce00/unison/pull/359
