### ISSUE TITLE
Don't recommend 2.51.3 for production use.

### ISSUE THREAD

**Issue by gbdrbob** [bcpierce00/unison#713]
I recently spent over an hour troubleshooting why a windows client wouldn't sync with a linux server because I followed the recommendation that 2.51.3 "[is the version of unison recommended for production use](https://github.com/bcpierce00/unison/releases/tag/v2.51.3)." 

That version has a fatal bug that prevents the windows binary release from syncing ([#419](https://github.com/bcpierce00/unison/pull/419))

I think it may be time for Unison to update the version you recommend as "production ready"

**Comment by gdt** [comment]
Release notes are accurate when they are written and then they age.  2.51.3 was the right choice in fall of 2020.

It is normal in open source that the proper release to use is the most recent formal release (meaning the most recent release that is not labeled alpha/etc.).  The 2.52.0 release notes say that everyone should be upgrading:  https://github.com/bcpierce00/unison/releases/tag/v2.52.0.

I think the mailinglist and https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests are  both clear that the recommendation is the most recent formal release, and I don't know how to be clearer about it.

Sorry you had a bad time, but I just can't see anything to fix here.
