### ISSUE TITLE
Feature request: keys to force all conflicts in to one direction or the other

### ISSUE THREAD

**Issue by tralce** [bcpierce00/unison#716]
Current setup:
Dual-booted system, sync files with unison in linux, reboot into windows and change some things, sync, and lots of conflicts show up in auto mode. That's what it should do. 

I'd love to be able to press a key that forces all conflicts in one direction or the other, a one-key equivalent of holding down > or < until I run out of conflicts.

**Comment by gdt** [comment]
Please bring this up on the mailinglist; it seems like you are doing something that shouldn't be happening.

I'll leave this open pending discussion of whether this is a good accomodation or dangerous, and relationship of value to both effort to implement and additional complexity.

**Comment by tleedjarv** [comment]
I don't think there is any enhancement needed.

Please look in the manual for preferences `prefer` (and `preferpartial`). You may also be interested in `force` (and `forcepartial`).

If you are using the GUI, just select all the rows and the change of direction will be applied to all selected rows.

If you are using the text version, you can hit `?` at the prompt to get help for the commands. It is possible to apply commands to many items at once. Unfortunately, it seems not well documented (#421).
