### ISSUE TITLE
Can't change the default file creation permission

### ISSUE THREAD

**Issue by petardo1** [bcpierce00/unison#718]
Hi,
I'm an unison newbie.

I'm trying to sync:

- root1: /mnt/<share> (NAS cifs mount) 
- root2: /var/samba/<share> (Linux shared folder)

Permissions:

- Root1 permissions: files and folders always have permission 770 (set in fstab: file_mode=0770,dir_mode=0770)
- Root2 permissions: I'm using ACL on my /var/samba/<share> and it is important to get permission 770 from synced updates.

If all files/folders on /var/samba/<share> have permission 770 then there is no problem at all (both root same permission).
At the normal operation that is fine, because all files added through samba share clients generate permission 770.

However when I add files to  the /var/samba/<share> manually (e.g. through sftp), and the resulting permission is other than 770 (e.g. 640), syncing will fail (the mount doesn't accept it).
So I have set **perms=0 and dontchmod=true** in the unison pref.
This setting works fine in the linux->NAS direction.
However when I'm syncing updates in the NAS->Linux direction,
the resulting permission is 600 which destroys my ACL! - I need 770.
I'm not finding any way to have permission other than 600 when NAS->Linux synchronization occurs.
I **can't change the default file creation permission of unison** (Unison 2.52.1).
Any solution?

**Comment by gdt** [comment]
https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
