### ISSUE TITLE
Mac builds not working

### ISSUE THREAD

**Issue by fnordware** [bcpierce00/unison#722]
The last Mac build that would run for me is Unison-2.51.2.OS.X.zip. When I try to run a newer one with a name like Unison-v2.52.1.ocaml-4.09.1.macos-10.15.app.tar.gz I get an error saying "'Unison.app' is damaged and can't be opened. You should move it to the Trash."

I wonder if the code signing it to blame.

**Comment by gdt** [comment]
hhttps://github.com/bcpierce00/unison/wiki/CI-Binary-instructions
ttps://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
https://github.com/bcpierce00/unison/issues/469

**Comment by gdt** [comment]
And see #723; I would like to get a test report before merging a change.
