### ISSUE TITLE
Unicode 2.52.0 fine, 2.52.1 doesn’t run under El Capitan

### ISSUE THREAD

**Issue by thetrial** [bcpierce00/unison#728]
Fyi:

```
Process:               Unison [17821]
Path:                  /Applications/_Tools/Unison.app/Contents/MacOS/Unison
Identifier:            edu.upenn.cis.Unison
Version:               2.52.1 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Unison [17821]
User ID:               502

Date/Time:             2022-05-17 17:45:06.756 +0200
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        802915F2-A418-2A83-2BF6-03959C6D8C7C

Sleep/Wake UUID:       C0C6C066-5D71-43AE-9817-5569DBAEB4EA

Time Awake Since Boot: 35000 seconds
Time Since Wake:       1500 seconds

System Integrity Protection: enabled

Crashed Thread:        9

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x8:
--> 
    __TEXT                 000000010688b000-0000000106a23000 [ 1632K] r-x/r-x SM=COW  /Applications/_Tools/Unison.app/Contents/MacOS/Unison

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/_Tools/Unison.app/Contents/MacOS/Unison
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by gdt** [comment]
You didn't explain how you compiled it.   10.11 is very old, and I am not aware of anyone building and testing unison on that, and I'm really not aware of anyone publishing binaries.

**Comment by gdt** [comment]
Also, please read carefully all of https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests

**Comment by thetrial** [comment]
I took the binary from https://github.com/bcpierce00/unison/releases as before. As said, the version before worked well. I had worked out an error in #328 and from then on, it worked.

**Comment by gdt** [comment]
The binaries built by CI are labeled10.15 because they were built on a 10.15 build host, which is what github provides for CI.   mac does not document that older operating systems will run programs targeted for newer systems.  It's simply a happy accident that previous versions ran on 10.11.   Thus, your problem is not a bug in unison.

You should be able to build it yourself from source.   If you need help please ask on unison-users@.
