### ISSUE TITLE
Selftest failing on Alpine Linux

### ISSUE THREAD

**Issue by ganwell** [bcpierce00/unison#73]
I try to get unison into alpine linux community repos, but I need to selftest to work.

1. I use unison since a more than 6 month on alpine -> no problems
2. When I google it seems that the selftest also fails on other lightwight distros
    -> Maybe due to busybox or musl?

```
Contacting server...
Running internal tests...
fastercheckUNSAFE 1...
Test fastercheckUNSAFE 1 / 2b:
Expected R2 =
  Dir [("x", File "newcontents")]
but found
  Dir [("x", File "bar")]

Fatal error: Self-test fastercheckUNSAFE 1 / 2b failed!

```
I first thought it fails because fastcheckUNSAFE is - well - UNSAFE. I then patched it away, but next test fails.

```
$> unison -selftest
Contacting server...
Running internal tests...
backups 1 (local)...
backups 2...
backups 2a...
Test backups 2a / 4:
Expected R2 =
  Dir [("foo", File "2"); (".bak.0.foo", File "1")]
but found
  Dir [("foo", File "2")]

Fatal error: Self-test backups 2a / 4 failed!
```

Here is the version I am testing: 

https://github.com/ganwell/aports/tree/bug_report/testing/unison

BTW I don't have both marshalling patches active at the same time. I just wanted to show, that I test both. I guess marshalling.patch is the correct one, right?

Unison is a important helper form me since many years. I can help you testing things on alpine, giving feedback or I can even give you a test environment. But I can't learn yet another language :-)

**Comment by bcpierce00** [comment]
It looks like the filesystem is behaving differently on this distro.  Next step would be to try to look at what Unison is doing in these tests and reproduce its behavior manually (by directly manipulating the same files).  OCaml knowledge needed should be minimal, fortunately.

**Comment by gdt** [comment]
Please file a new bug if this is still an issue with the current code.
