### ISSUE TITLE
Problems with Version 2.52.1 in Windows 10

### ISSUE THREAD

**Issue by prof-spock** [bcpierce00/unison#738]
Dear all,

the x86_64 unison-gtk2.exe in version v2.52.1 (OCaml 4.14) does not work in Windows 10, while the previous version v2.52.0 (OCaml-4.12.1) works without a problem.
Is there any explanation for that?

Best regards,
Prof. Spock

**Comment by gdt** [comment]
Please use the mailinglist for support.

https://github.com/bcpierce00/unison/wiki/Mailing-Lists
https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
