### ISSUE TITLE
Memory usage ~0.8kB/file

### ISSUE THREAD

**Issue by leftys** [bcpierce00/unison#74]
Hello!

We use unison for synchronizing two replica web servers. Our filesystem contains about 3M files and unison consumes about 2.5GB of memory for the main process and 0.5GB for the file system watcher (we use -repeat=watch). That is about 0.8kB per file just for the main process, which seems like unnecessarily lot. Because of this, the processes are often killed by OOM killer on our machines. (After which unison can not be started automatically because 'archives are locked' and we have to remove some state files and run again.)

Is there any possibility to fix those memory requirements? It can be replicated by creating a file structure by running a script like this one:
```
for i in `seq 1 50`
do 
  echo $i
  mkdir $i
  for j in `seq 1000`
  do 
    dd if=/dev/zero of=$i/$j.txt bs=1024 count=5 2>/dev/null
  done; 
done
```

Thank you!

**Comment by bcpierce00** [comment]
It would not be easy to reduce the per-file memory requirements, since we have to store a hash of the file contents to be safe.  Best workaround is probably to synchronize the replicas a bit at a time, if you're really limited to less than 2.5Gb per process.
