### ISSUE TITLE
Cannot build on Oracle Linux 8

### ISSUE THREAD

**Issue by Fairlight2cx** [bcpierce00/unison#741]
# make UISTYLE=text
make -C src
make[1]: Entering directory '/tmp/unison/src'
UISTYLE = text
Building for Unix
NATIVE = true
STATIC = false
OSTYPE =
OSARCH = Linux
ocamlopt: ubase/umarshal.ml ---> ubase/umarshal.cmx
ocamlopt -g -I lwt -I ubase -I system -I +unix -I +str -I fsmonitor -I fsmonitor/linux -I system/generic -I lwt/generic -c /tmp/unison/src/ubase/umarshal.ml
File "/tmp/unison/src/ubase/umarshal.ml", line 34, characters 12-30:
Error: Unbound value Bytes.get_int64_be
make[1]: *** [Makefile.OCaml:433: ubase/umarshal.cmx] Error 2
make[1]: Leaving directory '/tmp/unison/src'
make: *** [Makefile:9: src] Error 2

And sadly, this is 1) something which worked last year just fine, and 2) something which is holding up my deployment of new servers, as a build of unison is in my ansible roles...and it does a fresh pull of master from github right before build.

# rpm -qa |grep ocaml
ocaml-srpm-macros-5-4.el8.noarch
ocaml-compiler-libs-4.07.0-3.el8.x86_64
ocaml-4.07.0-3.el8.x86_64
ocaml-runtime-4.07.0-3.el8.x86_64
ocaml-cppo-1.6.4-4.el8.x86_64

That's the latest that was ever available from CentOS before they dropped CentOS 8, from their PowerTools repo.  That has remained constant in my builds since I started.  So if the devkit isn't changing, it would be the unison source itself that's at fault.

This worked a few weeks ago, actually.  I had deployed originally 1-2 weeks ago, and it was building fine, so it's a recent change.

Any chance of a quick fix?  I know -zero- ocaml, so I can't even munge it like I could C code.

**Comment by gdt** [comment]
master not building with ocaml 4.07 is not a bug; that was announced as impending on unison-users, and was in the 2.52.1 release notes.  I second the comment to use tags not master in deployment recipe.

**Comment by Fairlight2cx** [comment]
Fair enough.  How do I pull specifically 2.52.1 with git, please?
