### ISSUE TITLE
copyonconflict fails on windows

### ISSUE THREAD

**Issue by ndemou** [bcpierce00/unison#75]
On windows I get this error when using `copyonconflict`:

```
Failed: Error in renaming C:/adir/.unison.test2.txt..001..1979f4.unison.tmp
   to C:/adir/test2 (copy: conflict on 2017-04-20).txt
The filename, directory name, or volume label syntax is incorrect
```

Note that character `:` is not permitted in windows filenames but it seems to me that unison tries to use it regardless. Here are 5 lines from `files.ml` that seem suspicious to me:

```
      let tm = Unix.localtime (Unix.gettimeofday ()) in
      let rec copyPath n =
        let p =
          Path.addToFinalName path
            (Format.sprintf " (copy: conflict%s on %04d-%02d-%02d)"
```

P.S. Thanks for this great tool

**Comment by bcpierce00** [comment]
Yep, looks like ":" should be replaced with " for" or something similar.  Happy to accept a pull request.

**Comment by ndemou** [comment]
Whoops! Seems fixed on development version. Sorry for not checking in advance.

**Comment by ndemou** [comment]
For any one like me not sure of how to compile unison on windows the easy/ugly/hacky way to fix this is to open unison.exe with a good text editor (notepad++ worked for me), search for "copy: conflict", replace the `:` with a coma and save your changes.

**Comment by bcpierce00** [comment]
Sounds like a fine solution...  :-)
