### ISSUE TITLE
How about a new feature `xferbymoving`?

### ISSUE THREAD

**Issue by goulf-3m** [bcpierce00/unison#758]
Analogous to `xferbycopying`, it avoids transferring.
It will also avoid file copying, thus quickly propagates renaming of large files.
The proposed feature works behind the scene and does not introduce any extra complexity to end users.

**Comment by tleedjarv** [comment]
This is not easy to do. In fact, it is very difficult. Behind the scenes is really only possible for the simplest of the simple cases.

I propose a working solution in #576 which I think does what you are looking for. I will rebase that PR onto the latest version eventually but there are a few PRs in queue before that.

**Comment by gdt** [comment]
I'm closing to close this as mostly a blend of dup with #576 and a bit of  wontfix.
