### ISSUE TITLE
Windows download link in the Wiki

### ISSUE THREAD

**Issue by Peter-Csatlos** [bcpierce00/unison#760]
Hi, I noticed that in the [Downloading Unison section of the Wiki ](https://github.com/bcpierce00/unison/wiki/Downloading-Unison) the Windows download link is not pointing to this repository's releases section, but to a specific file to another user's repository: [Pedrocesarg/VideoCaptureUtility release page](https://github.com/Pedrocesarg/VideoCaptureUtility/releases).

Is this intentional? To be frank is is quite weird and concerning.
The zip file's contents look like the latest unison Windows build, but when started, it seemingly does nothing. (Fortunately I only tested it on a throwaway VM)

**Comment by gdt** [comment]
Thanks; that seems like leftover text and I have cleaned it up.

**Comment by IzumiRaine** [comment]
It seems the weird links are back. Looking at the page's edit history, it appears there was some vandalism with people inserting misleading links in the last 11 days? E.g., <https://github.com/bcpierce00/unison/wiki/_compare/ac38ad24b48881109fde1b2f1a550f632b5ba221...237d42630234b57429d4ff096fcac84da2d7d2f0>. (Maybe that page should be locked for some time; but I'm not sure if that's possible on github.)
