### ISSUE TITLE
Hangs on Windows when halfduplex=false

### ISSUE THREAD

**Issue by jirogoro** [bcpierce00/unison#762]
### Phenomenon
- A directory of many files (~400k files) are synchronized from a Windows client to a server by socket connection.
- Client hangs randomly during synchronization, not accepting Ctrl+C interruption.
- When hanged, no CPU, disk and network access occur on both of the client and the server.
- Server keeps locking one temp file (.unison.~~.unison.tmp) even after the client process is killed.
- When the client process is restarted, it hangs at the transfer around the locked temp file again.
- The hang repeats until the server process is restarted.
- The above has not happen with an option of `halfduplex=true`.

### Environment
- Windows 10
- Unison 2.52.1 (Ocaml 4.14.0)

### How to reproduce
Although the above phenomenon occurs randomly, I found a method to reproduce the similar situation (hangs without CPU, disk, and network usage, locking temp file).
1. Create a profile with empty directory pair synchronized by socket connection.
2. Add a file (a.zip, >10MB is convenient) to the client directory.
3. Run synchronization and interrupt with Ctrl+C while a.zip is being copied (while `[rsynctoken] growing string` is shown in `-debug all`).
4. When the client hanged, the phenomenon is reproduced.
5. When the process terminated with `Terminated!`, copy a.zip to another file (a2.zip).
6. Run synchronization again, and it surely hangs.
- When `halfduplex=true`, hangs and locking temp file do not occur but infinite loop of GC happens instead.

**Comment by tleedjarv** [comment]
I had a look at the reproducer and found several different issues which contribute to the hang.

Will you be able to test if I open a PR with some proposed fixes?

**Comment by jirogoro** [comment]
Thank you for your quick handling!
Yes, I can test fixed versions when binaries are provided.

**Comment by tleedjarv** [comment]
If have proposed fixes to several issues which cause or contribute to hangs revealed by your reproducer. I don't think any of these fixes is really doing anything to improve the issue you see in your real sync. Except that hopefully none of the files remain locked now.

To get binaries for testing, head over to https://github.com/bcpierce00/unison/actions/runs/2615759812 to see build artifacts from this PR (you may have to scroll quite a bit down). There are two kinds of artifacts, with and without `-publish` suffix. On all platforms except Windows you can always pick an artifact without `-publish` suffix. On Windows, you may first want an artifact with `-publish` suffix because it contains all required DLLs for the GUI (if you need it). For further iterations, if any, you can pick the artifact without `-publish` suffix and reuse the DLLs from before.

**Comment by jirogoro** [comment]
I tested the fixed binary (ac419901.ocaml-4.14.0) and no hangs and inappropriate file locking found in three full synchronizations with `halfduplex=false`.
This is a great improvement since hangs were happening at almost every time of full synchronization before the fix.
Probably at least the major cause of the hang was fixed in this PR.

**Comment by tleedjarv** [comment]
Thank you for testing. You can keep using that version if you wish. I'm not convinced that the real issue causing hangs in the 400k repo is fixed but you may still want to close this issue and reopen it if you see hangs or other problems again.

**Comment by jirogoro** [comment]
Thank you, I would like to use this version.
By the way, I noticed that transferring files with modification time older than 1970/1/1 fails in the new version showing following messages.
`Failed [test.zip]: Failed to set modification time of file __.unison.test.zip.d310bf447aaca166ad4b0b4776c0ff70.unison.tmp to (invalid date) (18446744073425523000.000000): the time was set to 1970-01-01 at  9:00:00 (0.000000) instead`
This has not happened in the release version.

**Comment by tleedjarv** [comment]
> I noticed that transferring files with modification time older than 1970/1/1 fails in the new version showing following messages

Nice find! This is a result of a recently merged PR. There's a simple fix. You can download artifacts from https://github.com/bcpierce00/unison/actions/runs/2641851342 (as soon as the builds are finished). But keep in mind that these builds do not contain the hang fixes. I would appreciate you testing this fix separately for now. You'll get both fixes together once they're both merged.

**Comment by jirogoro** [comment]
I confirmed files with mtime<1970/1/1 are correctly transferred in the fixed version.
Since no hangs and other problems are happening currently, I would like to close the issue for now.
Thank you very much again!

**Comment by tleedjarv** [comment]
Very good. Thank you for testing.
From now on, you should use the binaries from https://github.com/bcpierce00/unison/actions/runs/2645069783 then you get both fixes included.
