### ISSUE TITLE
Conflict between new files and merge setting

### ISSUE THREAD

**Issue by trebitzki** [bcpierce00/unison#78]
Is it possible to copy "new files" rather than merge them according to a merge setting? I need to sync text files and merging works fine for small changes, but new files are too different, making the merge tool fail.

The setting `merge = Name *.txt -> diff3 CURRENT1 CURRENTARCHOPT CURRENT2 > NEW`
(which I need for slightly different text files) seems to take precedence over copying new files, even a specific ignore setting `ignore = Name {Sites/*/readme.txt}` is "ignored."
`prefer = newer` didn't help, and `force = newer` turns off text merge for all files.

If this is not supported can you guide me to the file where I can try to fix it on my own?

See also [http://stackoverflow.com/questions/44020744/unison-conflict-between-new-files-and-merge-setting](http://stackoverflow.com/questions/44020744/unison-conflict-between-new-files-and-merge-setting)

**Comment by bcpierce00** [comment]
The forcepartial option might help in this case.  (Sorry for slow response!)
