### ISSUE TITLE
File contents are compared even with -fastcheck and -fastercheck enabled

### ISSUE THREAD

**Issue by Friptick** [bcpierce00/unison#783]
This is probably going to be a support request more than a bug. I am trying to find a config that resembles `sizes-only` in `rsync`. That is: do not check the file contents, just compare file size and pick whichever version was updated last, going by its timestamp or a tracking database. This is obviously much much faster, and easily good enough for a scenario where the files are enormous and low-value, like a media library.

As I understand the documentation, `--fastcheck` is useful mainly for Windows systems. And `-fastercheckUNSAFE` will "skip computing fingerprints for new files", which sounds more promising, except for the word "new".

But I have both enabled, and `unison` is still fastidiously checking each media file on every sync. Is this expected? Is there a flag or workaround to get a quicker sync?

Possibly useful detail: one of the replicas is mounted with SSHFS.

Thanks for advice, and for your work on this excellent project.

unison 2.51.5
Ubuntu 22 LTS

**Comment by tleedjarv** [comment]
The current issue title certainly describes a bug, just not clear if bug in Unison.

`fastcheck` is useful for all systems and is enabled by default. `fastercheckUNSAFE` should be used only for the initial sync of new replicas where you know the contents are equal. Using this preference on existing replicas requires extreme caution (in practice, you should check and confirm all the syncs manually).

> do not check the file contents, just compare file size and pick whichever version was updated last, going by its timestamp or a tracking database

`fastcheck` does almost exactly what you are describing. There is one caveat, though. Since the check is done against the tracking database (archive, as it's called) then a change in file time may trigger a rescan of its contents.

In your situation I suspect something is either changing file timestamps or not providing reliable timestamps in the first place (SSHFS?).

To investigate, run your sync with `-debug update+` (on command line; `debug = update+` in profile). That output should make it clear if contents rescan is happening and if so then why.

**Comment by Friptick** [comment]
@tleedjarv Very useful hints, thanks! I also suspect that the root trouble is SSHFS. I just ran the sync with `-debug update+` (seems undocumented) but I'm having difficulty understanding the output. The external replica is mounted with SSHFS at `~/.mob`

Here's an existing file being checked:
```
[update+]   Unchanged file
  lightbox/i20220812_180523_DRO.jpg
[update] buildUpdateRec: /home/jc/.mob/lightbox/i20220812_180523_DRO.jpg
[update] checkContentsChange: archStamp is inode (490) / info.inode (482) / times: 1660320331.000000 = 1660320331.000000... true / lengths: 5004609 - 5004609
[update+]   Double-check possibly updated file
[update]   archive digest = (6573baef59c3bca2ca743f69472c935e,)   current digest = (6573baef59c3bca2ca743f69472c935e,)
[update+]   Contents match: update archive with new time...1660320331.000000
```

Why is it double-checking? The inode number is different, could this be the issue? Times are the same. Lengths too (I tried `-times` but this seems unrelated). 

For reference, here's a new file being discovered:

```
[update]   Updated file
  lightbox/i20220829_192311_DRO.jpg
[update] buildUpdateRec: /home/jc/.mob/lightbox/i20220829_192311_DRO.jpg
[update] checkContentsChange: archStamp is inode (507) / info.inode (499) / times: 1661793702.000000 = 1661793702.000000... true / lengths: 3384160 - 3384160
[update+]   Double-check possibly updated file
[update]   archive digest = (LEN3384160@\!ӞdrƸ,)   current digest = (ad352d20a015791af4ce233ff9679eca,)

...

[BGN] Updating file lightbox/i20220829_192311_DRO.jpg from /home/jc/.mob to /home/jc
[update] updateArchive /home/jc lightbox/i20220829_192311_DRO.jpg
[update] checkNoUpdates /home/jc lightbox/i20220829_192311_DRO.jpg
[update] buildUpdateRec: /home/jc/lightbox/i20220829_192311_DRO.jpg
[update] checkContentsChange: archStamp is inode (897) / info.inode (897) / times: 1661793702.000000 = 1661793702.000000... true / lengths: 3384160 - 3384160
[update+]   Double-check possibly updated file
[update]   archive digest = (LEN3384160@\!ӞdrƸ,)   current digest = (ad352d20a015791af4ce233ff9679eca,)
[update]   Updated file
[update] markPossiblyUpdated /home/jc lightbox/i20220829_192311_DRO.jpg
[update+] updatePathInArchive ArchiveDir /home/jc [] [lightbox/i20220829_192311_DRO.jpg]
[update+] updatePathInArchive ArchiveDir /home/jc [lightbox] [i20220829_192311_DRO.jpg]
[update+] updatePathInArchive ArchiveFile /home/jc [lightbox/i20220829_192311_DRO.jpg] []
[update] Setting archive for //ubox//home/jc
[update] replaceArchiveLocal /home/jc lightbox/i20220829_192311_DRO.jpg
[update+] updatePathInArchive ArchiveDir /home/jc [] [lightbox/i20220829_192311_DRO.jpg]
[update+] updatePathInArchive ArchiveDir /home/jc [lightbox] [i20220829_192311_DRO.jpg]
[update+] updatePathInArchive ArchiveFile /home/jc [lightbox/i20220829_192311_DRO.jpg] []
[update] Setting archive for //ubox//home/jc
[update] updateArchive /home/jc/.mob lightbox/i20220829_192311_DRO.jpg
[update] replaceArchiveLocal /home/jc/.mob lightbox/i20220829_192311_DRO.jpg
[update+] updatePathInArchive ArchiveDir /home/jc/.mob [] [lightbox/i20220829_192311_DRO.jpg]
[update+] updatePathInArchive ArchiveDir /home/jc/.mob [lightbox] [i20220829_192311_DRO.jpg]
[update+] updatePathInArchive ArchiveFile /home/jc/.mob [lightbox/i20220829_192311_DRO.jpg] []
[update] Setting archive for //ubox//home/jc/.mob
[END] Updating file lightbox/i20220829_192311_DRO.jpg
```
Why is the `[update] Setting archive for //ubox//home/jc` duplicated? Could this be related? I am also having an issue of new files being synced "back" once. I was hoping to keep this for a second issue but this could all be related.

For completeness, here's the final part of the output:
```
Saving synchronizer state
[update] Updating archives
[update+] Archive name is //ubox//home/jc;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update+] Archive name is //ubox//home/jc/.mob;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 016f7df008530b4003b14b45bf65c657
[update+] Archive name is //ubox//home/jc;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update] Saving archive in /home/jc/.unison/sc92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update+] Archive name is //ubox//home/jc/.mob;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 016f7df008530b4003b14b45bf65c657
[update] Saving archive in /home/jc/.unison/sc016f7df008530b4003b14b45bf65c657
[update+] Archive name is //ubox//home/jc;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update+] Archive name is //ubox//home/jc;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update+] Archive name is //ubox//home/jc/.mob;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 016f7df008530b4003b14b45bf65c657
[update+] Archive name is //ubox//home/jc/.mob;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 016f7df008530b4003b14b45bf65c657
[update+] Archive name is //ubox//home/jc;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update+] Archive name is //ubox//home/jc;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update] Copying archive /home/jc/.unison/tm92623e8ad7bd3b6d38a7c6d4d5a2be8b to /home/jc/.unison/ar92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update+] Archive name is //ubox//home/jc/.mob;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 016f7df008530b4003b14b45bf65c657
[update+] Archive name is //ubox//home/jc/.mob;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 016f7df008530b4003b14b45bf65c657
[update] Copying archive /home/jc/.unison/tm016f7df008530b4003b14b45bf65c657 to /home/jc/.unison/ar016f7df008530b4003b14b45bf65c657
[update+] Archive name is //ubox//home/jc;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update] Removing archive /home/jc/.unison/tm92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update+] Archive name is //ubox//home/jc/.mob;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 016f7df008530b4003b14b45bf65c657
[update] Removing archive /home/jc/.unison/tm016f7df008530b4003b14b45bf65c657
[update+] Archive name is //ubox//home/jc;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 92623e8ad7bd3b6d38a7c6d4d5a2be8b
[update+] Archive name is //ubox//home/jc/.mob;//ubox//home/jc, //ubox//home/jc/.mob;22; hashcode is 016f7df008530b4003b14b45bf65c657
Synchronization complete at 09:27:02  (25 items transferred, 0 skipped, 0 failed)
```
Any ideas?

**Comment by tleedjarv** [comment]
> ```
> [update+]   Unchanged file
>   lightbox/i20220812_180523_DRO.jpg
> [update] buildUpdateRec: /home/jc/.mob/lightbox/i20220812_180523_DRO.jpg
> [update] checkContentsChange: archStamp is inode (490) / info.inode (482) / times: 1660320331.000000 = 1660320331.000000... true / lengths: 5004609 - 5004609
> [update+]   Double-check possibly updated file
> [update]   archive digest = (6573baef59c3bca2ca743f69472c935e,)   current digest = (6573baef59c3bca2ca743f69472c935e,)
> [update+]   Contents match: update archive with new time...1660320331.000000
> ```
> 
> Why is it double-checking? The inode number is different, could this be the issue? Times are the same. Lengths too (I tried `-times` but this seems unrelated).

We've found the issue. Yes, it's the inode number. SSHFS probably can't provide stable inode numbers. Try adding `-ignoreinodenumbers` and see if that works better.

> For reference, here's a new file being discovered:
> 
> ```
> [update]   Updated file
>   lightbox/i20220829_192311_DRO.jpg
> [update] buildUpdateRec: /home/jc/.mob/lightbox/i20220829_192311_DRO.jpg
> [update] checkContentsChange: archStamp is inode (507) / info.inode (499) / times: 1661793702.000000 = 1661793702.000000... true / lengths: 3384160 - 3384160
> [update+]   Double-check possibly updated file
> [update]   archive digest = (LEN3384160@\!ӞdrƸ,)   current digest = (ad352d20a015791af4ce233ff9679eca,)
> ```

This is the result of the `fastercheck` preference and the changing inode number.

> ```
> [BGN] Updating file lightbox/i20220829_192311_DRO.jpg from /home/jc/.mob to /home/jc
> [update] updateArchive /home/jc lightbox/i20220829_192311_DRO.jpg
> [update] checkNoUpdates /home/jc lightbox/i20220829_192311_DRO.jpg
> [update] buildUpdateRec: /home/jc/lightbox/i20220829_192311_DRO.jpg
> [update] checkContentsChange: archStamp is inode (897) / info.inode (897) / times: 1661793702.000000 = 1661793702.000000... true / lengths: 3384160 - 3384160
> [update+]   Double-check possibly updated file
> [update]   archive digest = (LEN3384160@\!ӞdrƸ,)   current digest = (ad352d20a015791af4ce233ff9679eca,)
> ```

Not quite sure what's going on here (inode is the same) but nevertheless, this file does not have a proper hash because it was first scanned with `fastercheck` enabled.

> ```
> [update]   Updated file
> [update] markPossiblyUpdated /home/jc lightbox/i20220829_192311_DRO.jpg
> [update+] updatePathInArchive ArchiveDir /home/jc [] [lightbox/i20220829_192311_DRO.jpg]
> [update+] updatePathInArchive ArchiveDir /home/jc [lightbox] [i20220829_192311_DRO.jpg]
> [update+] updatePathInArchive ArchiveFile /home/jc [lightbox/i20220829_192311_DRO.jpg] []
> [update] Setting archive for //ubox//home/jc
> [update] replaceArchiveLocal /home/jc lightbox/i20220829_192311_DRO.jpg
> [update+] updatePathInArchive ArchiveDir /home/jc [] [lightbox/i20220829_192311_DRO.jpg]
> [update+] updatePathInArchive ArchiveDir /home/jc [lightbox] [i20220829_192311_DRO.jpg]
> [update+] updatePathInArchive ArchiveFile /home/jc [lightbox/i20220829_192311_DRO.jpg] []
> [update] Setting archive for //ubox//home/jc
> [update] updateArchive /home/jc/.mob lightbox/i20220829_192311_DRO.jpg
> [update] replaceArchiveLocal /home/jc/.mob lightbox/i20220829_192311_DRO.jpg
> [update+] updatePathInArchive ArchiveDir /home/jc/.mob [] [lightbox/i20220829_192311_DRO.jpg]
> [update+] updatePathInArchive ArchiveDir /home/jc/.mob [lightbox] [i20220829_192311_DRO.jpg]
> [update+] updatePathInArchive ArchiveFile /home/jc/.mob [lightbox/i20220829_192311_DRO.jpg] []
> [update] Setting archive for //ubox//home/jc/.mob
> [END] Updating file lightbox/i20220829_192311_DRO.jpg
> ```
> 
> Why is the `[update] Setting archive for //ubox//home/jc` duplicated? Could this be related?

No, this is not related. This is just the debug output exposing the internal workings.

> I am also having an issue of new files being synced "back" once. I was hoping to keep this for a second issue but this could all be related.

This is probably related. I suspect this to be a combination of using `fastercheck` and the inodes not being stable. This should also go away with `-ignoreinodenumbers`.

> For completeness, here's the final part of the output:
> 
[skip]
> 
> It feels a bit like "too many archives" but possibly it's just particularly verbose output. Any ideas?

No worries, it's just a lot of debug output. Not related to your issue.

**Comment by Friptick** [comment]
It works! Exactly as you predicted.

`-ignoreinodenumbers` reduces the comparison time to a couple of seconds, just like `rsync --sizes-only`. I checked with file changes at each end, it discovers them fine. Even when a single character has been modified without altering the file size. Obviously, I understand that this is contingent on the internal database of modifications being up to date.

>You may also experiment with the use_ino FUSE option. I don't know if it works or how it works but it may prove useful to you.

Thanks, will keep this in mind. And for the other tips too, very helpful. I've been using other more fashionable sync tools but this seems just as good, while being universally available and easy to maintain. Nice work by all involved.

Thanks so much @tleedjarv for your help.
