### ISSUE TITLE
Manual does not explain that backup files (apparently) are never deleted

### ISSUE THREAD

**Issue by grothesque** [bcpierce00/unison#785]
From observation of Unison I have the impression that stale backup files are never deleted and thus accumulate over time.  This is a potentially problematic behavior that in addition can be surprising even to experienced users, since the other files that are automatically created under `~/.unison` do not require maintenance.  (The default backup location is within that directory.)

I suggest to clearly state in the documentation that (for now) the user is responsible for deleting stale backup files.  (But I believe that there should be a way for Unison to take care of this itself.)

See also #782.

**Comment by gdt** [comment]
I can see why you'd say that, but as one computer scientist reading text written by another computer scientist, it's clear that they are created and that the only deletion mechanism is the `maxbackups` mechanism, so I've tagged this as an enhancement request rather than a defect.

**Comment by gdt** [comment]
Please review #786

**Comment by grothesque** [comment]
> I can see why you'd say that, but as one computer scientist reading text written by another computer scientist, it's clear that they are created and that the only deletion mechanism is the maxbackups mechanism, so I've tagged this as an enhancement request rather than a defect.

Let’s look at what the manual says about the `backupcurr` feature that I use. According to it, Unison will “keep a backup of the current version of every file” that matches a `backupcurr` path specification.  However, the manual does not define what “current version” means.

Let’s consider a matching file that was in sync but now has been overwritten such that its new length is zero.  Upon the next synchronization, Unison will store the zero-length version as the backup.

Given the above and without a clear definition of “current version”, one could reasonably assume that when a `backupcurrent` file is deleted, its backup is deleted as well: after all, in analogy to the file that has lost its content, one could assume that the current version is “no file”.

(Instead, what seems to be the case is that, `backupcurr` is equivalent to setting `maxbackups` to 1 for the matching files.  But this is a guess from my side, not something that is clear from reading the manual.)

By the way, even the documentation of `maxbackups` does not state that it’s the only deletion mechanism: “This preference specifies the number of backup versions that will be kept by unison, *for each path that matches the predicate backup*.”  This says nothing about the fate of backups of deleted files, which are no longer “paths that match the predicate backup”.  So, in my opinion, the current documentation would be consistent with removal of stale backup files not only for files matching `backupcurr` but also for those matching plain `backup`.

In other words, the fate of stale backup files is undefined by the manual, and at least for `backupcurr` it could be expected by analogy that they are removed along with the files.

And even if I am wrong (by training I am a theoretical physicist, not a computer scientist), the unison manual is hopefully not meant to be a specification that requires formal analysis by an expert.

I hope to have demonstrated that even an experienced and reasonably intelligent user could wrongly assume that enabling `backupcurr` will not clog up his disk by indefinitely keeping copies of potentially confidential files that have been deleted long ago.  Therefore, I believe that a *clear* warning is in order.

----------------------------------------------------------------

Considering #786, thank your for formulating it.  I have two comments:

- Someone who, as me, is only interested in “Merging conflicting versions” may never read the backup section of the manual that contains your modifications.  Even to a careful reader the backup section seems irrelevant, since it does not mention `backupcurr`.  So, the new warning may be overseen.

- As I tried to explain above, I am not convinced that the statement “Note that this implies, by omission, that there are no other mechanisms for deleting backups” is actually true.  It’s certainly not obvious, so I would prefer if it was simply stated that upon deletion of a file its backups remain in place.

**Comment by gdt** [comment]
It is the nature of backups that they remain until cleaned up; that's how they are useful, so I really don't find this surprising.   Given that backups are created for deleted files (which seems obviously useful), it doesn't make sense for them to be removed because the files have been deleted.

I have changed "keep" to "create" to remove the implication that "keep" might expire, and I adjusted the wording about maxbackups  being the only mechanism.

I didn't realize about `backupcurr` raised this issue too.  I added a caution there and changed "keep" to "create".

**Comment by grothesque** [comment]
> It is the nature of backups that they remain until cleaned up; that's how they are useful, so I really don't find this surprising. Given that backups are created for deleted files (which seems obviously useful), it doesn't make sense for them to be removed because the files have been deleted.

I agree.  I personally don’t care about Unison’s regular backup mechanism, since I prefer to use it as a pure synchronizer, and organize backups separately.

Since you brought up the question of whether Unison’s behavior agrees with its specification, I wanted to point out that, in my eyes, Unison’s specification was not saying much about the fate even of regular backup files.

> I have changed "keep" to "create" to remove the implication that "keep" might expire, and I adjusted the wording about maxbackups being the only mechanism.
> 
> I didn't realize about `backupcurr` raised this issue too. I added a caution there and changed "keep" to "create".

Thanks a lot, the updated manual now seems very clear to me.
