### ISSUE TITLE
Sychronization fails because archives are not identical with `-xattr`

### ISSUE THREAD

**Issue by pamolloy** [bcpierce00/unison#787]
I've been using unison for a long time and would like to deploy the new xattr support. I'm building off of `a19c16ef8ffce4cb3da372e92324621192fc1c0f` for multiple hosts, distros and architectures.

| | Local | Remote |
| --- | --- | --- |
| Distro | Fedora 36 | Debian Bullseye |
| Arch | x86-64 | i386 |

Note that I built unison on the local host in a Fedora 34 container to match the ocaml version.

```
$ ssh server unison -version
unison version 2.52.1 (ocaml 4.11.1)
$ unison -version
unison version 2.52.1 (ocaml 4.11.1)
```

When I sync with `-xatter` I see the following:

```
Dumping archives to ~/unison.dump on both hosts
Finished dumping archives
Fatal error: Internal error: New archives are not identical.
Retaining original archives.  Please run Unison again to bring them up to date.
```

Running with `-ignorearchives` did not appear to fix the problem.

I did a diff of `~/.unison/<hash>.unison.dump` on both hosts and only noticed a time difference since the hosts are in different timezones.

When I ran unison without `-xattr` the directories synchronize successfully.

A side note, `~/unison.dump` was never created although a message stated that it was. With `-debug all -dumparchives` I see dumps in ~/.unison`.

**Comment by pamolloy** [comment]
With `-debug verbose` the message looks like:

```
[remote+] Waiting for next message
Finished dumping archives
[remote+] Exception caught by Thread.unwindProtect: Internal error: New archives are not identical.
Retaining original archives.  Please run Unison again to bring them up to date.
```

**Comment by gdt** [comment]
Thanks for testing xattr and following up about debugging. 

What operating system and CPU?
You say different timezones, but wouldn't the actual timestamps be in UTC (well, seconds since the epoch)?

**Comment by pamolloy** [comment]
> Thanks for testing xattr and following up about debugging.

Happy to help and thanks for the quick reply.

> What operating system and CPU? You say different timezones, but wouldn't the actual timestamps be in UTC (well, seconds since the epoch)?

I added a table with the Linux distribution and architecture above.

On closer inspection, unix time is in parenthesis, which matches, while local time without a timezone is printed before:

```
128248c128248
<       File, modified at 2011-08-24 at 22:38:52 (1314218332.000000)  size 21042529  rwxr-xr-x    (dd962096bf9e8571390d11b164b43042,)
---
>       File, modified at 2011-08-24 at 16:38:52 (1314218332.000000)  size 21042529  rwxr-xr-x    (dd962096bf9e8571390d11b164b43042,)
```

I assume this isn't the "none identical" issue. But I'm not sure how to figure out what `New archives are not identical` means.

**Comment by gdt** [comment]
That looks like the same time and it's just being rendered in the lcoal timezone.
Could you try a sync that's done over ssh but to the same machine, to replicate what you are doing, but with the same cputype?  In theory all the types in files should be fixed width but it's an easy thing to check.

**Comment by tleedjarv** [comment]
> Arch 	x86-64 	i386

This is the most likely culprit here.

How many files do you have in replicas that you are testing on? If it's not too many (let's say up to a few thousand is ok) then I can prepare a debug build for you to try so that we can get more information.

**Comment by tleedjarv** [comment]
@pamolloy grab the latest commit from here https://github.com/tleedjarv/unison/actions/runs/2987871861
It's based on the exact version you are testing so there are no other changes.

When running this, add `-debug xattr-fail-test` and don't use any other `-debug` arguments.

The output goes to stderr so you may want to redirect that to a file. I understand you're using ssh. This means that output from both machines will end up in the same file. Tha't may not be an issue (except you can't use `diff` directly), but we'll see.

**Comment by pamolloy** [comment]
I copied the local directory into another directory using `rsync -AXogpEtUr` and then did a sync with `-xattr` without any issues. I then copied the remote directory to the local machine with the same rsync flags (which took a little while) and did a sync with `-xattr` that was also successful.

I'll rebuild with the above when I have a bit more time later today.

**Comment by tleedjarv** [comment]
Your local sync succeeding is yet more evidence suggesting an issue with x86-64 vs i386.

**Comment by pamolloy** [comment]
> The output goes to stderr so you may want to redirect that to a file. I understand you're using ssh. This means that output from both machines will end up in the same file. Tha't may not be an issue (except you can't use `diff` directly), but we'll see.

@tleedjarv What are you looking for? I have 64,124 lines and 111 with >0 xattrs. All are prefixed with `server`. There's a mix of `String, String`, `String, Hash`, and `String, String, String`.

**Comment by pamolloy** [comment]
Here is the output for one file with extend attributes on each host:

```
File, modified at 2016-10-01 at 15:57:09 (1475351829.000000)  size 1248      rw-r--r-- 2 xattrs (48 bytes): birth, title   (5263fc032c264f773a871d1960153dc6,)
File, modified at 2016-10-01 at 21:57:09 (1475351829.394389)  size 1248      rw-r--r-- 2 xattrs (48 bytes): title, birth   (5263fc032c264f773a871d1960153dc6,)
```

It looks like the order is consistently reversed for all files with extended attributes.

**Comment by pamolloy** [comment]
`XATTR(7)`

>        Since the filesystems on which extended attributes are stored might also be used on architectures with a different byte order and
>        machine word size, care should be taken to store attribute values in an architecture-independent format.

**Comment by tleedjarv** [comment]
> What are you looking for?

I was looking for any differences.

I think you already found the problem. The ordering. This is not the architecture ordering that you quoted, but the actual ordering of the attributes in the list. When comparing equality of attributes then this is not a problem because that comparison is correctly ordering-independent. But checking archive integrity at the end of sync is mistakenly order-dependent. What an embarrassing bug...

I have prepared a new patch for you to test. It's based on the previous debug commit. Grab it here https://github.com/tleedjarv/unison/actions/runs/2991566826

If this works then I'll open a PR with the patch. Thank you for helping with testing.

**Comment by pamolloy** [comment]
> > What are you looking for?
> 
> I was looking for any differences.
> 
> I think you already found the problem. The ordering. This is not the architecture ordering that you quoted, but the actual ordering of the attributes in the list. When comparing equality of attributes then this is not a problem because that comparison is correctly ordering-independent. But checking archive integrity at the end of sync is mistakenly order-dependent. What an embarrassing bug...

Not at all! Thanks again for implementing the feature and helping with the debugging.

> I have prepared a new patch for you to test. It's based on the previous debug commit. Grab it here https://github.com/tleedjarv/unison/actions/runs/2991566826
> 
> If this works then I'll open a PR with the patch. Thank you for helping with testing.

I'll try to give it a try tonight. :crossed_fingers:

**Comment by pamolloy** [comment]
```
Unison 2.52.1 (ocaml 4.11.1) finished propagating changes at 21:18:17.43 on 06 Sep 2022, 0.859 s
Saving synchronizer state
Synchronization complete at 21:18:18  (2 items transferred, 5 skipped, 0 failed)
```

**Comment by pamolloy** [comment]
:champagne:
