### ISSUE TITLE
Parameters for forcing file and directory permissions

### ISSUE THREAD

**Issue by tomacco81** [bcpierce00/unison#789]
Would it be possible to implement the parameters like `force create mode` and `force directory mode` if the parameters `perms=0` and `dontchmod=true` are set (as in SAMBA)?
I synchronize a CIFS share with a directory on an ext4 volume. If I now set the parameter `perms=0o1777`, I very often get the error "Failed: Destination updated during synchronization. The properties of file xxx have been modified".
With the parameter `perms=0` on the other hand I have the problem that transferred files are created with permission 600 (`rw-------`).
It would be very helpful if unison had parameters to force permissions for new files. For example `force create mode = 775`.

**Comment by gdt** [comment]
Please use the mailnglist for questions.  There are a lot of issues wrapped up in your question.  There are very few people that subscribe to issues, and there are many more on the users list that may be dealing with the same issues.    There may be a bug lurking, and there may be something that turns into a well-articulated feature request.  Or it may just be that non-POSIX filesystems are trouble.

**Comment by tleedjarv** [comment]
Related: #660
