### ISSUE TITLE
work around macos 13 beta issue - Attribute not found setattrlist

### ISSUE THREAD

**Issue by bcbcabral** [bcpierce00/unison#798]
Hi,

i've just upgraded to the latest MacOS Ventura public beta (13 beta 6) and all my unison jobs that use either msdos or exfat are failing with the following error:

Unison 2.52.1 (ocaml 4.03.0) started propagating changes at 14:50:59.93 on 23 Sep 2022
[BGN] Copying  from //host//files/Media/Music_tbp to /Volumes/ZX300SD/Music_tbp
Failed: Error in setting file information:
Attribute not found [setattrlist(/Volumes/ZX300SD/.unison.Music_tbp.6e101def66a18deb42dc1bddf2807602.unison.tmp)]
Failed []: Error in setting file information:
Attribute not found [setattrlist(/Volumes/ZX300SD/.unison.Music_tbp.6e101def66a18deb42dc1bddf2807602.unison.tmp)]
Unison 2.52.1 (ocaml 4.03.0) finished propagating changes at 14:51:00.01 on 23 Sep 2022, 0.076 s
Saving synchronizer state
Synchronization incomplete at 14:51:00  (0 items transferred, 0 skipped, 1 failed)

This was working fine prior to the beta. If using apfs, unison will work just fine.

I've noticed the following on the ventura beta release notes:

"File System
New Features in macOS 13 Ventura Beta

    There’s a change to the implementation of the msdos and exfat file systems. Apps that check for those specific file system formats might not detect them. Please file feedback if this impacts your app. (90768681)"

(https://developer.apple.com/documentation/macos-release-notes/macos-13-release-notes)

If this is working with apfs and not with exfat, then unison might be affected by this change.

For reference, I've done multiple tests with multiple usb drives formated in exfat and msdos. Also, the configuration file is also new just in case.

Thanks

**Comment by tleedjarv** [comment]
I've just opened a PR with a potential fix. Please test it with all the fs types you've mentioned.
You can download binaries with the fix from here: https://github.com/bcpierce00/unison/actions/runs/3114826447
The fix is on top of what's soon to be released as 2.53.0. This means a couple of things. Builds with OCaml 4.03 are no longer available (I see 4.03 is the compiler in your current version). The archives will be upgraded in a way that 2.52.1 will no longer be able to read them.

**Comment by bcbcabral** [comment]
Hi,

looks good! For my test case, with just one file, it worked.

I'm now running normal job, but as it rebuilding the files checksum, it will take a couple of hours. Will report back.

Thanks for your help!

**Comment by bcbcabral** [comment]
Hi,

as a followup, everything seems to be ok at this point.

Thanks!
