### ISSUE TITLE
"sudo make install" fails with error

### ISSUE THREAD

**Issue by Akito13** [bcpierce00/unison#81]
`mv /root/bin//unison /tmp/unison-2875
mv: cannot stat '/root/bin//unison': No such file or directory
Makefile:83: recipe for target 'doinstall' failed
make: [doinstall] Error 1 (ignored)
cp unison /root/bin/
cp: cannot create regular file '/root/bin/': Not a directory
Makefile:83: recipe for target 'doinstall' failed
make: *** [doinstall] Error 1
`

Why the hell does it want to be installed there? I want it in /usr/local/bin or in /usr/local/sbin, because almost every program finds its way there. I have 0 programs in /root/bin.

**Comment by alkuzad** [comment]
First - lower your tone
Second - read the friendly manual - http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#install (hint - there is no "sudo" or "make install" there related to unison itself)
Third - look into sources to find the truth, answer is very easy to find: https://github.com/bcpierce00/unison/blob/master/src/Makefile#L71
