### ISSUE TITLE
Feature request: Allowing unison to back up an entire file system starting at /

### ISSUE THREAD

**Issue by TheHippoMan** [bcpierce00/unison#826]
I want to use unison to back up my entire linux filesystem (excluding a few specific directories via "ignore") to a directory on my Mac via an ssh connection.

I know how to set up this ssh-based unison transfer except for one key point: it seems that unison is not permitting the initial "root" of the source machine to be `/`. However, since I want to back up nearly everything on the linux machine, I need to start at the root of the linux filesystem tree.

Preference file which fails:
```
root = /
root = ssh://useronmac@thehost.com//Users/useronmac/backups
force = /
sshargs = -p 6543
[ A number of "ignore" commands go here ]
```
This is the error that I get ...
```
[ ...  etc. ... ]
Looking for changes
  Waiting for changes from server
Reconciling changes
         error            /  
The path / is a root directory
No updates to propagate
```
If I change the first "root" command to something like `root = /usr`, and if I change the "force" command to something like `force = /usr` , then the unison backup works fine. It seems that `/` is a special case which unison disallows.

Is there any way that we can have a unison option to allow these kinds of backups from the `/` directory?

**Comment by gdt** [comment]
Please use the mailinglist for support requests.  You didn't mention the version or OS, and you didn't point to the manual section which does or does not say what  you are doing is ok.

If after discussion you want to file a bug, that's ok, but it will need to follow the guideilnes.   That includes running 2.53.0 or git master past that tag.

https://github.com/bcpierce00/unison/wiki#mandatory-reading-before-reporting-bugs
https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
