### ISSUE TITLE
Fatal error unison 2.48.4_1

### ISSUE THREAD

**Issue by Nolfik** [bcpierce00/unison#83]
Good afternoon. After upgrading to version 2.48.4_1, I started the synchronization, after which I received an error:
Fatal error: Filesystem watcher error: unexpected error 23 while adding a watcher
The watcher can be disabled by setting preference 'watch' to false

Tried to add a line to the configuration file:
Watch = false
There was another mistake:
Fatal error: Server: File monitoring helper program not running

At the moment the system is FreeBSD 10.3-RELEASE-p19 # 0 r318353 and
Unison-2.48.4_1

The configuration file
root = /data/
root = socket://192.168.2.1:22000//data/
 #prefer = socket://192.168.2.1:22000//data/
prefer = /data/

  path = share/1
  path = share/2
  path = share/3
  path = share/4

ignore = Name {. *}
repeat = 1000

backup = Name *
backuploc = central
backupdir = /data/backup

 #force = newer
batch = true
 #times = true
owner = false
group = true
maxthreads = 4
rsync = false
 #debug = verbose

log = true
logfile = /var/log/unison/sync_data.log

If you leave only 2 and 3 folders, then it is synchronized normally. But 1 and 4 immediately produce errors ...

Thankful in advance for any help!

**Comment by mikepierce** [comment]
Wait, so if you don't sync folders 1 and 4, unison runs fine? So something specific about the contents of those folders is causing the errors in unison. How are folders 1 and 4 different from 2 and 3?

**Comment by Nolfik** [comment]
They basically differ in size about the number of files and directories. The content in them is the same, mostly video and audio files ...
data/1 47.1T
data/2 25.9T
data/3 2.75T
data/4 19.0T

But if I specify for example the synchronization path path = share/1/a/aa, then I synchronize path = share/1/a/ab and path = share/1/a/ac will go all ok, but if I specify path = share/1/a/ that's the error ...

**Comment by mikepierce** [comment]
Could you run `ls -R1 share/a | wc -l`on each of the directories to get a rough idea of how many files are being watched in each? I'm suspicious that this error has something to do with the filewatcher hitting an upper limit in the number of files it can watch.

**Comment by Nolfik** [comment]
data/1 - 197419
data/2 - 2198
data/3 - 665
data/4 - 418254

**Comment by mikepierce** [comment]
Yeah, directories 1 and 2 have **a lot** of files. The unison filewatcher uses `inotify` which has an upper limit on the number of files it can simultaneously watch. Having this upper limit in place prevents `inotify` from hogging too much of the system's memory. The default value for this upper limit is 8192. 

You can change the upper limit by editing a system file (on linux it's `/proc/sys/fs/inotify/max_user_watches`). But I would recommend against changing this upper limit. Watching that many files just isn't feasible. Maybe run unison at regular intervals instead?

**Comment by Nolfik** [comment]
Thanks for the answer. Tell me how to change this limit in FreeBSD?
And also did not quite understand what is meant by run unison at regular intervals instead?

**Comment by mikepierce** [comment]
I'm not sure how to change it in FreeBSD off the top of my head (but again, I recommend against it). And I mean something like run unison every hour on the hour, or something like that, instead of watching files at all.

**Comment by Nolfik** [comment]
It's strange, I have version 2.48.3 on the old repository ...
The ls -R1 databases/ | wc -l showed 2332842 and there everything is OK!

**Comment by Nolfik** [comment]
Are there any other ideas? Can try to upgrade Freebsd to 11?

**Comment by Salbei** [comment]
@Nolfik On Freebsd you can change the limit with sysctrl:
`sysctl kern.maxfiles=1257680`
 For  a definitive amendement edit the /etc/sysctl.conf file:
`kern.maxfiles=1257680`
