### ISSUE TITLE
Silent failure during fingerprint scan

### ISSUE THREAD

**Issue by cakinli** [bcpierce00/unison#84]
We've been using Unison to maintains dozens of whole filesystem mirrors (each 500GB/300k-500k files) for years , almost entirely between servers (all ext3/4 filesystems).  This has been working flawlessly for 3+ years now.

Recently, I setup a user to sync his own datastore (1TB/6M files) as a three-way mirror with his two Windows machines (both NTFS: Win 10) syncing with a centeral server copy (ext4).  This has worked well for several months, though not as flawlessly as the servers.  So far, the archives have gotten corrupted and needed rebuilds every couple of months.  But I just chalked that up to some combination of Windows and NTFS.

Now however, we seem to be stuck.  Every sync operation on one (and ONLY one) of the workstations is silently failing before the initial scan is complete.  The output below (debug verbose) **seems** to be indicating the receipt of an empty packet which (as best I can read OCaml) is interpreted as a dropped connection (`lostConnection` is called in remote.ml).  But that could be expected and not the root cause for all I know.

    Looking for changes
    [ui] temp: Globals.paths =
    [remote+] send [loadArchive-args] '\132\149\166\190\000\000\000\017\000\000...' 37 bytes
    [remote+] send [rsp] '\132\149\166\190\000\000\000\r\000\000...' 33 bytes
    [remote+] Sending request (id: 7)
    [remote+] Sending write token
    [remote_emit+] dump: \007\000\000\000\165$\000\000\000Ursp\132\149\166\190\000\000\000\r\000\000\000\000\000\000\000\006\000\000\000\005\146+loadArchive5\000\000\000\154loadArchive-args\132\149\166\190\000\000\000\017\000\000\000\000\000\000\000\n\000\000\000\b\160\144-/home/AD/joeuserA\000\000\000\000\017
    [update+] Archive name is //joeclient//cygdrive/c/Users/joeuser/Documents;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is 746c50fc43fcf5e4343cdbf892b1447e
    [update+] Archive name is //joeclient//cygdrive/c/Users/joeuser/Documents;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is 746c50fc43fcf5e4343cdbf892b1447e
    [update+] Archive name is //joeclient//cygdrive/c/Users/joeuser/Documents;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is 746c50fc43fcf5e4343cdbf892b1447e
    [update+] Archive name is //joeclient//cygdrive/c/Users/joeuser/Documents;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is 746c50fc43fcf5e4343cdbf892b1447e
    [update+] Archive name is //joeclient//cygdrive/c/Users/joeuser/Documents;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is 746c50fc43fcf5e4343cdbf892b1447e
    [update] Loading archive from /home/joeuser/.unison/ar746c50
    [server: remote_emit+] grab: \007\000\000\000\165$\000\000\000Ursp\132\149\166\190\000\000\000\r\000\000\000\000\000\000\000\006\000\000\000\005\146+loadArchive5\000\000\000\154loadArchive-args\132\149\166\190\000\000\000\017\000\000\000\000\000\000\000\n\000\000\000\b\160\144-/home/AD/joeuserA\000\000\000\000\017
    [server: remote+] Message received (id: 7)
    [server: remote+] receive 'rsp\132\149\166\190\000\000\000...' 36 bytes
    [server: remote+] receive 'loadArchiv...' 53 bytes
    [server: remote+] Waiting for next message
    [server: remote+] Received the write permission
    [server: remote+] Waiting for next message
    [server: update+] Archive name is //joeserver//home/AD/joeuser;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is b26e15756a3590271a60540ceae04325
    [server: update+] Archive name is //joeserver//home/AD/joeuser;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is b26e15756a3590271a60540ceae04325
    [server: update+] Archive name is //joeserver//home/AD/joeuser;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is b26e15756a3590271a60540ceae04325
    [server: update+] Archive name is //joeserver//home/AD/joeuser;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is b26e15756a3590271a60540ceae04325
    [server: update+] Archive name is //joeserver//home/AD/joeuser;//joeclient//cygdrive/c/Users/joeuser/Documents, //joeserver//home/AD/joeuser;22; hashcode is b26e15756a3590271a60540ceae04325
    [server: update] Loading archive from /home/AD/joeuser/.unison/arb26e15756a3590271a60540ceae04325
    Growing heap to 1145696k bytes
    Growing page table to 4096 entries
    Growing page table to 8192 entries
    Growing page table to 16384 entries
    Growing page table to 32768 entries
    Growing page table to 65536 entries
    Growing page table to 131072 entries
    Growing page table to 262144 entries
    Growing page table to 524288 entries
    joeuser@joeclient:~$ [server: update] Setting archive for //joeserver//home/AD/joeuser
    [server: remote+] Sending result (id: 7)
    [server: remote+] send [loadArchive-res] '\132\149\166\190\000\000\0002\000\000...' 70 bytes
    [server: remote+] send [rsp] '\132\149\166\190\000\000\000\001\000\000...' 21 bytes
    [server: remote+] Sending write token
    [server: remote_emit+] dump: \007\000\000\000\165\024\000\000\000\233rsp\132\149\166\190\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000@U\000\000\000eloadArchive-res\132\149\166\190\000\000\0002\000\000\000\000\000\000\000\017\000\000\000\012\144\160\002\027B{l\t)Unicode case insensitive\0001501947174.11396\000\000\000\000\017
    [server: remote_emit+] grab: EOF
    [server: remote] Connection closed by the client

The config used is
    root = /cygdrive/c/Users/joeuser/Documents
    root = ssh://joeuser@XXXXXXXXX.edu//home/AD/joeuser
    rootalias = ssh://joeuser@XXXXXXXXX.edu//home/AD/joeuser -> ssh://joeuser@XXXXXXXX//home/AD/joeuser
    servercmd = ssh -i /home/AD/joeuser/.ssh/joeuser_backup_rsa XXXXXXXX unison
    sshargs = -A -i /home/joeuser/.ssh/joeuser_backup_rsa
    addversionno = true
    backup = Name *
    backuploc = central
    backupdir = backup
    maxbackups = 5
    addprefsto = common
    fastercheckUNSAFE = true
    perms = 0
    dontchmod = true

though some of that has been varied (mainly servercmd, as I've varied the unison versions on either end, with and without debugging symbols, and fastercheck/fastercheckUNSAFE in trying to speedup the crash and/or rule out anything related to actual file contents).

I've also tried toggling/varying streaming, maxthreads, maxerrors, halfduplex, have removed the archives as I mentioned.  I've also tried most of those variations on 2.40.102, 2.48.1 amd 2.48.3, and attached debuggers to the processes at both ends.

With just one exception, every attempt ends with both processes exiting normally, with 0 exit statuses, before the fingerprint cache is written/completed.

Interestingly, **if** the fingerprint cache is written as its being generated (so that its order means something), then it would be worth pointing out that all of the incomplete cache files I have end at the same point, with the same file (on both ends).

And again, the whole operation works perfectly with the other nearly identical Windows 10 workstation.  It syncs just fine to the same server copy.

**Comment by bcpierce00** [comment]
Sorry to see that no one has been able to offer suggestions for this (I'm afraid I don't have any either).  Did the issue go away, in the end, or did you just work around it?
