### ISSUE TITLE
Unison with Network File System

### ISSUE THREAD

**Issue by ZubaeyrMSFT** [bcpierce00/unison#846]
I have a setup with multiple Apps using a common mounted network file system. Additionally, every Apps has its own local storage. On each of the App I have setup unison to sync the changes between that App's local storage and mounted network file system. 

Everything works fine when I have only single instance of App/Container. However, when I multiple instances of App, the changes made in one container are not being reflected in other. So, basically, the other containers are unable to get notified of the changes made to the network file system by the first container. Just FYI, I do not have control over network file system and cannot make any changes to it.

**Comment by gdt** [comment]
This does not seem like a bug report.
Please use the mailinglist for questions and help request. 

See
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists
