### ISSUE TITLE
Please add feature to define default user and permissions for the copied files.

### ISSUE THREAD

**Issue by ZubaeyrMSFT** [bcpierce00/unison#847]
When unison is setup to sync files between path A and B, it would be really helpful if there is a feature to define default user (chown) and permissions (chmod) for all the files copied to path A, and similarly for all files copied to path B. This is really helpful when one of the paths is a network file system (without any 'user' and with 777 permissions) and these permissions cannot be modified or copied. 

And, also it is more practical because nginx server are usually run with a '/sbin/nologin' user, whereas 'unison' is run with a different user (say root), and the files under the server directory are expected to have same ownership (i.e., nginx user).   

I am currently managing it using 'periodic' execution of chmod and chown commands over path A & B. But these operations are very costly in terms of CPU and it would be nice to have it implicitly defined in unison.

**Comment by gdt** [comment]
This feels out of scope, as unison has so far not really crossed into supporting deficient filesystems.   If you are contemplating writing code it would be good to discuss your approach as I suspect it will raise a number of other issues.  You also might want to ask on unison-users@ as others there may have suggestions.

**Comment by gdt** [comment]
I'm going to call this a sub-part of #868.
