### ISSUE TITLE
Pango-WARNING 

### ISSUE THREAD

**Issue by jspille** [bcpierce00/unison#848]
(unison-text+gui.exe:15084): Pango-WARNING **: couldn't load font "emoji Not-Rotated 9", falling back to "Sans Not-Rotated 9", expect ugly output.

Using unison-v2.53.0+ocaml-4.09.1+x86_64.windows.zip with local drives.

**Comment by gdt** [comment]
The words `emoji` and `Not-Rotated` do not appear in the unison sources so this is almost certainly not a unison bug.  It is likely due to a mismatch between pango's assumptions about fonts and what is on your system.  I suggest following up with pango, or asking on the user's list.
