### ISSUE TITLE
Q: Data Integrity with Multiple Syncs on the Same Dataset?

### ISSUE THREAD

**Issue by benyanke** [bcpierce00/unison#86]
I'm currently using unison to replicate a 2TB volume which contains 1.1 million files in it. A single unison instance isn't fast enough for our purposes. However, since our data is, for the most part, write-once/read-many, we decided after our testing to go with two unison instances: 

* one for the whole volume (takes a few hours, ensures old files are kept in sync if they are changed)
* one for a few of the most recent directories (takes about 30 seconds)

On the whole-volume instance, do I need to exclude the scope synced by the smaller sync?

Example:

I have 100 directories, named 'dir-1', 'dir-2', 'dir-...', 'dir-99', 'dir-100'.
The smaller sync instance specifies `path = /dir-99' and 'path = /dir-100'.
The larger sync instance specified 'path = /'.

Do I need to exclude '/dir-99' and '/dir-100' from the large sync to ensure the data integrity, or can unison sync pools overlap?

**Comment by bcpierce00** [comment]
The actual files should be fine: If, by bad luck, both instances happen to try to copy the same file at the same time, the worst that should happen is that one or both of them will notice that something went wrong and abort.  However, you'd need to make sure they aren't both trying to write to the same archive files in the .unison directory at the same time.  Not entirely sure what would be the best way to achieve that...  (One rather brutal way that might work in your situation -- where files are not changed after being written -- would be to add a command-line flag that causes unison to skip writing its archive file at the end of a run.)

**Comment by benyanke** [comment]
Hm...

Just trying to balance system complexity vs real world risk. What's the worst case scenario if the archive folders get double-written? Just a longer rescan and it's fine? Since the long scan takes multiple hours, it's likelyhood of conflicting with the sub-minute scans is very low.


My multi-instance unison control script is [here](https://github.com/benyanke/unisonctl), if you're curious. Currently developing it now to fit the usecase mentioned above.

**Comment by benyanke** [comment]
Also, one end of the server is a network share, not actually local storage to the unison instance running.

Would it solve the issue if I mounted the share twice, once at `/mnt/share_1` and again at `/mnt/share_1_duplicate`? I could then direct the hour-long sync to use `_duplicate`, and the archive files should be distinct...right? It would slow things down somewhat, but if data integrity is at risk, I can take the slowdown.

**Comment by benyanke** [comment]
Thanks for your assistance. In order to better fit our usecase, I ended up writing a python wrapper, which will dynamically start, stop, and reconfigure multiple unison instances to better handle our large dataset. Once this is up and going, it'll be trivial to ensure there's no overlap in syncing, so I think we'll be ok! It's nearly done. All the preprocessing and assigning directories to unison instances is complete, all I need to write is the actual handling of starting and stopping instances.

https://github.com/benyanke/unisonctrl
