### ISSUE TITLE
Unison chmod on partial transfers with "-dontchmod"

### ISSUE THREAD

**Issue by Netsplits** [bcpierce00/unison#87]
Unison tries to chmod when resuming interrupted transfers with dontchmod=true and parms=0 (using ssh).

I've tried on 2.48.4 and 2.50 (from GitHub).

Works flawlessly if deleting the partial files or when new files added so the dontchmod flag works.

My OCaml knowledge is 0, but I've found the offending line at file copy.ml:

  | `DATA_APPEND len ->
      let fullpath = Fspath.concat fspath path in
      let perm = 0o600 in
      let ch = Fs.open_out_gen [Open_wronly; Open_binary] perm fullpath in
      Fs.chmod fullpath perm;       <---------- this one is the cause of my problem
      LargeFile.seek_out ch (Uutil.Filesize.toInt64 len);
      ch

I've removed that line and recompiled unison and worked for me. Can someone check and do a proper patch? Thanks.

Tested on FreeBSD 10.3 (FreeNAS). Can't use chmod, because is disabled (FreeNAS uses setfacl).

**Comment by bcpierce00** [comment]
Thanks.  Fixed, I think.
