### ISSUE TITLE
Repo About Link points to a page that points to this repo

### ISSUE THREAD

**Issue by askpatrickw** [bcpierce00/unison#881]
You have a link in your about ---->>>>>

https://www.cis.upenn.edu/~bcpierce/unison/

That points to this repo.

**Comment by gdt** [comment]
That's not a bug.

**Comment by askpatrickw** [comment]
Its a bit of a circular reference... I was thinking there was some other home page to use instead and it got missed.

**Comment by gdt** [comment]
I did adjust the language to make it clearer that the Penn site is old, so I think it's ok.
