### ISSUE TITLE
unison-gtk waits 30 seconds when server sends text

### ISSUE THREAD

**Issue by thekswenson** [bcpierce00/unison#885]
My university has some silly message that appears every time I log in via SSH.  In the last year, unison-gtk has started to post this message in a new window, seeming to wait for a response:

![Screenshot from 2023-03-28 12-01-41](https://user-images.githubusercontent.com/9959942/228204848-d7ce6cdd-25fe-4093-9916-b84e2d5fbe7b.png)

There are two negative effects of this change:

1. The message doesn't appear for _30_ seconds, before which Unison seems to hang so I have to wait 30 seconds before I even get the "Connected" message and the changes start to calculate.
2. I have to click OK within a short period, or else there is a timeout.

Practically speaking, this means that I have to standby for 30 seconds each time I want to synchronize my files, waiting for the message window to open, so that I can press OK.  This was never a problem previous to the existence of this window.  If I use unison in a terminal there is no problem and things proceed normally.

**Comment by tleedjarv** [comment]
Which version are you using? If not the latest, are you able to try with the latest version?
Do you use password with ssh?

If I made you a debug version (if it gets to this) would you be able to try it out?

**Comment by thekswenson** [comment]
I have an RSA key on my server, so no password.  I'm using the Ubuntu package, which is version 2.52.0 (ocaml 4.13.1).
I'll try to use the most recent client.  It may be more difficult to update the server unison version.

**Comment by thekswenson** [comment]
I'll do whatever necessary to get a debug version running.

**Comment by tleedjarv** [comment]
> I'll try to use the most recent client. It may be more difficult to update the server unison version.

Please do try. You don't have to update the server version, these versions are interoperable.

**Comment by thekswenson** [comment]
This ocaml interoperability upgrade is really nice!

**Comment by tleedjarv** [comment]
Could I request one more bit of data from you? In terminal, could you execute the following:
`ssh !!your_server!! echo connected > ssh_stdout.txt 2> ssh_stderr.txt` (make sure to replace the hostname)
and then attach the files here (attach, not paste the contents). If there is any sensitive information in the files, you can overwrite those parts with some other characters but don't delete anything.

Also, paste any contents output by ssh that did not end up in those files.

**Comment by thekswenson** [comment]
I'm remembering that I have a non-standard setup.  That is, I have to ssh to campus through a machine that has access to the outside world using the "ProxyCommand" in `.ssh/config`.  Here is an anonymized version of my `.ssh/config` file:

[ssh_stderr.txt](https://github.com/bcpierce00/unison/files/11088480/ssh_stderr.txt)
[ssh_stdout.txt](https://github.com/bcpierce00/unison/files/11088481/ssh_stdout.txt)

**Comment by tleedjarv** [comment]
Thank you for your help. I've now identified the cause of this issue. A fix will be proposed shortly.

**Comment by tleedjarv** [comment]
You can get a build with the proposed fix from https://github.com/tleedjarv/unison/actions/runs/4546236635
If it works for you then you're welcome to keep using it (it's basically 2.53.2 + this fix).

You may still see the connection message because it's impossible to distinguish it from error messages. But it should not expect any input from you (please tell if it does) and it should not block the updates scanning in the background (please tell if it does).

**Comment by thekswenson** [comment]
What a relief!  It works as expected.  Thank you!
