### ISSUE TITLE
System error - libcairo-2.dll not found

### ISSUE THREAD

**Issue by cobni904** [bcpierce00/unison#889]
Hello,

I hope you are well.

I've just upgraded to the new version of Unison and when I launched the program I've the error message "unable to launch... libcairo-2.dll not found".

When I launch the older version it's ok but the new version doesn't work because of this error.

Thank you in advance for your help.

**Comment by gdt** [comment]
This is due to, we think, a bug in Github automations.   As was mentioned on unison-users@, use this link and scroll down.

Please follow up on  the unison-users@ mailinglist, as this is not a bug in unison sources.


https://github.com/bcpierce00/unison/actions/runs/4492634128

**Comment by tleedjarv** [comment]
You can also use DLLs from the previous release. They are needed for GTK, they don't contain any Unison code.
