### ISSUE TITLE
Fails to detect differences

### ISSUE THREAD

**Issue by Drugoy** [bcpierce00/unison#89]
I have 2 nodes with the synced folder via unison.
After the sync I've modified the local file on of the nodes, I ran unison and did a rescan (I've tried reconnecting and rescanning; restarting the app, reconnecting and rescanning - the result is the same).
It just sees no difference.
1.1K of weight difference, ~20min difference.

I am disappointed in Unison.

**Comment by brabalan** [comment]
What profile are you using? What operating system on each node?

**Comment by benyanke** [comment]
I am also having the same problem, but only when the unison instances are spawned by Python's `subprocess.Popen.`

**Comment by Drugoy** [comment]
@brabalan, I am using test profile.
One node is FreeBSD 11.1-RELEASE x64, the other is Xubuntu 17.04

**Comment by brabalan** [comment]
Could you please show the profile, and the output of running unison with the `-debug all` option.

**Comment by Drugoy** [comment]
<img src="http://i.imgur.com/0PbSMTz.png">
What part from the log would you like to see?
Upon hitting sync button it generates 3 lines per file, like these:
```
[server: pred] ignore 'zsh_scripting.txt' = false                                                         
[server: update] buildUpdateRec: /home/uzer/syncme/zsh_scripting.txt                                      
[server: update] checkContentsChange: archStamp is inode (21105385) / info.inode (21105385) / times: 14979
87120.443098 = 1497987120.443098... true / lengths: 852 - 852 
```
And that happens for each file, even for the one with different contents: it says lengths, times and inodes - they all match.
I do `ls filename` on both nodes and I see the difference in their weights and timestamps.

**Comment by brabalan** [comment]
I would like to see the whole log. You could send it to me by email (alan.schmitt@polytechnique.org). But this is very strange indeed.

I would also like to see the output of the commands: `ls -l /home/uzer/syncme` and `ssh work ls -l /home/uzer/syncme`.

**Comment by Drugoy** [comment]
Nevermind, I just realized that this software has not being actively developed for the last 2 years and it will probably either get abandoned or developed at very slow rate.

**Comment by Drugoy** [comment]
Oh wow, I f---ed up: I've 2 duplicate folders with similar contents and I just got confused, unison works like expected. Sorry, for bothering you.

**Comment by bcpierce00** [comment]
No worries.

For the record, Unison is not abandoned, though you're right that it's not under active development for new features.
