### ISSUE TITLE
Command tools not installed in MacOS Sierra

### ISSUE THREAD

**Issue by jpimbert** [bcpierce00/unison#90]
Tha MacOS binary version 2.48.15 in graphical mode proposes to install Command-line tool at startup. But if Yes is clicked, with MacOS Sierra, no command-line tool is installed.

This perhaps is due to **SIP security** in MacOS; /usr/bin is not modifiable. It is recommended by Apple to install new binaries in /usr/local/bin, and bin directory has to be created on fresh Sierra install.

A workaround is to copy command-line tool with Terminal:

    sudo mkdir /usr/local/bin
    sudo cp /Applications/Unison.app/Contents/MacOS/cltool /usr/local/bin/unison

**Comment by brabalan** [comment]
We install in /usr/local/bin since version 2.49.3. I don't think we check if the directory exists, however.

**Comment by smilesrg** [comment]
I think this issue should be reopened, at least path in the instruction window should be corrected

**Comment by bcpierce00** [comment]
What should I search for to find the thing that needs to be corrected?

**Comment by smilesrg** [comment]
Go to Unison GUI, then Unison -> install command line tool. You can find that window appears with instruction, but path is incorrect `/usr/bin/unison`

**Comment by bcpierce00** [comment]
I don’t see the string /usr/bin/unison anywhere in the current unison repo (or an instance of /usr/bin that looks related).  So maybe this is already fixed.

**Comment by smilesrg** [comment]
I think you need to fix that for 2.48.15 version

**Comment by bcpierce00** [comment]
Ah.  That would be a big job, I'm afraid -- getting a changed version out into all the distros that package unison.  I agree that it's annoying, but I haven't heard enough complaints about it to put the community to that kind of trouble.
