### ISSUE TITLE
unison cannot sync files in other directory than home /Mac OS

### ISSUE THREAD

**Issue by stefan11** [bcpierce00/unison#903]
I try to synchronize files from a web-server and created a symlink to the respective server directory. With earlier versions of unison/MacOS this worked. Now unison cannot create the temporary file in the webserver directory. I already granted it access to the complete harddisk, but this did not have any effect.

**Comment by tleedjarv** [comment]
Was this a false alarm or did you find a solution? If you had a real issue and found a solution then it may be interesting for others as well.

**Comment by stefan11** [comment]
It was a permissions issue on my side. Thanks for maintaining this software!
