### ISSUE TITLE
Windows installer 2.53.1+ misses required DLLs in bin folder

### ISSUE THREAD

**Issue by czerwinski1977** [bcpierce00/unison#905]
From version 2.53.1 on, the Windows installer no longer brings required DLLs in the bin folder. It only contains the 4 unison*.exe files, nothing else.

**Comment by tleedjarv** [comment]
This is a known issue. Next release will include DLLs again.
Meanwhile, you can use DLLs from the 2.53.0 release or get 2.53.2 package with included DLLs at https://github.com/bcpierce00/unison/actions/runs/4500920455 (look for a file name ending in "-publish").
