### ISSUE TITLE
Combine with all required gtk lib

### ISSUE THREAD

**Issue by nengxu** [bcpierce00/unison#910]
Unison is the only gtk program I run on Windows. So I used to just copy all required gtk lib into the bin folder of unison. But the latest 2.53.2 unison failed to run with my previous libs. It failed silently. I installed:
https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

And copied all lib files into the bin folder of unison. However, unison failed silently.

Could you please create a new package of unison on windows where all required gtk lib files are copied into the bin folder? Thanks.

**Comment by tleedjarv** [comment]
Next version is coming out very soon. You can download a preview of it here: https://github.com/bcpierce00/unison/actions/runs/4788914771 (scroll down and look for a file name ending in -publish).

**Comment by gdt** [comment]
CI binaries are not really in scope, as unison's product is source code.   Plus this is a dup of #602, an issue on which we have not received contributions.

Please use the mailinglist for support.

**Comment by nengxu** [comment]
> Next version is coming out very soon. You can download a preview of it here: https://github.com/bcpierce00/unison/actions/runs/4788914771 (scroll down and look for a file name ending in -publish).

That worked, thanks. Though on github release page, do we have similar -publich version?
