### ISSUE TITLE
Windows Unison GUI (but not text) fails with passphrased ssh public key auth 

### ISSUE THREAD

**Issue by alansz** [bcpierce00/unison#915]
Using the unison-v2.51.5+ocaml-4.04.2+i386.windows binaries on Windows 11.

From a cygwin terminal, I can use unison fine in text mode. The connection to the server uses an ssh public key that is passphrase-protected, so I am prompted to enter the passphrase and all goes well.

From the GTK interface, however, the SSH connection box appears and says "Permission denied (public key,keyboard-interactive)" and offers a password prompt that doesn't work. See attached screenshot of the dialog box. This used to work under unison 2.48.3, but the remote end had to upgrade to 2.51+, so somewhere between I guess this functionality changed.

A workaround is to open the cygwin terminal, use ssh-agent and ssh-add to load the keys, and then run the gtk interface from that shell, but it would be great to just run it directly as I used to.

**Comment by tleedjarv** [comment]
This is the same issue as #909. A fix is coming in the next release but there is still a long way before it is released.
To get things working now, you have to use the native Windows port of SSH, not the SSH from Cygwin. You can do that by adjusting the path to make sure a native ssh is found first in path or by using the 'sshcmd' preference from command line or in the profile.
