### ISSUE TITLE
move focus to filelist per default

### ISSUE THREAD

**Issue by olafhering** [bcpierce00/unison#931]
It would be nice if per default the keyboard focus is always in the filelist, instead of the various action buttons. 

run GTK version of `unison`
focus is in the profile list, key `Up`/`Down` can be used to select the desired profile
key `Enter` will select the profile
focus is in the file list, key `Up`/`Down` can be used to scroll through the changed files
key `G` will start the sync
key `P` will go back to the profile list
focus is in the profile list, key `Up`/`Down` can be used to select another profile
key `Enter` will select the profile
focus is now in the action buttons instead of the file list, key `Up`/`Down` can not be used to scroll through the changed files
key `Tab` has to be used to switch from action buttons to the file list.

**Comment by gdt** [comment]
Do you mean this as a bug report?  It seems like a bug that there is not consistent behavior.

**Comment by tleedjarv** [comment]
I think I know what the issue is. Proposed patch coming soon.
