### ISSUE TITLE
Best-effort synchronization: Permissions issue

### ISSUE THREAD

**Issue by stdedos** [bcpierce00/unison#934]
Hello there,

I'd like to propose a consideration for the syncing algorithm. Feel free to ignore me if that feels too much.

When synchronizing (via terminal), I encountered the following issue:
```
Failed [<top-level-dir>]: Failed to set permissions of file /root-b/.unison.top-level-dir.6b5b6fbc8e15ffae793d6a68adebe9c0.unison.tmp to rwxrwxrwx: the permissions was set to rwxr-xr-x instead. The filesystem probably does not support all permission bits. If this is a FAT filesystem, you should set the "fat" option to true. Otherwise, you should probably set the "perms" option to 0o1755 (or to 0 if you don't need to synchronize permissions).                                                                                                                                                                                    
```

In my case, the `root-a` is `fuseblk` (ntfs), and the `root-b` is `exfat`.

(I would've considered the `fat` option to `true`, but is `exfat` a `fat` filesystem?)

**Comment by gdt** [comment]
exfat is fat, and fat really means 'deficient like fat'.

Please use the mailinglist for support requests, as documented in the wiki.
