### ISSUE TITLE
Can the documentation for Unison be migrated from the UPenn site? 

### ISSUE THREAD

**Issue by YousufSSyed** [bcpierce00/unison#940]
Most of the documentation for Unison is on https://www.cis.upenn.edu/~bcpierce/unison/, however the documentation has been down for a month now and can only be accessed through The Wayback Machine: https://web.archive.org/web/20230607201850/https://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#unisondir. Searching for Unison documentation shows the site at the top.

Overall pretty inconvenient to figure out how it works, should the documentation be moved from that site? How much effort would it take to do so?

**Comment by gdt** [comment]
Please use the mailinglist for things other than source code defects.

https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
