### ISSUE TITLE
Presets like Toucan

### ISSUE THREAD

**Issue by Korb** [bcpierce00/unison#951]
I propose to add the ability to select pre-configured settings corresponding to the “Copy”, “Mirror”, “Equalise”, “Move” and “Clean” profiles that are in the Toucan application. I find that these profiles cover most of the user's tasks, and using them eliminates the need to check dozens of synchronization settings scattered across the many tabs of the Unison File Synchronizer application.

**Comment by gdt** [comment]
Could you send a note with longer rationale and details to unison-hackers@?  Not that many people pay attention to the tracker, and hackers has a lot more, and I've tried to ask in the Reporting Bugs page that this sort of discussion be on the mailinglist.  (Also, this proposal isn't yet baked enough to be in the tracker as a feature ticket.)

When you do post, please include how these names would map to existing preferences, and sketch out how they would be added in the config file, TUI and GUI.   (I do not think you are talking about removing any preferences.)  Plus your outline of implementation, esp if there are any tricky issues, or if you've prototyped this, any lessons learned.
