### ISSUE TITLE
sync failing on some files setattrlist input/output error

### ISSUE THREAD

**Issue by jmcisvt** [bcpierce00/unison#954]
About 10 files are failing to sync. This is on macOS Ventura, syncing from a user Desktop folder to a SMB mount on the same computer. I'm not sure what is special about these files. I'm using this version of unison:
unison-v2.53.2+ocaml-4.14.1+x86_64.macos-10.15

unison.log:
[BGN] Copying somefile from /Users/johnny/Desktop to /Volumes/johnny/Desktop
Failed [somefile]: Error in setting file information:
Input/output error [setattrlist(/Volumes/johnny/Desktop/.unison.somefile.9ff6b1f9ebc87435d92701cd920c172c.unison.tmp)]

**Comment by gdt** [comment]
Did you find and read https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests ?

Please ask for help on the mailinglist.   While this might be a bug in unison (there certainly are), the above doesn't establish that.

**Comment by jmcisvt** [comment]
Ok I understand. After more digging It looks like the underlying issue has to do with illegal characters in the directory name. macOS wants to store them in a xattr but the TrueNAS BSD based Samba share doesn't like it. Not unison's issue.
