### ISSUE TITLE
selftest fails on macOS High Sierra

### ISSUE THREAD

**Issue by Debilski** [bcpierce00/unison#96]
Maybe it is related to the new APFS…

```
$ make test
./src/unison -selftest
Unison 2.50.0 (ocaml 4.05.0): Contacting server...
Running internal tests...
Atomicity of certain directories 1...
Test Atomicity of certain directories 1 / 1: 
Expected R2 = 
  Dir [("foo", Dir [(".git", Dir [("a", File "modified on R1"); ("b", File "bar"); ("c", File "modified on R1")])])]
but found
  Dir [("foo", Dir [(".git", Dir [("b", File "modified on R2"); ("c", File "modified on R2"); ("a", File "foo")])])]

Fatal error: Self-test Atomicity of certain directories 1 / 1 failed!
make: *** [test] Error 3

```

**Comment by brabalan** [comment]
Did you compile from source? And does the source include this fix https://github.com/bcpierce00/unison/pull/93?

**Comment by Debilski** [comment]
Yes, simply did a `make` from source (af7b8d0a5be72ad44c5f49ff53a0917d2e8ac1ae).

**Comment by brabalan** [comment]
I don't have access to an APFS drive here, unfortunately. Could you try printing the list before and after the sorting? Or maybe there is another list that need to be sorted somewhere…

@mroi : have you tried to run `make test` after your patch.

**Comment by mroi** [comment]
Sorry, I did not. Probably should have looked closer, but I did not know `make test` exists.

I just quickly tried `unison -selftest` and I get the same test failure as above. I agree this seems to be another ordering issue. From a cursory look, I suspect an explicit sorting needs to go to the [`read_dir`](https://github.com/bcpierce00/unison/blob/af7b8d0a5be72ad44c5f49ff53a0917d2e8ac1ae/src/test.ml#L86-L98) function. Does anyone know enough OCaml to propose a fix?

**Comment by brabalan** [comment]
This is just to fix the test (which might be sufficient). You can try to replace `files` on line 98 with `Safelist.sort String.compare files`.

**Comment by Debilski** [comment]
Did it. This results in:

```
$ ./src/unison -selftest
Unison 2.50.0 (ocaml 4.05.0): Contacting server...
Running internal tests...
Atomicity of certain directories 1...
Test Atomicity of certain directories 1 / 1: 
Expected R2 = 
  Dir [("foo", Dir [(".git", Dir [("a", File "modified on R1"); ("b", File "bar"); ("c", File "modified on R1")])])]
but found
  Dir [("foo", Dir [(".git", Dir [("a", File "foo"); ("b", File "modified on R2"); ("c", File "modified on R2")])])]


Fatal error: Self-test Atomicity of certain directories 1 / 1 failed!
make: *** [test] Error 3
```

**Comment by mroi** [comment]
Wow. So it got synced the wrong way. I guess this needs more investigation as to why. I can try looking into this, but I won’t have time until Monday.

**Comment by Debilski** [comment]
Is there an easy way to set the temp folder that is being used for testing? I could try running the tests on another disk then.

**Comment by brabalan** [comment]
@Debilski I'm afraid it's hard coded: https://github.com/bcpierce00/unison/blob/7dbf3045a7e9a57715a62a2bb86c08e4a99e9887/src/uicommon.ml#L552

**Comment by Debilski** [comment]
Thanks, that hint was enough to change it. :)

So I can confirm that on my machine it indeed only happens with APFS.

**Comment by bcpierce00** [comment]
I am working on getting an APFS-equipped machine set up here for testing.

**Comment by mroi** [comment]
I looked into this a little and wanted to share my findings so far:
The `force = newer` is evaluated in the [`setDirection`](https://github.com/bcpierce00/unison/blob/af7b8d0a5be72ad44c5f49ff53a0917d2e8ac1ae/src/recon.ml#L26-L54) function by comparing timestamps. However, for the .git directory in the test, the timestamps compared during the second sync are the same as those for the first sync, resulting in the wrong syncing direction. I am lost as to why they were not updated. Is there same metadata caching going on, where the previous timestamp value could be obtained?

**Comment by bcpierce00** [comment]
I had been wondering the same thing on the basis of my own investigation.  Don't know anything about APFS, though -- is there, perhaps, a way to flush all caches (e.g., maybe "sync" would do it) so that we can test this hypothesis?

**Comment by mroi** [comment]
Weird thing is, when I enable verbose debugging during the test, I see unison traversing the roots and showing every file with its mtime and ctime. And there, everything seems to have the correct time stamp. But then later, during reconciliation, the old time stamp is back.

I have learned some OCaml along the way, but I did not succeed in tracing the origin of the wrong time stamp value backwards from setDirection. Any hints how I could go about doing this?

I am not aware of any specific caching that APFS would be doing here. Apart from the regular buffer cache, it should always act POSIX-compliant and return the proper time stamps.

**Comment by mroi** [comment]
It gets weirder. I instrumented two places in the code: I added debug output in `setDirection` to show the two timestamps being compared for the `force = newer` and I changed the `lstat` in `fs.ml` to output `st_mtime` if the file being stat’ed is the .git directory. Here is the output I get from the selftest:

```
Michael@carpo:~/Downloads/unison-2.49.543 > ./unison -selftest
2017-10-11 10:28:17.771 Unison[6241:86361] Calling nonGuiStartup
Contacting server...
Running internal tests...
Atomicity of certain directories 1...
lstat called on <truncated>/unisontest.6yARxdjza/foo/.git, mtime: 1507710497.787412
lstat called on <truncated>/unisontest.6yARxdjzb/foo/.git, mtime: 1507710497.788152
comparing 1507710497.788152 1507710497.787412
lstat called on <truncated>/unisontest.6yARxdjza/foo/.git, mtime: 1507710497.787412
lstat called on <truncated>/unisontest.6yARxdjza/foo/.git, mtime: 1507710497.787412
lstat called on <truncated>/unisontest.6yARxdjzb/foo/.git, mtime: 1507710497.788152
lstat called on <truncated>/unisontest.6yARxdjza/foo/.git, mtime: 1507710497.787412
lstat called on <truncated>/unisontest.6yARxdjza/foo/.git, mtime: 1507710497.903696
lstat called on <truncated>/unisontest.6yARxdjzb/foo/.git, mtime: 1507710497.902235
comparing 1507710497.788152 1507710497.787412
lstat called on <truncated>/unisontest.6yARxdjza/foo/.git, mtime: 1507710497.903696
lstat called on <truncated>/unisontest.6yARxdjza/foo/.git, mtime: 1507710497.903696
lstat called on <truncated>/unisontest.6yARxdjza/foo/.git, mtime: 1507710497.903696
lstat called on <truncated>/unisontest.6yARxdjza/foo/.git, mtime: 1507710497.903696
lstat called on <truncated>/unisontest.6yARxdjzb/foo/.git, mtime: 1507710497.902235
Test Atomicity of certain directories 1 / 1: 
Expected R2 = 
  Dir [("foo", Dir [(".git", Dir [("a", File "modified on R1"); ("b", File "bar"); ("c", File "modified on R1")])])]
but found
  Dir [("foo", Dir [(".git", Dir [("a", File "foo"); ("b", File "modified on R2"); ("c", File "modified on R2")])])]

Fatal error: Self-test Atomicity of certain directories 1 / 1 failed!
```

You can clearly see that unison is receiving an updated timestamp from the file system. But when it comes to the comparison, it is using a stale value that does not match the latest `lstat` result. This does not look like an APFS issue to me. Somehow, unison is holding on to the old mtime value internally somewhere. Any ideas how this could happen? Data race? Unison-internal caching?

**Comment by mroi** [comment]
More findings. I tried the selftest with the same instrumentation on HFS+ and I get this:
```
Michael@carpo:~/Downloads/unison-2.49.543 > ./unison -selftest
2017-10-11 10:48:34.362 Unison[6598:100612] Calling nonGuiStartup
Contacting server...
Running internal tests...
Atomicity of certain directories 1...
lstat called on <truncated>/unisontesta/foo/.git, mtime: 1507711714.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711714.000000
comparing 1507711714.000000 1507711714.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711714.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711714.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711714.000000
lstat called on <truncated>/unisontesta/foo/.git, mtime: 1507711714.000000
lstat called on <truncated>/unisontesta/foo/.git, mtime: 1507711715.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711715.000000
comparing 1507711714.000000 1507711714.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711715.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711715.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711715.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711715.000000
lstat called on <truncated>/unisontestb/foo/.git, mtime: 1507711716.000000
[…]
```

Clearly, the selftest is also comparing outdated timestamps here. But the test is still successful (the output would continue), because the timestamp resolution of HFS+ is lower than on APFS. This points to a more general logic error in unison, which only triggers on APFS due to the higher timestamp resolution.

**Comment by mroi** [comment]
I found the problem: It’s [this test](https://github.com/bcpierce00/unison/blob/af7b8d0a5be72ad44c5f49ff53a0917d2e8ac1ae/src/update.ml#L1651-L1654).

If a directory is considered unchanged (and timestamp updates do not count as a change for directories), the old stat information from the archive is reused. This causes problems with the combination of `atomic` and `force = newer`, because there, the directory timestamp becomes relevant to resolve conflicts.

I would suggest the following patch, which fixes the selftest on APFS, but I am not sure this is the right way to handle this:

```
--- src/update.ml	2016-03-02 01:19:26.000000000 +0100
+++ src/update.ml	2017-10-11 12:56:10.000000000 +0200
@@ -1649,7 +1649,10 @@
         debugverbose (fun() -> Util.msg "  buildUpdate -> Directory\n");
         let (permchange, desc) =
           if isPropUnchanged info.Fileinfo.desc archDesc then
-            (PropsSame, archDesc)
+            if Pred.test Globals.atomic (Path.toString path) then
+              (PropsSame, info.Fileinfo.desc)
+            else
+              (PropsSame, archDesc)
           else
             (PropsUpdated, info.Fileinfo.desc) in
         let unchanged =

```

**Comment by bcpierce00** [comment]
Your fix looks correct to me, and I will make it in the main source.  

But I'm still puzzled by one thing: If I add (Unix.sleep 2) between "put R2 (Dir ...)" and "put R1 expected" in the test that was failing on APFS, I'd expect it to now start failing even on non-APFS systems, but it does not seem to.

**Comment by mroi** [comment]
You mean the original test without the fix should fail? I think to provoke a failure, the sleep should go between the two `put` calls in [line 335](https://github.com/bcpierce00/unison/blob/5962b91171e23b43c04d9455da2d03c0396a91b1/src/test.ml#L335) in order to make R2 the newer one, hopefully causing a sync from R2 to R1 and thus failing the test. But I have not tried this yet, because I am sitting at the wrong machine right now.

**Comment by bcpierce00** [comment]
(Right, without the fix.)

Actually, it turns out we need both your suggestion and mine to provoke the failure.  :-)

   - B
