### ISSUE TITLE
This brilliant! Not an issue just kudos + a question

### ISSUE THREAD

**Issue by skironDotNet** [bcpierce00/unison#969]
I was always wondering how to sync X -> Y both directions and handle the deletes, at some point I thought I would need a utility program to delete files and stored that fact in the file, and then when syncing, to read that file and delete upon that, storing timestamps to make sure that new version of file A in Y should be copied to X even if deleted in X. But the problem was what if I delete using OS based rm?

Your approach is amazing with building initial and keeping state in .unison folder. I have 2 live USB OS, and thanks to this I can sync safely because I will keep unison only on one USB the primary, and only the primary will be responsible of syncing changes so there is no mismatch in `.unison`

If you are still reading, would it be possible to keep `.unison` in custom location? or better to sync `.unison` profile to another location, so in case I would like to use secondary USB/OS to sync, it could have it's own copy of latest tracking profile? This way I would have a backup not only of the files between 2 USBs but also a backup of latest `.unison` profile

**Comment by tleedjarv** [comment]
> If you are still reading, would it be possible to keep `.unison` in custom location?

It's possible. Currently the only way is by setting the `UNISON` environment variable to point to your `.unison` dir (this way it can have a different name, too).

> or better to sync `.unison` profile to another location, so in case I would like to use secondary USB/OS to sync, it could have it's own copy of latest tracking profile? This way I would have a backup not only of the files between 2 USBs but also a backup of latest `.unison` profile

A sync that uses `.unison` for its archive can't sync/copy `.unison` itself. You'd have to do that separately.

**Comment by gdt** [comment]
Questions are not allowed int the tracker.  Please use the mailingilst, as documented in the README.  (Did you not find the section about issue tracker use?)
