### ISSUE TITLE
Preserve extended file attributes?

### ISSUE THREAD

**Issue by glubsy** [bcpierce00/unison#97]
On Linux, Unison fails to preserve extended file attributes when backing up files (tested on EXT4 file system).

Have you considered implementing this feature? Would it be difficult to do? 
I wish I could contribute, sorry. :disappointed: 

Edit: nevermind, just noticed the project is no longer under development. Sad. :sob:

**Comment by brabalan** [comment]
@glubsy It's maintained and contributions are accepted, so don't hesitate to implement this feature. But we don't have developers actively coding feature requests.

**Comment by glubsy** [comment]
Wish I could, but I'm no programmer and I don't know ObjectiveC. 
I'm looking at implementing such feature for another project in C++, if I manage to do it successfully, maybe I'll look into learning a bit of ObjectiveC and try hacking at it, no promises though.

**Comment by alkuzad** [comment]
@glubsy It's OCaml mostly not ObjectiveC :P

what is another project in C++ ? Is it unison alternative ?

**Comment by glubsy** [comment]
My immediate "study case" is actually the [kio from the KDE project](https://github.com/KDE/kio/blob/master/src/ioslaves/file/file.cpp), in order to allow KDE Dolphin file manager to preserve xattr when copying/moving files on Linux file systems. 
And then, there is [FreeFileSync](https://www.freefilesync.org/) I'm hoping to have a serious look at, which is more or less a unison alternative and also doesn't preserve xattr. 
A third project called [Synkron](https://sourceforge.net/p/synkron/code/HEAD/tree/) is also in need of this improvement, but the project is discontinued it seems.

**Comment by bcpierce00** [comment]
As Alan said, we'd love to consider a patch for this, if anyone gets motivated...
