### ISSUE TITLE
ssh:// performance compared to rsync

### ISSUE THREAD

**Issue by Massimo-B** [bcpierce00/unison#977]
Hello,

first of all thanks for the continued development here, after I'm using unison for many years now.

I'm using unison on davfs2 mounts and cifs mounts. cifs mount via VPN is very slow. However rsync to OpenSSH Servers is quite efficient via VPN.
What about using ssh:// targets in unison, is that using SFTP just like scp does? Is that as efficient as rsync? As workaround I think about some gateway server behind the VPN, that does locally mount cifs and that I can use via unison and ssh:// . .Any idea about that?

**Comment by gdt** [comment]
Please use the mailinglist for questions. as documented in https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests

Please add a followup comment here explaining how you came to enter a question in the bug tracker without having read the above link.

**Comment by Massimo-B** [comment]
Sorry, I wasn't aware about the mailing list and did forward the idea there...

**Comment by Massimo-B** [comment]
Ok, it's not working, I mailed to [unison-users@seas.upenn.edu](mailto:unison-users@seas.upenn.edu)
I received a Delivery Status Notification (Failure):

<details>

```
From: Mail Delivery Subsystem <mailer-daemon@googlemail.com>
Subject: Delivery Status Notification (Failure)
Date: Wed, 08 Nov 2023 04:36:38 -0800 (PST)

Hello ...

We're writing to let you know that the group you tried to contact (unison-u=
sers) may not exist, or you may not have permission to post messages to the=
 group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the =
Help Center at https://support.google.com/a/seas.upenn.edu/bin/topic.py?top=
ic=3D25838.

Thanks,

seas.upenn.edu admins



----- Original message -----
...
```

</details>

**Comment by tleedjarv** [comment]
https://github.com/bcpierce00/unison/issues/871#issuecomment-1856055324
