### ISSUE TITLE
sync hangs after startup  between two macs

### ISSUE THREAD

**Issue by ondohotola** [bcpierce00/unison#992]
I have noticed since a day or so that when trying to sync between two Macs (any combination of 17.7.3 and 14.2.1) using unison version 2.53.3 (ocaml 4.14.1) from Homebrew it hangs.

On the remote side `ps ax|grep -i [u]nison` shows something like

`61461   ??  Ss     0:00.05 unison -server __new-rpc-mode`

and nothing else happens.

**Comment by gdt** [comment]
Your message does not have evidence that there is  bug in unison.   See the links below for advice on debugging and getting evidence about what's going on.  In particular, a change in behavior with the same unison binary points to something else changing.   The first link has information about minimizing your setup (command-line only, no repeat, no fswatcher), or at least should :-)  but this is just the standard debugging advice to have a minimal reproduction recipe.

Please feel free to follow up here with evidence of a bug in the unison source code (homebrew bugs, if any, should be reported to homebrew).    Please use the mailnglist for followup if you would like help debugging.

See
 * https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
 * https://github.com/bcpierce00/unison/wiki/Mailing-Lists
