### ISSUE TITLE
unison-gui: Add quiet/auto mode, that only shows window/GUI when necessary.

### ISSUE THREAD

**Issue by navid-zamani** [bcpierce00/unison#993]
### Situation ###
I use unison to sync multiple directories to and from my phone, with the phone being the server.  
This results in many windows being opened, and me having to close them, even when most are empty.  
I cannot use the text UI, because when there is something to sync, it can be a huge list where manually going through each one is unfeasible, saying e.g. yes to all of them is not what i want, and going over it multiple times seems unpractical, so a GUI to accept all and then change the ones that go the other way or shouldn’t be synced this time, is a huge help.

### Solution ##
So ideally, I’d use a `--quiet` switch or the like on `unison-gtk`, so it scans for differences as usual, but only if it finds something on which a decision has to be made (not just conflicts, but anything that’s not in sync), would it show the window.  
Of course if the profile would be configured to actually sync things and only ask on actual conflicts, then it should only show a window on actual conflicts. (I don’t need that. But others probably will.)

**What do you think? Is this feasible with the current design? Do you think it’s a reasonable and useful thing?**  
Or am I missing something about the concept of unison and the idiomatic way to do this?

### Context ###
Essentially I remember the old days of decentralised sync software, where such software would actually ask the user in case of conflicts. (Palm Sync did, for example.) Nowadays, to my horror, most software just assumes every change is instantly uploaded to a central server, meaning the server is always up-to-date, meaning the server always wins. … This has led to data loss in my case, as one device didn’t have a connection until after the data was changed on another device and synced to the server. … And that, plus me not having my head in the cloud, is how I came to unison in the first place. :) (Also, the language it’s written in was a big plus for me.)

**Comment by gdt** [comment]
If you want to work on writing code, please bring this up on -hackers.  Even then, I'd be concerned about the utility/complexity tradeoff, but this could be over the tline.   If you aren't going to write the code/docs, I dont't expect anyone  else to worki on it.   I'll leave this here and likely move it to a list of feature requests that aren't going to happen.

I'm not addressing your questions about "what do you think" because the guidelines for the issue tracker are that it is not for discussion and is for fully bake enhancement requests.  Please continue on -hackers if you'd like to discuss.

**Comment by navid-zamani** [comment]
I think I found a way to already do this: By first running the text UI unison in `-batch` mode, and using its return status (other than `0`) to determine if there is anything it could not resolve (i.e. conflicts), and only run the GUI if that is the case.

I first have to improve my profile files though. I think I will prepend the call to `unison` with a scan for files that are too big, and add them to an `include` profile as `ignore` directives. But this would mean running text `unison` a second time, to give the correct return status to decide whether to run the GUI.

Regarding the guidelines: I was not aware that it works that way for this project. I’m sorry for creating an issue just like that. (Maybe you could add a custom template to the issue creator, like other projects did, to warn the user about this, so it is avoided in the future.)  
In general, even as an old user from newsgroups times, nowadays, I avoid mailing lists due to to hassle of subscribing (as in: it being more than a “subscribe” link that opens my mail program), and due to also getting messages that are not replies. So I won’t do that. (Even patching the program myself feels like less of a commitment and hassle. :)

Anyway, thank you. I will close this now, as it feels resolved for me. (If something is missing, I will simply make a patch for it, as that is very easy on Gentoo.)
